var worker,BLOCK=128,startX,startY,division,completed=0,scene,camera,renderer,loader,sceneId;importScripts("../../../build/three.js");
self.onmessage=function(a){if(a=a.data){if(a.init){var t=a.init[0],d=a.init[1];worker=a.worker;BLOCK=a.blockSize;renderer||(renderer=new THREE.RaytracingRendererWorker);loader||(loader=new THREE.ObjectLoader);renderer.setSize(t,d);completed=0}if(a.scene){scene=loader.parse(a.scene);camera=loader.parse(a.camera);var x=a.annex;scene.traverse(function(a){a.isPointLight&&(a.physicalAttenuation=!0);if(a=a.material){var k=x[a.uuid],p;for(p in k)a[p]=k[p]}});sceneId=a.sceneId}a.render&&scene&&camera&&(startX=
a.x,startY=a.y,renderer.render(scene,camera))}};
THREE.RaytracingRendererWorker=function(){console.log("THREE.RaytracingRendererWorker",THREE.REVISION);var a,t,d,x,y=new THREE.Vector3,k=new THREE.Vector3,p=new THREE.Vector3,M=new THREE.Raycaster(y,k),H=M.ray,I=new THREE.Raycaster,J=I.ray,D,E=new THREE.Matrix3,F,A=[],G={};this.setSize=function(z,b){a=z;t=b;d=Math.floor(a/2);x=Math.floor(t/2)};var P=function(){for(var z=new THREE.Color,b=new THREE.Color,h=new THREE.Color,a=new THREE.Color,f=new THREE.Color,l=new THREE.Vector3,c=new THREE.Vector3,
g=new THREE.Vector3,K=new THREE.Vector3,k=new THREE.Vector3,q=new THREE.Vector3,p=new THREE.Vector3,t=[],d=0;3>d;d++)t[d]=new THREE.Color;return function N(d,w,B,x){B.setRGB(0,0,0);H.origin=d;H.direction=w;var r=M.intersectObjects(F,!0);if(0!==r.length){var m=r[0];d=m.point;var u=m.object,e=u.material,m=m.face,C=u.geometry.vertices,u=G[u.id];l.subVectors(H.origin,d).normalize();e.isMeshLambertMaterial||e.isMeshPhongMaterial||e.isMeshBasicMaterial?z.copyGammaToLinear(e.color):z.setRGB(1,1,1);e.vertexColors===
THREE.FaceColors&&z.multiply(m.color);J.origin.copy(d);if(e.isMeshBasicMaterial)for(var v=0,y=A.length;v<y;v++){var n=A[v];c.setFromMatrixPosition(n.matrixWorld);c.sub(d);J.direction.copy(c).normalize();r=I.intersectObjects(F,!0);0<r.length||B.add(z)}else if(e.isMeshLambertMaterial||e.isMeshPhongMaterial)for(var D=!1,v=0,y=A.length;v<y;v++)if(n=A[v],c.setFromMatrixPosition(n.matrixWorld),c.sub(d),J.direction.copy(c).normalize(),r=I.intersectObjects(F,!0),!(0<r.length)&&(!1===D&&(k.copy(d).applyMatrix4(u.inverseMatrix),
O(g,k,e.flatShading,m,C),g.applyMatrix3(u.normalMatrix).normalize(),D=!0),h.copyGammaToLinear(n.color),r=1,!0===n.physicalAttenuation&&(r=c.length(),r=1/(r*r)),c.normalize(),n=Math.max(g.dot(c),0)*n.intensity,f.copy(z),f.multiply(h),f.multiplyScalar(n*r),B.add(f),e.isMeshPhongMaterial)){K.addVectors(c,l).normalize();var L=Math.max(g.dot(K),0),L=Math.max(Math.pow(L,e.shininess),0)*n,E=(e.shininess+2)/8;b.copyGammaToLinear(e.specular);n=Math.pow(Math.max(1-c.dot(K),0),5);a.r=b.r+(1-b.r)*n;a.g=b.g+(1-
b.g)*n;a.b=b.b+(1-b.b)*n;f.copy(a);f.multiply(h);f.multiplyScalar(E*L*r);B.add(f)}m=e.reflectivity;(e.mirror||e.glass)&&0<m&&3>x&&(e.mirror?(q.copy(w),q.reflect(g)):e.glass&&(C=e.refractionRatio,u=w.dot(g),v=1-C*C*(1-u*u),0>v?q.set(0,0,0):(q.copy(w),q.multiplyScalar(C),n=C*u+Math.sqrt(v),p.copy(g),p.multiplyScalar(n),q.sub(p))),w=Math.max(l.dot(g),0),w=m+(1-m)*Math.pow(1-w,5),m=t[x],N(d,q,m,x+1),void 0!==e.specular&&m.multiply(e.specular),m.multiplyScalar(w),B.multiplyScalar(1-w),B.add(m))}}}(),O=
function(){var a=new THREE.Vector3,b=new THREE.Vector3,h=new THREE.Vector3;return function(d,f,l,c,g){var k=c.normal,p=c.vertexNormals;if(!0===l)d.copy(k);else{l=g[c.a];var q=g[c.b];c=g[c.c];h.crossVectors(a.subVectors(q,l),b.subVectors(c,l));g=k.dot(h);h.crossVectors(a.subVectors(q,f),b.subVectors(c,f));q=k.dot(h)/g;h.crossVectors(a.subVectors(c,f),b.subVectors(l,f));f=k.dot(h)/g;k=1-q-f;a.copy(p[0]);a.multiplyScalar(q);b.copy(p[1]);b.multiplyScalar(f);h.copy(p[2]);h.multiplyScalar(k);d.addVectors(a,
b);d.add(h)}}}(),Q=function(){var a=BLOCK,b=new Uint8ClampedArray(a*a*4),h=new THREE.Color;return function(t,f){for(var l=0,c=0;c<a;c++)for(var g=0;g<a;g++,l+=4)y.copy(p),k.set(g+t-d,-(c+f-x),-D),k.applyMatrix3(E).normalize(),P(y,k,h,0),b[l+0]=255*Math.sqrt(h.r),b[l+1]=255*Math.sqrt(h.g),b[l+2]=255*Math.sqrt(h.b),b[l+3]=255;self.postMessage({data:b.buffer,blockX:t,blockY:f,blockSize:a,sceneId:sceneId,time:Date.now()-reallyThen},[b.buffer]);b=new Uint8ClampedArray(a*a*4);completed++}}();this.render=
function(a,b){reallyThen=Date.now();!0===a.autoUpdate&&a.updateMatrixWorld();null===b.parent&&b.updateMatrixWorld();p.setFromMatrixPosition(b.matrixWorld);E.getNormalMatrix(b.matrixWorld);D=.5/Math.tan(THREE.Math.degToRad(.5*b.fov))*t;F=a.children;A.length=0;a.traverse(function(a){a.isPointLight&&A.push(a);void 0===G[a.id]&&(G[a.id]={normalMatrix:new THREE.Matrix3,inverseMatrix:new THREE.Matrix4});var b=G[a.id];b.normalMatrix.getNormalMatrix(a.matrixWorld);b.inverseMatrix.getInverse(a.matrixWorld)});
Q(startX,startY)}};Object.assign(THREE.RaytracingRendererWorker.prototype,THREE.EventDispatcher.prototype);