var computeLayout=function(){function Z(a){return a.charAt(0).toUpperCase()+a.slice(1)}function $(a){a.layout||(a.layout={width:void 0,height:void 0,top:0,left:0,right:0,bottom:0});a.style||(a.style={});a.children||(a.children=[]);a.children.forEach($);return a}function aa(a,d,c,f){for(var e=0;e<f.length;++e){var k=d+Z(f[e])+c;if(k in a.style&&0<=a.style[k])return a.style[k];k=d+c;if(k in a.style&&0<=a.style[k])return a.style[k]}return 0}function l(a){return void 0===a}function x(a){var d=[r[a]];
"row"!==a&&"row-reverse"!==a||d.unshift("start");return d}function I(a){var d=[u[a]];"row"!==a&&"row-reverse"!==a||d.unshift("end");return d}function A(a,d){var c;a:{for(c=0;c<d.length;++c){var f="margin"+Z(d[c])+"";if(f in a.style){c=a.style[f];break a}f="margin";if(f in a.style){c=a.style[f];break a}}c=0}return c}function U(a,d){return aa(a,"padding","",d)}function N(a,d){return aa(a,"border","Width",d)}function P(a,d){return U(a,x(d))+N(a,x(d))}function G(a,d){return A(a,x(d))+A(a,I(d))}function m(a,
d){var c=P(a,d),f;f=U(a,I(d))+N(a,I(d));return c+f}function V(a,d){return"alignSelf"in d.style?d.style.alignSelf:"alignItems"in a.style?a.style.alignItems:"stretch"}function W(a,d){if("rtl"===d){if("row"===a)return"row-reverse";if("row-reverse"===a)return"row"}return a}function B(a){return"position"in a.style?a.style.position:"relative"}function X(a){return"relative"===B(a)&&0<a.style.flex}function Q(a,d){return a.layout[f[d]]+G(a,d)}function H(a,d){return!l(a.style[f[d]])&&0<=a.style[f[d]]}function J(a,
d){return d in a.style?a.style[d]:0}function C(a,d,c){var f={row:a.style.minWidth,"row-reverse":a.style.minWidth,column:a.style.minHeight,"column-reverse":a.style.minHeight}[d];a={row:a.style.maxWidth,"row-reverse":a.style.maxWidth,column:a.style.maxHeight,"column-reverse":a.style.maxHeight}[d];!l(a)&&0<=a&&c>a&&(c=a);!l(f)&&0<=f&&c<f&&(c=f);return c}function v(a,d){return a>d?a:d}function ba(a,d){l(a.layout[f[d]])&&H(a,d)&&(a.layout[f[d]]=v(C(a,d,a.style[f[d]]),m(a,d)))}function R(a,d,c){d.layout[u[c]]=
a.layout[f[c]]-d.layout[f[c]]-d.layout[D[c]]}function S(a,d){return r[d]in a.style?J(a,r[d]):-J(a,u[d])}function Y(a,d,c){var q,e;e="direction"in a.style?a.style.direction:"inherit";"inherit"===e&&(e=void 0===c?"ltr":c);q=e;c="flexDirection"in a.style?a.style.flexDirection:"column";c=W(c,q);e="column"===c||"column-reverse"===c?W("row",q):"column";var k=W("row",q);ba(a,c);ba(a,e);a.layout.direction=q;a.layout[r[c]]+=A(a,x(c))+S(a,c);a.layout[u[c]]+=A(a,I(c))+S(a,c);a.layout[r[e]]+=A(a,x(e))+S(a,e);
a.layout[u[e]]+=A(a,I(e))+S(a,e);if("measure"in a.style){var h=T,h=H(a,k)?a.style.width:l(a.layout[f[k]])?d-G(a,k):a.layout[f[k]],h=h-m(a,k),g=!H(a,k)&&l(a.layout[f[k]]),b=!H(a,"column")&&l(a.layout[f.column]);if(g||b)h=a.style.measure(h),g&&(a.layout.width=h.width+m(a,k)),b&&(a.layout.height=h.height+m(a,"column"));if(0===a.children.length)return}for(var n,g=0;g<a.children.length;++g)if(b=a.children[g],"stretch"===V(a,b)&&"relative"===B(b)&&!l(a.layout[f[e]])&&!H(b,e))b.layout[f[e]]=v(C(b,e,a.layout[f[e]]-
m(a,e)-G(b,e)),m(b,e));else if("absolute"===B(b))for(n=0;2>n;n++)h=0!==n?"row":"column",l(a.layout[f[h]])||H(b,h)||l(b.style[r[h]])||l(b.style[u[h]])||(b.layout[f[h]]=v(C(b,h,a.layout[f[h]]-m(a,h)-G(b,h)-J(b,r[h])-J(b,u[h])),m(b,h)));n=T;l(a.layout[f[c]])||(n=a.layout[f[c]]-m(a,c));for(var y=0,s=0,E=0,O=h=0,z=0;s<a.children.length;){for(var K=0,t=0,F=0,M=0,p,g=y;g<a.children.length;++g){var b=a.children[g],w=0;!l(a.layout[f[c]])&&X(b)?(t++,F+=b.style.flex,w=m(b,c)+G(b,c)):(p=T,"row"!==c&&"row-reverse"!==
c&&(p=d-G(a,k)-m(a,k),H(a,k)&&(p=a.layout[f[k]]-m(a,k))),0===E&&Y(b,p,q),"relative"===B(b)&&(M++,w=Q(b,c)));if("wrap"===a.style.flexWrap&&!l(a.layout[f[c]])&&K+w>n&&g!==y){M--;E=1;break}E=0;K+=w;s=g+1}var L=0;p=w=0;p=l(a.layout[f[c]])?v(K,0)-K:n-K;if(0!==t){t=p/F;for(g=y;g<s;++g)b=a.children[g],X(b)&&(M=t*b.style.flex+m(b,c),K=C(b,c,M),M!==K&&(p-=K,F-=b.style.flex));t=p/F;0>t&&(t=0);for(g=y;g<s;++g)b=a.children[g],X(b)&&(b.layout[f[c]]=C(b,c,t*b.style.flex+m(b,c)),p=T,H(a,k)?p=a.layout[f[k]]-m(a,
k):"row"!==c&&"row-reverse"!==c&&(p=d-G(a,k)-m(a,k)),Y(b,p,q))}else g="justifyContent"in a.style?a.style.justifyContent:"flex-start","center"===g?L=p/2:"flex-end"===g?L=p:"space-between"===g?(p=v(p,0),w=0!==t+M-1?p/(t+M-1):0):"space-around"===g&&(w=p/(t+M),L=w/2);F=0;L+=P(a,c);for(g=y;g<s;++g)b=a.children[g],b.lineIndex=z,"absolute"!==B(b)||l(b.style[r[c]])?(b.layout[D[c]]+=L,l(a.layout[f[c]])||R(a,b,c)):b.layout[D[c]]=J(b,r[c])+N(a,x(c))+A(b,x(c)),"relative"===B(b)&&(L+=w+Q(b,c),F=v(F,C(b,e,Q(b,
e))));w=a.layout[f[e]];l(a.layout[f[e]])&&(w=v(C(a,e,F+m(a,e)),m(a,e)));for(g=y;g<s;++g)b=a.children[g],"absolute"!==B(b)||l(b.style[r[e]])?(y=P(a,e),"relative"===B(b)&&(p=V(a,b),"stretch"===p?H(b,e)||(b.layout[f[e]]=v(C(b,e,w-m(a,e)-G(b,e)),m(b,e))):"flex-start"!==p&&(t=w-m(a,e)-Q(b,e),y="center"===p?y+t/2:y+t)),b.layout[D[e]]+=h+y,l(a.layout[f[e]])||R(a,b,e)):b.layout[D[e]]=J(b,r[e])+N(a,x(e))+A(b,x(e));h+=F;O=v(O,L);z+=1;y=s}if(1<z&&!l(a.layout[f[e]]))for(g=a.layout[f[e]]-m(a,e),b=g-h,d=0,q=P(a,
e),k=("alignContent"in a.style)?a.style.alignContent:"flex-start","flex-end"===k?q+=b:"center"===k?q+=b/2:"stretch"===k&&g>h&&(d=b/z),g=k=0;g<z;++g){E=k;s=0;for(n=E;n<a.children.length;++n)if(b=a.children[n],"relative"===B(b)){if(b.lineIndex!==g)break;l(b.layout[f[e]])||(s=v(s,b.layout[f[e]]+G(b,e)))}k=n;s+=d;for(n=E;n<k;++n)b=a.children[n],"relative"===B(b)&&(E=V(a,b),"flex-start"===E?b.layout[D[e]]=q+A(b,x(e)):"flex-end"===E?b.layout[D[e]]=q+s-A(b,I(e))-b.layout[f[e]]:"center"===E?b.layout[D[e]]=
q+(s-b.layout[f[e]])/2:"stretch"===E&&(b.layout[D[e]]=q+A(b,x(e))));q+=s}z=d=!1;l(a.layout[f[c]])&&(g=a.layout,b=f[c],d=U(a,I(c))+N(a,I(c)),g[b]=v(C(a,c,O+d),m(a,c)),d=!0);l(a.layout[f[e]])&&(a.layout[f[e]]=v(C(a,e,h+m(a,e)),m(a,e)),z=!0);if(d||z)for(g=0;g<a.children.length;++g)b=a.children[g],d&&R(a,b,c),z&&R(a,b,e);for(g=0;g<a.children.length;++g)if(b=a.children[g],"absolute"===B(b)){for(n=0;2>n;n++)h=0!==n?"row":"column",l(a.layout[f[h]])||H(b,h)||l(b.style[r[h]])||l(b.style[u[h]])||(c=b.layout,
e=f[h],O=b,z=h,d=a.layout[f[h]],q=a,k=h,q=N(q,x(k))+N(q,I(k)),c[e]=v(C(O,z,d-q-G(b,h)-J(b,r[h])-J(b,u[h])),m(b,h)));for(n=0;2>n;n++)h=0!==n?"row":"column",!l(b.style[u[h]])&&l(b.style[r[h]])&&(b.layout[r[h]]=a.layout[f[h]]-b.layout[f[h]]-J(b,u[h]))}}var T,r={row:"left","row-reverse":"right",column:"top","column-reverse":"bottom"},u={row:"right","row-reverse":"left",column:"bottom","column-reverse":"top"},D={row:"left","row-reverse":"right",column:"top","column-reverse":"bottom"},f={row:"width","row-reverse":"width",
column:"height","column-reverse":"height"};return{computeLayout:Y,fillNodes:$}}();"object"===typeof exports&&(module.exports=computeLayout);