/*
 MIT License

 Copyright (c) 2012 Twilio Inc.

 Authors: Chad Etzel <chetzel@twilio.com>

 Permission is hereby granted, free of charge, to any person obtaining
 a copy of this software and associated documentation files (the
 "Software"), to deal in the Software without restriction, including
 without limitation the rights to use, copy, modify, merge, publish,
 distribute, sublicense, and/or sell copies of the Software, and to
 permit persons to whom the Software is furnished to do so, subject to
 the following conditions:

 The above copyright notice and this permission notice shall be
 included in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
(function(h){"undefined"===typeof window&&(window={});"undefined"===typeof window.localStorage&&h!==window&&(window.localStorage={},window.localStorage.store={},window.localStorage.setItem=function(f,h){window.localStorage.store[f]=h},window.localStorage.getItem=function(f){f=window.localStorage.store[f];return void 0===f?null:f},window.localStorage.removeItem=function(f){delete window.localStorage.store[f]},window.localStorage.clear=function(){window.localStorage.store={}});var C=function(f,h){if(isNaN(parseInt(f)))throw new r("db index must be an integer");
f=parseInt(f);h=h||{};var e=this,t=f,m=h.adapter;void 0===m?m=new A:null===m&&(m=new B);var k="bb:"+t.toString()+":",s="bb:"+t.toString()+"k:___keys___",p={};this.toString=function(){return"bb:"+t.toString()};if("undefined"==typeof JSON&&!(window.JSON&&window.JSON.parse&&window.JSON.stringify))throw"No JSON support detected. Please include a JSON module with 'parse' and 'stringify' functions.";var x=function(a,b){var c=p[a];if(void 0!==c)return c;var d=c=m.getItem(a);try{d=JSON.parse(c)}catch(e){}finally{p[a]=
d}return d},y=function(a,b){var c=x(a,b);return null===c?null:c.v},u=function(a,b,c){a=x(a,c);return null===a?null:a.m[b]},z=function(a,b,c){var d=x(a,c);if(void 0===d||null===d)d={m:{}};d.v=b;void 0!==c&&(d.m.t=c);b=d;p[a]=b;m.storeItem(a,JSON.stringify(b))},v=function(a,b,c){var d=p[a];void 0!==d&&null!==d&&(d.m[b]=c,p[a]=d,m.storeItem(a,JSON.stringify(d)))},n=function(a,b,c){z(k+a,b,c);void 0!==c&&v(k+a,"t",c);q[a]=1;z(s,q,"set")},l=function(a,b){return y(k+a,b)},g=function(a,b){var c=e.type(a),
d={get:"string",set:"string",strlen:"string",setnx:"string",append:"string",incr:"string",incrby:"string",getset:"string",lpush:"list",lpushx:"list",lpop:"list",rpush:"list",rpushx:"list",rpop:"list",rpoplpush:"list",llen:"list",lindex:"list",lrange:"list",lrem:"list",lset:"list",ltrim:"list",sadd:"set",scard:"set",sismember:"set",smembers:"set",srem:"set",smove:"set",spop:"set",srandmember:"set"};if(void 0===d[b])throw new r("unknown key operation in validate_key");if(void 0===c||null===c||void 0===
d[b]||d[b]==c)return!0;throw new w("invalid operation on key type: "+c);};this.del=function(a){var b=0;l(a)&&(b=1);var c=k+a;delete p[c];m.removeItem(c);delete q[a];z(s,q,"set");return b};this.exists=function(a){a=k+a;return p[a]||m.getItem(a)?!0:!1};this.type=function(a){return u(k+a,"t")};this.get=function(a){g(a,"get");return l(a)};this.getset=function(a,b){g(a,"getset");var c=e.get(a);e.set(a,b);return c};this.append=function(a,b){g(a,"append");var c=e.get(a);if(null!==c)return e.set(a,c+b),(c+
b).length;e.set(a,b);return b.toString().length};this.decr=function(a){return e.incrby(a,-1)};this.decrby=function(a,b){return e.incrby(a,0-b)};this.incr=function(a){return e.incrby(a,1)};this.incrby=function(a,b){g(a,"incrby");var c=e.get(a);if(null!==c){if(isNaN(parseInt(c)))throw new w("key is not parsable as an integer");e.set(a,c+b);return c+b}e.set(a,b);return b};this.set=function(a,b){g(a,"set");n(a,b);v(k+a,"t","string");return"OK"};this.setnx=function(a,b){g(a,"setnx");if(null!==e.get(a))return 0;
e.set(a,b);return 1};this.strlen=function(a){g(a,"strlen");a=e.get(a);return null!==a?a.toString().length:0};this.llen=function(a){g(a,"llen");a=l(a,"list");return null===a?0:a.length};this.lindex=function(a,b){g(a,"lindex");var c=l(a,"list");return null!==c?(0>b&&(b=c.length+b),c=c[b],void 0===c&&(c=null),c):null};this.lpop=function(a){g(a,"lpop");var b=l(a,"list");if(null===b)return null;var c=b.shift();0===b.length?e.del(a):n(a,b,"list");return c};this.lpush=function(a,b){g(a,"lpush");var c=l(a,
"list");null===c&&(c=[]);c.unshift(b);n(a,c,"list");return c.length};this.lpushx=function(a,b){g(a,"lpushx");return null!==l(a,"list")?e.lpush(a,b):0};this.lrange=function(a,b,c){g(a,"lrange");a=l(a,"list");return null===a?[]:-1===c?a.slice(b):a.slice(b,c+1)};this.lrem=function(a,b,c){g(a,"lrem");var d=l(a,"list");if(null===d)return 0;for(var f=0,h=[],k=0;k<d.length;k++)d[k]==c&&(h.push(k),f++);for(0<b?h=h.slice(0,b):0>b&&(h=h.slice(b));h.length;){k=h.pop();c=d;var m=c.slice(k+1||c.length);c.length=
0>k?c.length+k:k;c.push.apply(c,m)}0===d.length?e.del(a):n(a,d,"list");return 0==b?f:Math.min(f,Math.abs(b))};this.lset=function(a,b,c){g(a,"lset");var d=l(a,"list");if(null===d)throw new w("no such key");0>b&&(b=d.length+b);if(0>b||b>=d.length)throw new r("index out of range");d[b]=c;n(a,d,"list");return"OK"};this.ltrim=function(a,b,c){g(a,"ltrim");var d=l(a,"list");if(null===d)return"OK";d=-1===c?d.slice(b):d.slice(b,c+1);0===d.length?e.del(a):n(a,d,"list");return"OK"};this.rpop=function(a){g(a,
"rpop");var b=l(a,"list");if(null===b)return null;var c=b.pop();0===b.length?e.del(a):n(a,b,"list");return c};this.rpush=function(a,b){g(a,"rpush");var c=l(a);null===c&&(c=[]);c.push(b);n(a,c,"list");return c.length};this.rpushx=function(a,b){g(a,"rpushx");return null!==l(a,"list")?e.rpush(a,b):0};this.rpoplpush=function(a,b){g(a,"rpoplpush");g(b,"rpoplpush");var c=l(a,"list");l(b,"list");if(null===c)return null;c=e.rpop(a);e.lpush(b,c);return c};this.sadd=function(a,b){g(a,"sadd");var c=l(a,"set"),
d,e=0;null===c?(c={},d=0):d=parseInt(u(k+a,"card"));1!==c[b]&&(e=1,d+=1);c[b]=1;n(a,c,"set");v(k+a,"card",d);return e};this.scard=function(a){g(a,"scard");return e.exists(a)?parseInt(u(k+a,"card")):0};this.sismember=function(a,b){g(a,"sismember");var c=l(a,"set");return null===c?!1:1===c[b]?!0:!1};this.smembers=function(a){g(a,"smembers");a=l(a,"set");if(null===a)return[];var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push(c);return b};this.smove=function(a,b,c){g(a,"smove");g(b,"smove");if(null===
l(a,"set"))return 0;(a=e.srem(a,c))&&e.sadd(b,c);return a};this.spop=function(a){g(a,"spop");var b=e.srandmember(a);null!==b&&e.srem(a,b);return b};this.srandmember=function(a){g(a,"srandmember");if(null===l(a,"set"))return null;a=e.smembers(a);var b=Math.floor(Math.random()*a.length);return a[b]};this.srem=function(a,b){g(a,"srem");var c=l(a,"set");if(null===c)return 0;var d=0;if(1===c[b]){d=1;delete c[b];var f=parseInt(u(k+a,"card"))-1;0===f?e.del(a):(n(a,c,"set"),v(k+a,"card",f))}return d};this.keys=
function(a){a=[];for(var b in q)q.hasOwnProperty(b)&&a.push(b);return a};this.flushdb=function(){var a=e.keys("*"),b;for(b in a)e.del(a[b]);a=s;delete p[a];m.removeItem(a);return"OK"};this.select=function(a){if(isNaN(parseInt(a)))throw new r("db index must be an integer");t=a;k="bb:"+a.toString()+":";s="bb:"+a.toString()+"k:___keys___";q=y(s,"set")||{}};var q=y(s,"set")||{}};C.toString=function(){return"[object BankersBox]"};var r=function(f){this.type="BankersBoxException";this.toString=function(){return this.type+
": "+f.toString()}},w=function(f){r.call(this,f);this.type="BankersBoxKeyException"},A=function(){if("undefined"===typeof window||"undefined"===typeof window.localStorage)throw"window.localStorage is undefined, consider a different storage adapter";this.getItem=function(f){return window.localStorage.getItem(f)};this.storeItem=function(f,h){try{window.localStorage.setItem(f,h)}catch(e){throw e;}};this.removeItem=function(f){window.localStorage.removeItem(f)};this.clear=function(){window.localStorage.clear()}},
B=function(){this.getItem=function(f){};this.storeItem=function(f,h){};this.removeItem=function(f){};this.clear=function(){}};h.BankersBox=C;h.BankersBoxException=r;h.BankersBoxKeyException=w;h.BankersBoxLocalStorageAdapter=A;h.BankersBoxNullAdapter=B;h!==window&&(h.mock_window=window)})("undefined"!==typeof module&&module&&module.exports?module.exports:window);