(function(){function n(){this.id=0;this.data=null}function r(){}r.prototype={set:function(a,b){this[a]=b},get:function(a,b){return this.hasOwnProperty(a)?this[a]:b}};THREE.AWDLoader=function(a){this.manager=void 0!==a?a:THREE.DefaultLoadingManager;this.trunk=new THREE.Object3D;this.materialFactory=void 0;this._baseDir=this._url="";this._data=void 0;this._ptr=0;this._version=[];this._optimized_for_accuracy=this._streaming=!1;this._compression=0;this._bodylen=4294967295;this._blocks=[new n];this._accuracyProps=
this._accuracyGeo=this._accuracyMatrix=!1};THREE.AWDLoader.prototype={constructor:THREE.AWDLoader,load:function(a,b,c,d){var e=this;this._url=a;this._baseDir=a.substr(0,a.lastIndexOf("/")+1);var g=new THREE.FileLoader(this.manager);g.setResponseType("arraybuffer");g.load(a,function(a){b(e.parse(a))},c,d)},parse:function(a){var b=a.byteLength;this._ptr=0;this._data=new DataView(a);this._parseHeader();0!=this._compression&&console.error("compressed AWD not supported");for(this._streaming||this._bodylen==
a.byteLength-this._ptr||console.error("AWDLoader: body len does not match file length",this._bodylen,b-this._ptr);this._ptr<b;)this.parseNextBlock();return this.trunk},parseNextBlock:function(){var a,b,c,d=this.readU32();this.readU8();b=this.readU8();this.readU8();c=this.readU32();switch(b){case 1:a=this.parseMeshData(c);break;case 22:a=this.parseContainer(c);break;case 23:a=this.parseMeshInstance(c);break;case 81:a=this.parseMaterial(c);break;case 82:a=this.parseTexture(c);break;case 101:a=this.parseSkeleton(c);
break;case 112:a=this.parseMeshPoseAnimation(c,!1);break;case 113:a=this.parseVertexAnimationSet(c);break;case 102:a=this.parseSkeletonPose(c);break;case 103:a=this.parseSkeletonAnimation(c);break;case 122:a=this.parseAnimatorSet(c);break;default:this._ptr+=c}this._blocks[d]=b=new n;b.data=a;b.id=d},_parseHeader:function(){var a=this._version;if(4282180!=(this.readU8()<<16|this.readU8()<<8|this.readU8()))throw Error("AWDLoader - bad magic");a[0]=this.readU8();a[1]=this.readU8();var b=this.readU16();
this._streaming=1==(b&1);2===a[0]&&1===a[1]&&(this._accuracyMatrix=2===(b&2),this._accuracyGeo=4===(b&4),this._accuracyProps=8===(b&8));this._geoNrType=this._accuracyGeo?8:7;this._matrixNrType=this._accuracyMatrix?8:7;this._propsNrType=this._accuracyProps?8:7;this._optimized_for_accuracy=2===(b&2);this._compression=this.readU8();this._bodylen=this.readU32()},parseContainer:function(a){a=new THREE.Object3D;var b=this.readU32(),c=this.parseMatrix4();a.name=this.readUTF();a.applyMatrix(c);(this._blocks[b].data||
this.trunk).add(a);this.parseProperties({1:this._matrixNrType,2:this._matrixNrType,3:this._matrixNrType,4:4});a.extra=this.parseUserAttributes();return a},parseMeshInstance:function(a){var b,c,d,e,g,k,f,h;k=this.readU32();f=this.parseMatrix4();b=this.readUTF();a=this.readU32();c=this.readU16();d=this.getBlock(a);a=[];for(h=0;h<c;h++)e=this.readU32(),e=this.getBlock(e),a.push(e);e=d.length;g=[];if(1<e)for(c=new THREE.Object3D,h=0;h<e;h++){var l=new THREE.Mesh(d[h]);g.push(l);c.add(l)}else c=new THREE.Mesh(d[0]),
g.push(c);c.applyMatrix(f);c.name=b;(this.getBlock(k)||this.trunk).add(c);b=a.length;k=Math.max(e,b);for(h=0;h<k;h++)g[h%e].material=a[h%b];this.parseProperties(null);c.extra=this.parseUserAttributes();return c},parseMaterial:function(a){var b,c,d;b=this.readUTF();c=this.readU8();d=this.readU8();for(a=this.parseProperties({1:3,2:23,11:21,12:7,13:21});0<d;)this.readU16(),this.parseProperties(null),this.parseUserAttributes();d=this.parseUserAttributes();if(void 0!==this.materialFactory&&(b=this.materialFactory(b)))return b;
b=new THREE.MeshPhongMaterial;1===c?b.color.setHex(a.get(1,13421772)):2===c&&(c=a.get(2,0),b.map=this.getBlock(c));b.extra=d;b.alphaThreshold=a.get(12,0);b.repeat=a.get(13,!1);return b},parseTexture:function(a){this.readUTF();var b;0===this.readU8()&&(a=this.readU32(),a=this.readUTFBytes(a),console.log(a),b=this.loadTexture(a));this.parseProperties(null);this.parseUserAttributes();return b},loadTexture:function(a){var b=new THREE.Texture;(new THREE.ImageLoader(this.manager)).load(this._baseDir+a,
function(a){b.image=a;b.needsUpdate=!0});return b},parseSkeleton:function(a){this.readUTF();a=this.readU16();var b=[],c=0;for(this.parseProperties(null);c<a;){var d,e;this.readU16();d=new THREE.Bone;d.parent=this.readU16()-1;d.name=this.readUTF();e=this.parseMatrix4();d.skinMatrix=e;this.parseProperties(null);this.parseUserAttributes();b.push(d);c++}this.parseUserAttributes();return b},parseSkeletonPose:function(a){this.readUTF();a=this.readU16();this.parseProperties(null);for(var b=[],c=0;c<a;){var d;
d=1===this.readU8()?this.parseMatrix4():new THREE.Matrix4;b[c]=d;c++}this.parseUserAttributes();return b},parseSkeletonAnimation:function(a){var b;this.readUTF();var c=[],d=this.readU16();this.parseProperties(null);for(var e=0;e<d;)b=this.readU32(),a=this.readU16(),b=this._blocks[b].data,c.push({pose:b,duration:a}),e++;if(0!==c.length)return this.parseUserAttributes(),c},parseVertexAnimationSet:function(a){this.readUTF();var b=this.readU16();this.parseProperties({1:5});for(var c=0,d=[];c<b;)a=this.readU32(),
d.push(this._blocks[a].data),c++;this.parseUserAttributes();return d},parseAnimatorSet:function(a){var b;this.readUTF();a=this.readU16();var c=this.parseProperties({1:23});b=this.readU32();for(var d=this.readU16(),e=[],g=0;g<d;g++)e.push(this.readU32());this.readU16();this.readU8();this.parseUserAttributes();this.parseUserAttributes();d=[];for(g=0;g<e.length;g++)d.push(this._blocks[e[g]].data);b=this._blocks[b].data;var k;1==a&&(k={animationSet:b,skeleton:this._blocks[c.get(1,0)].data});for(g=0;g<
d.length;g++)d[g].animator=k;return k},parseMeshData:function(a){a=this.readUTF();var b=this.readU16(),c,d=0,e,g=[];for(this.parseProperties({1:this._geoNrType,2:this._geoNrType});d<b;){var k,f;c=new THREE.BufferGeometry;c.name=a;g.push(c);k=this.readU32();k=this._ptr+k;for(this.parseProperties({1:this._geoNrType,2:this._geoNrType});this._ptr<k;){f=0;e=this.readU8();this.readU8();f=this.readU32();var h=f+this._ptr;if(1===e)for(e=new Float32Array(f/12*3),f=new THREE.BufferAttribute(e,3),c.addAttribute("position",
f),f=0;this._ptr<h;)e[f]=-this.readF32(),e[f+1]=this.readF32(),e[f+2]=this.readF32(),f+=3;else if(2===e)for(e=new Uint16Array(f/2),f=new THREE.BufferAttribute(e,1),c.setIndex(f),f=0;this._ptr<h;)e[f+1]=this.readU16(),e[f]=this.readU16(),e[f+2]=this.readU16(),f+=3;else if(3===e)for(e=new Float32Array(f/8*2),f=new THREE.BufferAttribute(e,2),c.addAttribute("uv",f),f=0;this._ptr<h;)e[f]=this.readF32(),e[f+1]=1-this.readF32(),f+=2;else if(4===e)for(e=new Float32Array(f/12*3),f=new THREE.BufferAttribute(e,
3),c.addAttribute("normal",f),f=0;this._ptr<h;)e[f]=-this.readF32(),e[f+1]=this.readF32(),e[f+2]=this.readF32(),f+=3;else this._ptr=h}this.parseUserAttributes();c.computeBoundingSphere();d++}this.parseUserAttributes();return g},parseMeshPoseAnimation:function(a,b){var c=1,d,e,g,k,f,h,l=0,q,m,n=[];this.readUTF();d=this.readU32();h=this.getBlock(d);if(null===h)console.log("parseMeshPoseAnimation target mesh not found at:",d);else{h=h.geometry;h.morphTargets=[];b||(c=this.readU16());d=this.readU16();
q=this.readU16();for(m=0;m<q;)n.push(this.readU16()),m++;e=this.parseProperties({1:21,2:21});e.get(1,!0);e.get(2,!1);for(e=0;e<c;){this.readU16();for(g=0;g<d;)for(m=0,k=this.readU32(),f=this._ptr+k;m<q;){if(1===n[m]){var p=new Float32Array(k/4);h.morphTargets.push({array:p});for(l=0;this._ptr<f;)p[l]=this.readF32(),p[l+1]=this.readF32(),p[l+2]=this.readF32(),l+=3;g++}else this._ptr=f;m++}e++}this.parseUserAttributes();return null}},getBlock:function(a){return this._blocks[a].data},parseMatrix4:function(){var a=
new THREE.Matrix4,b=a.elements;b[0]=this.readF32();b[1]=this.readF32();b[2]=this.readF32();b[3]=0;b[4]=this.readF32();b[5]=this.readF32();b[6]=this.readF32();b[7]=0;b[8]=this.readF32();b[9]=this.readF32();b[10]=this.readF32();b[11]=0;b[12]=-this.readF32();b[13]=this.readF32();b[14]=this.readF32();b[15]=1;return a},parseProperties:function(a){var b=this.readU32(),b=this._ptr+b,c=new r;if(a)for(;this._ptr<b;){var d=this.readU16(),e=this.readU32(),g;a.hasOwnProperty(d)?(g=a[d],c.set(d,this.parseAttrValue(g,
e))):this._ptr+=e}return c},parseUserAttributes:function(){this._ptr=this.readU32()+this._ptr;return null},parseAttrValue:function(a,b){var c,d;switch(a){case 1:c=1;d=this.readI8;break;case 2:c=2;d=this.readI16;break;case 3:c=4;d=this.readI32;break;case 21:case 4:c=1;d=this.readU8;break;case 5:c=2;d=this.readU16;break;case 6:case 23:c=4;d=this.readU32;break;case 7:c=4;d=this.readF32;break;case 8:c=8;d=this.readF64;break;case 41:case 42:case 43:case 44:case 45:case 46:case 47:c=8,d=this.readF64}if(c<
b){var e,g;e=[];g=0;for(c=b/c;g<c;)e.push(d.call(this)),g++;return e}return d.call(this)},readU8:function(){return this._data.getUint8(this._ptr++)},readI8:function(){return this._data.getInt8(this._ptr++)},readU16:function(){var a=this._data.getUint16(this._ptr,!0);this._ptr+=2;return a},readI16:function(){var a=this._data.getInt16(this._ptr,!0);this._ptr+=2;return a},readU32:function(){var a=this._data.getUint32(this._ptr,!0);this._ptr+=4;return a},readI32:function(){var a=this._data.getInt32(this._ptr,
!0);this._ptr+=4;return a},readF32:function(){var a=this._data.getFloat32(this._ptr,!0);this._ptr+=4;return a},readF64:function(){var a=this._data.getFloat64(this._ptr,!0);this._ptr+=8;return a},readUTF:function(){var a=this.readU16();return this.readUTFBytes(a)},readUTFBytes:function(a){for(var b=[],c=0;b.length<a;){var d=this._data.getUint8(this._ptr++,!0);if(128>d)b[c++]=String.fromCharCode(d);else if(191<d&&224>d){var e=this._data.getUint8(this._ptr++,!0);b[c++]=String.fromCharCode((d&31)<<6|
e&63)}else{var e=this._data.getUint8(this._ptr++,!0),g=this._data.getUint8(this._ptr++,!0);b[c++]=String.fromCharCode((d&15)<<12|(e&63)<<6|g&63)}}return b.join("")}}})();