THREE.BinaryLoader=function(h){"boolean"===typeof h&&(console.warn("THREE.BinaryLoader: showStatus parameter has been removed from constructor."),h=void 0);this.manager=void 0!==h?h:THREE.DefaultLoadingManager};
THREE.BinaryLoader.prototype={constructor:THREE.BinaryLoader,crossOrigin:"Anonymous",load:function(h,B,v,z){var n=this.texturePath||THREE.LoaderUtils.extractUrlBase(h),l=this.binaryPath||THREE.LoaderUtils.extractUrlBase(h),p=this;(new THREE.FileLoader(this.manager)).load(h,function(h){var H=JSON.parse(h);h=l+H.buffers;var I=new THREE.FileLoader(p.manager);I.setResponseType("arraybuffer");I.load(h,function(h){p.parse(h,B,n,H.materials)},v,z)},v,z)},setBinaryPath:function(h){this.binaryPath=h},setCrossOrigin:function(h){this.crossOrigin=
h},setTexturePath:function(h){this.texturePath=h},parse:function(h,B,v,z){var n=function(){function l(b){return b%4?4-b%4:0}function p(b,a){return(new Uint8Array(b,a,1))[0]}function q(b,a){return(new Uint32Array(b,a,1))[0]}function n(b,a){var c,e,d,w,f,J,g,m=new Uint32Array(h,a,3*b);for(c=0;c<b;c++)e=m[3*c],d=m[3*c+1],w=m[3*c+2],f=k[2*e],J=k[2*e+1],e=k[2*d],g=k[2*d+1],d=k[2*w],w=k[2*w+1],y.faceVertexUvs[0].push([new THREE.Vector2(f,J),new THREE.Vector2(e,g),new THREE.Vector2(d,w)])}function v(b,a){var c,
e,d,w,f,g,A,m,r,u=new Uint32Array(h,a,4*b);for(c=0;c<b;c++)e=u[4*c],d=u[4*c+1],w=u[4*c+2],f=u[4*c+3],g=k[2*e],A=k[2*e+1],e=k[2*d],m=k[2*d+1],d=k[2*w],r=k[2*w+1],w=k[2*f],f=k[2*f+1],y.faceVertexUvs[0].push([new THREE.Vector2(g,A),new THREE.Vector2(e,m),new THREE.Vector2(w,f)]),y.faceVertexUvs[0].push([new THREE.Vector2(e,m),new THREE.Vector2(d,r),new THREE.Vector2(w,f)])}function z(b,a,c){var e,d,f,g;a=new Uint32Array(h,a,3*b);var k=new Uint16Array(h,c,b);for(c=0;c<b;c++)e=a[3*c],d=a[3*c+1],f=a[3*
c+2],g=k[c],y.faces.push(new THREE.Face3(e,d,f,null,null,g))}function B(b,a,c){var e,d,f,g,k;a=new Uint32Array(h,a,4*b);var A=new Uint16Array(h,c,b);for(c=0;c<b;c++)e=a[4*c],d=a[4*c+1],f=a[4*c+2],g=a[4*c+3],k=A[c],y.faces.push(new THREE.Face3(e,d,g,null,null,k)),y.faces.push(new THREE.Face3(d,f,g,null,null,k))}function K(b,a,c,e){var d,g,k,n,A,m,r;a=new Uint32Array(h,a,3*b);c=new Uint32Array(h,c,3*b);var u=new Uint16Array(h,e,b);for(e=0;e<b;e++){d=a[3*e];g=a[3*e+1];k=a[3*e+2];A=c[3*e];m=c[3*e+1];
r=c[3*e+2];n=u[e];var p=f[3*m],q=f[3*m+1];m=f[3*m+2];var l=f[3*r],t=f[3*r+1];r=f[3*r+2];y.faces.push(new THREE.Face3(d,g,k,[new THREE.Vector3(f[3*A],f[3*A+1],f[3*A+2]),new THREE.Vector3(p,q,m),new THREE.Vector3(l,t,r)],null,n))}}function L(b,a,c,d){var g,k,n,p,q,m,r,u,l;a=new Uint32Array(h,a,4*b);c=new Uint32Array(h,c,4*b);var t=new Uint16Array(h,d,b);for(d=0;d<b;d++){g=a[4*d];k=a[4*d+1];n=a[4*d+2];p=a[4*d+3];m=c[4*d];r=c[4*d+1];u=c[4*d+2];l=c[4*d+3];q=t[d];var v=f[3*r],x=f[3*r+1];r=f[3*r+2];var z=
f[3*u],B=f[3*u+1];u=f[3*u+2];var C=f[3*l],D=f[3*l+1];l=f[3*l+2];y.faces.push(new THREE.Face3(g,k,p,[new THREE.Vector3(f[3*m],f[3*m+1],f[3*m+2]),new THREE.Vector3(v,x,r),new THREE.Vector3(C,D,l)],null,q));y.faces.push(new THREE.Face3(k,n,p,[new THREE.Vector3(v,x,r),new THREE.Vector3(z,B,u),new THREE.Vector3(C,D,l)],null,q))}}var y=this,g=0,d,f=[],k=[],C,D,E,F,G,t,x;THREE.Geometry.call(this);d=function(b,a){return{signature:THREE.LoaderUtils.decodeText(new Uint8Array(b,a,12)),header_bytes:p(b,a+12),
vertex_coordinate_bytes:p(b,a+13),normal_coordinate_bytes:p(b,a+14),uv_coordinate_bytes:p(b,a+15),vertex_index_bytes:p(b,a+16),normal_index_bytes:p(b,a+17),uv_index_bytes:p(b,a+18),material_index_bytes:p(b,a+19),nvertices:q(b,a+20),nnormals:q(b,a+20+4),nuvs:q(b,a+20+8),ntri_flat:q(b,a+20+12),ntri_smooth:q(b,a+20+16),ntri_flat_uv:q(b,a+20+20),ntri_smooth_uv:q(b,a+20+24),nquad_flat:q(b,a+20+28),nquad_smooth:q(b,a+20+32),nquad_flat_uv:q(b,a+20+36),nquad_smooth_uv:q(b,a+20+40)}}(h,g);g+=d.header_bytes;
t=3*d.vertex_index_bytes+d.material_index_bytes;x=4*d.vertex_index_bytes+d.material_index_bytes;C=d.ntri_flat*t;D=d.ntri_smooth*(t+3*d.normal_index_bytes);E=d.ntri_flat_uv*(t+3*d.uv_index_bytes);F=d.ntri_smooth_uv*(t+3*d.normal_index_bytes+3*d.uv_index_bytes);G=d.nquad_flat*x;t=d.nquad_smooth*(x+4*d.normal_index_bytes);x=d.nquad_flat_uv*(x+4*d.uv_index_bytes);g+=function(b){var a=d.nvertices;b=new Float32Array(h,b,3*a);var c,e,f,g;for(c=0;c<a;c++)e=b[3*c],f=b[3*c+1],g=b[3*c+2],y.vertices.push(new THREE.Vector3(e,
f,g));return 3*a*Float32Array.BYTES_PER_ELEMENT}(g);g+=function(b){var a=d.nnormals;if(a){b=new Int8Array(h,b,3*a);var c,e,g,k;for(c=0;c<a;c++)e=b[3*c],g=b[3*c+1],k=b[3*c+2],f.push(e/127,g/127,k/127)}return 3*a*Int8Array.BYTES_PER_ELEMENT}(g);g+=l(3*d.nnormals);g+=function(b){var a=d.nuvs;if(a){b=new Float32Array(h,b,2*a);var c,e,f;for(c=0;c<a;c++)e=b[2*c],f=b[2*c+1],k.push(e,f)}return 2*a*Float32Array.BYTES_PER_ELEMENT}(g);C=g+C+l(2*d.ntri_flat);D=C+D+l(2*d.ntri_smooth);E=D+E+l(2*d.ntri_flat_uv);
F=E+F+l(2*d.ntri_smooth_uv);G=F+G+l(2*d.nquad_flat);t=G+t+l(2*d.nquad_smooth);x=t+x+l(2*d.nquad_flat_uv);(function(b){var a=d.ntri_flat_uv;if(a){var c=b+a*Uint32Array.BYTES_PER_ELEMENT*3;z(a,b,c+a*Uint32Array.BYTES_PER_ELEMENT*3);n(a,c)}})(D);(function(b){var a=d.ntri_smooth_uv;if(a){var c=b+a*Uint32Array.BYTES_PER_ELEMENT*3,e=c+a*Uint32Array.BYTES_PER_ELEMENT*3;K(a,b,c,e+a*Uint32Array.BYTES_PER_ELEMENT*3);n(a,e)}})(E);(function(b){var a=d.nquad_flat_uv;if(a){var c=b+a*Uint32Array.BYTES_PER_ELEMENT*
4;B(a,b,c+a*Uint32Array.BYTES_PER_ELEMENT*4);v(a,c)}})(t);(function(b){var a=d.nquad_smooth_uv;if(a){var c=b+a*Uint32Array.BYTES_PER_ELEMENT*4,e=c+a*Uint32Array.BYTES_PER_ELEMENT*4;L(a,b,c,e+a*Uint32Array.BYTES_PER_ELEMENT*4);v(a,e)}})(x);(function(b){var a=d.ntri_flat;a&&z(a,b,b+a*Uint32Array.BYTES_PER_ELEMENT*3)})(g);(function(b){var a=d.ntri_smooth;if(a){var c=b+a*Uint32Array.BYTES_PER_ELEMENT*3;K(a,b,c,c+a*Uint32Array.BYTES_PER_ELEMENT*3)}})(C);(function(b){var a=d.nquad_flat;a&&B(a,b,b+a*Uint32Array.BYTES_PER_ELEMENT*
4)})(F);(function(b){var a=d.nquad_smooth;if(a){var c=b+a*Uint32Array.BYTES_PER_ELEMENT*4;L(a,b,c,c+a*Uint32Array.BYTES_PER_ELEMENT*4)}})(G);this.computeFaceNormals()};n.prototype=Object.create(THREE.Geometry.prototype);n.prototype.constructor=n;n=new n;v=THREE.Loader.prototype.initMaterials(z,v,this.crossOrigin);B(n,v)}};