void 0===THREE.LoaderSupport&&(THREE.LoaderSupport={});THREE.LoaderSupport.Validator={isValid:function(b){return null!==b&&void 0!==b},verifyInput:function(b,c){return null===b||void 0===b?c:b}};
THREE.LoaderSupport.Callbacks=function(){function b(){this.onLoadMaterials=this.onLoad=this.onMeshAlter=this.onProgress=null}var c=THREE.LoaderSupport.Validator;b.prototype.setCallbackOnProgress=function(a){this.onProgress=c.verifyInput(a,this.onProgress)};b.prototype.setCallbackOnMeshAlter=function(a){this.onMeshAlter=c.verifyInput(a,this.onMeshAlter)};b.prototype.setCallbackOnLoad=function(a){this.onLoad=c.verifyInput(a,this.onLoad)};b.prototype.setCallbackOnLoadMaterials=function(a){this.onLoadMaterials=
c.verifyInput(a,this.onLoadMaterials)};return b}();THREE.LoaderSupport.LoadedMeshUserOverride=function(){function b(c,a){this.disregardMesh=!0===c;this.alteredMesh=!0===a;this.meshes=[]}b.prototype.addMesh=function(c){this.meshes.push(c);this.alteredMesh=!0};b.prototype.isDisregardMesh=function(){return this.disregardMesh};b.prototype.providesAlteredMeshes=function(){return this.alteredMesh};return b}();
THREE.LoaderSupport.ResourceDescriptor=function(){function b(a,d){var e=a.split("/");2>e.length?(this.path=null,this.name=a):(this.path=c.verifyInput(e.slice(0,e.length-1).join("/")+"/",null),this.name=c.verifyInput(e[e.length-1],null));this.url=a;this.extension=c.verifyInput(d,"default");this.extension=this.extension.trim();this.content=null}var c=THREE.LoaderSupport.Validator;b.prototype.setContent=function(a){this.content=c.verifyInput(a,null)};return b}();
THREE.LoaderSupport.PrepData=function(){function b(a){this.logging={enabled:!0,debug:!1};this.modelName=c.verifyInput(a,"");this.resources=[];this.callbacks=new THREE.LoaderSupport.Callbacks}var c=THREE.LoaderSupport.Validator;b.prototype.setLogging=function(a,d){this.logging.enabled=!0===a;this.logging.debug=!0===d};b.prototype.getCallbacks=function(){return this.callbacks};b.prototype.addResource=function(a){this.resources.push(a)};b.prototype.clone=function(){var a=new THREE.LoaderSupport.PrepData(this.modelName);
a.logging.enabled=this.logging.enabled;a.logging.debug=this.logging.debug;a.resources=this.resources;a.callbacks=this.callbacks;var d,e;for(d in this)e=this[d],a.hasOwnProperty(d)||"function"===typeof this[d]||(a[d]=e);return a};b.prototype.checkResourceDescriptorFiles=function(a,d){var e,f,g,k,b={},h;for(h in a)if(e=a[h],k=!1,c.isValid(e.name)){if(c.isValid(e.content))for(g=0;g<d.length&&!k;g++){if(f=d[g],e.extension.toLowerCase()===f.ext.toLowerCase())if(f.ignore)k=!0;else if("ArrayBuffer"===f.type){if(!(e.content instanceof
ArrayBuffer||e.content instanceof Uint8Array))throw"Provided content is not of type ArrayBuffer! Aborting...";b[f.ext]=e;k=!0}else if("String"===f.type){if(!("string"===typeof e.content||e.content instanceof String))throw"Provided  content is not of type String! Aborting...";b[f.ext]=e;k=!0}}else{if(!("string"===typeof e.name||e.name instanceof String))throw"Provided file is not properly defined! Aborting...";for(g=0;g<d.length&&!k;g++)f=d[g],e.extension.toLowerCase()===f.ext.toLowerCase()&&(f.ignore||
(b[f.ext]=e),k=!0)}if(!k)throw'Unidentified resource "'+e.name+'": '+e.url;}return b};return b}();
THREE.LoaderSupport.MeshBuilder=function(){function b(){console.info("Using THREE.LoaderSupport.MeshBuilder version: 1.2.0");this.logging={enabled:!0,debug:!1};this.callbacks=new THREE.LoaderSupport.Callbacks;this.materials=[]}var c=THREE.LoaderSupport.Validator;b.prototype.setLogging=function(a,d){this.logging.enabled=!0===a;this.logging.debug=!0===d};b.prototype.init=function(){var a=new THREE.MeshStandardMaterial({color:14479871});a.name="defaultMaterial";var d=new THREE.MeshStandardMaterial({color:14479871});
d.name="defaultVertexColorMaterial";d.vertexColors=THREE.VertexColors;var e=new THREE.LineBasicMaterial;e.name="defaultLineMaterial";var c=new THREE.PointsMaterial({size:1});c.name="defaultPointMaterial";var g={};g[a.name]=a;g[d.name]=d;g[e.name]=e;g[c.name]=c;this.updateMaterials({cmd:"materialData",materials:{materialCloneInstructions:null,serializedMaterials:null,runtimeMaterials:g}})};b.prototype.setMaterials=function(a){a={cmd:"materialData",materials:{materialCloneInstructions:null,serializedMaterials:null,
runtimeMaterials:c.isValid(this.callbacks.onLoadMaterials)?this.callbacks.onLoadMaterials(a):a}};this.updateMaterials(a)};b.prototype._setCallbacks=function(a){c.isValid(a.onProgress)&&this.callbacks.setCallbackOnProgress(a.onProgress);c.isValid(a.onMeshAlter)&&this.callbacks.setCallbackOnMeshAlter(a.onMeshAlter);c.isValid(a.onLoad)&&this.callbacks.setCallbackOnLoad(a.onLoad);c.isValid(a.onLoadMaterials)&&this.callbacks.setCallbackOnLoadMaterials(a.onLoadMaterials)};b.prototype.processPayload=function(a){if("meshData"===
a.cmd)return this.buildMeshes(a);if("materialData"===a.cmd)return this.updateMaterials(a),null};b.prototype.buildMeshes=function(a){var d=a.params.meshName,e=new THREE.BufferGeometry;e.addAttribute("position",new THREE.BufferAttribute(new Float32Array(a.buffers.vertices),3));c.isValid(a.buffers.indices)&&e.setIndex(new THREE.BufferAttribute(new Uint32Array(a.buffers.indices),1));c.isValid(a.buffers.colors)&&e.addAttribute("color",new THREE.BufferAttribute(new Float32Array(a.buffers.colors),3));c.isValid(a.buffers.normals)?
e.addAttribute("normal",new THREE.BufferAttribute(new Float32Array(a.buffers.normals),3)):e.computeVertexNormals();c.isValid(a.buffers.uvs)&&e.addAttribute("uv",new THREE.BufferAttribute(new Float32Array(a.buffers.uvs),2));var f,g,b=a.materials.materialNames,n=a.materials.multiMaterial,h=[];for(g in b)f=b[g],f=this.materials[f],n&&h.push(f);if(n)for(g in f=h,b=a.materials.materialGroups,b)n=b[g],e.addGroup(n.start,n.count,n.index);g=[];h=this.callbacks.onMeshAlter;b=!0;n=c.verifyInput(a.geometryType,
0);if(c.isValid(h)&&(h=h({detail:{meshName:d,bufferGeometry:e,material:f,geometryType:n}}),c.isValid(h))){if(!h.isDisregardMesh()&&h.providesAlteredMeshes())for(var l in h.meshes)g.push(h.meshes[l]);b=!1}b&&(a.computeBoundingSphere&&e.computeBoundingSphere(),e=0===n?new THREE.Mesh(e,f):1===n?new THREE.LineSegments(e,f):new THREE.Points(e,f),e.name=d,g.push(e));if(c.isValid(g)&&0<g.length){f=[];for(l in g)e=g[l],f[l]=e.name;l="Adding mesh(es) ("+f.length+": "+f+") from input mesh: "+d}else l="Not adding mesh: "+
d;l+=" ("+(100*a.progress.numericalValue).toFixed(2)+"%)";d=this.callbacks.onProgress;c.isValid(d)&&(a=new CustomEvent("MeshBuilderEvent",{detail:{type:"progress",modelName:a.params.meshName,text:l,numericalValue:a.progress.numericalValue}}),d(a));return g};b.prototype.updateMaterials=function(a){var d,e,b=a.materials.materialCloneInstructions;if(c.isValid(b)){d=b.materialNameOrg;var g=this.materials[d];if(c.isValid(d)){d=g.clone();e=b.materialName;d.name=e;var b=b.materialProperties,k;for(k in b)d.hasOwnProperty(k)&&
b.hasOwnProperty(k)&&(d[k]=b[k]);this.materials[e]=d}else console.warn('Requested material "'+d+'" is not available!')}k=a.materials.serializedMaterials;if(c.isValid(k)&&0<Object.keys(k).length)for(e in b=new THREE.MaterialLoader,k)d=k[e],c.isValid(d)&&(d=b.parse(d),this.logging.enabled&&console.info('De-serialized material with name "'+e+'" will be added.'),this.materials[e]=d);k=a.materials.runtimeMaterials;if(c.isValid(k)&&0<Object.keys(k).length)for(e in k)d=k[e],this.logging.enabled&&console.info('Material with name "'+
e+'" will be added.'),this.materials[e]=d};b.prototype.getMaterialsJSON=function(){var a={},d,c;for(c in this.materials)d=this.materials[c],a[c]=d.toJSON();return a};b.prototype.getMaterials=function(){return this.materials};return b}();
THREE.LoaderSupport.WorkerRunnerRefImpl=function(){function b(){var c=this;self.addEventListener("message",function(a){c.processMessage(a.data)},!1)}b.prototype.applyProperties=function(c,a){var d,b,f;for(d in a)if(b="set"+d.substring(0,1).toLocaleUpperCase()+d.substring(1),f=a[d],"function"===typeof c[b])c[b](f);else c.hasOwnProperty(d)&&(c[d]=f)};b.prototype.processMessage=function(c){if("run"===c.cmd){var a={callbackMeshBuilder:function(a){self.postMessage(a)},callbackProgress:function(a){c.logging.enabled&&
c.logging.debug&&console.debug("WorkerRunner: progress: "+a)}},d=new Parser;"function"===typeof d.setLogging&&d.setLogging(c.logging.enabled,c.logging.debug);this.applyProperties(d,c.params);this.applyProperties(d,c.materials);this.applyProperties(d,a);d.workerScope=self;d.parse(c.data.input,c.data.options);c.logging.enabled&&console.log("WorkerRunner: Run complete!");a.callbackMeshBuilder({cmd:"complete",msg:"WorkerRunner completed run."})}else console.error("WorkerRunner: Received unknown command: "+
c.cmd)};return b}();
THREE.LoaderSupport.WorkerSupport=function(){function b(){console.info("Using THREE.LoaderSupport.WorkerSupport version: 2.2.0");this.logging={enabled:!0,debug:!1};if(void 0===window.Worker)throw"This browser does not support web workers!";if(void 0===window.Blob)throw"This browser does not support Blob!";if("function"!==typeof window.URL.createObjectURL)throw"This browser does not support Object creation from URL!";this.loaderWorker=new a}var c=THREE.LoaderSupport.Validator,a=function(){function a(){this._reset()}
a.prototype._reset=function(){this.logging={enabled:!0,debug:!1};this.runnerImplName=this.worker=null;this.callbacks={meshBuilder:null,onLoad:null};this.terminateRequested=!1;this.queuedMessage=null;this.forceCopy=this.started=!1};a.prototype.setLogging=function(a,d){this.logging.enabled=!0===a;this.logging.debug=!0===d};a.prototype.setForceCopy=function(a){this.forceCopy=!0===a};a.prototype.initWorker=function(a,d){this.runnerImplName=d;var c=new Blob([a],{type:"application/javascript"});this.worker=
new Worker(window.URL.createObjectURL(c));this.worker.onmessage=this._receiveWorkerMessage;this.worker.runtimeRef=this;this._postMessage()};a.prototype._receiveWorkerMessage=function(a){a=a.data;switch(a.cmd){case "meshData":case "materialData":case "imageData":this.runtimeRef.callbacks.meshBuilder(a);break;case "complete":this.runtimeRef.queuedMessage=null;this.started=!1;this.runtimeRef.callbacks.onLoad(a.msg);this.runtimeRef.terminateRequested&&(this.runtimeRef.logging.enabled&&console.info("WorkerSupport ["+
this.runtimeRef.runnerImplName+"]: Run is complete. Terminating application on request!"),this.runtimeRef._terminate());break;case "error":console.error("WorkerSupport ["+this.runtimeRef.runnerImplName+"]: Reported error: "+a.msg);this.runtimeRef.queuedMessage=null;this.started=!1;this.runtimeRef.callbacks.onLoad(a.msg);this.runtimeRef.terminateRequested&&(this.runtimeRef.logging.enabled&&console.info("WorkerSupport ["+this.runtimeRef.runnerImplName+"]: Run reported error. Terminating application on request!"),
this.runtimeRef._terminate());break;default:console.error("WorkerSupport ["+this.runtimeRef.runnerImplName+"]: Received unknown command: "+a.cmd)}};a.prototype.setCallbacks=function(a,d){this.callbacks.meshBuilder=c.verifyInput(a,this.callbacks.meshBuilder);this.callbacks.onLoad=c.verifyInput(d,this.callbacks.onLoad)};a.prototype.run=function(a){if(c.isValid(this.queuedMessage))console.warn("Already processing message. Rejecting new run instruction");else{this.queuedMessage=a;this.started=!0;if(!c.isValid(this.callbacks.meshBuilder))throw'Unable to run as no "MeshBuilder" callback is set.';
if(!c.isValid(this.callbacks.onLoad))throw'Unable to run as no "onLoad" callback is set.';"run"!==a.cmd&&(a.cmd="run");c.isValid(a.logging)?(a.logging.enabled=!0===a.logging.enabled,a.logging.debug=!0===a.logging.debug):a.logging={enabled:!0,debug:!1};this._postMessage()}};a.prototype._postMessage=function(){if(c.isValid(this.queuedMessage)&&c.isValid(this.worker))if(this.queuedMessage.data.input instanceof ArrayBuffer){var a;a=this.forceCopy?this.queuedMessage.data.input.slice(0):this.queuedMessage.data.input;
this.worker.postMessage(this.queuedMessage,[a])}else this.worker.postMessage(this.queuedMessage)};a.prototype.setTerminateRequested=function(a){(this.terminateRequested=!0===a)&&c.isValid(this.worker)&&!c.isValid(this.queuedMessage)&&this.started&&(this.logging.enabled&&console.info("Worker is terminated immediately as it is not running!"),this._terminate())};a.prototype._terminate=function(){this.worker.terminate();this._reset()};return a}();b.prototype.setLogging=function(a,d){this.logging.enabled=
!0===a;this.logging.debug=!0===d;this.loaderWorker.setLogging(this.logging.enabled,this.logging.debug)};b.prototype.setForceWorkerDataCopy=function(a){this.loaderWorker.setForceCopy(a)};b.prototype.validate=function(a,b,k,n,h){if(!c.isValid(this.loaderWorker.worker)){this.logging.enabled&&(console.info("WorkerSupport: Building worker code..."),console.time("buildWebWorkerCode"));c.isValid(h)?this.logging.enabled&&console.info('WorkerSupport: Using "'+h.name+'" as Runner class for worker.'):(h=THREE.LoaderSupport.WorkerRunnerRefImpl,
this.logging.enabled&&console.info('WorkerSupport: Using DEFAULT "THREE.LoaderSupport.WorkerRunnerRefImpl" as Runner class for worker.'));var l=a(d,e),l=l+("var Parser \x3d "+b+";\n\n"),l=l+e(h.name,h),l=l+("new "+h.name+"();\n\n"),m=this;if(c.isValid(k)&&0<k.length){var p="",q=function(a,d){if(0===d.length)m.loaderWorker.initWorker(p+l,h.name),m.logging.enabled&&console.timeEnd("buildWebWorkerCode");else{var c=new THREE.FileLoader;c.setPath(a);c.setResponseType("text");c.load(d[0],function(c){p+=
c;q(a,d)});d.shift()}};q(n,k)}else this.loaderWorker.initWorker(l,h.name),this.logging.enabled&&console.timeEnd("buildWebWorkerCode")}};b.prototype.setCallbacks=function(a,d){this.loaderWorker.setCallbacks(a,d)};b.prototype.run=function(a){this.loaderWorker.run(a)};b.prototype.setTerminateRequested=function(a){this.loaderWorker.setTerminateRequested(a)};var d=function(a,d){var c=a+" \x3d {\n",b,e;for(e in d)b=d[e],"string"===typeof b||b instanceof String?(b=b.replace("\n","\\n"),b=b.replace("\r",
"\\r"),c+="\t"+e+': "'+b+'",\n'):b instanceof Array?c+="\t"+e+": ["+b+"],\n":Number.isInteger(b)?c+="\t"+e+": "+b+",\n":"function"===typeof b&&(c+="\t"+e+": "+b+",\n");return c+"}\n\n"},e=function(a,d,b,e,h){var l="";b=c.isValid(b)?b:d.name;var m,p;h=c.verifyInput(h,[]);for(var q in d.prototype)m=d.prototype[q],"constructor"===q?(m=m.toString(),m=m.replace("function",""),p="\tfunction "+b+m+";\n\n"):"function"===typeof m&&0>h.indexOf(q)&&(m=m.toString(),l+="\t"+b+".prototype."+q+" \x3d "+m+";\n\n");
l=l+("\treturn "+b+";\n")+"})();\n\n";h="";c.isValid(e)&&(h=h+"\n"+(b+".prototype \x3d Object.create( "+e+".prototype );\n"),h+=b+".constructor \x3d "+b+";\n",h+="\n");c.isValid(p)?l=a+" \x3d (function () {\n\n"+h+p+l:(p=a+" \x3d (function () {\n\n"+(h+"\t"+d.prototype.constructor.toString()+"\n\n"),l=p+l);return l};return b}();
THREE.LoaderSupport.WorkerDirector=function(){function b(a){console.info("Using THREE.LoaderSupport.WorkerDirector version: 2.2.0");this.logging={enabled:!0,debug:!1};this.maxQueueSize=8192;this.maxWebWorkers=16;this.crossOrigin=null;if(!c.isValid(a))throw"Provided invalid classDef: "+a;this.workerDescription={classDef:a,globalCallbacks:{},workerSupports:{},forceWorkerDataCopy:!0};this.objectsCompleted=0;this.instructionQueue=[];this.instructionQueuePointer=0;this.callbackOnFinishedProcessing=null}
var c=THREE.LoaderSupport.Validator;b.prototype.setLogging=function(a,d){this.logging.enabled=!0===a;this.logging.debug=!0===d};b.prototype.getMaxQueueSize=function(){return this.maxQueueSize};b.prototype.getMaxWebWorkers=function(){return this.maxWebWorkers};b.prototype.setCrossOrigin=function(a){this.crossOrigin=a};b.prototype.setForceWorkerDataCopy=function(a){this.workerDescription.forceWorkerDataCopy=!0===a};b.prototype.prepareWorkers=function(a,d,b){c.isValid(a)&&(this.workerDescription.globalCallbacks=
a);this.maxQueueSize=Math.min(d,8192);this.maxWebWorkers=Math.min(b,16);this.maxWebWorkers=Math.min(this.maxWebWorkers,this.maxQueueSize);this.objectsCompleted=0;this.instructionQueue=[];for(a=this.instructionQueuePointer=0;a<this.maxWebWorkers;a++)d=new THREE.LoaderSupport.WorkerSupport,d.setLogging(this.logging.enabled,this.logging.debug),d.setForceWorkerDataCopy(this.workerDescription.forceWorkerDataCopy),this.workerDescription.workerSupports[a]={instanceNo:a,inUse:!1,terminateRequested:!1,workerSupport:d,
loader:null}};b.prototype.enqueueForRun=function(a){this.instructionQueue.length<this.maxQueueSize&&this.instructionQueue.push(a)};b.prototype.isRunning=function(){var a=Object.keys(this.workerDescription.workerSupports);return 0<this.instructionQueue.length&&this.instructionQueuePointer<this.instructionQueue.length||0<a.length};b.prototype.processQueue=function(){var a,b,c;for(c in this.workerDescription.workerSupports)b=this.workerDescription.workerSupports[c],b.inUse||(this.instructionQueuePointer<
this.instructionQueue.length?(a=this.instructionQueue[this.instructionQueuePointer],this._kickWorkerRun(a,b),this.instructionQueuePointer++):this._deregister(b));this.isRunning()||null===this.callbackOnFinishedProcessing||(this.callbackOnFinishedProcessing(),this.callbackOnFinishedProcessing=null)};b.prototype._kickWorkerRun=function(a,b){b.inUse=!0;b.workerSupport.setTerminateRequested(b.terminateRequested);this.logging.enabled&&console.info("\nAssigning next item from queue to worker (queue length: "+
this.instructionQueue.length+")\n\n");var e=this,f=a.getCallbacks(),g=this.workerDescription.globalCallbacks;b.loader=this._buildLoader(b.instanceNo);var k=new THREE.LoaderSupport.Callbacks;k.setCallbackOnLoad(function(a){if(c.isValid(g.onLoad))g.onLoad(a);if(c.isValid(f.onLoad))f.onLoad(a);e.objectsCompleted++;b.inUse=!1;e.processQueue()});k.setCallbackOnProgress(function(a){if(c.isValid(g.onProgress))g.onProgress(a);if(c.isValid(f.onProgress))f.onProgress(a)});k.setCallbackOnMeshAlter(function(a){if(c.isValid(g.onMeshAlter))g.onMeshAlter(a);
if(c.isValid(f.onMeshAlter))f.onMeshAlter(a)});a.callbacks=k;b.loader.run(a,b.workerSupport)};b.prototype._buildLoader=function(a){var b=this.workerDescription.classDef,e=Object.create(b.prototype);b.call(e,THREE.DefaultLoadingManager);if(!e.hasOwnProperty("instanceNo"))throw b.name+' has no property "instanceNo".';e.instanceNo=a;if(!e.hasOwnProperty("workerSupport"))throw b.name+' has no property "workerSupport".';if("function"!==typeof e.run)throw b.name+' has no function "run".';e.hasOwnProperty("callbacks")&&
c.isValid(e.callbacks)||(console.warn(b.name+' has an invalid property "callbacks". Will change to "THREE.LoaderSupport.Callbacks"'),e.callbacks=new THREE.LoaderSupport.Callbacks);return e};b.prototype._deregister=function(a){if(c.isValid(a)){a.workerSupport.setTerminateRequested(!0);this.logging.enabled&&console.info("Requested termination of worker #"+a.instanceNo+".");var b=a.loader.callbacks;if(c.isValid(b.onProgress))b.onProgress({detail:{text:""}});delete this.workerDescription.workerSupports[a.instanceNo]}};
b.prototype.tearDown=function(a){this.logging.enabled&&console.info("WorkerDirector received the deregister call. Terminating all workers!");this.instructionQueuePointer=this.instructionQueue.length;this.callbackOnFinishedProcessing=c.verifyInput(a,null);for(var b in this.workerDescription.workerSupports)this.workerDescription.workerSupports[b].terminateRequested=!0};return b}();