THREE.NRRDLoader=function(a){this.manager=void 0!==a?a:THREE.DefaultLoadingManager};
THREE.NRRDLoader.prototype={constructor:THREE.NRRDLoader,load:function(a,d,c,g){var e=this,b=new THREE.FileLoader(e.manager);b.setResponseType("arraybuffer");b.load(a,function(a){d(e.parse(a))},c,g)},parse:function(a){function d(a,c,e){var h="";c=c||0;e=e||a.length;var n=b.sizes.reduce(function(a,b){return a*b},1),d=10;"hex"===b.encoding&&(d=16);var n=new b.__array(n),g=0,f=parseInt;if(b.__array===Float32Array||b.__array===Float64Array)f=parseFloat;for(var k=c;k<e;k++)c=a[k],(9>c||13<c)&&32!==c?h+=
String.fromCharCode(c):(""!==h&&(n[g]=f(h,d),g++),h="");""!==h&&(n[g]=f(h,d),g++);return n}var c=a,g=0,e=0<(new Int8Array((new Int16Array([1])).buffer))[0],b={},f=function(a,b){if(void 0===b||null===b)b=1;var d=1,h=Uint8Array;switch(a){case "schar":h=Int8Array;break;case "ushort":h=Uint16Array;d=2;break;case "sshort":h=Int16Array;d=2;break;case "uint":h=Uint32Array;d=4;break;case "sint":h=Int32Array;d=4;break;case "float":h=Float32Array;d=4;break;case "complex":h=Float64Array;d=8;break;case "double":h=
Float64Array,d=8}h=new h(c.slice(g,g+=b*d));if(1!=e)for(var n=new Uint8Array(h.buffer,h.byteOffset,h.byteLength),f=0;f<h.byteLength;f+=d)for(var k=f+d-1,l=f;k>l;k--,l++){var m=n[l];n[l]=n[k];n[k]=m}return 1==b?h[0]:h}("uchar",a.byteLength),p=f.length,l=null,m=0;for(a=1;a<p;a++)if(10==f[a-1]&&10==f[a]){l=this.parseChars(f,0,a-2);m=a+1;break}(function(a){var c,d,h,e,f,g;a=a.split(/\r?\n/);f=0;for(g=a.length;f<g;f++)c=a[f],c.match(/NRRD\d+/)?b.isNrrd=!0:!c.match(/^#/)&&(e=c.match(/(.*):(.*)/))&&(d=e[1].trim(),
c=e[2].trim(),(h=THREE.NRRDLoader.prototype.fieldFunctions[d])?h.call(b,c):b[d]=c);if(!b.isNrrd)throw Error("Not an NRRD file");if("bz2"===b.encoding||"bzip2"===b.encoding)throw Error("Bzip is not supported");if(!b.vectors&&(b.vectors=[new THREE.Vector3(1,0,0),new THREE.Vector3(0,1,0),new THREE.Vector3(0,0,1)],b.spacings))for(e=0;2>=e;e++)isNaN(b.spacings[e])||b.vectors[e].multiplyScalar(b.spacings[e])})(l);c=f.subarray(m);if("gzip"===b.encoding||"gz"===b.encoding)c=(new Zlib.Gunzip(new Uint8Array(c))).decompress();
else if("ascii"===b.encoding||"text"===b.encoding||"txt"===b.encoding||"hex"===b.encoding)c=d(c);else if("raw"===b.encoding){f=new Uint8Array(c.length);for(a=0;a<c.length;a++)f[a]=c[a];c=f}c=c.buffer;a=new THREE.Volume;a.header=b;a.data=new b.__array(c);p=a.computeMinMax();f=p[0];p=p[1];a.windowLow=f;a.windowHigh=p;a.dimensions=[b.sizes[0],b.sizes[1],b.sizes[2]];a.xLength=a.dimensions[0];a.yLength=a.dimensions[1];a.zLength=a.dimensions[2];var l=(new THREE.Vector3(b.vectors[0][0],b.vectors[0][1],b.vectors[0][2])).length(),
m=(new THREE.Vector3(b.vectors[1][0],b.vectors[1][1],b.vectors[1][2])).length(),k=(new THREE.Vector3(b.vectors[2][0],b.vectors[2][1],b.vectors[2][2])).length();a.spacing=[l,m,k];a.matrix=new THREE.Matrix4;m=l=1;"left-posterior-superior"==b.space?m=l=-1:"left-anterior-superior"===b.space&&(l=-1);b.vectors?(k=b.vectors,a.matrix.set(l*k[0][0],l*k[1][0],l*k[2][0],0,m*k[0][1],m*k[1][1],m*k[2][1],0,1*k[0][2],1*k[1][2],1*k[2][2],0,0,0,0,1)):a.matrix.set(l,0,0,0,0,m,0,0,0,0,1,0,0,0,0,1);a.inverseMatrix=new THREE.Matrix4;
a.inverseMatrix.getInverse(a.matrix);a.RASDimensions=(new THREE.Vector3(a.xLength,a.yLength,a.zLength)).applyMatrix4(a.matrix).round().toArray().map(Math.abs);-Infinity===a.lowerThreshold&&(a.lowerThreshold=f);Infinity===a.upperThreshold&&(a.upperThreshold=p);return a},parseChars:function(a,d,c){void 0===d&&(d=0);void 0===c&&(c=a.length);for(var g="",e=0,e=d;e<c;++e)g+=String.fromCharCode(a[e]);return g},fieldFunctions:{type:function(a){switch(a){case "uchar":case "unsigned char":case "uint8":case "uint8_t":this.__array=
Uint8Array;break;case "signed char":case "int8":case "int8_t":this.__array=Int8Array;break;case "short":case "short int":case "signed short":case "signed short int":case "int16":case "int16_t":this.__array=Int16Array;break;case "ushort":case "unsigned short":case "unsigned short int":case "uint16":case "uint16_t":this.__array=Uint16Array;break;case "int":case "signed int":case "int32":case "int32_t":this.__array=Int32Array;break;case "uint":case "unsigned int":case "uint32":case "uint32_t":this.__array=
Uint32Array;break;case "float":this.__array=Float32Array;break;case "double":this.__array=Float64Array;break;default:throw Error("Unsupported NRRD data type: "+a);}return this.type=a},endian:function(a){return this.endian=a},encoding:function(a){return this.encoding=a},dimension:function(a){return this.dim=parseInt(a,10)},sizes:function(a){var d,c,g,e;g=a.split(/\s+/);e=[];d=0;for(c=g.length;d<c;d++)a=g[d],e.push(parseInt(a,10));return this.sizes=e},space:function(a){return this.space=a},"space origin":function(a){return this.space_origin=
a.split("(")[1].split(")")[0].split(",")},"space directions":function(a){var d,c,g;c=a.match(/\(.*?\)/g);return this.vectors=function(){var a,b,f;f=[];a=0;for(b=c.length;a<b;a++)g=c[a],f.push(function(){var a,b,c,e;c=g.slice(1,-1).split(/,/);e=[];a=0;for(b=c.length;a<b;a++)d=c[a],e.push(parseFloat(d));return e}());return f}()},spacings:function(a){var d;d=a.split(/\s+/);var c,g,e=[];c=0;for(g=d.length;c<g;c++)a=d[c],e.push(parseFloat(a));return this.spacings=e}}};