THREE.TDSLoader=function(a){this.manager=void 0!==a?a:THREE.DefaultLoadingManager;this.debug=!1;this.group=null;this.position=0;this.materials=[];this.meshes=[]};
THREE.TDSLoader.prototype={constructor:THREE.TDSLoader,load:function(a,b,d,c){var e=this,g=void 0!==this.path?this.path:THREE.LoaderUtils.extractUrlBase(a),f=new THREE.FileLoader(this.manager);f.setResponseType("arraybuffer");f.load(a,function(a){b(e.parse(a,g))},d,c)},parse:function(a,b){this.group=new THREE.Group;this.position=0;this.materials=[];this.meshes=[];this.readFile(a,b);for(var d=0;d<this.meshes.length;d++)this.group.add(this.meshes[d]);return this.group},readFile:function(a,b){var d=
new DataView(a),c=this.readChunk(d);if(c.id===MLIBMAGIC||c.id===CMAGIC||c.id===M3DMAGIC)for(var e=this.nextChunk(d,c);0!==e;)e===M3D_VERSION?(e=this.readDWord(d),this.debugMessage("3DS file version: "+e)):e===MDATA?(this.resetPosition(d),this.readMeshData(d,b)):this.debugMessage("Unknown main chunk: "+e.toString(16)),e=this.nextChunk(d,c);this.debugMessage("Parsed "+this.meshes.length+" meshes")},readMeshData:function(a,b){for(var d=this.readChunk(a),c=this.nextChunk(a,d);0!==c;)c===MESH_VERSION?
(c=+this.readDWord(a),this.debugMessage("Mesh Version: "+c)):c===MASTER_SCALE?(c=this.readFloat(a),this.debugMessage("Master scale: "+c),this.group.scale.set(c,c,c)):c===NAMED_OBJECT?(this.debugMessage("Named Object"),this.resetPosition(a),this.readNamedObject(a)):c===MAT_ENTRY?(this.debugMessage("Material"),this.resetPosition(a),this.readMaterialEntry(a,b)):this.debugMessage("Unknown MDATA chunk: "+c.toString(16)),c=this.nextChunk(a,d)},readNamedObject:function(a){var b=this.readChunk(a),d=this.readString(a,
64);b.cur=this.position;for(var c=this.nextChunk(a,b);0!==c;)c===N_TRI_OBJECT?(this.resetPosition(a),c=this.readMesh(a),c.name=d,this.meshes.push(c)):this.debugMessage("Unknown named object chunk: "+c.toString(16)),c=this.nextChunk(a,b);this.endChunk(b)},readMaterialEntry:function(a,b){for(var d=this.readChunk(a),c=this.nextChunk(a,d),e=new THREE.MeshPhongMaterial;0!==c;)c===MAT_NAME?(e.name=this.readString(a,64),this.debugMessage("   Name: "+e.name)):c===MAT_WIRE?(this.debugMessage("   Wireframe"),
e.wireframe=!0):c===MAT_WIRE_SIZE?(c=this.readByte(a),e.wireframeLinewidth=c,this.debugMessage("   Wireframe Thickness: "+c)):c===MAT_TWO_SIDE?(e.side=THREE.DoubleSide,this.debugMessage("   DoubleSided")):c===MAT_ADDITIVE?(this.debugMessage("   Additive Blending"),e.blending=THREE.AdditiveBlending):c===MAT_DIFFUSE?(this.debugMessage("   Diffuse Color"),e.color=this.readColor(a)):c===MAT_SPECULAR?(this.debugMessage("   Specular Color"),e.specular=this.readColor(a)):c===MAT_AMBIENT?(this.debugMessage("   Ambient color"),
e.color=this.readColor(a)):c===MAT_SHININESS?(c=this.readWord(a),e.shininess=c,this.debugMessage("   Shininess : "+c)):c===MAT_TEXMAP?(this.debugMessage("   ColorMap"),this.resetPosition(a),e.map=this.readMap(a,b)):c===MAT_BUMPMAP?(this.debugMessage("   BumpMap"),this.resetPosition(a),e.bumpMap=this.readMap(a,b)):c===MAT_OPACMAP?(this.debugMessage("   OpacityMap"),this.resetPosition(a),e.alphaMap=this.readMap(a,b)):c===MAT_SPECMAP?(this.debugMessage("   SpecularMap"),this.resetPosition(a),e.specularMap=
this.readMap(a,b)):this.debugMessage("   Unknown material chunk: "+c.toString(16)),c=this.nextChunk(a,d);this.endChunk(d);this.materials[e.name]=e},readMesh:function(a){var b,d=this.readChunk(a);b=this.nextChunk(a,d);var c=null,e=[],c=new THREE.Geometry,g=new THREE.MeshPhongMaterial,g=new THREE.Mesh(c,g);for(g.name="mesh";0!==b;){if(b===POINT_ARRAY){var f=this.readWord(a);this.debugMessage("   Vertex: "+f);for(b=0;b<f;b++)c.vertices.push(new THREE.Vector3(this.readFloat(a),this.readFloat(a),this.readFloat(a)))}else if(b===
FACE_ARRAY)this.resetPosition(a),this.readFaceArray(a,g);else if(b===TEX_VERTS)for(f=this.readWord(a),this.debugMessage("   UV: "+f),e=[],b=0;b<f;b++)e.push(new THREE.Vector2(this.readFloat(a),this.readFloat(a)));else if(b===MESH_MATRIX){this.debugMessage("   Tranformation Matrix (TODO)");f=[];for(b=0;12>b;b++)f[b]=this.readFloat(a);b=new THREE.Matrix4;b.elements[0]=f[0];b.elements[1]=f[6];b.elements[2]=f[3];b.elements[3]=f[9];b.elements[4]=f[2];b.elements[5]=f[8];b.elements[6]=f[5];b.elements[7]=
f[11];b.elements[8]=f[1];b.elements[9]=f[7];b.elements[10]=f[4];b.elements[11]=f[10];b.elements[12]=0;b.elements[13]=0;b.elements[14]=0;b.elements[15]=1;b.transpose();f=new THREE.Matrix4;f.getInverse(b,!0);c.applyMatrix(f);b.decompose(g.position,g.quaternion,g.scale)}else this.debugMessage("   Unknown mesh chunk: "+b.toString(16));b=this.nextChunk(a,d)}this.endChunk(d);if(0<e.length){a=[];for(b=0;b<c.faces.length;b++)a.push([e[c.faces[b].a],e[c.faces[b].b],e[c.faces[b].c]]);c.faceVertexUvs[0]=a}c.computeVertexNormals();
return g},readFaceArray:function(a,b){var d=this.readChunk(a),c=this.readWord(a);this.debugMessage("   Faces: "+c);for(var e=0;e<c;++e)b.geometry.faces.push(new THREE.Face3(this.readWord(a),this.readWord(a),this.readWord(a))),this.readWord(a);for(;this.position<d.end;)d=this.readChunk(a),d.id===MSH_MAT_GROUP?(this.debugMessage("      Material Group"),this.resetPosition(a),c=this.readMaterialGroup(a),c=this.materials[c.name],void 0!==c&&(b.material=c,""===c.name&&(c.name=b.name))):this.debugMessage("      Unknown face array chunk: "+
d.toString(16)),this.endChunk(d);this.endChunk(d)},readMap:function(a,b){var d=this.readChunk(a),c=this.nextChunk(a,d),e={},g=new THREE.TextureLoader(this.manager);for(g.setPath(b);0!==c;)c===MAT_MAPNAME?(c=this.readString(a,128),e=g.load(c),this.debugMessage("      File: "+b+c)):c===MAT_MAP_UOFFSET?(e.offset.x=this.readFloat(a),this.debugMessage("      OffsetX: "+e.offset.x)):c===MAT_MAP_VOFFSET?(e.offset.y=this.readFloat(a),this.debugMessage("      OffsetY: "+e.offset.y)):c===MAT_MAP_USCALE?(e.repeat.x=
this.readFloat(a),this.debugMessage("      RepeatX: "+e.repeat.x)):c===MAT_MAP_VSCALE?(e.repeat.y=this.readFloat(a),this.debugMessage("      RepeatY: "+e.repeat.y)):this.debugMessage("      Unknown map chunk: "+c.toString(16)),c=this.nextChunk(a,d);this.endChunk(d);return e},readMaterialGroup:function(a){this.readChunk(a);var b=this.readString(a,64),d=this.readWord(a);this.debugMessage("         Name: "+b);this.debugMessage("         Faces: "+d);for(var c=[],e=0;e<d;++e)c.push(this.readWord(a));return{name:b,
index:c}},readColor:function(a){var b=this.readChunk(a),d=new THREE.Color;if(b.id===COLOR_24||b.id===LIN_COLOR_24){var c=this.readByte(a),e=this.readByte(a);a=this.readByte(a);d.setRGB(c/255,e/255,a/255);this.debugMessage("      Color: "+d.r+", "+d.g+", "+d.b)}else b.id===COLOR_F||b.id===LIN_COLOR_F?(c=this.readFloat(a),e=this.readFloat(a),a=this.readFloat(a),d.setRGB(c,e,a),this.debugMessage("      Color: "+d.r+", "+d.g+", "+d.b)):this.debugMessage("      Unknown color chunk: "+b.toString(16));this.endChunk(b);
return d},readChunk:function(a){var b={};b.cur=this.position;b.id=this.readWord(a);b.size=this.readDWord(a);b.end=b.cur+b.size;b.cur+=6;return b},endChunk:function(a){this.position=a.end},nextChunk:function(a,b){if(b.cur>=b.end)return 0;this.position=b.cur;try{var d=this.readChunk(a);b.cur+=d.size;return d.id}catch(c){return this.debugMessage("Unable to read chunk at "+this.position),0}},resetPosition:function(){this.position-=6},readByte:function(a){a=a.getUint8(this.position,!0);this.position+=
1;return a},readFloat:function(a){try{var b=a.getFloat32(this.position,!0);this.position+=4;return b}catch(d){this.debugMessage(d+" "+this.position+" "+a.byteLength)}},readInt:function(a){a=a.getInt32(this.position,!0);this.position+=4;return a},readShort:function(a){a=a.getInt16(this.position,!0);this.position+=2;return a},readDWord:function(a){a=a.getUint32(this.position,!0);this.position+=4;return a},readWord:function(a){a=a.getUint16(this.position,!0);this.position+=2;return a},readString:function(a,
b){for(var d="",c=0;c<b;c++){var e=this.readByte(a);if(!e)break;d+=String.fromCharCode(e)}return d},setPath:function(a){this.path=a;return this},debugMessage:function(a){this.debug&&console.log(a)}};
var NULL_CHUNK=0,M3DMAGIC=19789,SMAGIC=11565,LMAGIC=11581,MLIBMAGIC=15786,MATMAGIC=15871,CMAGIC=49725,M3D_VERSION=2,M3D_KFVERSION=5,COLOR_F=16,COLOR_24=17,LIN_COLOR_24=18,LIN_COLOR_F=19,INT_PERCENTAGE=48,FLOAT_PERCENTAGE=49,MDATA=15677,MESH_VERSION=15678,MASTER_SCALE=256,LO_SHADOW_BIAS=5120,HI_SHADOW_BIAS=5136,SHADOW_MAP_SIZE=5152,SHADOW_SAMPLES=5168,SHADOW_RANGE=5184,SHADOW_FILTER=5200,RAY_BIAS=5216,O_CONSTS=5376,AMBIENT_LIGHT=8448,BIT_MAP=4352,SOLID_BGND=4608,V_GRADIENT=4864,USE_BIT_MAP=4353,USE_SOLID_BGND=
4609,USE_V_GRADIENT=4865,FOG=8704,FOG_BGND=8720,LAYER_FOG=8962,DISTANCE_CUE=8960,DCUE_BGND=8976,USE_FOG=8705,USE_LAYER_FOG=8963,USE_DISTANCE_CUE=8961,MAT_ENTRY=45055,MAT_NAME=40960,MAT_AMBIENT=40976,MAT_DIFFUSE=40992,MAT_SPECULAR=41008,MAT_SHININESS=41024,MAT_SHIN2PCT=41025,MAT_TRANSPARENCY=41040,MAT_XPFALL=41042,MAT_USE_XPFALL=41536,MAT_REFBLUR=41043,MAT_SHADING=41216,MAT_USE_REFBLUR=41552,MAT_SELF_ILLUM=41092,MAT_TWO_SIDE=41089,MAT_DECAL=41090,MAT_ADDITIVE=41091,MAT_WIRE=41093,MAT_FACEMAP=41096,
MAT_TRANSFALLOFF_IN=41098,MAT_PHONGSOFT=41100,MAT_WIREABS=41102,MAT_WIRE_SIZE=41095,MAT_TEXMAP=41472,MAT_SXP_TEXT_DATA=41760,MAT_TEXMASK=41790,MAT_SXP_TEXTMASK_DATA=41770,MAT_TEX2MAP=41786,MAT_SXP_TEXT2_DATA=41761,MAT_TEX2MASK=41792,MAT_SXP_TEXT2MASK_DATA=41772,MAT_OPACMAP=41488,MAT_SXP_OPAC_DATA=41762,MAT_OPACMASK=41794,MAT_SXP_OPACMASK_DATA=41774,MAT_BUMPMAP=41520,MAT_SXP_BUMP_DATA=41764,MAT_BUMPMASK=41796,MAT_SXP_BUMPMASK_DATA=41776,MAT_SPECMAP=41476,MAT_SXP_SPEC_DATA=41765,MAT_SPECMASK=41800,
MAT_SXP_SPECMASK_DATA=41778,MAT_SHINMAP=41788,MAT_SXP_SHIN_DATA=41766,MAT_SHINMASK=41798,MAT_SXP_SHINMASK_DATA=41780,MAT_SELFIMAP=41789,MAT_SXP_SELFI_DATA=41768,MAT_SELFIMASK=41802,MAT_SXP_SELFIMASK_DATA=41782,MAT_REFLMAP=41504,MAT_REFLMASK=41804,MAT_SXP_REFLMASK_DATA=41784,MAT_ACUBIC=41744,MAT_MAPNAME=41728,MAT_MAP_TILING=41809,MAT_MAP_TEXBLUR=41811,MAT_MAP_USCALE=41812,MAT_MAP_VSCALE=41814,MAT_MAP_UOFFSET=41816,MAT_MAP_VOFFSET=41818,MAT_MAP_ANG=41820,MAT_MAP_COL1=41824,MAT_MAP_COL2=41826,MAT_MAP_RCOL=
41828,MAT_MAP_GCOL=41830,MAT_MAP_BCOL=41832,NAMED_OBJECT=16384,N_DIRECT_LIGHT=17920,DL_OFF=17952,DL_OUTER_RANGE=18010,DL_INNER_RANGE=18009,DL_MULTIPLIER=18011,DL_EXCLUDE=18004,DL_ATTENUATE=17957,DL_SPOTLIGHT=17936,DL_SPOT_ROLL=18006,DL_SHADOWED=17968,DL_LOCAL_SHADOW2=17985,DL_SEE_CONE=18E3,DL_SPOT_RECTANGULAR=18001,DL_SPOT_ASPECT=18007,DL_SPOT_PROJECTOR=18003,DL_SPOT_OVERSHOOT=18002,DL_RAY_BIAS=18008,DL_RAYSHAD=17959,N_CAMERA=18176,CAM_SEE_CONE=18192,CAM_RANGES=18208,OBJ_HIDDEN=16400,OBJ_VIS_LOFTER=
16401,OBJ_DOESNT_CAST=16402,OBJ_DONT_RECVSHADOW=16407,OBJ_MATTE=16403,OBJ_FAST=16404,OBJ_PROCEDURAL=16405,OBJ_FROZEN=16406,N_TRI_OBJECT=16640,POINT_ARRAY=16656,POINT_FLAG_ARRAY=16657,FACE_ARRAY=16672,MSH_MAT_GROUP=16688,SMOOTH_GROUP=16720,MSH_BOXMAP=16784,TEX_VERTS=16704,MESH_MATRIX=16736,MESH_COLOR=16741,MESH_TEXTURE_INFO=16752,KFDATA=45056,KFHDR=45066,KFSEG=45064,KFCURTIME=45065,AMBIENT_NODE_TAG=45057,OBJECT_NODE_TAG=45058,CAMERA_NODE_TAG=45059,TARGET_NODE_TAG=45060,LIGHT_NODE_TAG=45061,L_TARGET_NODE_TAG=
45062,SPOTLIGHT_NODE_TAG=45063,NODE_ID=45104,NODE_HDR=45072,PIVOT=45075,INSTANCE_NAME=45073,MORPH_SMOOTH=45077,BOUNDBOX=45076,POS_TRACK_TAG=45088,COL_TRACK_TAG=45093,ROT_TRACK_TAG=45089,SCL_TRACK_TAG=45090,MORPH_TRACK_TAG=45094,FOV_TRACK_TAG=45091,ROLL_TRACK_TAG=45092,HOT_TRACK_TAG=45095,FALL_TRACK_TAG=45096,HIDE_TRACK_TAG=45097,POLY_2D=20480,SHAPE_OK=20496,SHAPE_NOT_OK=20497,SHAPE_HOOK=20512,PATH_3D=24576,PATH_MATRIX=24581,SHAPE_2D=24592,M_SCALE=24608,M_TWIST=24624,M_TEETER=24640,M_FIT=24656,M_BEVEL=
24672,XZ_CURVE=24688,YZ_CURVE=24704,INTERPCT=24720,DEFORM_LIMIT=24736,USE_CONTOUR=24832,USE_TWEEN=24848,USE_SCALE=24864,USE_TWIST=24880,USE_TEETER=24896,USE_FIT=24912,USE_BEVEL=24928,DEFAULT_VIEW=12288,VIEW_TOP=12304,VIEW_BOTTOM=12320,VIEW_LEFT=12336,VIEW_RIGHT=12352,VIEW_FRONT=12368,VIEW_BACK=12384,VIEW_USER=12400,VIEW_CAMERA=12416,VIEW_WINDOW=12432,VIEWPORT_LAYOUT_OLD=28672,VIEWPORT_DATA_OLD=28688,VIEWPORT_LAYOUT=28673,VIEWPORT_DATA=28689,VIEWPORT_DATA_3=28690,VIEWPORT_SIZE=28704,NETWORK_VIEW=28720;