THREE.VRMLLoader=function(e){this.manager=void 0!==e?e:THREE.DefaultLoadingManager};
THREE.VRMLLoader.prototype={constructor:THREE.VRMLLoader,isRecordingPoints:!1,isRecordingFaces:!1,points:[],indexes:[],isRecordingAngles:!1,isRecordingColors:!1,angles:[],colors:[],recordingFieldname:null,crossOrigin:"Anonymous",load:function(e,t,y,x){var u=this;(new THREE.FileLoader(this.manager)).load(e,function(e){t(u.parse(e))},y,x)},setCrossOrigin:function(e){this.crossOrigin=e},parse:function(e){function t(e,m){function r(b,h,a,d,c){for(var e=!0===c?1:-1,f=[],n,l={},m=!1,l=0;l<a.length;l++)f.push({x:e*
Math.cos(a[l])*h,y:e*Math.sin(a[l])*h});a=b.index;for(var e=b.attributes.position,k=new THREE.BufferAttribute(new Float32Array(3*b.attributes.position.count),3),g=new THREE.Vector3,q=new THREE.Color,u=0;u<a.count;u++){var p=a.getX(u);g.fromBufferAttribute(e,p);for(var v=0;v<d.length;v++)n=0===v?!0===c?h:-1*h:f[v-1].y,l=f[v],void 0!==l&&(m=!0===c?g.y<=n&&g.y>l.y:g.y>=n&&g.y<l.y,!0===m?(m=d[v+1],l=Math.abs(g.y-n)/(n-l.y),q.copy(d[v]).lerp(m,l),k.setXYZ(p,q.r,q.g,q.b)):(l=d[!0===c?d.length-1:0],k.setXYZ(p,
l.r,l.g,l.b)))}b.addAttribute("color",k)}function k(b,h){for(var a=[],d,c={},e=/[^\s,\[\]]+/g;null!==(d=e.exec(h));)a.push(d[0]);d=a[0];switch(d){case "skyAngle":case "groundAngle":this.recordingFieldname=d;this.isRecordingAngles=!0;this.angles=[];break;case "skyColor":case "groundColor":this.recordingFieldname=d;this.isRecordingColors=!0;this.colors=[];break;case "point":this.recordingFieldname=d;this.isRecordingPoints=!0;this.points=[];break;case "coordIndex":case "texCoordIndex":this.recordingFieldname=
d,this.isRecordingFaces=!0,this.indexes=[]}if(this.isRecordingFaces){if(0<a.length)for(d=0;d<a.length;d++)/(-?\d+)/.test(a[d])&&("-1"===a[d]?(0<p.length&&this.indexes.push(p),p=[]):p.push(parseInt(a[d])));/]/.exec(h)&&(0<p.length&&this.indexes.push(p),p=[],this.isRecordingFaces=!1,b[this.recordingFieldname]=this.indexes)}else if(this.isRecordingPoints){if("Coordinate"==b.nodeType)for(;null!==(a=w.exec(h));)a={x:parseFloat(a[1]),y:parseFloat(a[2]),z:parseFloat(a[3])},this.points.push(a);if("TextureCoordinate"==
b.nodeType)for(;null!==(a=A.exec(h));)a={x:parseFloat(a[1]),y:parseFloat(a[2])},this.points.push(a);/]/.exec(h)&&(this.isRecordingPoints=!1,b.points=this.points)}else if(this.isRecordingAngles){if(0<a.length)for(d=0;d<a.length;d++)t.test(a[d])&&this.angles.push(parseFloat(a[d]));/]/.exec(h)&&(this.isRecordingAngles=!1,b[this.recordingFieldname]=this.angles)}else if(this.isRecordingColors){for(;null!==(a=w.exec(h));)a={r:parseFloat(a[1]),g:parseFloat(a[2]),b:parseFloat(a[3])},this.colors.push(a);/]/.exec(h)&&
(this.isRecordingColors=!1,b[this.recordingFieldname]=this.colors)}else if("NULL"!==a[a.length-1]&&"children"!==d){switch(d){case "diffuseColor":case "emissiveColor":case "specularColor":case "color":if(4!==a.length){console.warn("THREE.VRMLLoader: Invalid color format detected for %s.",d);break}c={r:parseFloat(a[1]),g:parseFloat(a[2]),b:parseFloat(a[3])};break;case "location":case "direction":case "translation":case "scale":case "size":if(4!==a.length){console.warn("THREE.VRMLLoader: Invalid vector format detected for %s.",
d);break}c={x:parseFloat(a[1]),y:parseFloat(a[2]),z:parseFloat(a[3])};break;case "intensity":case "cutOffAngle":case "radius":case "topRadius":case "bottomRadius":case "height":case "transparency":case "shininess":case "ambientIntensity":if(2!==a.length){console.warn("THREE.VRMLLoader: Invalid single float value specification detected for %s.",d);break}c=parseFloat(a[1]);break;case "rotation":if(5!==a.length){console.warn("THREE.VRMLLoader: Invalid quaternion format detected for %s.",d);break}c={x:parseFloat(a[1]),
y:parseFloat(a[2]),z:parseFloat(a[3]),w:parseFloat(a[4])};break;case "on":case "ccw":case "solid":case "colorPerVertex":case "convex":2!==a.length?console.warn("THREE.VRMLLoader: Invalid format detected for %s.",d):c="TRUE"===a[1]?!0:!1}b[d]=c}return c}function u(b,h){var a;if("string"===typeof b){if(/USE/.exec(b)){var d=/USE\s+?([^\s]+)/.exec(b)[1];void 0==q[d]?console.warn("THREE.VRMLLoader: %s is not defined.",d):/appearance/.exec(b)&&d?h.material=q[d].clone():/geometry/.exec(b)&&d?(h.geometry=
q[d].clone(),void 0!==q[d].solid&&!1===q[d].solid&&(h.geometry.solid=!1,h.material.side=THREE.DoubleSide)):d&&(a=q[d].clone(),h.add(a))}}else{a=h;-1<b.string.indexOf("AmbientLight")&&"PointLight"===b.nodeType&&(b.nodeType="AmbientLight");var c=void 0!==b.on?b.on:!0,e=void 0!==b.intensity?b.intensity:1,f=new THREE.Color;b.color&&f.copy(b.color);if("AmbientLight"===b.nodeType)a=new THREE.AmbientLight(f,e),a.visible=c,h.add(a);else if("PointLight"===b.nodeType)a=0,void 0!==b.radius&&1E3>b.radius&&(a=
b.radius),a=new THREE.PointLight(f,e,a),a.visible=c,h.add(a);else if("SpotLight"===b.nodeType)a=0,e=Math.PI/3,c=!0,void 0!==b.radius&&1E3>b.radius&&(a=b.radius),void 0!==b.cutOffAngle&&(e=b.cutOffAngle),a=new THREE.SpotLight(f,1,a,e,0),a.visible=c,h.add(a);else if("Transform"===b.nodeType||"Group"===b.nodeType)a=new THREE.Object3D,/DEF/.exec(b.string)&&(a.name=/DEF\s+([^\s]+)/.exec(b.string)[1],q[a.name]=a),void 0!==b.translation&&(f=b.translation,a.position.set(f.x,f.y,f.z)),void 0!==b.rotation&&
(c=b.rotation,a.quaternion.setFromAxisAngle(new THREE.Vector3(c.x,c.y,c.z),c.w)),void 0!==b.scale&&(f=b.scale,a.scale.set(f.x,f.y,f.z)),h.add(a);else if("Shape"===b.nodeType)a=new THREE.Mesh,/DEF/.exec(b.string)&&(a.name=/DEF\s+([^\s]+)/.exec(b.string)[1],q[a.name]=a),h.add(a);else if("Background"===b.nodeType)c=2E4,f=new THREE.SphereBufferGeometry(c,20,20),e=new THREE.MeshBasicMaterial({fog:!1,side:THREE.BackSide}),1<b.skyColor.length?(r(f,c,b.skyAngle,b.skyColor,!0),e.vertexColors=THREE.VertexColors):
(c=b.skyColor[0],e.color.setRGB(c.r,c.b,c.g)),m.add(new THREE.Mesh(f,e)),void 0!==b.groundColor&&(c=12E3,f=new THREE.SphereBufferGeometry(c,20,20,0,2*Math.PI,.5*Math.PI,1.5*Math.PI),e=new THREE.MeshBasicMaterial({fog:!1,side:THREE.BackSide,vertexColors:THREE.VertexColors}),r(f,c,b.groundAngle,b.groundColor,!1),m.add(new THREE.Mesh(f,e)));else{if(/geometry/.exec(b.string)){if("Box"===b.nodeType)f=b.size,h.geometry=new THREE.BoxBufferGeometry(f.x,f.y,f.z);else if("Cylinder"===b.nodeType)h.geometry=
new THREE.CylinderBufferGeometry(b.radius,b.radius,b.height);else if("Cone"===b.nodeType)h.geometry=new THREE.CylinderBufferGeometry(b.topRadius,b.bottomRadius,b.height);else if("Sphere"===b.nodeType)h.geometry=new THREE.SphereBufferGeometry(b.radius);else if("IndexedFaceSet"===b.nodeType){a=new THREE.BufferGeometry;for(var d=[],f=[],n,l,k,p,c=0,e=b.children.length;c<e;c++){var g=b.children[c];if("TextureCoordinate"===g.nodeType&&g.points)for(k=0,p=g.points.length;k<p;k++)l=g.points[k],f.push(l.x,
l.y);if("Coordinate"===g.nodeType){if(g.points)for(k=0,p=g.points.length;k<p;k++)n=g.points[k],d.push(n.x,n.y,n.z);-1<g.string.indexOf("DEF")&&(n=/DEF\s+([^\s]+)/.exec(g.string)[1],q[n]=d.slice(0));-1<g.string.indexOf("USE")&&(d=/USE\s+([^\s]+)/.exec(g.string)[1],d=q[d])}}g=0;if(b.coordIndex){k=[];p=[];n=new THREE.Vector3;l=new THREE.Vector2;c=0;for(e=b.coordIndex.length;c<e;c++)for(var t=b.coordIndex[c],g=0;3<=t.length&&g<t.length-2;){void 0===b.ccw&&(b.ccw=!0);var w=t[0],z=t[g+(b.ccw?1:2)],v=t[g+
(b.ccw?2:1)];n.fromArray(d,3*w);l.fromArray(f,2*w);k.push(n.x,n.y,n.z);p.push(l.x,l.y);n.fromArray(d,3*z);l.fromArray(f,2*z);k.push(n.x,n.y,n.z);p.push(l.x,l.y);n.fromArray(d,3*v);l.fromArray(f,2*v);k.push(n.x,n.y,n.z);p.push(l.x,l.y);g++}d=k;f=p}else h.parent.remove(h);!1===b.solid&&(h.material.side=THREE.DoubleSide);a.solid=b.solid;a.addAttribute("position",new THREE.Float32BufferAttribute(d,3));0<f.length&&a.addAttribute("uv",new THREE.Float32BufferAttribute(f,2));a.computeVertexNormals();a.computeBoundingSphere();
/DEF/.exec(b.string)&&(a.name=/DEF ([^\s]+)/.exec(b.string)[1],q[a.name]=a);h.geometry=a}return}if(/appearance/.exec(b.string)){for(c=0;c<b.children.length;c++)if(g=b.children[c],"Material"===g.nodeType&&(a=new THREE.MeshPhongMaterial,void 0!==g.diffuseColor&&(f=g.diffuseColor,a.color.setRGB(f.r,f.g,f.b)),void 0!==g.emissiveColor&&(f=g.emissiveColor,a.emissive.setRGB(f.r,f.g,f.b)),void 0!==g.specularColor&&(f=g.specularColor,a.specular.setRGB(f.r,f.g,f.b)),void 0!==g.transparency&&(f=g.transparency,
a.opacity=Math.abs(1-f),a.transparent=!0),/DEF/.exec(b.string)&&(a.name=/DEF ([^\s]+)/.exec(b.string)[1],q[a.name]=a),h.material=a),"ImageTexture"===g.nodeType&&(a=/"([^"]+)"/.exec(g.children[0])))h.material.name=a[1],h.material.map=x.load(y+a[1]);return}}c=0;for(f=b.children.length;c<f;c++)u(b.children[c],a)}}var q={},t=/(\b|\-|\+)([\d\.e]+)/,A=/([\d\.\+\-e]+)\s+([\d\.\+\-e]+)/g,w=/([\d\.\+\-e]+)\s+([\d\.\+\-e]+)\s+([\d\.\+\-e]+)/g,p=[];u(function(b){for(var e={string:"Scene",children:[]},a=e,d,
c,m=0;m<b.length;m++){var f="";c=b[m];null===/^\s+?$/g.exec(c)&&(c=c.trim(),""!==c&&(/#/.exec(c)&&(d=c.split("#"),c=d[0],f=d[1]),(d=/([^\s]*){1}(?:\s+)?{/.exec(c))?(d={nodeType:d[1],string:c,parent:a,children:[],comment:f},a.children.push(d),a=d,/}/.exec(c)&&(c=/{(.*)}/.exec(c)[1],d.children.push(c),k(a,c),a=a.parent)):/}/.exec(c)?a=a.parent:""!==c&&(k(a,c),a.children.push(c))))}return e}(e),m)}var y=this.texturePath||"",x=new THREE.TextureLoader(this.manager);x.setCrossOrigin(this.crossOrigin);var u=
new THREE.Scene;e=e.split("\n");for(var m=e.length-1;-1<m;m--){var r=e[m];if(/{.*[{\[]/.test(r)){var k=r.split("{").join("{\n").split("\n");k.unshift(1);k.unshift(m);e.splice.apply(e,k)}else/\].*}/.test(r)&&(k=r.split("]").join("]\n").split("\n"),k.unshift(1),k.unshift(m),e.splice.apply(e,k));/}.*}/.test(r)&&(k=r.split("}").join("}\n").split("\n"),k.unshift(1),k.unshift(m),e.splice.apply(e,k));/^\b[^\s]+\b$/.test(r.trim())?(e[m+1]=r+" "+e[m+1].trim(),e.splice(m,1)):-1<r.indexOf("coord")&&0>r.indexOf("[")&&
0>r.indexOf("{")&&(e[m]+=" Coordinate {}")}m=e.shift();/V1.0/.exec(m)?console.warn("THREE.VRMLLoader: V1.0 not supported yet."):/V2.0/.exec(m)&&t(e,u);return u}};