var ReactTruncate=function(f){function e(g){if(c[g])return c[g].exports;var p=c[g]={exports:{},id:g,loaded:!1};f[g].call(p.exports,p,p.exports,e);p.loaded=!0;return p.exports}var c={};e.m=f;e.c=c;e.p="";return e(0)}([function(f,e,c){function g(c,d){if("function"!==typeof d&&null!==d)throw new TypeError("Super expression must either be null or a function, not "+typeof d);c.prototype=Object.create(d&&d.prototype,{constructor:{value:c,enumerable:!1,writable:!0,configurable:!0}});d&&(Object.setPrototypeOf?
Object.setPrototypeOf(c,d):c.__proto__=d)}Object.defineProperty(e,"__esModule",{value:!0});var p=Object.assign||function(c){for(var d=1;d<arguments.length;d++){var a=arguments[d],b;for(b in a)Object.prototype.hasOwnProperty.call(a,b)&&(c[b]=a[b])}return c},v=function(){function c(d,a){for(var b=0;b<a.length;b++){var l=a[b];l.enumerable=l.enumerable||!1;l.configurable=!0;"value"in l&&(l.writable=!0);Object.defineProperty(d,l.key,l)}}return function(d,a,b){a&&c(d.prototype,a);b&&c(d,b);return d}}(),
r=(c=c(1))&&c.__esModule?c:{"default":c},t=function(c){function d(){var a;if(!(this instanceof d))throw new TypeError("Cannot call a class as a function");for(var b=arguments.length,l=Array(b),c=0;c<b;c++)l[c]=arguments[c];b=(a=d.__proto__||Object.getPrototypeOf(d)).call.apply(a,[this].concat(l));if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");a=!b||"object"!==typeof b&&"function"!==typeof b?this:b;a.state={};a.styles={ellipsis:{position:"fixed",visibility:"hidden",
top:0,left:0}};a.onResize=a.onResize.bind(a);a.onTruncate=a.onTruncate.bind(a);a.calcTargetWidth=a.calcTargetWidth.bind(a);a.measureWidth=a.measureWidth.bind(a);a.getLines=a.getLines.bind(a);a.renderLine=a.renderLine.bind(a);return a}g(d,c);v(d,[{key:"componentDidMount",value:function(){var a=this.refs,b=a.text,a=a.ellipsis,c=this.calcTargetWidth,d=this.onResize;this.canvas=document.createElement("canvas").getContext("2d");document.body.appendChild(a);c(function(){b&&b.parentNode.removeChild(b)});
window.addEventListener("resize",d)}},{key:"componentDidUpdate",value:function(a){this.props.children!==a.children&&this.forceUpdate()}},{key:"componentWillUnmount",value:function(){var a=this.refs.ellipsis,b=this.onResize,c=this.timeout;a.parentNode.removeChild(a);window.removeEventListener("resize",b);cancelAnimationFrame(c)}},{key:"innerText",value:function(a){var b=document.createElement("div");b.innerHTML=a.innerHTML.replace(/\r\n|\r|\n/g," ");a=b.innerText;var c=document.createElement("div");
c.innerHTML="foo\x3cbr/\x3ebar";"foo\nbar"!==c.innerText.replace(/\r\n|\r/g,"\n")&&(b.innerHTML=b.innerHTML.replace(/<br.*?[\/]?>/gi,"\n"),a=b.innerText);return a}},{key:"onResize",value:function(){this.calcTargetWidth()}},{key:"onTruncate",value:function(a){var b=this.props.onTruncate;"function"===typeof b&&(this.timeout=requestAnimationFrame(function(){b(a)}))}},{key:"calcTargetWidth",value:function(a){var b=this.refs.target,c=this.calcTargetWidth,d=this.canvas;if(b){var e=b.parentNode.getBoundingClientRect().width;
if(!e)return requestAnimationFrame(function(){return c(a)});b=window.getComputedStyle(b);b=[b["font-weight"],b["font-style"],b["font-size"],b["font-family"]].join(" ");d.font=b;this.setState({targetWidth:e},a)}}},{key:"measureWidth",value:function(a){return this.canvas.measureText(a).width}},{key:"ellipsisWidth",value:function(a){return a.offsetWidth}},{key:"getLines",value:function(){for(var a=this.props,b=a.lines,a=a.ellipsis,c=this.state.targetWidth,d=this.innerText,e=this.measureWidth,g=this.onTruncate,
u=[],d=d(this.refs.text).split("\n").map(function(a){return a.split(" ")}),m=!0,p=this.ellipsisWidth(this.refs.ellipsis),q=1;q<=b;q++){var n=d[0];if(0===n.length)u.push(),d.shift(),q--;else{var h=n.join(" ");if(e(h)<=c&&1===d.length){m=!1;u.push(h);break}if(q===b){for(var n=n.join(" "),k=0,h=n.length-1;k<=h;){var s=Math.floor((k+h)/2),f=n.slice(0,s+1);e(f)+p<=c?k=s+1:h=s-1}h=r["default"].createElement("span",null,n.slice(0,k),a)}else{k=0;for(h=n.length-1;k<=h;)s=Math.floor((k+h)/2),f=n.slice(0,s+
1).join(" "),e(f)<=c?k=s+1:h=s-1;if(0===k){q=b-1;continue}h=n.slice(0,k).join(" ");d[0].splice(0,k)}u.push(h)}}g(m);return u}},{key:"renderLine",value:function(a,b,c){if(b===c.length-1)return r["default"].createElement("span",{key:b},a);c=r["default"].createElement("br",{key:b+"br"});return a?[r["default"].createElement("span",{key:b},a),c]:c}},{key:"render",value:function(){var a=this.refs.target,b=this.props,c=b.children,d=b.ellipsis,e=b.lines,f=["children","ellipsis","lines"],g={},m;for(m in b)0<=
f.indexOf(m)||Object.prototype.hasOwnProperty.call(b,m)&&(g[m]=b[m]);b=this.state.targetWidth;f=this.getLines;m=this.renderLine;var t=this.onTruncate,q=void 0;"undefined"!==typeof window&&a&&b&&(0<e?q=f().map(m):(q=c,t(!1)));delete g.onTruncate;return r["default"].createElement("span",p({},g,{ref:"target"}),q,r["default"].createElement("span",{ref:"text"},c),r["default"].createElement("span",{ref:"ellipsis",style:this.styles.ellipsis},d))}}]);return d}(c.Component);t.propTypes={children:c.PropTypes.node,
ellipsis:c.PropTypes.node,lines:c.PropTypes.oneOfType([c.PropTypes.oneOf([!1]),c.PropTypes.number]),onTruncate:c.PropTypes.func};t.defaultProps={children:"",ellipsis:"…",lines:1};e["default"]=t;f.exports=e["default"]},function(f,e){f.exports=React}]);