(function(n){"object"===typeof exports&&"undefined"!==typeof module?module.exports=n():"function"===typeof define&&define.amd?define([],n):("undefined"!==typeof window?window:"undefined"!==typeof global?global:"undefined"!==typeof self?self:this).Delegator=n()})(function(){return function b(d,f,a){function c(e,l){if(!f[e]){if(!d[e]){var h="function"==typeof require&&require;if(!l&&h)return h(e,!0);if(g)return g(e,!0);h=Error("Cannot find module '"+e+"'");throw h.code="MODULE_NOT_FOUND",h;}h=f[e]=
{exports:{}};d[e][0].call(h.exports,function(a){var g=d[e][1][a];return c(g?g:a)},h,h.exports,b,d,f,a)}return f[e].exports}for(var g="function"==typeof require&&require,e=0;e<a.length;e++)c(a[e]);return c}({1:[function(b,d,f){var a=b("ev-store");d.exports=function(c,g,e){c=a(c);var b=c[g];b?Array.isArray(b)?-1===b.indexOf(e)&&b.push(e):b!==e&&(c[g]=[b,e]):c[g]=e}},{"ev-store":6}],2:[function(b,d,f){function a(c){if(!(this instanceof a))return new a(c);c=c||p;this.target=c.documentElement;this.events=
{};this.rawEventListeners={};this.globalListeners={}}function c(a,c){var e=c.globalListeners,b=c.target;return function(c){var k=e[a]||[];if(0<k.length){var d=new r(c);d.currentTarget=b;m(k,d)}g(c.target,c,a)}}function g(a,c,b){if((a=e(a,b))&&0<a.handlers.length){var k=new r(c);k.currentTarget=a.currentTarget;m(a.handlers,k);k._bubbles&&g(a.currentTarget.parentNode,c,b)}}function e(a,c){if(null===a||"undefined"===typeof a)return null;var b=s(a),g=b[c],b=b.event;if(!g&&!b)return e(a.parentNode,c);
g=[].concat(g||[],b||[]);return new l(a,g)}function m(a,c){a.forEach(function(b){if("function"===typeof b)b(c);else if("function"===typeof b.handleEvent)b.handleEvent(c);else if("dom-delegator-handle"===b.type)q(b).func(c);else throw Error("dom-delegator: unknown handler found: "+JSON.stringify(a));})}function l(a,c){this.currentTarget=a;this.handlers=c}function h(){this.type="dom-delegator-handle"}var p=b("global/document"),s=b("ev-store");f=b("weakmap-shim/create-store");var k=b("./add-event.js"),
t=b("./remove-event.js"),r=b("./proxy-event.js"),q=f();d.exports=a;a.prototype.addEventListener=k;a.prototype.removeEventListener=t;a.allocateHandle=function(a){var c=new h;q(c).func=a;return c};a.transformHandle=function(a,c){var b=q(a).func;return this.allocateHandle(function(a){c(a,b)})};a.prototype.addGlobalEventListener=function(a,c){var b=this.globalListeners[a]||[];-1===b.indexOf(c)&&b.push(c);this.globalListeners[a]=b};a.prototype.removeGlobalEventListener=function(a,c){var b=this.globalListeners[a]||
[],g=b.indexOf(c);-1!==g&&b.splice(g,1)};a.prototype.listenTo=function(a){a in this.events||(this.events[a]=0);this.events[a]++;if(1===this.events[a]){var b=this.rawEventListeners[a];b||(b=this.rawEventListeners[a]=c(a,this));this.target.addEventListener(a,b,!0)}};a.prototype.unlistenTo=function(a){a in this.events||(this.events[a]=0);if(0===this.events[a])throw Error("already unlistened to event.");this.events[a]--;if(0===this.events[a]){var c=this.rawEventListeners[a];if(!c)throw Error("dom-delegator#unlistenTo: cannot unlisten to "+
a);this.target.removeEventListener(a,c,!0)}}},{"./add-event.js":1,"./proxy-event.js":14,"./remove-event.js":15,"ev-store":6,"global/document":9,"weakmap-shim/create-store":12}],3:[function(b,d,f){function a(a){a=a||{};var b=a.document||g,d=b["__DOM_DELEGATOR_CACHE_TOKEN@13"];d||(d=b["__DOM_DELEGATOR_CACHE_TOKEN@13"]=c());var k=m.delegators[d];k||(k=m.delegators[d]=new e(b));if(!1!==a.defaultEvents)for(a=0;a<l.length;a++)k.listenTo(l[a]);return k}f=b("individual");var c=b("cuid"),g=b("global/document"),
e=b("./dom-delegator.js"),m=f("__DOM_DELEGATOR_CACHE@13",{delegators:{}}),l="blur change click contextmenu dblclick error focus focusin focusout input keydown keypress keyup load mousedown mouseup resize select submit touchcancel touchend touchstart unload".split(" ");d.exports=a;a.allocateHandle=e.allocateHandle;a.transformHandle=e.transformHandle},{"./dom-delegator.js":2,cuid:5,"global/document":9,individual:10}],4:[function(b,d,f){},{}],5:[function(b,d,f){(function(a){var c=0,b=Math.pow(36,4),
e=function(a,c){var b="000000000"+a;return b.substr(b.length-c)},f=function(){return e((Math.random()*b<<0).toString(36),4)},l=function(){c=c<b?c:0;c++;return c-1},h=function(){var a=(new Date).getTime().toString(36),c,b=h.fingerprint(),g=f()+f();c=e(l().toString(36),4);return"c"+a+c+b+g};h.slug=function(){var a=(new Date).getTime().toString(36),c,b=h.fingerprint().slice(0,1)+h.fingerprint().slice(-1),g=f().slice(-2);c=l().toString(36).slice(-4);return a.slice(-2)+c+b+g};h.globalCount=function(){var a=
function(){var a,c=0;for(a in window)c++;return c}();h.globalCount=function(){return a};return a};h.fingerprint=function(){return e((navigator.mimeTypes.length+navigator.userAgent.length).toString(36)+h.globalCount().toString(36),4)};a.register?a.register("cuid",h):"undefined"!==typeof d?d.exports=h:a.cuid=h})(this.applitude||this)},{}],6:[function(b,d,f){b("individual/one-version")("ev-store","7");d.exports=function(a){var c=a["__EV_STORE_KEY@7"];c||(c=a["__EV_STORE_KEY@7"]={});return c}},{"individual/one-version":8}],
7:[function(b,d,f){(function(a){var c="undefined"!==typeof window?window:"undefined"!==typeof a?a:{};d.exports=function(a,b){return a in c?c[a]:c[a]=b}}).call(this,"undefined"!==typeof global?global:"undefined"!==typeof self?self:"undefined"!==typeof window?window:{})},{}],8:[function(b,d,f){var a=b("./index.js");d.exports=function(c,b,e){var d="__INDIVIDUAL_ONE_VERSION_"+c,f=a(d+"_ENFORCE_SINGLETON",b);if(f!==b)throw Error("Can only have one copy of "+c+".\nYou already have version "+f+" installed.\nThis means you cannot install version "+
b);return a(d,e)}},{"./index.js":7}],9:[function(b,d,f){f="undefined"!==typeof global?global:"undefined"!==typeof self?self:"undefined"!==typeof window?window:{};f="undefined"!==typeof f?f:"undefined"!==typeof window?window:{};b=b("min-document");if("undefined"!==typeof document)d.exports=document;else{var a=f["__GLOBAL_DOCUMENT_CACHE@4"];a||(a=f["__GLOBAL_DOCUMENT_CACHE@4"]=b);d.exports=a}},{"min-document":4}],10:[function(b,d,f){(function(a){var c="undefined"!==typeof window?window:"undefined"!==
typeof a?a:{};d.exports=function(a,b){if(c[a])return c[a];Object.defineProperty(c,a,{value:b,configurable:!0});return b}}).call(this,"undefined"!==typeof global?global:"undefined"!==typeof self?self:"undefined"!==typeof window?window:{})},{}],11:[function(b,d,f){d.exports="function"===typeof Object.create?function(a,c){a.super_=c;a.prototype=Object.create(c.prototype,{constructor:{value:a,enumerable:!1,writable:!0,configurable:!0}})}:function(a,c){a.super_=c;var b=function(){};b.prototype=c.prototype;
a.prototype=new b;a.prototype.constructor=a}},{}],12:[function(b,d,f){var a=b("./hidden-store.js");d.exports=function(){var c={};return function(b){if(("object"!==typeof b||null===b)&&"function"!==typeof b)throw Error("Weakmap-shim: Key must be object");var e=b.valueOf(c);return e&&e.identity===c?e:a(b,c)}}},{"./hidden-store.js":13}],13:[function(b,d,f){d.exports=function(a,b){var d={identity:b},e=a.valueOf;Object.defineProperty(a,"valueOf",{value:function(a){return a!==b?e.apply(this,arguments):
d},writable:!0});return d}},{}],14:[function(b,d,f){function a(b){if(!(this instanceof a))return new a(b);if(h.test(b.type))return new g(b);if(p.test(b.type))return new c(b);for(var d=0;d<e.length;d++){var f=e[d];this[f]=b[f]}this._rawEvent=b;this._bubbles=!1}function c(a){for(var b=0;b<e.length;b++){var c=e[b];this[c]=a[c]}for(b=0;b<l.length;b++)c=l[b],this[c]=a[c];this._rawEvent=a}function g(a){for(var b=0;b<e.length;b++){var c=e[b];this[c]=a[c]}for(b=0;b<m.length;b++)c=m[b],this[c]=a[c];this._rawEvent=
a}b=b("inherits");var e="altKey bubbles cancelable ctrlKey eventPhase metaKey relatedTarget shiftKey target timeStamp type view which".split(" "),m=["char","charCode","key","keyCode"],l="button buttons clientX clientY layerX layerY offsetX offsetY pageX pageY screenX screenY toElement".split(" "),h=/^key|input/,p=/^(?:mouse|pointer|contextmenu)|click/;d.exports=a;a.prototype.preventDefault=function(){this._rawEvent.preventDefault()};a.prototype.startPropagation=function(){this._bubbles=!0};b(c,a);
b(g,a)},{inherits:11}],15:[function(b,d,f){var a=b("ev-store");d.exports=function(b,d,e){var f=a(b);if(b=f[d])Array.isArray(b)?(d=b.indexOf(e),-1!==d&&b.splice(d,1)):b===e&&(f[d]=null)}},{"ev-store":6}]},{},[3])(3)});