THREE.CCDIKSolver=function(a){this.mesh=a;this._valid()};
THREE.CCDIKSolver.prototype={constructor:THREE.CCDIKSolver,_valid:function(){for(var a=this.mesh.geometry.iks,e=this.mesh.skeleton.bones,c=0,b=a.length;c<b;c++)for(var h=a[c],f=h.links,l,h=e[h.effector],m=0,u=f.length;m<u;m++)l=e[f[m].index],h.parent!==l&&console.warn("THREE.CCDIKSolver: bone "+h.name+" is not the child of bone "+l.name),h=l},_saveOriginalBonesInfo:function(){for(var a=this.mesh.skeleton.bones,e=0,c=a.length;e<c;e++){var b=a[e];void 0===b.userData.ik&&(b.userData.ik={});b.userData.ik.originalMatrix=
b.matrix.toArray()}},update:function(a){var e=new THREE.Quaternion,c=new THREE.Vector3,b=new THREE.Vector3,h=new THREE.Vector3,f=new THREE.Vector3,l=new THREE.Vector3,m=new THREE.Quaternion,u=new THREE.Vector3,n=new THREE.Vector3,t=this.mesh.skeleton.bones,v=this.mesh.geometry.iks,k=Math;this.mesh.updateMatrixWorld(!0);!0===a&&this._saveOriginalBonesInfo();a=0;for(var r=v.length;a<r;a++){var d=v[a],y=t[d.effector];c.setFromMatrixPosition(t[d.target].matrixWorld);for(var p=d.links,B=void 0!==d.iteration?
d.iteration:1,A=0;A<B;A++){for(var q=!1,w=0,C=p.length;w<C;w++){var x=t[p[w].index];if(!1===p[w].enabled)break;var z=p[w].limitation;x.matrixWorld.decompose(l,m,u);m.inverse();h.setFromMatrixPosition(y.matrixWorld);f.subVectors(h,l);f.applyQuaternion(m);f.normalize();b.subVectors(c,l);b.applyQuaternion(m);b.normalize();var g=b.dot(f);1<g?g=1:-1>g&&(g=-1);g=k.acos(g);1E-5>g||(void 0!==d.minAngle&&g<d.minAngle&&(g=d.minAngle),void 0!==d.maxAngle&&g>d.maxAngle&&(g=d.maxAngle),n.crossVectors(f,b),n.normalize(),
e.setFromAxisAngle(n,g),x.quaternion.multiply(e),void 0!==z&&(q=x.quaternion.w,1<q&&(q=1),g=k.sqrt(1-q*q),x.quaternion.set(z.x*g,z.y*g,z.z*g,q)),x.updateMatrixWorld(!0),q=!0)}if(!q)break}}this.mesh.updateMatrixWorld(!0)}};
THREE.CCDIKHelper=function(a){if(void 0===a.geometry.iks||void 0===a.skeleton)throw"THREE.CCDIKHelper requires iks in mesh.geometry and skeleton in mesh.";THREE.Object3D.call(this);this.root=a;this.matrix=a.matrixWorld;this.matrixAutoUpdate=!1;this.sphereGeometry=new THREE.SphereBufferGeometry(.25,16,8);this.targetSphereMaterial=new THREE.MeshBasicMaterial({color:new THREE.Color(16746632),depthTest:!1,depthWrite:!1,transparent:!0});this.effectorSphereMaterial=new THREE.MeshBasicMaterial({color:new THREE.Color(8978312),
depthTest:!1,depthWrite:!1,transparent:!0});this.linkSphereMaterial=new THREE.MeshBasicMaterial({color:new THREE.Color(8947967),depthTest:!1,depthWrite:!1,transparent:!0});this.lineMaterial=new THREE.LineBasicMaterial({color:new THREE.Color(16711680),depthTest:!1,depthWrite:!1,transparent:!0});this._init();this.update()};THREE.CCDIKHelper.prototype=Object.create(THREE.Object3D.prototype);THREE.CCDIKHelper.prototype.constructor=THREE.CCDIKHelper;
THREE.CCDIKHelper.prototype._init=function(){function a(a){var b=new THREE.BufferGeometry;a=new Float32Array(3*(2+a.links.length));b.addAttribute("position",new THREE.BufferAttribute(a,3));return b}for(var e=this.root.geometry.iks,c=0,b=e.length;c<b;c++){var h=e[c];this.add(new THREE.Mesh(this.sphereGeometry,this.targetSphereMaterial));this.add(new THREE.Mesh(this.sphereGeometry,this.effectorSphereMaterial));for(var f=0,l=h.links.length;f<l;f++)this.add(new THREE.Mesh(this.sphereGeometry,this.linkSphereMaterial));
this.add(new THREE.Line(a(h),this.lineMaterial))}};
THREE.CCDIKHelper.prototype.update=function(){function a(a){m.setFromMatrixPosition(a.matrixWorld);m.applyMatrix4(l);return m}function e(b,d,c){c=a(c);b[3*d+0]=c.x;b[3*d+1]=c.y;b[3*d+2]=c.z}for(var c=0,b=this.root,h=b.geometry.iks,f=b.skeleton.bones,l=(new THREE.Matrix4).getInverse(b.matrixWorld),m=new THREE.Vector3,b=0,u=h.length;b<u;b++){var n=h[b],t=f[n.target],v=f[n.effector],k=this.children[c++],r=this.children[c++];k.position.copy(a(t));r.position.copy(a(v));k=0;for(r=n.links.length;k<r;k++){var d=
n.links[k],d=f[d.index];this.children[c++].position.copy(a(d))}var y=this.children[c++],p=y.geometry.attributes.position.array;e(p,0,t);e(p,1,v);k=0;for(r=n.links.length;k<r;k++)d=n.links[k],d=f[d.index],e(p,k+2,d);y.geometry.attributes.position.needsUpdate=!0}};