/*
 2015 Robert Benko (Quazistax) <quazistax@gmail.com>
      @license MIT
 2015 Robert Benko (Quazistax) <quazistax@gmail.com>
       @license MIT
*/
(function(G){"object"===typeof exports&&"undefined"!==typeof module?module.exports=G():"function"===typeof define&&define.amd?define([],G):("undefined"!==typeof window?window:"undefined"!==typeof global?global:"undefined"!==typeof self?self:this).SvgIntersections=G()})(function(){return function x(s,C,c){function a(f,g){if(!C[f]){if(!s[f]){var e="function"==typeof require&&require;if(!g&&e)return e(f,!0);if(b)return b(f,!0);e=Error("Cannot find module '"+f+"'");throw e.code="MODULE_NOT_FOUND",e;}e=
C[f]={exports:{}};s[f][0].call(e.exports,function(b){var g=s[f][1][b];return a(g?g:b)},e,e.exports,x,s,C,c)}return C[f].exports}for(var b="function"==typeof require&&require,f=0;f<c.length;f++)a(c[f]);return a}({1:[function(x,s,C){C.intersect=x("./lib/intersect");C.shape=x("./lib/IntersectionParams").newShape},{"./lib/IntersectionParams":3,"./lib/intersect":4}],2:[function(x,s,C){function c(a){this.init(a)}c.prototype.init=function(a){this.status=a;this.points=[]};c.prototype.appendPoint=function(a){this.points.push(a)};
c.prototype.appendPoints=function(a){this.points=this.points.concat(a)};s.exports=c},{}],3:[function(x,s,C){function c(a,b,m,f,q,d,w){function g(a,b,m,f){var q=a*m+b*f,H=Math.sqrt((a*a+b*b)*(m*m+f*f)),q=Math.acos(q/H);0>a*f-b*m&&(q=-q);return q}q=q*Math.PI/180;var c=Math.cos(q);q=Math.sin(q);var e=a.subtract(b).divide(2),k=e.x*c+e.y*q,e=e.x*-q+e.y*c,p=k*k,h=e*e,B=p/(m*m)+h/(f*f);1<B&&(B=Math.sqrt(B),m*=B,f*=B);var B=m*m,E=f*f,h=B*h,p=E*p,B=(B*E-h-p)/(h+p);1E-6>Math.abs(B)&&(B=0);p=Math.sqrt(B);d==
w&&(p=-p);a=a.add(b).divide(2);b=p*m*e/f;d=p*-f*k/m;p=(k-b)/m;k=(k+b)/m;h=(e-d)/f;B=(e+d)/f;e=g(1,0,p,h);k=g(p,h,-k,-B);for(p=2*Math.PI;k>p;)k-=p;for(;0>k;)k+=p;0==w&&(k-=p);return{center:new t(b*c-d*q+a.x,b*q+d*c+a.y),rx:m,ry:f,theta1:e,deltaTheta:k}}function a(a,b){this.init(a,b)}function b(a){return a.split(" ").map(function(a){a=a.split(",");return new t(a[0],a[1])})}function f(a,b){0<arguments.length&&this.init(a,b)}function d(a,b,m){0<arguments.length&&this.init(a,b,m)}function g(a,b){0<arguments.length&&
this.init("A",a,b)}function e(a,b){0<arguments.length&&this.init("Q",a,b)}function h(a,b){0<arguments.length&&this.init("C",a,b)}function r(a,b){0<arguments.length&&this.init("H",a,b)}function l(a,b){0<arguments.length&&this.init("L",a,b)}function n(a,b){0<arguments.length&&this.init("M",a,b)}function D(a,b){0<arguments.length&&this.init("T",a,b)}function m(a,b){0<arguments.length&&this.init("S",a,b)}function q(a,b,m){0<arguments.length&&this.init(a,b,m)}function w(a,b){0<arguments.length&&this.init("z",
a,b)}function E(a,b){0<arguments.length&&this.init("q",a,b)}function B(a,b){0<arguments.length&&this.init("c",a,b)}function p(a,b){0<arguments.length&&this.init("l",a,b)}function k(a,b){0<arguments.length&&this.init("m",a,b)}function F(a,b){0<arguments.length&&this.init("t",a,b)}function A(a,b){0<arguments.length&&this.init("s",a,b)}var t=x("kld-affine").Point2D;a.prototype.init=function(a,b){this.type=a;this.params=b;this.meta={}};a.TYPE={};var v=a.TYPE;v.LINE="Line";v.RECT="Rectangle";v.ROUNDRECT=
"RoundRectangle";v.CIRCLE="Circle";v.ELLIPSE="Ellipse";v.POLYGON="Polygon";v.POLYLINE="Polyline";v.PATH="Path";v.ARC="Arc";v.BEZIER2="Bezier2";v.BEZIER3="Bezier3";a.newShape=function(m,f){m=m.toLowerCase();if("line"===m)return a.newLine(new t(f.x1,f.y1),new t(f.x2,f.y2));if("rect"===m)return 0<f.rx||0<f.ry?a.newRoundRect(f.x,f.y,f.width,f.height,f.rx,f.ry):a.newRect(f.x,f.y,f.width,f.height);if("circle"===m)return a.newCircle(new t(f.cx,f.cy),f.r);if("ellipse"===m)return a.newEllipse(new t(f.cx,f.cy),
f.rx,f.ry);if("polygon"===m)return a.newPolygon(b(f.points));if("polyline"===m)return a.newPolyline(b(f.points));if("path"===m)return a.newPath(f.d)};a.newArc=function(b,f,m,q,d,w,g){b=c(b,f,m,q,d,w,g);return new a(v.ARC,[b.center,b.rx,b.ry,d*Math.PI/180,b.theta1,b.deltaTheta])};a.newBezier2=function(b,f,m){return new a(v.BEZIER2,[b,f,m])};a.newBezier3=function(b,f,m,q){return new a(v.BEZIER3,[b,f,m,q])};a.newCircle=function(b,f){return new a(v.CIRCLE,[b,f])};a.newEllipse=function(b,f,m){return new a(v.ELLIPSE,
[b,f,m])};a.newLine=function(b,f){return new a(v.LINE,[b,f])};a.newPolygon=function(b){return new a(v.POLYGON,[b])};a.newPolyline=function(b){return new a(v.POLYLINE,[b])};a.newRect=function(b,f,m,q){var d=[];d.push(new t(b,f));d.push(new t(b+m,f));d.push(new t(b+m,f+q));d.push(new t(b,f+q));return new a(v.RECT,[d])};a.newRoundRect=function(b,f,m,q,d,w){if(0===d&&0===w)return a.newRect(b,f,m,q);0===d&&(d=w);0===w&&(w=d);d>m/2&&(d=m/2);w>q/2&&(d=q/2);var g=[],k=b+d,p=b+m-d;m=b+m;var e=f+w,c=f+q-w;
q=f+q;g.push(new a(v.ARC,[new t(k,e),d,w,0,180*Math.PI/180,90*Math.PI/180]));g.push(new a(v.LINE,[new t(k,f),new t(p,f)]));g.push(new a(v.ARC,[new t(p,e),d,w,0,-90*Math.PI/180,90*Math.PI/180]));g.push(new a(v.LINE,[new t(m,e),new t(m,c)]));g.push(new a(v.ARC,[new t(p,c),d,w,0,0*Math.PI/180,90*Math.PI/180]));g.push(new a(v.LINE,[new t(p,q),new t(k,q)]));g.push(new a(v.ARC,[new t(k,c),d,w,0,90*Math.PI/180,90*Math.PI/180]));g.push(new a(v.LINE,[new t(b,c),new t(b,e)]));g[g.length-1].meta.closePath=!0;
return new a(v.ROUNDRECT,[g])};f.prototype.init=function(a,b){this.type=a;this.text=b};f.prototype.typeis=function(a){return this.type==a};var u;u={A:"rx ry x-axis-rotation large-arc-flag sweep-flag x y".split(" "),a:"rx ry x-axis-rotation large-arc-flag sweep-flag x y".split(" "),C:"x1 y1 x2 y2 x y".split(" "),c:"x1 y1 x2 y2 x y".split(" "),H:["x"],h:["x"],L:["x","y"],l:["x","y"],M:["x","y"],m:["x","y"],Q:["x1","y1","x","y"],q:["x1","y1","x","y"],S:["x2","y2","x","y"],s:["x2","y2","x","y"],T:["x",
"y"],t:["x","y"],V:["y"],v:["y"],Z:[],z:[]};a.newPath=function(b){for(var q=[];""!=b;)if(b.match(/^([ \t\r\n,]+)/))b=b.substr(RegExp.$1.length);else if(b.match(/^([aAcChHlLmMqQsStTvVzZ])/))q[q.length]=new f(0,RegExp.$1),b=b.substr(RegExp.$1.length);else if(b.match(/^(([-+]?[0-9]+(\.[0-9]*)?|[-+]?\.[0-9]+)([eE][-+]?[0-9]+)?)/))q[q.length]=new f(1,parseFloat(RegExp.$1)),b=b.substr(RegExp.$1.length);else throw Error("Unrecognized segment command: "+b);q[q.length]=new f(2,null);var d=0,c=q[d],t="BOD";
for(b=[];!c.typeis(2);){var s,z=[];if("BOD"==t)if("M"==c.text||"m"==c.text)d++,s=u[c.text].length,t=c.text;else throw Error("Path data must begin with a moveto command");else c.typeis(1)?s=u[t].length:(d++,s=u[c.text].length,t=c.text);if(d+s<q.length){for(c=d;c<d+s;c++){var x=q[c];if(x.typeis(1))z[z.length]=x.text;else throw Error("Parameter type is not a number: "+t+","+x.text);}c=b.length;c=0==c?null:b[c-1];switch(t){case "A":z=new g(z,c);break;case "C":z=new h(z,c);break;case "c":z=new B(z,c);
break;case "H":z=new r(z,c);break;case "L":z=new l(z,c);break;case "l":z=new p(z,c);break;case "M":z=new n(z,c);break;case "m":z=new k(z,c);break;case "Q":z=new e(z,c);break;case "q":z=new E(z,c);break;case "S":z=new m(z,c);break;case "s":z=new A(z,c);break;case "T":z=new D(z,c);break;case "t":z=new F(z,c);break;case "Z":z=new w(z,c);break;case "z":z=new w(z,c);break;default:throw Error("Unsupported segment type: "+t);}b.push(z);d+=s;c=q[d];"M"==t&&(t="L");"m"==t&&(t="l")}else throw Error("Path data ended before all parameters were found");
}q=[];for(c=0;c<b.length;c++)(d=b[c].getIntersectionParams())&&q.push(d);return new a(v.PATH,[q])};d.prototype.init=function(a,b,f){this.command=a;this.previous=f;this.points=[];for(a=0;a<b.length;)this.points.push(new t(b[a],b[a+1])),a+=2};d.prototype.getLastPoint=function(){return this.points[this.points.length-1]};d.prototype.getIntersectionParams=function(){return null};g.prototype=new d;g.prototype.constructor=e;g.superclass=d.prototype;g.prototype.init=function(a,b,f){var m=[],q=b.pop(),d=b.pop();
m.push(d,q);g.superclass.init.call(this,a,m,f);this.rx=parseFloat(b.shift());this.ry=parseFloat(b.shift());this.angle=parseFloat(b.shift());this.arcFlag=parseFloat(b.shift());this.sweepFlag=parseFloat(b.shift())};g.prototype.getIntersectionParams=function(){return a.newArc(this.previous.getLastPoint(),this.points[0],this.rx,this.ry,this.angle,this.arcFlag,this.sweepFlag)};e.prototype=new d;e.prototype.constructor=e;e.superclass=d.prototype;e.prototype.getIntersectionParams=function(){return a.newBezier2(this.previous.getLastPoint(),
this.points[0],this.points[1])};h.prototype=new d;h.prototype.constructor=h;h.superclass=d.prototype;h.prototype.getLastControlPoint=function(){return this.points[1]};h.prototype.getIntersectionParams=function(){return a.newBezier3(this.previous.getLastPoint(),this.points[0],this.points[1],this.points[2])};r.prototype=new d;r.prototype.constructor=r;r.superclass=d.prototype;r.prototype.init=function(b,a,f){var m=f.getLastPoint(),q=[];q.push(a.pop(),m.y);r.superclass.init.call(this,b,q,f)};l.prototype=
new d;l.prototype.constructor=l;l.superclass=d.prototype;l.prototype.getIntersectionParams=function(){return a.newLine(this.previous.getLastPoint(),this.points[0])};n.prototype=new d;n.prototype.constructor=n;n.superclass=d.prototype;D.prototype=new d;D.prototype.constructor=D;D.superclass=d.prototype;D.prototype.getControlPoint=function(){var b=this.previous.getLastPoint();if(this.previous.command.match(/^[QqTt]$/))var a=this.previous.getControlPoint().subtract(b),b=b.subtract(a);return b};D.prototype.getIntersectionParams=
function(){return a.newBezier2(this.previous.getLastPoint(),this.getControlPoint(),this.points[0])};m.prototype=new d;m.prototype.constructor=m;m.superclass=d.prototype;m.prototype.getFirstControlPoint=function(){var b=this.previous.getLastPoint();if(this.previous.command.match(/^[SsCc]$/))var a=this.previous.getLastControlPoint().subtract(b),b=b.subtract(a);return b};m.prototype.getLastControlPoint=function(){return this.points[0]};m.prototype.getIntersectionParams=function(){return a.newBezier3(this.previous.getLastPoint(),
this.getFirstControlPoint(),this.points[0],this.points[1])};q.prototype=new d;q.prototype.constructor=q;q.superclass=d.prototype;q.prototype.init=function(b,a,f){this.command=b;this.previous=f;this.points=[];b=this.previous?this.previous.getLastPoint():new t(0,0);for(f=0;f<a.length;){var m=new t(b.x+a[f],b.y+a[f+1]);this.points.push(m);f+=2}};w.prototype=new q;w.prototype.constructor=w;w.superclass=q.prototype;w.prototype.getLastPoint=function(){for(var b=this.previous,a;b;){if(b.command.match(/^[mMzZ]$/)){a=
b.getLastPoint();break}b=b.previous}return a};w.prototype.getIntersectionParams=function(){return a.newLine(this.previous.getLastPoint(),this.getLastPoint())};E.prototype=new q;E.prototype.constructor=E;E.superclass=q.prototype;E.prototype.getControlPoint=function(){return this.points[0]};E.prototype.getIntersectionParams=function(){return a.newBezier2(this.previous.getLastPoint(),this.points[0],this.points[1])};B.prototype=new q;B.prototype.constructor=B;B.superclass=q.prototype;B.prototype.getLastControlPoint=
function(){return this.points[1]};B.prototype.getIntersectionParams=function(){return a.newBezier3(this.previous.getLastPoint(),this.points[0],this.points[1],this.points[2])};p.prototype=new q;p.prototype.constructor=p;p.superclass=q.prototype;p.prototype.toString=function(){var b;b=this.previous?this.previous.getLastPoint():new Point(0,0);b=this.points[0].subtract(b);this.previous.constructor!=this.constuctor&&this.previous.constructor!=k&&(cmd=this.command);return cmd+b.toString()};p.prototype.getIntersectionParams=
function(){return a.newLine(this.previous.getLastPoint(),this.points[0])};k.prototype=new q;k.prototype.constructor=k;k.superclass=q.prototype;F.prototype=new q;F.prototype.constructor=F;F.superclass=q.prototype;F.prototype.getControlPoint=function(){var b=this.previous.getLastPoint();if(this.previous.command.match(/^[QqTt]$/))var a=this.previous.getControlPoint().subtract(b),b=b.subtract(a);return b};F.prototype.getIntersectionParams=function(){return a.newBezier2(this.previous.getLastPoint(),this.getControlPoint(),
this.points[0])};A.prototype=new q;A.prototype.constructor=A;A.superclass=q.prototype;A.prototype.getFirstControlPoint=function(){var b=this.previous.getLastPoint();if(this.previous.command.match(/^[SsCc]$/))var a=this.previous.getLastControlPoint().subtract(b),b=b.subtract(a);return b};A.prototype.getLastControlPoint=function(){return this.points[0]};A.prototype.getIntersectionParams=function(){return a.newBezier3(this.previous.getLastPoint(),this.getFirstControlPoint(),this.points[0],this.points[1])};
s.exports=a},{"kld-affine":5}],4:[function(x,s,C){function c(b,a){var f=b[0]*a[1]-a[0]*b[1],d=b[0]*a[2]-a[0]*b[2],c=b[0]*a[3]-a[0]*b[3],g=b[0]*a[4]-a[0]*b[4],k=b[0]*a[5]-a[0]*b[5],h=b[1]*a[2]-a[1]*b[2],l=b[3]*a[5]-a[3]*b[5],r=b[1]*a[5]-a[1]*b[5]+(b[3]*a[4]-a[3]*b[4]),n=b[1]*a[4]-a[1]*b[4]-(b[2]*a[3]-a[2]*b[3]);return new e(f*h-d*d,f*n+c*h-2*d*g,f*r+c*n-g*g-2*d*k,f*l+c*r-2*g*k,c*l-k*k)}function a(b,a){if(0!==b.length&&0!==a.length)for(var f=function(b,a){b<a.x&&(b=a.x);b<a.y&&(b=a.y);return b},d=b.reduce(f,
0),d=a.reduce(f,d),f=1E-13*d*Math.SQRT2,c=0;c<b.length;){for(d=0;d<a.length;d++)if(b[c].distanceFrom(a[d])<=f){b.splice(c,1);break}d==a.length&&c++}}function b(b,a,d,c){if(null!==b&&null!==a){var e;if(e=D[b.type])d=e(b,a,d,c);else if(e=D[a.type])d=e(a,b,c,d);else{var p,k;b.type===l.CIRCLE?(p=[b.params[0],b.params[1],b.params[1]],e=l.ELLIPSE):(p=b.params.slice(),e=b.type);a.type===l.CIRCLE?(b=[a.params[0],a.params[1],a.params[1]],k=l.ELLIPSE):(b=a.params.slice(),k=a.type);var h;if(a=d instanceof g&&
c instanceof g)if(e===l.ELLIPSE&&k===l.ELLIPSE){var A=p[0],t=p[1],v=p[2],u=b[0],s=b[1],x=b[2];d=d.multiply(g.IDENTITY.translate(A.x,A.y).scaleNonUniform(t/1,v/1));A=new f(0,0);t=v=1;c=c.multiply(g.IDENTITY.translate(u.x,u.y).scaleNonUniform(s,x));u=new f(0,0);s=x=1;c=d.inverse().multiply(c).getDecomposition();h=c.rotation.inverse().multiply(c.translation.inverse());c=c.scale;s=c.a;x=c.d;A=A.transform(h);h=d.multiply(h.inverse());p[0]=A;p[1]=t;p[2]=v;b[0]=u;b[1]=s;b[2]=x}else h=function(b,a,f){var d=
function(b){a[b]=a[b].transform(f)};if(b===l.LINE)d(0),d(1);else if(b===l.BEZIER2)d(0),d(1),d(2);else if(b===l.BEZIER3)d(0),d(1),d(2),d(3);else throw Error("Unknown shape: "+b);},k===l.ELLIPSE&&(A=b,b=p,p=A,A=k,k=e,e=A,A=c,c=d,d=A),e===l.ELLIPSE?(A=p[0],t=p[1],v=p[2],d=d.multiply(g.IDENTITY.translate(A.x,A.y).scaleNonUniform(t/1,v/1)),A=new f(0,0),t=v=1,c=d.inverse().multiply(c),h(k,b,c),h=d,p[0]=A,p[1]=t,p[2]=v):(h(e,p,d),h(k,b,c),h=g.IDENTITY);e<k?(e="intersect"+e+k,d=p.concat(b)):(e="intersect"+
k+e,d=b.concat(p));d=n[e].apply(null,d);if(a)for(p=0;p<d.points.length;p++)d.points[p]=d.points[p].transform(h)}}else d=new r;return d}var f=x("kld-affine").Point2D,d=x("kld-affine").Vector2D,g=x("kld-affine").Matrix2D,e=x("kld-polynomial").Polynomial,h=x("./IntersectionParams"),r=x("./Intersection"),l=h.TYPE,n={intersectPathShape:function(f,d,c,g){var e=new r;f=f.params[0];for(var p,k,h,l=0;l<f.length;l++)h=b(f[l],d,c,g),p||(p=h),k&&(a(k.points,h.points),e.appendPoints(k.points)),k=h;k&&e.appendPoints(k.points);
return e},intersectLinesShape:function(f,d,c,g,e){var p=h.TYPE,k=f.params[0],l=new h(p.LINE,[0,0]),n=new r,t,v,u=function(f,m){l.params[0]=k[f];l.params[1]=k[m];t=b(l,d,c,g);a(t.points,[k[m]]);n.appendPoints(t.points)};for(v=0;v<k.length-1;v++)u(v,v+1);("undefined"!==typeof e&&e||f.type===p.RECT||f.type===p.POLYGON)&&u(k.length-1,0);return n},intersectArcShape:function(a,c,e,l){e=e||g.IDENTITY;l=l||g.IDENTITY;var r=a.params[0],p=a.params[1],k=a.params[2],n=a.params[3],A=a.params[4];a=a.params[5];
e.isIdentity()&&0===n||(e=e.multiply(g.IDENTITY.translate(r.x,r.y).rotate(n)),r=new f(0,0),n=0);c=b(h.newEllipse(r,p,k),c,e,l);var t=n,n=a;if(0!==c.points.length){if(e&&!e.isIdentity())var v=e.inverse();e=[];a=new d(1,0);l=2*Math.PI;var u=0>n,s=Math.abs(n)>Math.PI,D=(new g).scaleNonUniform(1,k/p).rotate(A),p=(new g).scaleNonUniform(1,k/p).rotate(A+n);a.angleBetween(a.transform(D));n=a.transform(D).angleBetween(a.transform(p));n=(s?l-Math.abs(n):Math.abs(n))*(u?-1:1);p=(new g).rotate(t).multiply(D);
for(k=0;k<c.points.length;k++)A=c.points[k],t=a.transform(p).angleBetween(d.fromPoints(r,v?A.transform(v):A)),0<=n?(t=(t+2*l)%l,t<=n&&e.push(A)):(t=(t-2*l)%l,t>=n&&e.push(A));c.points=e}return c},intersectEllipseEllipse:function(b,a,d,g,h,p){var k=[d*d,0,a*a,-2*d*d*b.x,-2*a*a*b.y,d*d*b.x*b.x+a*a*b.y*b.y-a*a*d*d],l=[p*p,0,h*h,-2*p*p*g.x,-2*h*h*g.y,p*p*g.x*g.x+h*h*g.y*g.y-h*h*p*p];a=c(k,l);var n=a.getRoots(),t=.001*(k[0]*k[0]+2*k[1]*k[1]+k[2]*k[2]),v=.001*(l[0]*l[0]+2*l[1]*l[1]+l[2]*l[2]);h=new r;var u;
for(u=0;u<n.length;u++)n[u]=Math.max(b.y-d,Math.min(b.y+d,n[u])),n[u]=Math.max(g.y-p,Math.min(g.y+p,n[u]));n.sort(function(b,a){return b-a});u=[];for(b=0;b<n.length;b++)for(d=new e(k[0],k[3]+n[b]*k[1],k[5]+n[b]*(k[4]+n[b]*k[2])),Math.abs(d.coefs[0])<10*1E-15*Math.abs(d.coefs[2])&&(d.coefs[0]=0),d=d.getRoots(),u.push(0),g=0;g<d.length;g++)p=(k[0]*d[g]+k[1]*n[b]+k[3])*d[g]+(k[2]*n[b]+k[4])*n[b]+k[5],Math.abs(p)<t&&(p=(l[0]*d[g]+l[1]*n[b]+l[3])*d[g]+(l[2]*n[b]+l[4])*n[b]+l[5],Math.abs(p)<v&&(h.appendPoint(new f(d[g],
n[b])),u[b]+=1));if(0>=h.points.length)return h;k=h.points;if(8==k.length)k=k.splice(0,6),k.splice(2,2);else if(7==k.length)k=k.splice(0,6),k.splice(2,2),k.splice(u.indexOf(1),1);else if(6==k.length)k.splice(2,2),-1<u.indexOf(0)?k[0].distanceFrom(k[1])<k[2].distanceFrom(k[3])?k.splice(0,1):k.splice(2,1):u[0]==u[3]&&k.splice(1,2);else if(4==k.length)(2==n.length||4==n.length&&(2==u[0]&&2==u[1]||2==u[2]&&2==u[3]))&&k.splice(2,2);else if(3==k.length||5==k.length)u=u.indexOf(2),-1<u&&(3==k.length&&(u%=
2),n=u+(u%2?-1:2),l=k[u].distanceFrom(k[u+1]),t=k[u].distanceFrom(k[n]),v=k[u+1].distanceFrom(k[n]),l<t&&l<v?k.splice(u,1):k.splice(n,1));a=a.zeroErrorEstimate();a=100*a*Math.SQRT2;for(u=0;u<k.length-1;)k[u].distanceFrom(k[u+1])<a?k.splice(u+1,1):u++;h.points=k;return h},intersectEllipseLine:function(b,a,f,c,g){var e,h=new d(c.x,c.y);e=d.fromPoints(c,g);b=new d(b.x,b.y);b=h.subtract(b);h=new d(e.x/(a*a),e.y/(f*f));f=new d(b.x/(a*a),b.y/(f*f));a=e.dot(h);e=e.dot(f);b=b.dot(f)-1;f=e*e-a*b;b=10*Math.max(Math.abs(a),
Math.abs(e),Math.abs(b))*1E-15;Math.abs(f)<b&&(f=0);0>f?e=new r("Outside"):0<f?(f=Math.sqrt(f),b=(-e-f)/a,a=(-e+f)/a,a=1<a?a-1E-15:0>a?a+1E-15:a,b=1<b?b-1E-15:0>b?b+1E-15:b,(0>b||1<b)&&(0>a||1<a)?e=0>b&&0>a||1<b&&1<a?new r("Outside"):new r("Inside"):(e=new r,0<=b&&1>=b&&e.appendPoint(c.lerp(g,b)),0<=a&&1>=a&&e.appendPoint(c.lerp(g,a)))):(a=-e/a,0<=a&&1>=a?(e=new r,e.appendPoint(c.lerp(g,a))):e=new r("Outside"));return e},intersectLineLine:function(b,a,d,c){var e,g=(c.x-d.x)*(b.y-d.y)-(c.y-d.y)*(b.x-
d.x);e=(a.x-b.x)*(b.y-d.y)-(a.y-b.y)*(b.x-d.x);d=(c.y-d.y)*(a.x-b.x)-(c.x-d.x)*(a.y-b.y);0!==d?(g/=d,e/=d,0<=g&&1>=g&&0<=e&&1>=e?(e=new r,e.points.push(new f(b.x+g*(a.x-b.x),b.y+g*(a.y-b.y)))):e=new r):e=0===g||0===e?new r("Coincident"):new r("Parallel");return e},intersectRayRay:function(b,a,d,c){var e;e=(c.x-d.x)*(b.y-d.y)-(c.y-d.y)*(b.x-d.x);var g=(a.x-b.x)*(b.y-d.y)-(a.y-b.y)*(b.x-d.x);d=(c.y-d.y)*(a.x-b.x)-(c.x-d.x)*(a.y-b.y);0!==d?(g=e/d,e=new r,e.points.push(new f(b.x+g*(a.x-b.x),b.y+g*(a.y-
b.y)))):e=0===e||0===g?new r("Coincident"):new r("Parallel");return e}},D={};D[l.PATH]=n.intersectPathShape;D[l.POLYLINE]=n.intersectLinesShape;D[l.POLYGON]=n.intersectLinesShape;D[l.RECT]=n.intersectLinesShape;D[l.ROUNDRECT]=n.intersectPathShape;D[l.ARC]=n.intersectArcShape;b.plugin=function(){for(var b=0;b<arguments.length;b++){var a=arguments[b],f;for(f in a)a.hasOwnProperty(f)&&(n[f]=a[f])}};s.exports=b},{"./Intersection":2,"./IntersectionParams":3,"kld-affine":5,"kld-polynomial":9}],5:[function(x,
s,C){C.Point2D=x("./lib/Point2D");C.Vector2D=x("./lib/Vector2D");C.Matrix2D=x("./lib/Matrix2D")},{"./lib/Matrix2D":6,"./lib/Point2D":7,"./lib/Vector2D":8}],6:[function(x,s,C){function c(a,b,f,d,c,e){Object.defineProperties(this,{a:{value:void 0!==a?a:1,writable:!1,enumerable:!0,configurable:!1},b:{value:void 0!==b?b:0,writable:!1,enumerable:!0,configurable:!1},c:{value:void 0!==f?f:0,writable:!1,enumerable:!0,configurable:!1},d:{value:void 0!==d?d:1,writable:!1,enumerable:!0,configurable:!1},e:{value:void 0!==
c?c:0,writable:!1,enumerable:!0,configurable:!1},f:{value:void 0!==e?e:0,writable:!1,enumerable:!0,configurable:!1}})}c.IDENTITY=new c(1,0,0,1,0,0);c.IDENTITY.isIdentity=function(){return!0};c.prototype.multiply=function(a){return this.isIdentity()?a:a.isIdentity()?this:new this.constructor(this.a*a.a+this.c*a.b,this.b*a.a+this.d*a.b,this.a*a.c+this.c*a.d,this.b*a.c+this.d*a.d,this.a*a.e+this.c*a.f+this.e,this.b*a.e+this.d*a.f+this.f)};c.prototype.inverse=function(){if(this.isIdentity())return this;
var a=this.a*this.d-this.b*this.c;if(0===a)throw"Matrix is not invertible";a=1/a;return new this.constructor(this.d*a,-this.b*a,-this.c*a,this.a*a,(this.f*this.c-this.e*this.d)*a,(this.e*this.b-this.f*this.a)*a)};c.prototype.translate=function(a,b){return new this.constructor(this.a,this.b,this.c,this.d,this.a*a+this.c*b+this.e,this.b*a+this.d*b+this.f)};c.prototype.scale=function(a){return new this.constructor(this.a*a,this.b*a,this.c*a,this.d*a,this.e,this.f)};c.prototype.scaleAt=function(a,b){var f=
b.x-a*b.x,d=b.y-a*b.y;return new this.constructor(this.a*a,this.b*a,this.c*a,this.d*a,this.a*f+this.c*d+this.e,this.b*f+this.d*d+this.f)};c.prototype.scaleNonUniform=function(a,b){return new this.constructor(this.a*a,this.b*a,this.c*b,this.d*b,this.e,this.f)};c.prototype.scaleNonUniformAt=function(a,b,f){var d=f.x-a*f.x;f=f.y-b*f.y;return new this.constructor(this.a*a,this.b*a,this.c*b,this.d*b,this.a*d+this.c*f+this.e,this.b*d+this.d*f+this.f)};c.prototype.rotate=function(a){var b=Math.cos(a);a=
Math.sin(a);return new this.constructor(this.a*b+this.c*a,this.b*b+this.d*a,this.a*-a+this.c*b,this.b*-a+this.d*b,this.e,this.f)};c.prototype.rotateAt=function(a,b){var f=Math.cos(a),d=Math.sin(a),c=-b.x+b.x*f-b.y*d,e=-b.y+b.y*f+b.x*d;return new this.constructor(this.a*f+this.c*d,this.b*f+this.d*d,this.a*-d+this.c*f,this.b*-d+this.d*f,this.a*c+this.c*e+this.e,this.b*c+this.d*e+this.f)};c.prototype.rotateFromVector=function(a){var b=a.unit();a=b.x;b=b.y;return new this.constructor(this.a*a+this.c*
b,this.b*a+this.d*b,this.a*-b+this.c*a,this.b*-b+this.d*a,this.e,this.f)};c.prototype.flipX=function(){return new this.constructor(-this.a,-this.b,this.c,this.d,this.e,this.f)};c.prototype.flipY=function(){return new this.constructor(this.a,this.b,-this.c,-this.d,this.e,this.f)};c.prototype.skewX=function(a){a=Math.tan(a);return new this.constructor(this.a,this.b,this.a*a+this.c,this.b*a+this.d,this.e,this.f)};c.prototype.skewY=function(a){a=Math.tan(a);return new this.constructor(this.a+this.c*a,
this.b+this.d*a,this.c,this.d,this.e,this.f)};c.prototype.isIdentity=function(){return 1===this.a&&0===this.b&&0===this.c&&1===this.d&&0===this.e&&0===this.f};c.prototype.isInvertible=function(){return 0!==this.a*this.d-this.b*this.c};c.prototype.getScale=function(){return{scaleX:Math.sqrt(this.a*this.a+this.c*this.c),scaleY:Math.sqrt(this.b*this.b+this.d*this.d)}};c.prototype.getDecomposition=function(){var a=.5*(this.a+this.d),b=.5*(this.a-this.d),f=.5*(this.b+this.c),d=.5*(this.b-this.c),c=Math.sqrt(a*
a+d*d),e=Math.sqrt(b*b+f*f),h=c+e,c=c-e,b=Math.atan2(f,b),d=Math.atan2(d,a),a=.5*(d-b),d=.5*(d+b);return{translation:new this.constructor(1,0,0,1,this.e,this.f),rotation:this.constructor.IDENTITY.rotate(d),scale:new this.constructor(h,0,0,c,0,0),rotation0:this.constructor.IDENTITY.rotate(a)}};c.prototype.equals=function(a){return this.a===a.a&&this.b===a.b&&this.c===a.c&&this.d===a.d&&this.e===a.e&&this.f===a.f};c.prototype.toString=function(){return"matrix("+[this.a,this.b,this.c,this.d,this.e,this.f].join()+
")"};"undefined"!==typeof s&&(s.exports=c)},{}],7:[function(x,s,C){function c(a,b){Object.defineProperties(this,{x:{value:a,writable:!1,enumerable:!0,configurable:!1},y:{value:b,writable:!1,enumerable:!0,configurable:!1}})}c.prototype.clone=function(){return new this.constructor(this.x,this.y)};c.prototype.add=function(a){return new this.constructor(this.x+a.x,this.y+a.y)};c.prototype.subtract=function(a){return new this.constructor(this.x-a.x,this.y-a.y)};c.prototype.multiply=function(a){return new this.constructor(this.x*
a,this.y*a)};c.prototype.divide=function(a){return new this.constructor(this.x/a,this.y/a)};c.prototype.equals=function(a){return this.x===a.x&&this.y===a.y};c.prototype.lerp=function(a,b){var f=1-b;return new this.constructor(this.x*f+a.x*b,this.y*f+a.y*b)};c.prototype.distanceFrom=function(a){var b=this.x-a.x;a=this.y-a.y;return Math.sqrt(b*b+a*a)};c.prototype.min=function(a){return new this.constructor(Math.min(this.x,a.x),Math.min(this.y,a.y))};c.prototype.max=function(a){return new this.constructor(Math.max(this.x,
a.x),Math.max(this.y,a.y))};c.prototype.transform=function(a){return new this.constructor(a.a*this.x+a.c*this.y+a.e,a.b*this.x+a.d*this.y+a.f)};c.prototype.toString=function(){return"point("+this.x+","+this.y+")"};"undefined"!==typeof s&&(s.exports=c)},{}],8:[function(x,s,C){function c(a,b){Object.defineProperties(this,{x:{value:a,writable:!1,enumerable:!0,configurable:!1},y:{value:b,writable:!1,enumerable:!0,configurable:!1}})}c.fromPoints=function(a,b){return new c(b.x-a.x,b.y-a.y)};c.prototype.length=
function(){return Math.sqrt(this.x*this.x+this.y*this.y)};c.prototype.magnitude=function(){return this.x*this.x+this.y*this.y};c.prototype.dot=function(a){return this.x*a.x+this.y*a.y};c.prototype.cross=function(a){return this.x*a.y-this.y*a.x};c.prototype.determinant=function(a){return this.x*a.y-this.y*a.x};c.prototype.unit=function(){return this.divide(this.length())};c.prototype.add=function(a){return new this.constructor(this.x+a.x,this.y+a.y)};c.prototype.subtract=function(a){return new this.constructor(this.x-
a.x,this.y-a.y)};c.prototype.multiply=function(a){return new this.constructor(this.x*a,this.y*a)};c.prototype.divide=function(a){return new this.constructor(this.x/a,this.y/a)};c.prototype.angleBetween=function(a){var b=this.dot(a)/(this.length()*a.length()),b=Math.max(-1,Math.min(b,1)),b=Math.acos(b);return 0>this.cross(a)?-b:b};c.prototype.perp=function(){return new this.constructor(-this.y,this.x)};c.prototype.perpendicular=function(a){return this.subtract(this.project(a))};c.prototype.project=
function(a){var b=this.dot(a)/a.dot(a);return a.multiply(b)};c.prototype.transform=function(a){return new this.constructor(a.a*this.x+a.c*this.y,a.b*this.x+a.d*this.y)};c.prototype.equals=function(a){return this.x===a.x&&this.y===a.y};c.prototype.toString=function(){return"vector("+this.x+","+this.y+")"};"undefined"!==typeof s&&(s.exports=c)},{}],9:[function(x,s,C){C.Polynomial=x("./lib/Polynomial");C.SqrtPolynomial=x("./lib/SqrtPolynomial")},{"./lib/Polynomial":10,"./lib/SqrtPolynomial":11}],10:[function(x,
s,C){function c(){this.init(arguments)}c.TOLERANCE=1E-6;c.ACCURACY=15;c.interpolate=function(b,a,d,c,e){if(b.constructor!==Array||a.constructor!==Array)throw Error("Polynomial.interpolate: xs and ys must be arrays");if(isNaN(d)||isNaN(c)||isNaN(e))throw Error("Polynomial.interpolate: n, offset, and x must be numbers");for(var h=0,r=0,l=Array(d),n=Array(d),s=0,h=Math.abs(e-b[c]),m=0;m<d;m++){var q=Math.abs(e-b[c+m]);q<h&&(s=m,h=q);l[m]=n[m]=a[c+m]}h=a[c+s];s--;for(a=1;a<d;a++){for(m=0;m<d-a;m++){var r=
b[c+m]-e,q=b[c+m+a]-e,w=r-q;if(0==w)break;w=(l[m+1]-n[m])/w;n[m]=q*w;l[m]=r*w}r=2*(s+1)<d-a?l[s+1]:n[s--];h+=r}return{y:h,dy:r}};c.prototype.init=function(b){this.coefs=[];for(var a=b.length-1;0<=a;a--)this.coefs.push(b[a]);this._variable="t";this._s=0};c.prototype.eval=function(b){if(isNaN(b))throw Error("Polynomial.eval: parameter must be a number");for(var a=0,d=this.coefs.length-1;0<=d;d--)a=a*b+this.coefs[d];return a};c.prototype.add=function(b){for(var a=new c,d=this.getDegree(),g=b.getDegree(),
e=Math.max(d,g),h=0;h<=e;h++)a.coefs[h]=(h<=d?this.coefs[h]:0)+(h<=g?b.coefs[h]:0);return a};c.prototype.multiply=function(b){for(var a=new c,d=0;d<=this.getDegree()+b.getDegree();d++)a.coefs.push(0);for(d=0;d<=this.getDegree();d++)for(var g=0;g<=b.getDegree();g++)a.coefs[d+g]+=this.coefs[d]*b.coefs[g];return a};c.prototype.divide_scalar=function(b){for(var a=0;a<this.coefs.length;a++)this.coefs[a]/=b};c.prototype.simplify=function(){for(var b=this.getDegree();0<=b;b--)if(1E-15>=Math.abs(this.coefs[b]))this.coefs.pop();
else break};c.prototype.bisection=function(b,a){var d=this.eval(b),g=this.eval(a),e;if(Math.abs(d)<=c.TOLERANCE)e=b;else if(Math.abs(g)<=c.TOLERANCE)e=a;else if(0>=d*g)for(var g=Math.log(a-b),g=Math.ceil((g+Math.LN10*c.ACCURACY)/Math.LN2),h=0;h<g;h++){e=.5*(b+a);var r=this.eval(e);if(Math.abs(r)<=c.TOLERANCE)break;0>r*d?a=e:(b=e,d=r)}return e};c.prototype.toString=function(){for(var b=[],a=[],d=this.coefs.length-1;0<=d;d--){var c=Math.round(1E3*this.coefs[d])/1E3;if(0!=c){var e=0>c?" - ":" + ",c=
Math.abs(c);0<d&&(c=1==c?this._variable:c+this._variable);1<d&&(c+="^"+d);a.push(e);b.push(c)}}a[0]=" + "==a[0]?"":"-";c="";for(d=0;d<b.length;d++)c+=a[d]+b[d];return c};c.prototype.trapezoid=function(b,a,d){if(isNaN(b)||isNaN(a)||isNaN(d))throw Error("Polynomial.trapezoid: parameters must be numbers");var c=a-b;if(1==d)d=this.eval(b),a=this.eval(a),this._s=.5*c*(d+a);else{a=1<<d-2;d=c/a;b+=.5*d;for(var e=0,h=0;h<a;h++)e+=this.eval(b),b+=d;this._s=.5*(this._s+c*e/a)}if(isNaN(this._s))throw Error("Polynomial.trapezoid: this._s is NaN");
return this._s};c.prototype.simpson=function(a,c){if(isNaN(a)||isNaN(c))throw Error("Polynomial.simpson: parameters must be numbers");for(var d=c-a,g=.5*d*(this.eval(a)+this.eval(c)),e=g,h=4*g/3,r=h,l=g,n=1,s=2;20>=s;s++){for(var g=d/n,h=a+.5*g,m=0,q=1;q<=n;q++)m+=this.eval(h),h+=g;g=e=.5*(e+d*m/n);h=(4*g-l)/3;if(Math.abs(h-r)<1E-7*Math.abs(r))break;r=h;l=g;n<<=1}return h};c.prototype.romberg=function(a,f){if(isNaN(a)||isNaN(f))throw Error("Polynomial.romberg: parameters must be numbers");for(var d=
Array(21),g=Array(21),e={y:0,dy:0},h=g[0]=1;20>=h;h++){d[h-1]=this.trapezoid(a,f,h);if(3<=h&&(e=c.interpolate(g,d,3,h-3,0),Math.abs(e.dy)<=1E-6*e.y))break;d[h]=d[h-1];g[h]=.25*g[h-1]}return e.y};c.prototype.getDegree=function(){return this.coefs.length-1};c.prototype.getDerivative=function(){for(var a=new c,f=1;f<this.coefs.length;f++)a.coefs.push(f*this.coefs[f]);return a};c.prototype.getRoots=function(){var a;this.simplify();switch(this.getDegree()){case 0:a=[];break;case 1:a=this.getLinearRoot();
break;case 2:a=this.getQuadraticRoots();break;case 3:a=this.getCubicRoots();break;case 4:a=this.getQuarticRoots();break;default:a=[]}return a};c.prototype.getRootsInInterval=function(a,c){var d=[],g;if(1==this.getDegree())g=this.bisection(a,c);else{var e=this.getDerivative().getRootsInInterval(a,c);if(0<e.length){g=this.bisection(a,e[0]);null!=g&&d.push(g);for(i=0;i<=e.length-2;i++)g=this.bisection(e[i],e[i+1]),null!=g&&d.push(g);g=this.bisection(e[e.length-1],c)}else g=this.bisection(a,c)}null!=
g&&d.push(g);return d};c.prototype.getLinearRoot=function(){var a=[],c=this.coefs[1];0!=c&&a.push(-this.coefs[0]/c);return a};c.prototype.getQuadraticRoots=function(){var a=[];if(2==this.getDegree()){var c=this.coefs[2],d=this.coefs[1]/c,c=d*d-this.coefs[0]/c*4;0<c?(c=Math.sqrt(c),a.push(.5*(-d+c)),a.push(.5*(-d-c))):0==c&&a.push(.5*-d)}return a};c.prototype.getCubicRoots=function(){var a=[];if(3==this.getDegree()){var c=this.coefs[3],d=this.coefs[2]/c,g=this.coefs[1]/c,e=(3*g-d*d)/3,c=(2*d*d*d-9*
g*d+this.coefs[0]/c*27)/27,d=d/3,g=c*c/4+e*e*e/27,c=c/2,h=this.zeroErrorEstimate();Math.abs(g)<=h&&(g=0);0<g?(e=Math.sqrt(g),g=-c+e,h=0<=g?Math.pow(g,1/3):-Math.pow(-g,1/3),g=-c-e,h=0<=g?h+Math.pow(g,1/3):h-Math.pow(-g,1/3),a.push(h-d)):0>g?(e=Math.sqrt(-e/3),g=Math.atan2(Math.sqrt(-g),-c)/3,c=Math.cos(g),g=Math.sin(g),h=Math.sqrt(3),a.push(2*e*c-d),a.push(-e*(c+h*g)-d),a.push(-e*(c-h*g)-d)):(g=0<=c?-Math.pow(c,1/3):Math.pow(-c,1/3),a.push(2*g-d),a.push(-g-d))}return a};var a=function(a){return"number"===
typeof a?a?0>a?-1:1:a===a?a:NaN:NaN};c.prototype.getQuarticRoots=function(){var b=[],f=this.getDegree();if(4==f){var d=new c;d.coefs=this.coefs.slice();d.divide_scalar(d.coefs[f]);Math.abs(d.coefs[0])<10*1E-15*Math.abs(d.coefs[3])&&(d.coefs[0]=0);var g=d.getDerivative(),e=g.getRoots().sort(function(a,b){return a-b}),h=[],r=e.length-1,l,n=this.bounds();maxabsX=Math.max(Math.abs(n.minX),Math.abs(n.maxX));var s=this.zeroErrorEstimate(maxabsX);for(l=0;l<=r;l++)h.push(d.eval(e[l]));for(l=0;l<=r;l++)Math.abs(h[l])<
s&&(h[l]=0);l=0;var m=Math.max(.1*(n.maxX-n.minX)/f,1E-15),f=[],s=[];if(-1<r){0!=h[0]?a(h[0])!=a(d.eval(e[0]-m)-h[0])&&(f.push(e[0]-m),s.push([n.minX,e[0]])):(b.push(e[0],e[0]),l++);for(;l<r;l++)0==h[l+1]?(b.push(e[l+1],e[l+1]),l++):a(h[l])!=a(h[l+1])&&(f.push((e[l]+e[l+1])/2),s.push([e[l],e[l+1]]));0!=h[r]&&a(h[r])!=a(d.eval(e[r]+m)-h[r])&&(f.push(e[r]+m),s.push([e[r],n.maxX]))}e=function(a){return d.eval(a)};h=function(a){return g.eval(a)};if(0<f.length)for(l=0;l<f.length;l++)f[l]=c.newton_secant_bisection(f[l],
e,h,32,s[l][0],s[l][1]);b=b.concat(f)}return b};c.prototype.zeroErrorEstimate=function(a){if("undefined"===typeof a){var c=this.bounds();a=Math.max(Math.abs(c.minX),Math.abs(c.maxX))}if(.001>a)return 2*Math.abs(this.eval(1E-15));var d=this.coefs[this.coefs.length-1];return 10*1E-15*this.coefs.reduce(function(c,f,h){f=f/d*Math.pow(a,h);return f>c?f:c},0)};c.prototype.bounds_UpperReal_Fujiwara=function(){var a=this.coefs,c=a.length-1,d=a[c];1!=d&&(a=this.coefs.map(function(a){return a/d}));var g=a.map(function(a,
b){return b<c?Math.pow(Math.abs(0==b?a/2:a),1/(c-b)):a}),e,h=function(a,b,c){e(c)&&(a.max<b?(a.nearmax=a.max,a.max=b):a.nearmax<b&&(a.nearmax=b));return a};e=function(d){return d<c&&0>a[d]};var r=g.reduce(h,{max:0,nearmax:0});e=function(d){return d<c&&(c%2==d%2?0>a[d]:0<a[d])};return{negX:-2*g.reduce(h,{max:0,nearmax:0}).max,posX:2*r.max}};c.prototype.bounds_LowerReal_Fujiwara=function(){var a=new c;a.coefs=this.coefs.slice().reverse();a=a.bounds_UpperReal_Fujiwara();a.negX=1/a.negX;a.posX=1/a.posX;
return a};c.prototype.bounds=function(){var a=this.bounds_UpperReal_Fujiwara(),c={minX:a.negX,maxX:a.posX};if(0===a.negX&&0===a.posX)return c;0===a.negX?c.minX=this.bounds_LowerReal_Fujiwara().posX:0===a.posX&&(c.maxX=this.bounds_LowerReal_Fujiwara().negX);c.minX>c.maxX&&(c.minX=c.maxX=0);return c};c.newton_secant_bisection=function(b,c,d,g,e,h){var r,l=0,n,s=0,m,q,w;r=b;var x=Math.pow(10,-14);if(b="number"===typeof e&&"number"===typeof h){if(e>h)throw Error("newton root finding: min must be greater than max");
q=c(e);w=c(h);if(a(q)==a(w))throw Error("newton root finding: y values of bounds must be of opposite sign");}var B=function(){return Math.abs(m)<=x*Math.abs(r)||s==r-m-r},p;for(p=0;p<g;p++){n=d(r);if(0==n){if(0==l)throw Error("newton root finding: df(x) is zero");n=l}l=n;y=c(r);m=y/n;n=r-m;if(B())break;if(b){if(a(y)==a(w))h=r,w=y;else if(a(y)==a(q))e=r,q=y;else{r=n;break}if(n<e||n>h){if(a(q)==a(w))break;n=w-q;var k=h-e;m=0==n?r-(e+.5*k):50<Math.abs(n/Math.min(q,w))?r-(e+k*(.5+(Math.abs(q)<Math.abs(w)?
-.25:.25))):r-(e-q/n*k);n=r-m;if(B())break}}s=r-n;r=n}return r};"undefined"!==typeof s&&(s.exports=c)},{}],11:[function(x,s,C){function c(){this.init(arguments)}if("undefined"!==typeof s)var a=x("./Polynomial");c.VERSION=1;c.prototype=new a;c.prototype.constructor=c;c.superclass=a.prototype;c.prototype.eval=function(a){a=c.superclass.eval.call(this,a);1E-7>Math.abs(a)&&(a=0);if(0>a)throw Error("SqrtPolynomial.eval: cannot take square root of negative number");return Math.sqrt(a)};c.prototype.toString=
function(){return"sqrt("+c.superclass.toString.call(this)+")"};"undefined"!==typeof s&&(s.exports=c)},{"./Polynomial":10}]},{},[1])(1)});