/*
 React v16.8.6
 react-is.production.min.js

 Copyright (c) Facebook, Inc. and its affiliates.

 This source code is licensed under the MIT license found in the
 LICENSE file in the root directory of this source tree.
 React v16.8.6
 react-is.development.js

 Copyright (c) Facebook, Inc. and its affiliates.

 This source code is licensed under the MIT license found in the
 LICENSE file in the root directory of this source tree.
*/
var $jscomp={scope:{},getGlobal:function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global?global:a}};$jscomp.global=$jscomp.getGlobal(this);$jscomp.initSymbol=function(){$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol);$jscomp.initSymbol=function(){}};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return"jscomp_symbol_"+a+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();$jscomp.global.Symbol.iterator||($jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));$jscomp.initSymbolIterator=function(){}};
$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();if(a[$jscomp.global.Symbol.iterator])return a[$jscomp.global.Symbol.iterator]();if(!(a instanceof Array||"string"==typeof a||a instanceof String))throw new TypeError(a+" is not iterable");var b=0;return{next:function(){return b==a.length?{done:!0}:{done:!1,value:a[b++]}}}};$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.arrayFromArguments=function(a){for(var b=[],c=0;c<a.length;c++)b.push(a[c]);return b};$jscomp.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if($jscomp.global.Object.defineProperties){var e=$jscomp.global.Object.getOwnPropertyDescriptor(b,d);$jscomp.global.Object.defineProperty(a,d,e)}else a[d]=b[d]};
$jscomp.array=$jscomp.array||{};$jscomp.array.done_=function(){return{done:!0,value:void 0}};$jscomp.array.arrayIterator_=function(a,b){a instanceof String&&(a=String(a));var c=0;$jscomp.initSymbol();$jscomp.initSymbolIterator();var d={},e=(d.next=function(){if(c<a.length){var d=c++;return{value:b(d,a[d]),done:!1}}e.next=$jscomp.array.done_;return $jscomp.array.done_()},d[Symbol.iterator]=function(){return e},d);return e};
$jscomp.array.findInternal_=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var h=a[e];if(b.call(c,h,e,a))return{i:e,v:h}}return{i:-1,v:void 0}};
$jscomp.array.from=function(a,b,c){b=void 0===b?function(a){return a}:b;var d=[];$jscomp.initSymbol();$jscomp.initSymbolIterator();if(a[Symbol.iterator]){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=a[Symbol.iterator]();for(var e;!(e=a.next()).done;)d.push(b.call(c,e.value))}else{e=a.length;for(var h=0;h<e;h++)d.push(b.call(c,a[h]))}return d};$jscomp.array.of=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];return $jscomp.array.from(b)};
$jscomp.array.entries=function(){return $jscomp.array.arrayIterator_(this,function(a,b){return[a,b]})};$jscomp.array.entries$install=function(){Array.prototype.entries||(Array.prototype.entries=$jscomp.array.entries)};$jscomp.array.keys=function(){return $jscomp.array.arrayIterator_(this,function(a){return a})};$jscomp.array.keys$install=function(){Array.prototype.keys||(Array.prototype.keys=$jscomp.array.keys)};$jscomp.array.values=function(){return $jscomp.array.arrayIterator_(this,function(a,b){return b})};
$jscomp.array.values$install=function(){Array.prototype.values||(Array.prototype.values=$jscomp.array.values)};$jscomp.array.copyWithin=function(a,b,c){var d=this.length;a=Number(a);b=Number(b);c=Number(null!=c?c:d);if(a<b)for(c=Math.min(c,d);b<c;)b in this?this[a++]=this[b++]:(delete this[a++],b++);else for(c=Math.min(c,d+b-a),a+=c-b;c>b;)--c in this?this[--a]=this[c]:delete this[a];return this};$jscomp.array.copyWithin$install=function(){Array.prototype.copyWithin||(Array.prototype.copyWithin=$jscomp.array.copyWithin)};
$jscomp.array.fill=function(a,b,c){null!=c&&a.length||(c=this.length||0);c=Number(c);for(b=Number((void 0===b?0:b)||0);b<c;b++)this[b]=a;return this};$jscomp.array.fill$install=function(){Array.prototype.fill||(Array.prototype.fill=$jscomp.array.fill)};$jscomp.array.find=function(a,b){return $jscomp.array.findInternal_(this,a,b).v};$jscomp.array.find$install=function(){Array.prototype.find||(Array.prototype.find=$jscomp.array.find)};
$jscomp.array.findIndex=function(a,b){return $jscomp.array.findInternal_(this,a,b).i};$jscomp.array.findIndex$install=function(){Array.prototype.findIndex||(Array.prototype.findIndex=$jscomp.array.findIndex)};$jscomp.Map=function(a){a=void 0===a?[]:a;this.data_={};this.head_=$jscomp.Map.createHead_();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var b=a.next();!b.done;b=a.next())b=b.value,this.set(b[0],b[1])}};
$jscomp.Map.checkBrowserConformance_=function(){var a=$jscomp.global.Map;if(!a||!a.prototype.entries||!Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a($jscomp.makeIterator([[b,"s"]]));if("s"!=c.get(b)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var d=c.entries(),e=d.next();if(e.done||e.value[0]!=b||"s"!=e.value[1])return!1;e=d.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!d.next().done?!1:!0}catch(h){return!1}};
$jscomp.Map.createHead_=function(){var a={};return a.previous=a.next=a.head=a};$jscomp.Map.getId_=function(a){if(!(a instanceof Object))return String(a);$jscomp.Map.key_ in a||a instanceof Object&&Object.isExtensible&&Object.isExtensible(a)&&$jscomp.Map.defineProperty_(a,$jscomp.Map.key_,++$jscomp.Map.index_);return $jscomp.Map.key_ in a?a[$jscomp.Map.key_]:" "+a};
$jscomp.Map.prototype.set=function(a,b){var c=this.maybeGetEntry_(a),d=c.id,e=c.list,c=c.entry;e||(e=this.data_[d]=[]);c?c.value=b:(c={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,value:b},e.push(c),this.head_.previous.next=c,this.head_.previous=c,this.size++);return this};
$jscomp.Map.prototype["delete"]=function(a){var b=this.maybeGetEntry_(a);a=b.id;var c=b.list,d=b.index;return(b=b.entry)&&c?(c.splice(d,1),c.length||delete this.data_[a],b.previous.next=b.next,b.next.previous=b.previous,b.head=null,this.size--,!0):!1};$jscomp.Map.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=$jscomp.Map.createHead_();this.size=0};$jscomp.Map.prototype.has=function(a){return!!this.maybeGetEntry_(a).entry};
$jscomp.Map.prototype.get=function(a){return(a=this.maybeGetEntry_(a).entry)&&a.value};$jscomp.Map.prototype.maybeGetEntry_=function(a){var b=$jscomp.Map.getId_(a),c=this.data_[b];if(c)for(var d=0;d<c.length;d++){var e=c[d];if(a!==a&&e.key!==e.key||a===e.key)return{id:b,list:c,index:d,entry:e}}return{id:b,list:c,index:-1,entry:void 0}};$jscomp.Map.prototype.entries=function(){return this.iter_(function(a){return[a.key,a.value]})};$jscomp.Map.prototype.keys=function(){return this.iter_(function(a){return a.key})};
$jscomp.Map.prototype.values=function(){return this.iter_(function(a){return a.value})};$jscomp.Map.prototype.forEach=function(a,b){for(var c=$jscomp.makeIterator(this.entries()),d=c.next();!d.done;d=c.next())d=d.value,a.call(b,d[1],d[0],this)};
$jscomp.Map.prototype.iter_=function(a){var b=this,c=this.head_;$jscomp.initSymbol();$jscomp.initSymbolIterator();var d={};return d.next=function(){if(c){for(;c.head!=b.head_;)c=c.previous;for(;c.next!=c.head;)return c=c.next,{done:!1,value:a(c)};c=null}return{done:!0,value:void 0}},d[Symbol.iterator]=function(){return this},d};$jscomp.Map.index_=0;$jscomp.Map.defineProperty_=Object.defineProperty?function(a,b,c){Object.defineProperty(a,b,{value:String(c)})}:function(a,b,c){a[b]=String(c)};
$jscomp.Map.Entry_=function(){};$jscomp.Map.ASSUME_NO_NATIVE=!1;$jscomp.Map$install=function(){$jscomp.initSymbol();$jscomp.initSymbolIterator();!$jscomp.Map.ASSUME_NO_NATIVE&&$jscomp.Map.checkBrowserConformance_()?$jscomp.Map=$jscomp.global.Map:($jscomp.initSymbol(),$jscomp.initSymbolIterator(),$jscomp.Map.prototype[Symbol.iterator]=$jscomp.Map.prototype.entries,$jscomp.initSymbol(),$jscomp.Map.key_=Symbol("map-id-key"));$jscomp.Map$install=function(){}};$jscomp.math=$jscomp.math||{};
$jscomp.math.clz32=function(a){a=Number(a)>>>0;if(0===a)return 32;var b=0;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);0===(a&2147483648)&&b++;return b};$jscomp.math.imul=function(a,b){a=Number(a);b=Number(b);var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0};$jscomp.math.sign=function(a){a=Number(a);return 0===a||isNaN(a)?a:0<a?1:-1};
$jscomp.math.log10=function(a){return Math.log(a)/Math.LN10};$jscomp.math.log2=function(a){return Math.log(a)/Math.LN2};$jscomp.math.log1p=function(a){a=Number(a);if(.25>a&&-.25<a){for(var b=a,c=1,d=a,e=0,h=1;e!=d;)b*=a,h*=-1,d=(e=d)+h*b/++c;return d}return Math.log(1+a)};$jscomp.math.expm1=function(a){a=Number(a);if(.25>a&&-.25<a){for(var b=a,c=1,d=a,e=0;e!=d;)b*=a/++c,d=(e=d)+b;return d}return Math.exp(a)-1};$jscomp.math.cosh=function(a){a=Number(a);return(Math.exp(a)+Math.exp(-a))/2};
$jscomp.math.sinh=function(a){a=Number(a);return 0===a?a:(Math.exp(a)-Math.exp(-a))/2};$jscomp.math.tanh=function(a){a=Number(a);if(0===a)return a;var b=Math.exp(2*-Math.abs(a)),b=(1-b)/(1+b);return 0>a?-b:b};$jscomp.math.acosh=function(a){a=Number(a);return Math.log(a+Math.sqrt(a*a-1))};$jscomp.math.asinh=function(a){a=Number(a);if(0===a)return a;var b=Math.log(Math.abs(a)+Math.sqrt(a*a+1));return 0>a?-b:b};
$jscomp.math.atanh=function(a){a=Number(a);return($jscomp.math.log1p(a)-$jscomp.math.log1p(-a))/2};
$jscomp.math.hypot=function(a,b,c){for(var d=[],e=2;e<arguments.length;++e)d[e-2]=arguments[e];a=Number(a);b=Number(b);for(var h=Math.max(Math.abs(a),Math.abs(b)),q=$jscomp.makeIterator(d),e=q.next();!e.done;e=q.next())h=Math.max(h,Math.abs(e.value));if(1E100<h||1E-100>h){a/=h;b/=h;q=a*a+b*b;d=$jscomp.makeIterator(d);for(e=d.next();!e.done;e=d.next())e=e.value,e=Number(e)/h,q+=e*e;return Math.sqrt(q)*h}h=a*a+b*b;d=$jscomp.makeIterator(d);for(e=d.next();!e.done;e=d.next())e=e.value,h+=e*e;return Math.sqrt(h)};
$jscomp.math.trunc=function(a){a=Number(a);if(isNaN(a)||Infinity===a||-Infinity===a||0===a)return a;var b=Math.floor(Math.abs(a));return 0>a?-b:b};$jscomp.math.cbrt=function(a){if(0===a)return a;a=Number(a);var b=Math.pow(Math.abs(a),1/3);return 0>a?-b:b};$jscomp.number=$jscomp.number||{};$jscomp.number.isFinite=function(a){return"number"!==typeof a?!1:!isNaN(a)&&Infinity!==a&&-Infinity!==a};$jscomp.number.isInteger=function(a){return $jscomp.number.isFinite(a)?a===Math.floor(a):!1};
$jscomp.number.isNaN=function(a){return"number"===typeof a&&isNaN(a)};$jscomp.number.isSafeInteger=function(a){return $jscomp.number.isInteger(a)&&Math.abs(a)<=$jscomp.number.MAX_SAFE_INTEGER};$jscomp.number.EPSILON=Math.pow(2,-52);$jscomp.number.MAX_SAFE_INTEGER=9007199254740991;$jscomp.number.MIN_SAFE_INTEGER=-9007199254740991;$jscomp.object=$jscomp.object||{};
$jscomp.object.assign=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];c=$jscomp.makeIterator(c);for(d=c.next();!d.done;d=c.next()){var d=d.value,e;for(e in d)Object.prototype.hasOwnProperty.call(d,e)&&(a[e]=d[e])}return a};$jscomp.object.is=function(a,b){return a===b?0!==a||1/a===1/b:a!==a&&b!==b};$jscomp.Set=function(a){a=void 0===a?[]:a;this.map_=new $jscomp.Map;if(a){a=$jscomp.makeIterator(a);for(var b=a.next();!b.done;b=a.next())this.add(b.value)}this.size=this.map_.size};
$jscomp.Set.checkBrowserConformance_=function(){var a=$jscomp.global.Set;if(!a||!a.prototype.entries||!Object.seal)return!1;var b=Object.seal({x:4}),a=new a($jscomp.makeIterator([b]));if(a.has(b)||1!=a.size||a.add(b)!=a||1!=a.size||a.add({x:4})!=a||2!=a.size)return!1;var a=a.entries(),c=a.next();if(c.done||c.value[0]!=b||c.value[1]!=b)return!1;c=a.next();return c.done||c.value[0]==b||4!=c.value[0].x||c.value[1]!=c.value[0]?!1:a.next().done};
$jscomp.Set.prototype.add=function(a){this.map_.set(a,a);this.size=this.map_.size;return this};$jscomp.Set.prototype["delete"]=function(a){a=this.map_["delete"](a);this.size=this.map_.size;return a};$jscomp.Set.prototype.clear=function(){this.map_.clear();this.size=0};$jscomp.Set.prototype.has=function(a){return this.map_.has(a)};$jscomp.Set.prototype.entries=function(){return this.map_.entries()};$jscomp.Set.prototype.values=function(){return this.map_.values()};
$jscomp.Set.prototype.forEach=function(a,b){var c=this;this.map_.forEach(function(d){return a.call(b,d,d,c)})};$jscomp.Set.ASSUME_NO_NATIVE=!1;$jscomp.Set$install=function(){!$jscomp.Set.ASSUME_NO_NATIVE&&$jscomp.Set.checkBrowserConformance_()?$jscomp.Set=$jscomp.global.Set:($jscomp.Map$install(),$jscomp.initSymbol(),$jscomp.initSymbolIterator(),$jscomp.Set.prototype[Symbol.iterator]=$jscomp.Set.prototype.values);$jscomp.Set$install=function(){}};$jscomp.string=$jscomp.string||{};
$jscomp.string.noRegExp_=function(a,b){if(a instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");};
$jscomp.string.fromCodePoint=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];for(var c="",b=$jscomp.makeIterator(b),d=b.next();!d.done;d=b.next()){d=d.value;d=+d;if(0>d||1114111<d||d!==Math.floor(d))throw new RangeError("invalid_code_point "+d);65535>=d?c+=String.fromCharCode(d):(d-=65536,c+=String.fromCharCode(d>>>10&1023|55296),c+=String.fromCharCode(d&1023|56320))}return c};
$jscomp.string.repeat=function(a){var b=this.toString();if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var c="";a;)if(a&1&&(c+=b),a>>>=1)b+=b;return c};$jscomp.string.repeat$install=function(){String.prototype.repeat||(String.prototype.repeat=$jscomp.string.repeat)};
$jscomp.string.codePointAt=function(a){var b=this.toString(),c=b.length;a=Number(a)||0;if(0<=a&&a<c){a|=0;var d=b.charCodeAt(a);if(55296>d||56319<d||a+1===c)return d;a=b.charCodeAt(a+1);return 56320>a||57343<a?d:1024*(d-55296)+a+9216}};$jscomp.string.codePointAt$install=function(){String.prototype.codePointAt||(String.prototype.codePointAt=$jscomp.string.codePointAt)};
$jscomp.string.includes=function(a,b){b=void 0===b?0:b;$jscomp.string.noRegExp_(a,"includes");return-1!==this.toString().indexOf(a,b)};$jscomp.string.includes$install=function(){String.prototype.includes||(String.prototype.includes=$jscomp.string.includes)};
$jscomp.string.startsWith=function(a,b){b=void 0===b?0:b;$jscomp.string.noRegExp_(a,"startsWith");var c=this.toString();a+="";for(var d=c.length,e=a.length,h=Math.max(0,Math.min(b|0,c.length)),q=0;q<e&&h<d;)if(c[h++]!=a[q++])return!1;return q>=e};$jscomp.string.startsWith$install=function(){String.prototype.startsWith||(String.prototype.startsWith=$jscomp.string.startsWith)};
$jscomp.string.endsWith=function(a,b){$jscomp.string.noRegExp_(a,"endsWith");var c=this.toString();a+="";void 0===b&&(b=c.length);for(var d=Math.max(0,Math.min(b|0,c.length)),e=a.length;0<e&&0<d;)if(c[--d]!=a[--e])return!1;return 0>=e};$jscomp.string.endsWith$install=function(){String.prototype.endsWith||(String.prototype.endsWith=$jscomp.string.endsWith)};
var agGridReact=function(a){function b(d){if(c[d])return c[d].exports;var e=c[d]={exports:{},id:d,loaded:!1};a[d].call(e.exports,e,e.exports,b);e.loaded=!0;return e.exports}var c={};b.m=a;b.c=c;b.p="";return b(0)}([function(a,b,c){b.AgGridReact=c(1).AgGridReact;b.AgGridColumn=c(15).AgGridColumn},function(a,b,c){function d(a,b){a.forEach(function(a){l[a]=b})}var e=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=
b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),h=this&&this.__decorate||function(a,b,c,d){var e=arguments.length,f=3>e?b:null===d?d=Object.getOwnPropertyDescriptor(b,c):d,g;if("object"===typeof Reflect&&"function"===typeof Reflect.decorate)f=Reflect.decorate(a,b,c,d);else for(var k=a.length-1;0<=k;k--)if(g=a[k])f=(3>e?g(f):3<e?g(b,
c,f):g(b,c))||f;return 3<e&&f&&Object.defineProperty(b,c,f),f},q=this&&this.__metadata||function(a,b){if("object"===typeof Reflect&&"function"===typeof Reflect.metadata)return Reflect.metadata(a,b)};Object.defineProperty(b,"__esModule",{value:!0});var p=c(2),n=c(3);a=c(4);var f=c(14),g=c(14),k=c(15),t=c(16),r=c(18),m=c(19),l=function(a){function b(c,d){var e=a.call(this,c,d)||this;e.props=c;e.state=d;e.destroyed=!1;e.changeDetectionService=new r.ChangeDetectionService;e.api=null;e.portals=[];e.hasPendingPortalUpdate=
!1;return e}e(b,a);b.prototype.render=function(){var a=this;return p.createElement("div",{style:this.createStyleForDiv(),ref:function(b){a.eGridDiv=b}},this.portals)};b.prototype.createStyleForDiv=function(){var a={height:"100%"},b=this.props.containerStyle;b&&Object.keys(b).forEach(function(c){a[c]=b[c]});return a};b.prototype.componentDidMount=function(){var a={seedBeanInstances:{agGridReact:this}},b=this.props.gridOptions||{};k.AgGridColumn.hasChildColumns(this.props)&&(b.columnDefs=k.AgGridColumn.mapChildColumnDefs(this.props));
this.gridOptions=f.ComponentUtil.copyAttributesToGridOptions(b,this.props);new f.Grid(this.eGridDiv,this.gridOptions,a);this.api=this.gridOptions.api;this.columnApi=this.gridOptions.columnApi};b.prototype.shouldComponentUpdate=function(){return!1};b.prototype.waitForInstance=function(a,c,d){var e=this;void 0===d&&(d=0);a.isStatelesComponent()&&a.statelessComponentRendered()?c(null):!a.isStatelesComponent()&&a.getFrameworkComponentInstance()?c(null):d>=b.MAX_COMPONENT_CREATION_TIME?console.error("ag-Grid: React Component '"+
a.getReactComponentName()+"' not created within "+b.MAX_COMPONENT_CREATION_TIME+"ms"):window.setTimeout(function(){return e.waitForInstance(a,c,d+5)},5)};b.prototype.mountReactPortal=function(a,b,c){this.portals=this.portals.concat([a]);this.batchUpdate(this.waitForInstance(b,c))};b.prototype.batchUpdate=function(a){var b=this;if(this.hasPendingPortalUpdate)return a&&a();setTimeout(function(){b.api&&b.forceUpdate(function(){a&&a();b.hasPendingPortalUpdate=!1})});this.hasPendingPortalUpdate=!0};b.prototype.destroyPortal=
function(a){this.portals=this.portals.filter(function(b){return b!==a});this.batchUpdate()};b.prototype.getStrategyTypeForProp=function(a){if("rowData"===a){if(this.props.rowDataChangeDetectionStrategy)return this.props.rowDataChangeDetectionStrategy;if(this.props.deltaRowDataMode)return r.ChangeDetectionStrategyType.IdentityCheck}return r.ChangeDetectionStrategyType.DeepValueCheck};b.prototype.componentWillReceiveProps=function(a){var b={};this.extractGridPropertyChanges(a,b);this.extractDeclarativeColDefChanges(a,
b);f.ComponentUtil.processOnChange(b,this.gridOptions,this.api,this.columnApi)};b.prototype.extractDeclarativeColDefChanges=function(a,b){var c=!!a.debug;if(k.AgGridColumn.hasChildColumns(a)){var d=this.changeDetectionService.getStrategy(r.ChangeDetectionStrategyType.DeepValueCheck),e=this.gridOptions.columnDefs,f=k.AgGridColumn.mapChildColumnDefs(a);d.areEqual(e,f)||(c&&console.log("agGridReact: colDefs definitions changed"),b.columnDefs={previousValue:this.gridOptions.columnDefs,currentValue:k.AgGridColumn.mapChildColumnDefs(a)})}};
b.prototype.extractGridPropertyChanges=function(a,b){var c=this,d=!!a.debug;Object.keys(a).forEach(function(e){-1===f.ComponentUtil.ALL_PROPERTIES.indexOf(e)||c.changeDetectionService.getStrategy(c.getStrategyTypeForProp(e)).areEqual(c.props[e],a[e])||(d&&console.log("agGridReact: ["+e+"] property changed"),b[e]={previousValue:c.props[e],currentValue:a[e]})});f.ComponentUtil.getEventCallbacks().forEach(function(e){c.props[e]!==a[e]&&(d&&console.log("agGridReact: ["+e+"] event callback changed"),b[e]=
{previousValue:c.props[e],currentValue:a[e]})})};b.prototype.componentWillUnmount=function(){this.api&&(this.api.destroy(),this.api=null)};b.MAX_COMPONENT_CREATION_TIME=1E3;return b}(p.Component);b.AgGridReact=l;l.propTypes={gridOptions:a.object};d(f.ComponentUtil.getEventCallbacks(),a.func);d(f.ComponentUtil.BOOLEAN_PROPERTIES,a.bool);d(f.ComponentUtil.STRING_PROPERTIES,a.string);d(f.ComponentUtil.OBJECT_PROPERTIES,a.object);d(f.ComponentUtil.ARRAY_PROPERTIES,a.array);d(f.ComponentUtil.NUMBER_PROPERTIES,
a.number);d(f.ComponentUtil.FUNCTION_PROPERTIES,a.func);b=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}e(b,a);b.prototype.createWrapper=function(a){return this.useLegacyReact()?new m.LegacyReactComponent(a,this.agGridReact):new t.ReactComponent(a,this.agGridReact)};b.prototype.useLegacyReact=function(){return"function"!==typeof n.unstable_renderSubtreeIntoContainer||this.agGridReact&&this.agGridReact.gridOptions&&!this.agGridReact.gridOptions.reactNext};h([g.Autowired("agGridReact"),
q("design:type",l)],b.prototype,"agGridReact",void 0);return b=h([g.Bean("frameworkComponentWrapper")],b)}(g.BaseComponentWrapper);f.Grid.setFrameworkBeans([b])},function(a,b){a.exports=React},function(a,b){a.exports=ReactDOM},function(a,b,c){(function(b){"production"!==b.env.NODE_ENV?(b=c(6),a.exports=c(9)(b.isElement,!0)):a.exports=c(13)()}).call(b,c(5))},function(a,b){function c(){throw Error("setTimeout has not been defined");}function d(){throw Error("clearTimeout has not been defined");}function e(a){if(k===
setTimeout)return setTimeout(a,0);if((k===c||!k)&&setTimeout)return k=setTimeout,setTimeout(a,0);try{return k(a,0)}catch(b){try{return k.call(null,a,0)}catch(d){return k.call(this,a,0)}}}function h(a){if(t===clearTimeout)return clearTimeout(a);if((t===d||!t)&&clearTimeout)return t=clearTimeout,clearTimeout(a);try{return t(a)}catch(b){try{return t.call(null,a)}catch(c){return t.call(this,a)}}}function q(){m&&l&&(m=!1,l.length?r=l.concat(r):u=-1,r.length&&p())}function p(){if(!m){var a=e(q);m=!0;for(var b=
r.length;b;){l=r;for(r=[];++u<b;)l&&l[u].run();u=-1;b=r.length}l=null;m=!1;h(a)}}function n(a,b){this.fun=a;this.array=b}function f(){}var g=a.exports={},k,t;try{k="function"===typeof setTimeout?setTimeout:c}catch(v){k=c}try{t="function"===typeof clearTimeout?clearTimeout:d}catch(v){t=d}var r=[],m=!1,l,u=-1;g.nextTick=function(a){var b=Array(arguments.length-1);if(1<arguments.length)for(var c=1;c<arguments.length;c++)b[c-1]=arguments[c];r.push(new n(a,b));1!==r.length||m||e(p)};n.prototype.run=function(){this.fun.apply(null,
this.array)};g.title="browser";g.browser=!0;g.env={};g.argv=[];g.version="";g.versions={};g.on=f;g.addListener=f;g.once=f;g.off=f;g.removeListener=f;g.removeAllListeners=f;g.emit=f;g.prependListener=f;g.prependOnceListener=f;g.listeners=function(a){return[]};g.binding=function(a){throw Error("process.binding is not supported");};g.cwd=function(){return"/"};g.chdir=function(a){throw Error("process.chdir is not supported");};g.umask=function(){return 0}},function(a,b,c){(function(b){a.exports="production"===
b.env.NODE_ENV?c(7):c(8)}).call(b,c(5))},function(a,b){function c(a){if("object"===typeof a&&null!==a){var b=a.$$typeof;switch(b){case h:switch(a=a.type,a){case t:case r:case p:case f:case n:case l:return a;default:switch(a=a&&a.$$typeof,a){case k:case m:case g:return a;default:return b}}case v:case u:case q:return b}}}function d(a){return c(a)===r}Object.defineProperty(b,"__esModule",{value:!0});$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();
$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();var e="function"===typeof Symbol&&Symbol.for,h=e?Symbol.for("react.element"):60103,q=e?Symbol.for("react.portal"):60106,p=e?Symbol.for("react.fragment"):60107,n=e?Symbol.for("react.strict_mode"):60108,f=e?Symbol.for("react.profiler"):60114,g=e?Symbol.for("react.provider"):60109,k=e?Symbol.for("react.context"):
60110,t=e?Symbol.for("react.async_mode"):60111,r=e?Symbol.for("react.concurrent_mode"):60111,m=e?Symbol.for("react.forward_ref"):60112,l=e?Symbol.for("react.suspense"):60113,u=e?Symbol.for("react.memo"):60115,v=e?Symbol.for("react.lazy"):60116;b.typeOf=c;b.AsyncMode=t;b.ConcurrentMode=r;b.ContextConsumer=k;b.ContextProvider=g;b.Element=h;b.ForwardRef=m;b.Fragment=p;b.Lazy=v;b.Memo=u;b.Portal=q;b.Profiler=f;b.StrictMode=n;b.Suspense=l;b.isValidElementType=function(a){return"string"===typeof a||"function"===
typeof a||a===p||a===r||a===f||a===n||a===l||"object"===typeof a&&null!==a&&(a.$$typeof===v||a.$$typeof===u||a.$$typeof===g||a.$$typeof===k||a.$$typeof===m)};b.isAsyncMode=function(a){return d(a)||c(a)===t};b.isConcurrentMode=d;b.isContextConsumer=function(a){return c(a)===k};b.isContextProvider=function(a){return c(a)===g};b.isElement=function(a){return"object"===typeof a&&null!==a&&a.$$typeof===h};b.isForwardRef=function(a){return c(a)===m};b.isFragment=function(a){return c(a)===p};b.isLazy=function(a){return c(a)===
v};b.isMemo=function(a){return c(a)===u};b.isPortal=function(a){return c(a)===q};b.isProfiler=function(a){return c(a)===f};b.isStrictMode=function(a){return c(a)===n};b.isSuspense=function(a){return c(a)===l}},function(a,b,c){(function(a){"production"!==a.env.NODE_ENV&&function(){function a(b){if("object"===typeof b&&null!==b){var c=b.$$typeof;switch(c){case p:switch(b=b.type,b){case m:case l:case f:case k:case g:case v:return b;default:switch(b=b&&b.$$typeof,b){case r:case u:case t:return b;default:return c}}case w:case x:case n:return c}}}
function c(b){return a(b)===l}Object.defineProperty(b,"__esModule",{value:!0});$jscomp.initSymbol();$jscomp.initSymbol();var d="function"===typeof Symbol&&Symbol.for;$jscomp.initSymbol();var p=d?Symbol.for("react.element"):60103;$jscomp.initSymbol();var n=d?Symbol.for("react.portal"):60106;$jscomp.initSymbol();var f=d?Symbol.for("react.fragment"):60107;$jscomp.initSymbol();var g=d?Symbol.for("react.strict_mode"):60108;$jscomp.initSymbol();var k=d?Symbol.for("react.profiler"):60114;$jscomp.initSymbol();
var t=d?Symbol.for("react.provider"):60109;$jscomp.initSymbol();var r=d?Symbol.for("react.context"):60110;$jscomp.initSymbol();var m=d?Symbol.for("react.async_mode"):60111;$jscomp.initSymbol();var l=d?Symbol.for("react.concurrent_mode"):60111;$jscomp.initSymbol();var u=d?Symbol.for("react.forward_ref"):60112;$jscomp.initSymbol();var v=d?Symbol.for("react.suspense"):60113;$jscomp.initSymbol();var x=d?Symbol.for("react.memo"):60115;$jscomp.initSymbol();var w=d?Symbol.for("react.lazy"):60116,d=function(){},
z=function(a){for(var b=arguments.length,c=Array(1<b?b-1:0),d=1;d<b;d++)c[d-1]=arguments[d];var e=0,b="Warning: "+a.replace(/%s/g,function(){return c[e++]});"undefined"!==typeof console&&console.warn(b);try{throw Error(b);}catch(f){}},D=d=function(a,b){if(void 0===b)throw Error("`lowPriorityWarning(condition, format, ...args)` requires a warning message argument");if(!a){for(var c=arguments.length,d=Array(2<c?c-2:0),e=2;e<c;e++)d[e-2]=arguments[e];z.apply(void 0,[b].concat(d))}},A=!1;b.typeOf=a;b.AsyncMode=
m;b.ConcurrentMode=l;b.ContextConsumer=r;b.ContextProvider=t;b.Element=p;b.ForwardRef=u;b.Fragment=f;b.Lazy=w;b.Memo=x;b.Portal=n;b.Profiler=k;b.StrictMode=g;b.Suspense=v;b.isValidElementType=function(a){return"string"===typeof a||"function"===typeof a||a===f||a===l||a===k||a===g||a===v||"object"===typeof a&&null!==a&&(a.$$typeof===w||a.$$typeof===x||a.$$typeof===t||a.$$typeof===r||a.$$typeof===u)};b.isAsyncMode=function(b){A||(A=!0,D(!1,"The ReactIs.isAsyncMode() alias has been deprecated, and will be removed in React 17+. Update your code to use ReactIs.isConcurrentMode() instead. It has the exact same API."));
return c(b)||a(b)===m};b.isConcurrentMode=c;b.isContextConsumer=function(b){return a(b)===r};b.isContextProvider=function(b){return a(b)===t};b.isElement=function(a){return"object"===typeof a&&null!==a&&a.$$typeof===p};b.isForwardRef=function(b){return a(b)===u};b.isFragment=function(b){return a(b)===f};b.isLazy=function(b){return a(b)===w};b.isMemo=function(b){return a(b)===x};b.isPortal=function(b){return a(b)===n};b.isProfiler=function(b){return a(b)===k};b.isStrictMode=function(b){return a(b)===
g};b.isSuspense=function(b){return a(b)===v}}()}).call(b,c(5))},function(a,b,c){(function(b){function e(){return null}var h=c(6),q=c(10),p=c(11),n=c(12),f=Function.call.bind(Object.prototype.hasOwnProperty),g=function(){};"production"!==b.env.NODE_ENV&&(g=function(a){a="Warning: "+a;"undefined"!==typeof console&&console.error(a);try{throw Error(a);}catch(b){}});a.exports=function(a,c){function r(a,b){return a===b?0!==a||1/a===1/b:a!==a&&b!==b}function m(a){this.message=a;this.stack=""}function l(a){function e(n,
h,q,y,r,l,C){y=y||"\x3c\x3canonymous\x3e\x3e";l=l||q;if(C!==p){if(c)throw n=Error("Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them. Read more at http://fb.me/use-check-prop-types"),n.name="Invariant Violation",n;"production"!==b.env.NODE_ENV&&"undefined"!==typeof console&&(C=y+":"+q,!f[C]&&3>k&&(g("You are manually calling a React.PropTypes validation function for the `"+l+"` prop on `"+y+"`. This is deprecated and will throw in the standalone `prop-types` package. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details."),
f[C]=!0,k++))}return null==h[q]?n?null===h[q]?new m("The "+r+" `"+l+"` is marked as required "+("in `"+y+"`, but its value is `null`.")):new m("The "+r+" `"+l+"` is marked as required in "+("`"+y+"`, but its value is `undefined`.")):null:a(h,q,y,r,l)}if("production"!==b.env.NODE_ENV)var f={},k=0;var n=e.bind(null,!1);n.isRequired=e.bind(null,!0);return n}function u(a){return l(function(b,c,d,e,f,g){b=b[c];return w(b)!==a?(b=z(b),new m("Invalid "+e+" `"+f+"` of type "+("`"+b+"` supplied to `"+d+"`, expected ")+
("`"+a+"`."))):null})}function v(b){switch(typeof b){case "number":case "string":case "undefined":return!0;case "boolean":return!b;case "object":if(Array.isArray(b))return b.every(v);if(null===b||a(b))return!0;var c;var d=b&&(A&&b[A]||b["@@iterator"]);c="function"===typeof d?d:void 0;if(c)if(d=c.call(b),c!==b.entries)for(;!(b=d.next()).done;){if(!v(b.value))return!1}else for(;!(b=d.next()).done;){if((b=b.value)&&!v(b[1]))return!1}else return!1;return!0;default:return!1}}function x(a,b){if("symbol"===
a)return!0;if(!b)return!1;if("Symbol"===b["@@toStringTag"])return!0;$jscomp.initSymbol();$jscomp.initSymbol();return"function"===typeof Symbol&&b instanceof Symbol?!0:!1}function w(a){var b=typeof a;return Array.isArray(a)?"array":a instanceof RegExp?"object":x(b,a)?"symbol":b}function z(a){if("undefined"===typeof a||null===a)return""+a;var b=w(a);if("object"===b){if(a instanceof Date)return"date";if(a instanceof RegExp)return"regexp"}return b}function D(a){a=z(a);switch(a){case "array":case "object":return"an "+
a;case "boolean":case "date":case "regexp":return"a "+a;default:return a}}$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbolIterator();var A="function"===typeof Symbol&&Symbol.iterator,B={array:u("array"),bool:u("boolean"),func:u("function"),number:u("number"),object:u("object"),string:u("string"),symbol:u("symbol"),any:l(e),arrayOf:function(a){return l(function(b,c,d,e,f){if("function"!==typeof a)return new m("Property `"+f+"` of component `"+d+"` has invalid PropType notation inside arrayOf.");
b=b[c];if(!Array.isArray(b))return b=w(b),new m("Invalid "+e+" `"+f+"` of type "+("`"+b+"` supplied to `"+d+"`, expected an array."));for(c=0;c<b.length;c++){var g=a(b,c,d,e,f+"["+c+"]",p);if(g instanceof Error)return g}return null})},element:function(){return l(function(b,c,d,e,f){b=b[c];return a(b)?null:(b=w(b),new m("Invalid "+e+" `"+f+"` of type "+("`"+b+"` supplied to `"+d+"`, expected a single ReactElement.")))})}(),elementType:function(){return l(function(a,b,c,d,e){a=a[b];return h.isValidElementType(a)?
null:(a=w(a),new m("Invalid "+d+" `"+e+"` of type "+("`"+a+"` supplied to `"+c+"`, expected a single ReactElement type.")))})}(),instanceOf:function(a){return l(function(b,c,d,e,f){if(!(b[c]instanceof a)){var g=a.name||"\x3c\x3canonymous\x3e\x3e";b=b[c];b=b.constructor&&b.constructor.name?b.constructor.name:"\x3c\x3canonymous\x3e\x3e";return new m("Invalid "+e+" `"+f+"` of type "+("`"+b+"` supplied to `"+d+"`, expected ")+("instance of `"+g+"`."))}return null})},node:function(){return l(function(a,
b,c,d,e){return v(a[b])?null:new m("Invalid "+d+" `"+e+"` supplied to "+("`"+c+"`, expected a ReactNode."))})}(),objectOf:function(a){return l(function(b,c,d,e,g){if("function"!==typeof a)return new m("Property `"+g+"` of component `"+d+"` has invalid PropType notation inside objectOf.");b=b[c];c=w(b);if("object"!==c)return new m("Invalid "+e+" `"+g+"` of type "+("`"+c+"` supplied to `"+d+"`, expected an object."));for(var k in b)if(f(b,k)&&(c=a(b,k,d,e,g+"."+k,p),c instanceof Error))return c;return null})},
oneOf:function(a){return Array.isArray(a)?l(function(b,c,d,e,f){b=b[c];for(c=0;c<a.length;c++)if(r(b,a[c]))return null;c=JSON.stringify(a,function(a,b){return"symbol"===z(b)?String(b):b});return new m("Invalid "+e+" `"+f+"` of value `"+String(b)+"` "+("supplied to `"+d+"`, expected one of "+c+"."))}):("production"!==b.env.NODE_ENV&&(1<arguments.length?g("Invalid arguments supplied to oneOf, expected an array, got "+arguments.length+" arguments. A common mistake is to write oneOf(x, y, z) instead of oneOf([x, y, z])."):
g("Invalid argument supplied to oneOf, expected an array.")),e)},oneOfType:function(a){if(!Array.isArray(a))return"production"!==b.env.NODE_ENV?g("Invalid argument supplied to oneOfType, expected an instance of array."):void 0,e;for(var c=0;c<a.length;c++){var f=a[c];if("function"!==typeof f)return g("Invalid argument supplied to oneOfType. Expected an array of check functions, but received "+D(f)+" at index "+c+"."),e}return l(function(b,c,d,e,f){for(var g=0;g<a.length;g++)if(null==(0,a[g])(b,c,
d,e,f,p))return null;return new m("Invalid "+e+" `"+f+"` supplied to "+("`"+d+"`."))})},shape:function(a){return l(function(b,c,d,e,f){b=b[c];c=w(b);if("object"!==c)return new m("Invalid "+e+" `"+f+"` of type `"+c+"` "+("supplied to `"+d+"`, expected `object`."));for(var g in a)if(c=a[g])if(c=c(b,g,d,e,f+"."+g,p))return c;return null})},exact:function(a){return l(function(b,c,d,e,f){var g=b[c],k=w(g);if("object"!==k)return new m("Invalid "+e+" `"+f+"` of type `"+k+"` "+("supplied to `"+d+"`, expected `object`."));
var k=q({},b[c],a),n;for(n in k){k=a[n];if(!k)return new m("Invalid "+e+" `"+f+"` key `"+n+"` supplied to `"+d+"`.\nBad object: "+JSON.stringify(b[c],null,"  ")+"\nValid keys: "+JSON.stringify(Object.keys(a),null,"  "));if(k=k(g,n,d,e,f+"."+n,p))return k}return null})}};m.prototype=Error.prototype;B.checkPropTypes=n;B.resetWarningCache=n.resetWarningCache;return B.PropTypes=B}}).call(b,c(5))},function(a,b){var c=Object.getOwnPropertySymbols,d=Object.prototype.hasOwnProperty,e=Object.prototype.propertyIsEnumerable;
a.exports=function(){try{if(!Object.assign)return!1;var a=new String("abc");a[5]="de";if("5"===Object.getOwnPropertyNames(a)[0])return!1;for(var b={},a=0;10>a;a++)b["_"+String.fromCharCode(a)]=a;if("0123456789"!==Object.getOwnPropertyNames(b).map(function(a){return b[a]}).join(""))return!1;var c={};"abcdefghijklmnopqrst".split("").forEach(function(a){c[a]=a});return"abcdefghijklmnopqrst"!==Object.keys(Object.assign({},c)).join("")?!1:!0}catch(d){return!1}}()?Object.assign:function(a,b){var p,n;if(null===
a||void 0===a)throw new TypeError("Object.assign cannot be called with null or undefined");n=Object(a);for(var f,g=1;g<arguments.length;g++){p=Object(arguments[g]);for(var k in p)d.call(p,k)&&(n[k]=p[k]);if(c){f=c(p);for(var t=0;t<f.length;t++)e.call(p,f[t])&&(n[f[t]]=p[f[t]])}}return n}},function(a,b){a.exports="SECRET_DO_NOT_PASS_THIS_OR_YOU_WILL_BE_FIRED"},function(a,b,c){(function(b){function e(a,c,e,t,r){if("production"!==b.env.NODE_ENV)for(var m in a)if(n(a,m)){var l;try{if("function"!==typeof a[m]){var u=
Error((t||"React class")+": "+e+" type `"+m+"` is invalid; it must be a function, usually from the `prop-types` package, but received `"+typeof a[m]+"`.");u.name="Invariant Violation";throw u;}l=a[m](c,m,t,e,null,q)}catch(x){l=x}!l||l instanceof Error||h((t||"React class")+": type specification of "+e+" `"+m+"` is invalid; the type checker function must return `null` or an `Error` but returned a "+typeof l+". You may have forgotten to pass an argument to the type checker creator (arrayOf, instanceOf, objectOf, oneOf, oneOfType, and shape all require an argument).");
if(l instanceof Error&&!(l.message in p)){p[l.message]=!0;var v=r?r():"";h("Failed "+e+" type: "+l.message+(null!=v?v:""))}}}var h=function(){};if("production"!==b.env.NODE_ENV)var q=c(11),p={},n=Function.call.bind(Object.prototype.hasOwnProperty),h=function(a){a="Warning: "+a;"undefined"!==typeof console&&console.error(a);try{throw Error(a);}catch(b){}};e.resetWarningCache=function(){"production"!==b.env.NODE_ENV&&(p={})};a.exports=e}).call(b,c(5))},function(a,b,c){function d(){}function e(){}var h=
c(11);e.resetWarningCache=d;a.exports=function(){function a(b,c,d,e,p,n){if(n!==h)throw b=Error("Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them. Read more at http://fb.me/use-check-prop-types"),b.name="Invariant Violation",b;}function b(){return a}a.isRequired=a;var c={array:a,bool:a,func:a,number:a,object:a,string:a,symbol:a,any:a,arrayOf:b,element:a,elementType:a,instanceOf:b,node:a,objectOf:b,oneOf:b,oneOfType:b,shape:b,
exact:b,checkPropTypes:e,resetWarningCache:d};return c.PropTypes=c}},function(a,b){a.exports=agGrid},function(a,b,c){function d(a,b){a.forEach(function(a){p[a]=b})}var e=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,
new d)}}();Object.defineProperty(b,"__esModule",{value:!0});var h=c(2);a=c(2);var q=c(4);c=c(14);var p=function(a){function b(c,d){var e=a.call(this,c,d)||this;e.props=c;e.state=d;return e}e(b,a);b.prototype.render=function(){return null};b.mapChildColumnDefs=function(a){return h.Children.map(a.children,function(a){return b.toColDef(a.props)})};b.toColDef=function(a){var c=b.createColDefFromGridColumn(a);b.hasChildColumns(a)&&(c.children=b.getChildColDefs(a.children));return c};b.hasChildColumns=
function(a){return 0<h.Children.count(a.children)};b.getChildColDefs=function(a){return h.Children.map(a,function(a){return b.createColDefFromGridColumn(a.props)})};b.createColDefFromGridColumn=function(a){var c={};b.assign(c,a);delete c.children;return c};b.assign=function(a,b){return[b].reduce(function(a,b){Object.keys(b).forEach(function(c){a[c]=b[c]});return a},a)};return b}(a.Component);b.AgGridColumn=p;d(c.ColDefUtil.BOOLEAN_PROPERTIES,q.bool);d(c.ColDefUtil.STRING_PROPERTIES,q.string);d(c.ColDefUtil.OBJECT_PROPERTIES,
q.object);d(c.ColDefUtil.ARRAY_PROPERTIES,q.array);d(c.ColDefUtil.NUMBER_PROPERTIES,q.number);d(c.ColDefUtil.FUNCTION_PROPERTIES,q.func)},function(a,b,c){var d=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,
new d)}}();Object.defineProperty(b,"__esModule",{value:!0});var e=c(2),h=c(3),q=c(14),p=c(14);a=function(a){function b(c,d){var e=a.call(this)||this;e.portal=null;e.componentWrappingElement="div";e.unwrapComponent=!0;e.reactComponent=c;e.parentComponent=d;e.orphans=[];e.statelessComponent=b.isStateless(e.reactComponent);return e}d(b,a);b.prototype.getFrameworkComponentInstance=function(){return this.componentInstance};b.prototype.isStatelesComponent=function(){return this.statelessComponent};b.prototype.getReactComponentName=
function(){return this.reactComponent.name};b.prototype.init=function(a){var b=this;return new p.Promise(function(c){b.unwrapComponent=!1;b.eParentElement=b.createParentElement(a);b.createReactComponent(a,c)})};b.prototype.getGui=function(){if(this.unwrapComponent){var a=document.createDocumentFragment();if(0<this.orphans.length)for(var b=0,c=this.orphans;b<c.length;b++)a.appendChild(c[b]);else for(;this.eParentElement.firstChild;)this.orphans.push(this.eParentElement.firstChild),a.appendChild(this.eParentElement.firstChild);
return a}return this.eParentElement};b.prototype.destroy=function(){if(this.unwrapComponent)for(var a=0,b=this.orphans;a<b.length;a++)this.eParentElement.appendChild(b[a]);return this.parentComponent.destroyPortal(this.portal)};b.prototype.createReactComponent=function(a,b){var c=this;this.statelessComponent||(a.ref=function(a){c.componentInstance=a});var d=e.createElement(this.reactComponent,a);this.portal=d=h.createPortal(d,this.eParentElement);this.parentComponent.mountReactPortal(d,this,b)};b.prototype.createParentElement=
function(a){var b=document.createElement(this.parentComponent.props.componentWrappingElement||"div");this.unwrapComponent||(q.Utils.addCssClass(b,"ag-react-container"),a.reactContainer=this.eParentElement);return b};b.prototype.statelessComponentRendered=function(){return 0<this.eParentElement.childElementCount};b.isStateless=function(a){return"function"===typeof a&&!(a.prototype&&a.prototype.isReactComponent)};return b}(c(17).BaseReactComponent);b.ReactComponent=a},function(a,b){Object.defineProperty(b,
"__esModule",{value:!0});var c=function(){function a(){}a.prototype.hasMethod=function(a){var b=this.getFrameworkComponentInstance();return null==b?!1:null!=b[a]};a.prototype.callMethod=function(a,b){var c=this,d=this.getFrameworkComponentInstance();if(null==d)window.setTimeout(function(){return c.callMethod(a,b)},100);else{var n=this.getFrameworkComponentInstance()[a];if(null!=n)return n.apply(d,b)}};a.prototype.addMethod=function(a,b){this[a]=b};return a}();b.BaseReactComponent=c},function(a,b){Object.defineProperty(b,
"__esModule",{value:!0});var c;(function(a){a.IdentityCheck="IdentityCheck";a.DeepValueCheck="DeepValueCheck";a.NoCheck="NoCheck"})(c=b.ChangeDetectionStrategyType||(b.ChangeDetectionStrategyType={}));var d=function(){function a(){var b;this.strategyMap=(b={},b[c.DeepValueCheck]=new h,b[c.IdentityCheck]=new e(function(a,b){return a===b}),b[c.NoCheck]=new e(function(a,b){return!0}),b)}a.prototype.getStrategy=function(a){return this.strategyMap[a]};return a}();b.ChangeDetectionService=d;var e=function(){function a(b){this.strategy=
b}a.prototype.areEqual=function(a,b){return this.strategy(a,b)};return a}(),h=function(){function a(){}a.prototype.areEqual=function(b,c){return a.areEquivalent(a.copy(b),a.copy(c))};a.unwrapStringOrNumber=function(a){return a instanceof Number||a instanceof String?a.valueOf():a};a.copy=function(a){if(!a)return a;if(Array.isArray(a)){for(var b=[],c=0;c<a.length;c++)b.push(this.copy(a[c]));return b}return"object"!==typeof a?a:[{},a].reduce(function(a,b){Object.keys(b).forEach(function(c){a[c]=b[c]});
return a},{})};a.areEquivalent=function(b,c){b=a.unwrapStringOrNumber(b);c=a.unwrapStringOrNumber(c);if(b===c)return!0;if(null===b||null===c||typeof b!==typeof c)return!1;if(b instanceof Date)return c instanceof Date&&b.valueOf()===c.valueOf();if("function"===typeof b)return b.toString()===c.toString();if("object"!==typeof b)return b==c;var d=void 0===b.areEquivPropertyTracking,e=void 0===c.areEquivPropertyTracking;try{var k=void 0;if(d)b.areEquivPropertyTracking=[];else if(b.areEquivPropertyTracking.some(function(a){return a===
c}))return!0;if(e)c.areEquivPropertyTracking=[];else if(c.areEquivPropertyTracking.some(function(a){return a===b}))return!0;b.areEquivPropertyTracking.push(c);c.areEquivPropertyTracking.push(b);var h={};for(k in b)"areEquivPropertyTracking"!=k&&(h[k]=null);for(k in c)"areEquivPropertyTracking"!=k&&(h[k]=null);for(k in h)if(!this.areEquivalent(b[k],c[k]))return!1;return!0}finally{d&&delete b.areEquivPropertyTracking,e&&delete c.areEquivPropertyTracking}};return a}()},function(a,b,c){var d=this&&this.__extends||
function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}();Object.defineProperty(b,"__esModule",{value:!0});var e=c(2),h=c(3),q=c(14),p=c(14);a=function(a){function b(c,d){var e=a.call(this)||this;e.reactComponent=c;e.parentComponent=
d;return e}d(b,a);b.prototype.getFrameworkComponentInstance=function(){return this.componentInstance};b.prototype.getReactComponentName=function(){return this.reactComponent.name};b.prototype.init=function(a){var b=this;return new p.Promise(function(c){b.eParentElement=document.createElement(b.parentComponent.props.componentWrappingElement||"div");q.Utils.addCssClass(b.eParentElement,"ag-react-container");a.reactContainer=b.eParentElement;b.createReactComponentLegacy(a,c)})};b.prototype.getGui=function(){return this.eParentElement};
b.prototype.destroy=function(){h.unmountComponentAtNode(this.eParentElement)};b.prototype.createReactComponentLegacy=function(a,b){var c=this,d=e.createElement(this.reactComponent,a);this.parentComponent?h.unstable_renderSubtreeIntoContainer(this.parentComponent,d,this.eParentElement,function(){c.componentInstance=this;b(null)}):h.render(d,this.eParentElement,function(){c.componentInstance=this;b(null)})};return b}(c(17).BaseReactComponent);b.LegacyReactComponent=a}]);