(function(f){"object"===typeof exports&&"undefined"!==typeof module?module.exports=f():"function"===typeof define&&define.amd?define([],f):("undefined"!==typeof window?window:"undefined"!==typeof global?global:"undefined"!==typeof self?self:this).qs=f()})(function(){return function(){function f(k,n,m){function h(c,a){if(!n[c]){if(!k[c]){var b="function"==typeof require&&require;if(!a&&b)return b(c,!0);if(p)return p(c,!0);b=Error("Cannot find module '"+c+"'");throw b.code="MODULE_NOT_FOUND",b;}b=n[c]=
{exports:{}};k[c][0].call(b.exports,function(a){return h(k[c][1][a]||a)},b,b.exports,f,k,n,m)}return n[c].exports}for(var p="function"==typeof require&&require,c=0;c<m.length;c++)h(m[c]);return h}return f}()({1:[function(f,k,n){var m=String.prototype.replace,h=/%20/g;k.exports={"default":"RFC3986",formatters:{RFC1738:function(f){return m.call(f,h,"+")},RFC3986:function(h){return h}},RFC1738:"RFC1738",RFC3986:"RFC3986"}},{}],2:[function(f,k,n){n=f("./stringify");var m=f("./parse");f=f("./formats");
k.exports={formats:f,parse:m,stringify:n}},{"./formats":1,"./parse":3,"./stringify":4}],3:[function(f,k,n){var m=f("./utils"),h=Object.prototype.hasOwnProperty,p=m.decode;k.exports=function(c,g){var a=g?m.assign({},g):{};if(null!==a.decoder&&void 0!==a.decoder&&"function"!==typeof a.decoder)throw new TypeError("Decoder has to be a function.");a.ignoreQueryPrefix=!0===a.ignoreQueryPrefix;a.delimiter="string"===typeof a.delimiter||m.isRegExp(a.delimiter)?a.delimiter:"\x26";a.depth="number"===typeof a.depth?
a.depth:5;a.arrayLimit="number"===typeof a.arrayLimit?a.arrayLimit:20;a.parseArrays=!1!==a.parseArrays;a.decoder="function"===typeof a.decoder?a.decoder:p;a.allowDots="boolean"===typeof a.allowDots?a.allowDots:!1;a.plainObjects="boolean"===typeof a.plainObjects?a.plainObjects:!1;a.allowPrototypes="boolean"===typeof a.allowPrototypes?a.allowPrototypes:!1;a.parameterLimit="number"===typeof a.parameterLimit?a.parameterLimit:1E3;a.strictNullHandling="boolean"===typeof a.strictNullHandling?a.strictNullHandling:
!1;if(""===c||null===c||"undefined"===typeof c)return a.plainObjects?Object.create(null):{};var b;if("string"===typeof c){b={};for(var f=(a.ignoreQueryPrefix?c.replace(/^\?/,""):c).split(a.delimiter,Infinity===a.parameterLimit?void 0:a.parameterLimit),x=0;x<f.length;++x){var t=f[x],e=t.indexOf("]\x3d"),d=-1===e?t.indexOf("\x3d"):e+1;-1===d?(e=a.decoder(t,p),t=a.strictNullHandling?null:""):(e=a.decoder(t.slice(0,d),p),t=a.decoder(t.slice(d+1),p));h.call(b,e)?b[e]=[].concat(b[e]).concat(t):b[e]=t}}else b=
c;f=a.plainObjects?Object.create(null):{};x=Object.keys(b);for(t=0;t<x.length;++t){e=x[t];a:{var u=e,e=b[e],d=a;if(u){var u=d.allowDots?u.replace(/\.([^.[]+)/g,"[$1]"):u,k=/(\[[^[\]]*])/g,l=/(\[[^[\]]*])/.exec(u),l=l?u.slice(0,l.index):u,q=[];if(l){if(!d.plainObjects&&h.call(Object.prototype,l)&&!d.allowPrototypes){e=void 0;break a}q.push(l)}for(var v=0;null!==(l=k.exec(u))&&v<d.depth;){v+=1;if(!d.plainObjects&&h.call(Object.prototype,l[1].slice(1,-1))&&!d.allowPrototypes){e=void 0;break a}q.push(l[1])}l&&
q.push("["+u.slice(l.index)+"]");u=q;for(k=u.length-1;0<=k;--k){l=u[k];if("[]"===l)q=[],q=q.concat(e);else{var q=d.plainObjects?Object.create(null):{},v="["===l.charAt(0)&&"]"===l.charAt(l.length-1)?l.slice(1,-1):l,y=parseInt(v,10);!isNaN(y)&&l!==v&&String(y)===v&&0<=y&&d.parseArrays&&y<=d.arrayLimit?(q=[],q[y]=e):q[v]=e}e=q}}else e=void 0}f=m.merge(f,e,a)}return m.compact(f)}},{"./utils":5}],4:[function(f,k,n){var m=f("./utils"),h=f("./formats"),p={brackets:function(a){return a+"[]"},indices:function(a,
b){return a+"["+b+"]"},repeat:function(a){return a}},c=Date.prototype.toISOString,g=m.encode,a=function(a){return c.call(a)},b=function x(a,b,d,c,f,l,h,k,p,n,z,C){if("function"===typeof h)a=h(b,a);else if(a instanceof Date)a=n(a);else if(null===a){if(c)return l&&!C?l(b,g):b;a=""}if("string"===typeof a||"number"===typeof a||"boolean"===typeof a||m.isBuffer(a))return l?(b=C?b:l(b,g),[z(b)+"\x3d"+z(l(a,g))]):[z(b)+"\x3d"+z(String(a))];var B=[];if("undefined"===typeof a)return B;var r;Array.isArray(h)?
r=h:(r=Object.keys(a),r=k?r.sort(k):r);for(var A=0;A<r.length;++A){var w=r[A];f&&null===a[w]||(B=Array.isArray(a)?B.concat(x(a[w],d(b,w),d,c,f,l,h,k,p,n,z,C)):B.concat(x(a[w],b+(p?"."+w:"["+w+"]"),d,c,f,l,h,k,p,n,z,C)))}return B};k.exports=function(c,f){var e=c,d=f?m.assign({},f):{};if(null!==d.encoder&&void 0!==d.encoder&&"function"!==typeof d.encoder)throw new TypeError("Encoder has to be a function.");var k="undefined"===typeof d.delimiter?"\x26":d.delimiter,n="boolean"===typeof d.strictNullHandling?
d.strictNullHandling:!1,l="boolean"===typeof d.skipNulls?d.skipNulls:!1,q="boolean"===typeof d.encode?d.encode:!0,v="function"===typeof d.encoder?d.encoder:g,y="function"===typeof d.sort?d.sort:null,F="undefined"===typeof d.allowDots?!1:d.allowDots,z="function"===typeof d.serializeDate?d.serializeDate:a,C="boolean"===typeof d.encodeValuesOnly?d.encodeValuesOnly:!1;if("undefined"===typeof d.format)d.format=h["default"];else if(!Object.prototype.hasOwnProperty.call(h.formatters,d.format))throw new TypeError("Unknown format option provided.");
var B=h.formatters[d.format],r,A;"function"===typeof d.filter?(A=d.filter,e=A("",e)):Array.isArray(d.filter)&&(r=A=d.filter);var w=[];if("object"!==typeof e||null===e)return"";var G=p[d.arrayFormat in p?d.arrayFormat:"indices"in d?d.indices?"indices":"repeat":"indices"];r||(r=Object.keys(e));y&&r.sort(y);for(var D=0;D<r.length;++D){var E=r[D];l&&null===e[E]||(w=w.concat(b(e[E],E,G,n,l,q?v:null,A,y,F,z,B,C)))}e=w.join(k);d=!0===d.addQueryPrefix?"?":"";return 0<e.length?d+e:""}},{"./formats":1,"./utils":5}],
5:[function(f,k,n){var m=Object.prototype.hasOwnProperty,h=function(){for(var c=[],g=0;256>g;++g)c.push("%"+((16>g?"0":"")+g.toString(16)).toUpperCase());return c}(),p=function(c,g){for(var a=g&&g.plainObjects?Object.create(null):{},b=0;b<c.length;++b)"undefined"!==typeof c[b]&&(a[b]=c[b]);return a};k.exports={arrayToObject:p,assign:function(c,g){return Object.keys(g).reduce(function(a,b){a[b]=g[b];return a},c)},compact:function(c){c=[{obj:{o:c},prop:"o"}];for(var g=[],a=0;a<c.length;++a)for(var b=
c[a],b=b.obj[b.prop],f=Object.keys(b),h=0;h<f.length;++h){var k=f[h],e=b[k];"object"===typeof e&&null!==e&&-1===g.indexOf(e)&&(c.push({obj:b,prop:k}),g.push(e))}for(var d;c.length;)if(g=c.pop(),d=g.obj[g.prop],Array.isArray(d)){a=[];for(b=0;b<d.length;++b)"undefined"!==typeof d[b]&&a.push(d[b]);g.obj[g.prop]=a}return d},decode:function(c){try{return decodeURIComponent(c.replace(/\+/g," "))}catch(g){return c}},encode:function(c){if(0===c.length)return c;c="string"===typeof c?c:String(c);for(var g=
"",a=0;a<c.length;++a){var b=c.charCodeAt(a);45===b||46===b||95===b||126===b||48<=b&&57>=b||65<=b&&90>=b||97<=b&&122>=b?g+=c.charAt(a):128>b?g+=h[b]:2048>b?g+=h[192|b>>6]+h[128|b&63]:55296>b||57344<=b?g+=h[224|b>>12]+h[128|b>>6&63]+h[128|b&63]:(a+=1,b=65536+((b&1023)<<10|c.charCodeAt(a)&1023),g+=h[240|b>>18]+h[128|b>>12&63]+h[128|b>>6&63]+h[128|b&63])}return g},isBuffer:function(c){return null===c||"undefined"===typeof c?!1:!!(c.constructor&&c.constructor.isBuffer&&c.constructor.isBuffer(c))},isRegExp:function(c){return"[object RegExp]"===
Object.prototype.toString.call(c)},merge:function g(a,b,f){if(!b)return a;if("object"!==typeof b){if(Array.isArray(a))a.push(b);else if("object"===typeof a){if(f.plainObjects||f.allowPrototypes||!m.call(Object.prototype,b))a[b]=!0}else return[a,b];return a}if("object"!==typeof a)return[a].concat(b);var h=a;Array.isArray(a)&&!Array.isArray(b)&&(h=p(a,f));return Array.isArray(a)&&Array.isArray(b)?(b.forEach(function(b,e){m.call(a,e)?a[e]&&"object"===typeof a[e]?a[e]=g(a[e],b,f):a.push(b):a[e]=b}),a):
Object.keys(b).reduce(function(a,e){var d=b[e];m.call(a,e)?a[e]=g(a[e],d,f):a[e]=d;return a},h)}}},{}],6:[function(f,k,n){k.exports=f("qs")},{qs:2}]},{},[6])(6)});