var WEBGL_CONSTANTS={POINTS:0,LINES:1,LINE_LOOP:2,LINE_STRIP:3,TRIANGLES:4,TRIANGLE_STRIP:5,TRIANGLE_FAN:6,UNSIGNED_BYTE:5121,UNSIGNED_SHORT:5123,FLOAT:5126,UNSIGNED_INT:5125,ARRAY_BUFFER:34962,ELEMENT_ARRAY_BUFFER:34963,NEAREST:9728,LINEAR:9729,NEAREST_MIPMAP_NEAREST:9984,LINEAR_MIPMAP_NEAREST:9985,NEAREST_MIPMAP_LINEAR:9986,LINEAR_MIPMAP_LINEAR:9987},THREE_TO_WEBGL={1003:WEBGL_CONSTANTS.NEAREST,1004:WEBGL_CONSTANTS.NEAREST_MIPMAP_NEAREST,1005:WEBGL_CONSTANTS.NEAREST_MIPMAP_LINEAR,1006:WEBGL_CONSTANTS.LINEAR,
1007:WEBGL_CONSTANTS.LINEAR_MIPMAP_NEAREST,1008:WEBGL_CONSTANTS.LINEAR_MIPMAP_LINEAR},PATH_PROPERTIES={scale:"scale",position:"translation",quaternion:"rotation",morphTargetInfluences:"weights"};THREE.GLTFExporter=function(){};
THREE.GLTFExporter.prototype={constructor:THREE.GLTFExporter,parse:function(O,z,u){function A(a,c){return a.length===c.length&&a.every(function(a,d){return a===c[d]})}function P(a){if(void 0!==window.TextEncoder)return(new TextEncoder).encode(a).buffer;for(var c=new Uint8Array(new ArrayBuffer(a.length)),b=0,d=a.length;b<d;b++){var e=a.charCodeAt(b);c[b]=255<e?32:e}return c.buffer}function Q(a){return THREE.Math.isPowerOfTwo(a.width)&&THREE.Math.isPowerOfTwo(a.height)}function D(a,c){c=c||0;var b=
4*Math.ceil(a.byteLength/4);if(b!==a.byteLength){var d=new Uint8Array(b);d.set(new Uint8Array(a));if(0!==c)for(var e=a.byteLength;e<b;e++)d[e]=c;return d.buffer}return a}function H(a){e.buffers||(e.buffers=[{byteLength:0}]);I.push(a);return 0}function R(a){e.bufferViews||(e.bufferViews=[]);return new Promise(function(c){var b=new window.FileReader;b.readAsArrayBuffer(a);b.onloadend=function(){var a=D(b.result),h={buffer:H(a),byteOffset:y,byteLength:a.byteLength};y+=a.byteLength;e.bufferViews.push(h);
c(e.bufferViews.length-1)}})}function B(a,c,b,d){e.accessors||(e.accessors=[]);var h;if(a.array.constructor===Float32Array)h=WEBGL_CONSTANTS.FLOAT;else if(a.array.constructor===Uint32Array)h=WEBGL_CONSTANTS.UNSIGNED_INT;else if(a.array.constructor===Uint16Array)h=WEBGL_CONSTANTS.UNSIGNED_SHORT;else throw Error("THREE.GLTFExporter: Unsupported bufferAttribute component type.");void 0===b&&(b=0);void 0===d&&(d=a.count);if(u.truncateDrawRange&&void 0!==c&&null===c.index){d=b+d;var k=Infinity===c.drawRange.count?
a.count:c.drawRange.start+c.drawRange.count;b=Math.max(b,c.drawRange.start);d=Math.min(d,k)-b;0>d&&(d=0)}for(var t=b,n=d,k=Array(a.itemSize).fill(Number.POSITIVE_INFINITY),q=Array(a.itemSize).fill(Number.NEGATIVE_INFINITY),g=t;g<t+n;g++)for(var m=0;m<a.itemSize;m++){var r=a.array[g*a.itemSize+m];k[m]=Math.min(k[m],r);q[m]=Math.max(q[m],r)}var v;void 0!==c&&(v=a===c.index?WEBGL_CONSTANTS.ELEMENT_ARRAY_BUFFER:WEBGL_CONSTANTS.ARRAY_BUFFER);c=h;t=d;e.bufferViews||(e.bufferViews=[]);for(var n=c===WEBGL_CONSTANTS.UNSIGNED_SHORT?
2:4,g=4*Math.ceil(t*a.itemSize*n/4),m=new DataView(new ArrayBuffer(g)),r=0,p=b;p<b+t;p++)for(var f=0;f<a.itemSize;f++){var l=a.array[p*a.itemSize+f];c===WEBGL_CONSTANTS.FLOAT?m.setFloat32(r,l,!0):c===WEBGL_CONSTANTS.UNSIGNED_INT?m.setUint32(r,l,!0):c===WEBGL_CONSTANTS.UNSIGNED_SHORT&&m.setUint16(r,l,!0);r+=n}c={buffer:H(m.buffer),byteOffset:y,byteLength:g};void 0!==v&&(c.target=v);v===WEBGL_CONSTANTS.ARRAY_BUFFER&&(c.byteStride=a.itemSize*n);y+=g;e.bufferViews.push(c);v={id:e.bufferViews.length-1,
byteLength:0};e.accessors.push({bufferView:v.id,byteOffset:v.byteOffset,componentType:h,count:d,max:q,min:k,type:{1:"SCALAR",2:"VEC2",3:"VEC3",4:"VEC4",16:"MAT4"}[a.itemSize]});return e.accessors.length-1}function S(a){e.images||(e.images=[]);var c=a.format===THREE.RGBAFormat?"image/png":"image/jpeg",b={mimeType:c};if(u.embedImages){var d=J=J||document.createElement("canvas");d.width=a.image.width;d.height=a.image.height;u.forcePowerOfTwoTextures&&!Q(a.image)&&(console.warn("GLTFExporter: Resized non-power-of-two image.",
a.image),d.width=THREE.Math.floorPowerOfTwo(d.width),d.height=THREE.Math.floorPowerOfTwo(d.height));var h=d.getContext("2d");!0===a.flipY&&(h.translate(0,d.height),h.scale(1,-1));h.drawImage(a.image,0,0,d.width,d.height);!0===u.binary?K.push(new Promise(function(a){d.toBlob(function(d){R(d).then(function(d){b.bufferView=d;a()})},c)})):b.uri=d.toDataURL(c)}else b.uri=a.image.src;e.images.push(b);return e.images.length-1}function E(a){if(C.textures.has(a))return C.textures.get(a);e.textures||(e.textures=
[]);e.samplers||(e.samplers=[]);e.samplers.push({magFilter:THREE_TO_WEBGL[a.magFilter],minFilter:THREE_TO_WEBGL[a.minFilter],wrapS:THREE_TO_WEBGL[a.wrapS],wrapT:THREE_TO_WEBGL[a.wrapT]});var c={sampler:e.samplers.length-1,source:S(a)};e.textures.push(c);c=e.textures.length-1;C.textures.set(a,c);return c}function L(a){if(a.isLight)return console.warn("GLTFExporter: Unsupported node type:",a.constructor.name),null;e.nodes||(e.nodes=[]);var c={};if(u.trs){var b=a.quaternion.toArray(),d=a.position.toArray(),
h=a.scale.toArray();A(b,[0,0,0,1])||(c.rotation=b);A(d,[0,0,0])||(c.translation=d);A(h,[1,1,1])||(c.scale=h)}else a.updateMatrix(),A(a.matrix.elements,[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1])||(c.matrix=a.matrix.elements);""!==a.name&&(c.name=String(a.name));if(a.userData&&0<Object.keys(a.userData).length)try{c.extras=JSON.parse(JSON.stringify(a.userData))}catch(y){throw Error("THREE.GLTFExporter: userData can't be serialized");}if(a.isMesh||a.isLine||a.isPoints){e.meshes||(e.meshes=[]);b=a.geometry;a.isLineSegments?
d=WEBGL_CONSTANTS.LINES:a.isLineLoop?d=WEBGL_CONSTANTS.LINE_LOOP:a.isLine?d=WEBGL_CONSTANTS.LINE_STRIP:a.isPoints?d=WEBGL_CONSTANTS.POINTS:(b.isBufferGeometry||(d=new THREE.BufferGeometry,d.fromGeometry(b),b=d),a.drawMode===THREE.TriangleFanDrawMode?(console.warn("GLTFExporter: TriangleFanDrawMode and wireframe incompatible."),d=WEBGL_CONSTANTS.TRIANGLE_FAN):d=a.drawMode===THREE.TriangleStripDrawMode?a.material.wireframe?WEBGL_CONSTANTS.LINE_STRIP:WEBGL_CONSTANTS.TRIANGLE_STRIP:a.material.wireframe?
WEBGL_CONSTANTS.LINES:WEBGL_CONSTANTS.TRIANGLES);var h={},k={},t=[],n=[],q={uv:"TEXCOORD_0",uv2:"TEXCOORD_1",color:"COLOR_0",skinWeight:"WEIGHTS_0",skinIndex:"JOINTS_0"},g;for(g in b.attributes){var m=b.attributes[g];g=q[g]||g.toUpperCase();"MORPH"!==g.substr(0,5)&&(k[g]=B(m,b))}if(void 0!==a.morphTargetInfluences&&0<a.morphTargetInfluences.length){var q=[],r=[],v={};if(void 0!==a.morphTargetDictionary)for(var p in a.morphTargetDictionary)v[a.morphTargetDictionary[p]]=p;for(p=0;p<a.morphTargetInfluences.length;++p){var f=
{},l=!1;for(g in b.morphAttributes)if("position"!==g&&"normal"!==g)l||(console.warn("GLTFExporter: Only POSITION and NORMAL morph are supported."),l=!0);else{for(var m=b.morphAttributes[g][p],w=b.attributes[g],z=m.clone(),x=0,D=m.count;x<D;x++)z.setXYZ(x,m.getX(x)-w.getX(x),m.getY(x)-w.getY(x),m.getZ(x)-w.getZ(x));f[g.toUpperCase()]=B(z,b)}n.push(f);q.push(a.morphTargetInfluences[p]);void 0!==a.morphTargetDictionary&&r.push(v[p])}h.weights=q;0<r.length&&(h.extras={},h.extras.targetNames=r)}p=u.forceIndices;
r=Array.isArray(a.material);!p&&null===b.index&&r&&(console.warn("THREE.GLTFExporter: Creating index for non-indexed multi-material mesh."),p=!0);g=!1;if(null===b.index&&p){g=[];p=0;for(m=b.attributes.position.count;p<m;p++)g[p]=p;b.setIndex(g);g=!0}q=r?a.material:[a.material];r=r?a.geometry.groups:[{materialIndex:0,start:void 0,count:void 0}];p=0;for(m=r.length;p<m;p++){v={mode:d,attributes:k};0<n.length&&(v.targets=n);f=q[r[p].materialIndex];if(C.materials.has(f))f=C.materials.get(f);else if(e.materials||
(e.materials=[]),f.isShaderMaterial)console.warn("GLTFExporter: THREE.ShaderMaterial not supported."),f=null;else{l={pbrMetallicRoughness:{}};f.isMeshBasicMaterial?(l.extensions={KHR_materials_unlit:{}},M.KHR_materials_unlit=!0):f.isMeshStandardMaterial||console.warn("GLTFExporter: Use MeshStandardMaterial or MeshBasicMaterial for best results.");w=f.color.toArray().concat([f.opacity]);A(w,[1,1,1,1])||(l.pbrMetallicRoughness.baseColorFactor=w);f.isMeshStandardMaterial?(l.pbrMetallicRoughness.metallicFactor=
f.metalness,l.pbrMetallicRoughness.roughnessFactor=f.roughness):f.isMeshBasicMaterial?(l.pbrMetallicRoughness.metallicFactor=0,l.pbrMetallicRoughness.roughnessFactor=.9):(l.pbrMetallicRoughness.metallicFactor=.5,l.pbrMetallicRoughness.roughnessFactor=.5);if(f.metalnessMap||f.roughnessMap)f.metalnessMap===f.roughnessMap?l.pbrMetallicRoughness.metallicRoughnessTexture={index:E(f.metalnessMap)}:console.warn("THREE.GLTFExporter: Ignoring metalnessMap and roughnessMap because they are not the same Texture.");
f.map&&(l.pbrMetallicRoughness.baseColorTexture={index:E(f.map)});f.isMeshBasicMaterial||f.isLineBasicMaterial||f.isPointsMaterial||(w=f.emissive.clone().multiplyScalar(f.emissiveIntensity).toArray(),A(w,[0,0,0])||(l.emissiveFactor=w),f.emissiveMap&&(l.emissiveTexture={index:E(f.emissiveMap)}));f.normalMap&&(l.normalTexture={index:E(f.normalMap)},-1!==f.normalScale.x&&(f.normalScale.x!==f.normalScale.y&&console.warn("THREE.GLTFExporter: Normal scale components are different, ignoring Y and exporting X."),
l.normalTexture.scale=f.normalScale.x));f.aoMap&&(l.occlusionTexture={index:E(f.aoMap)},1!==f.aoMapIntensity&&(l.occlusionTexture.strength=f.aoMapIntensity));if(f.transparent||0<f.alphaTest)l.alphaMode=1>f.opacity?"BLEND":"MASK",0<f.alphaTest&&.5!==f.alphaTest&&(l.alphaCutoff=f.alphaTest);f.side===THREE.DoubleSide&&(l.doubleSided=!0);""!==f.name&&(l.name=f.name);e.materials.push(l);l=e.materials.length-1;C.materials.set(f,l);f=l}null!==f&&(v.material=f);null!==b.index&&(v.indices=B(b.index,b,r[p].start,
r[p].count));t.push(v)}g&&b.setIndex(null);h.primitives=t;e.meshes.push(h);c.mesh=e.meshes.length-1}else a.isCamera&&(e.cameras||(e.cameras=[]),b=a.isOrthographicCamera,d={type:b?"orthographic":"perspective"},b?d.orthographic={xmag:2*a.right,ymag:2*a.top,zfar:0>=a.far?.001:a.far,znear:0>a.near?0:a.near}:d.perspective={aspectRatio:a.aspect,yfov:THREE.Math.degToRad(a.fov)/a.aspect,zfar:0>=a.far?.001:a.far,znear:0>a.near?0:a.near},""!==a.name&&(d.name=a.type),e.cameras.push(d),c.camera=e.cameras.length-
1);a.isSkinnedMesh&&G.push(a);if(0<a.children.length){b=[];d=0;for(h=a.children.length;d<h;d++)if(k=a.children[d],k.visible||!1===u.onlyVisible)k=L(k),null!==k&&b.push(k);0<b.length&&(c.children=b)}e.nodes.push(c);c=e.nodes.length-1;F.set(a,c);return c}function N(a){e.scenes||(e.scenes=[],e.scene=0);var c={nodes:[]};""!==a.name&&(c.name=a.name);e.scenes.push(c);for(var b=[],d=0,h=a.children.length;d<h;d++){var k=a.children[d];if(k.visible||!1===u.onlyVisible)k=L(k),null!==k&&b.push(k)}0<b.length&&
(c.nodes=b)}u=Object.assign({},{trs:!1,onlyVisible:!0,truncateDrawRange:!0,embedImages:!0,animations:[],forceIndices:!1,forcePowerOfTwoTextures:!1},u);0<u.animations.length&&(u.trs=!0);var e={asset:{version:"2.0",generator:"THREE.GLTFExporter"}},y=0,I=[],K=[],F=new Map,G=[],M={},C={materials:new Map,textures:new Map},J;(function(a){a=a instanceof Array?a:[a];for(var c=[],b=0;b<a.length;b++)a[b]instanceof THREE.Scene?N(a[b]):c.push(a[b]);if(0<c.length){b=new THREE.Scene;b.name="AuxScene";for(var d=
0;d<c.length;d++)b.children.push(c[d]);N(b)}for(b=0;b<G.length;++b){var h=G[b],c=e.nodes[F.get(h)],d=h.skeleton,h=h.skeleton.bones[0];if(void 0!==h){for(var k=[],t=new Float32Array(16*d.bones.length),n=0;n<d.bones.length;++n)k.push(F.get(d.bones[n])),d.boneInverses[n].toArray(t,16*n);void 0===e.skins&&(e.skins=[]);e.skins.push({inverseBindMatrices:B(new THREE.BufferAttribute(t,16)),joints:k,skeleton:F.get(h)});c.skin=e.skins.length-1}}for(b=0;b<u.animations.length;++b)a:{c=u.animations[b];d=a[0];
e.animations||(e.animations=[]);h=[];k=[];for(t=0;t<c.tracks.length;++t){var n=c.tracks[t],q=THREE.PropertyBinding.parseTrackName(n.name),g=THREE.PropertyBinding.findNode(d,q.nodeName),m=PATH_PROPERTIES[q.propertyName];"bones"===q.objectName&&(g=!0===g.isSkinnedMesh?g.skeleton.getBoneByName(q.objectIndex):void 0);if(!g||!m){console.warn('THREE.GLTFExporter: Could not export animation track "%s".',n.name);break a}q=n.values.length/n.times.length;m===PATH_PROPERTIES.morphTargetInfluences&&(q/=g.morphTargetInfluences.length);
var r;!0===n.createInterpolant.isInterpolantFactoryMethodGLTFCubicSpline?(r="CUBICSPLINE",q/=3):r=n.getInterpolation()===THREE.InterpolateDiscrete?"STEP":"LINEAR";k.push({input:B(new THREE.BufferAttribute(n.times,1)),output:B(new THREE.BufferAttribute(n.values,q)),interpolation:r});h.push({sampler:k.length-1,target:{node:F.get(g),path:m}})}e.animations.push({name:c.name||"clip_"+e.animations.length,samplers:k,channels:h})}})(O);Promise.all(K).then(function(){var a=new Blob(I,{type:"application/octet-stream"}),
c=Object.keys(M);0<c.length&&(e.extensionsUsed=c);if(e.buffers&&0<e.buffers.length){e.buffers[0].byteLength=a.size;var b=new window.FileReader;!0===u.binary?(b.readAsArrayBuffer(a),b.onloadend=function(){var a=D(b.result),c=new DataView(new ArrayBuffer(8));c.setUint32(0,a.byteLength,!0);c.setUint32(4,5130562,!0);var k=D(P(JSON.stringify(e)),32),t=new DataView(new ArrayBuffer(8));t.setUint32(0,k.byteLength,!0);t.setUint32(4,1313821514,!0);var n=new ArrayBuffer(12),q=new DataView(n);q.setUint32(0,1179937895,
!0);q.setUint32(4,2,!0);q.setUint32(8,12+t.byteLength+k.byteLength+c.byteLength+a.byteLength,!0);var a=new Blob([n,t,k,c,a],{type:"application/octet-stream"}),g=new window.FileReader;g.readAsArrayBuffer(a);g.onloadend=function(){z(g.result)}}):(b.readAsDataURL(a),b.onloadend=function(){e.buffers[0].uri=b.result;z(e)})}else z(e)})}};