"object"===typeof module?ICAL=module.exports:"object"!==typeof ICAL&&(this.ICAL={});ICAL.foldLength=75;ICAL.newLineChar="\r\n";
ICAL.helpers={isStrictlyNaN:function(b){return"number"===typeof b&&isNaN(b)},strictParseInt:function(b){var a=parseInt(b,10);if(ICAL.helpers.isStrictlyNaN(a))throw Error('Could not extract integer from "'+b+'"');return a},formatClassType:function(b,a){return"undefined"===typeof b?void 0:b instanceof a?b:new a(b)},unescapedIndexOf:function(b,a,c){for(;-1!==(c=b.indexOf(a,c));)if(0<c&&"\\"===b[c-1])c+=1;else return c;return-1},binsearchInsert:function(b,a,c){if(!b.length)return 0;for(var e=0,d=b.length-
1,f,h;e<=d;)if(f=e+Math.floor((d-e)/2),h=c(a,b[f]),0>h)d=f-1;else if(0<h)e=f+1;else break;return 0>h?f:0<h?f+1:f},dumpn:function(b){ICAL.debug&&(ICAL.helpers.dumpn="undefined"!==typeof console&&"log"in console?function(a){console.log(a)}:function(a){dump(a+"\n")},ICAL.helpers.dumpn(b))},clone:function(b,a){if(b&&"object"==typeof b){if(b instanceof Date)return new Date(b.getTime());if("clone"in b)return b.clone();if(Array.isArray(b)){for(var c=[],e=0;e<b.length;e++)c.push(a?ICAL.helpers.clone(b[e],
!0):b[e]);return c}c={};for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(c[e]=a?ICAL.helpers.clone(b[e],!0):b[e]);return c}return b},foldline:function(b){var a="";for(b=b||"";b.length;)a+=ICAL.newLineChar+" "+b.substr(0,ICAL.foldLength),b=b.substr(ICAL.foldLength);return a.substr(ICAL.newLineChar.length+1)},pad2:function(b){"string"!==typeof b&&("number"===typeof b&&(b=parseInt(b)),b=String(b));switch(b.length){case 0:return"00";case 1:return"0"+b;default:return b}},trunc:function(b){return 0>
b?Math.ceil(b):Math.floor(b)},inherits:function(b,a,c){function e(){}e.prototype=b.prototype;a.prototype=new e;c&&ICAL.helpers.extend(c,a.prototype)},extend:function(b,a){for(var c in b){var e=Object.getOwnPropertyDescriptor(b,c);e&&!Object.getOwnPropertyDescriptor(a,c)&&Object.defineProperty(a,c,e)}return a}};
ICAL.design=function(){function b(c,e){return{matches:/.*/,fromICAL:function(e,b){var d;d=c;-1===e.indexOf("\\")?d=e:(b&&(d=new RegExp(d.source+"|\\\\"+b)),d=e.replace(d,a));return d},toICAL:function(a,c){var b=e;c&&(b=new RegExp(b.source+"|"+c));return a.replace(b,function(a){switch(a){case "\\":return"\\\\";case ";":return"\\;";case ",":return"\\,";case "\n":return"\\n";default:return a}})}}}function a(a){switch(a){case "\\\\":return"\\";case "\\;":return";";case "\\,":return",";case "\\n":case "\\N":return"\n";
default:return a}}var c=/\\\\|\\,|\\[Nn]/g,e=/\\|,|\n/g,d={defaultType:"text"},f={defaultType:"text",multiValue:","},h={defaultType:"text",structuredValue:";"},g={defaultType:"integer"},l={defaultType:"date-time",allowedTypes:["date-time","date"]},m={defaultType:"date-time"},k={defaultType:"uri"},n={defaultType:"utc-offset"},p={defaultType:"recur"},q={defaultType:"date-and-or-time",allowedTypes:["date-time","date","text"]},r={categories:f,url:k,version:d,uid:d},u={"boolean":{values:["TRUE","FALSE"],
fromICAL:function(a){switch(a){case "TRUE":return!0;case "FALSE":return!1;default:return!1}},toICAL:function(a){return a?"TRUE":"FALSE"}},float:{matches:/^[+-]?\d+\.\d+$/,fromICAL:function(a){a=parseFloat(a);return ICAL.helpers.isStrictlyNaN(a)?0:a},toICAL:function(a){return String(a)}},integer:{fromICAL:function(a){a=parseInt(a);return ICAL.helpers.isStrictlyNaN(a)?0:a},toICAL:function(a){return String(a)}},"utc-offset":{toICAL:function(a){return 7>a.length?a.substr(0,3)+a.substr(4,2):a.substr(0,
3)+a.substr(4,2)+a.substr(7,2)},fromICAL:function(a){return 6>a.length?a.substr(0,3)+":"+a.substr(3,2):a.substr(0,3)+":"+a.substr(3,2)+":"+a.substr(5,2)},decorate:function(a){return ICAL.UtcOffset.fromString(a)},undecorate:function(a){return a.toString()}}},s=ICAL.helpers.extend(u,{text:b(/\\\\|\\;|\\,|\\[Nn]/g,/\\|;|,|\n/g),uri:{},binary:{decorate:function(a){return ICAL.Binary.fromString(a)},undecorate:function(a){return a.toString()}},"cal-address":{},date:{decorate:function(a,c){return ICAL.Time.fromDateString(a,
c)},undecorate:function(a){return a.toString()},fromICAL:function(a){return a.substr(0,4)+"-"+a.substr(4,2)+"-"+a.substr(6,2)},toICAL:function(a){return 11<a.length?a:a.substr(0,4)+a.substr(5,2)+a.substr(8,2)}},"date-time":{fromICAL:function(a){var c=a.substr(0,4)+"-"+a.substr(4,2)+"-"+a.substr(6,2)+"T"+a.substr(9,2)+":"+a.substr(11,2)+":"+a.substr(13,2);a[15]&&"Z"===a[15]&&(c+="Z");return c},toICAL:function(a){if(19>a.length)return a;var c=a.substr(0,4)+a.substr(5,2)+a.substr(8,5)+a.substr(14,2)+
a.substr(17,2);a[19]&&"Z"===a[19]&&(c+="Z");return c},decorate:function(a,c){return ICAL.Time.fromDateTimeString(a,c)},undecorate:function(a){return a.toString()}},duration:{decorate:function(a){return ICAL.Duration.fromString(a)},undecorate:function(a){return a.toString()}},period:{fromICAL:function(a){a=a.split("/");a[0]=s["date-time"].fromICAL(a[0]);ICAL.Duration.isValueString(a[1])||(a[1]=s["date-time"].fromICAL(a[1]));return a},toICAL:function(a){a[0]=s["date-time"].toICAL(a[0]);ICAL.Duration.isValueString(a[1])||
(a[1]=s["date-time"].toICAL(a[1]));return a.join("/")},decorate:function(a,c){return ICAL.Period.fromJSON(a,c)},undecorate:function(a){return a.toJSON()}},recur:{fromICAL:function(a){return ICAL.Recur._stringToData(a,!0)},toICAL:function(a){var c="",e;for(e in a)if(Object.prototype.hasOwnProperty.call(a,e)){var b=a[e];"until"==e?b=10<b.length?s["date-time"].toICAL(b):s.date.toICAL(b):"wkst"==e?"number"===typeof b&&(b=ICAL.Recur.numericDayToIcalDay(b)):Array.isArray(b)&&(b=b.join(","));c+=e.toUpperCase()+
"\x3d"+b+";"}return c.substr(0,c.length-1)},decorate:function(a){return ICAL.Recur.fromData(a)},undecorate:function(a){return a.toJSON()}},time:{fromICAL:function(a){if(6>a.length)return a;var c=a.substr(0,2)+":"+a.substr(2,2)+":"+a.substr(4,2);"Z"===a[6]&&(c+="Z");return c},toICAL:function(a){if(8>a.length)return a;var c=a.substr(0,2)+a.substr(3,2)+a.substr(6,2);"Z"===a[8]&&(c+="Z");return c}}}),g=ICAL.helpers.extend(r,{action:d,attach:{defaultType:"uri"},attendee:{defaultType:"cal-address"},calscale:d,
"class":d,comment:d,completed:m,contact:d,created:m,description:d,dtend:l,dtstamp:m,dtstart:l,due:l,duration:{defaultType:"duration"},exdate:{defaultType:"date-time",allowedTypes:["date-time","date"],multiValue:","},exrule:p,freebusy:{defaultType:"period",multiValue:","},geo:{defaultType:"float",structuredValue:";"},"last-modified":m,location:d,method:d,organizer:{defaultType:"cal-address"},"percent-complete":g,priority:g,prodid:d,"related-to":d,repeat:g,rdate:{defaultType:"date-time",allowedTypes:["date-time",
"date","period"],multiValue:",",detectType:function(a){return-1!==a.indexOf("/")?"period":-1===a.indexOf("T")?"date":"date-time"}},"recurrence-id":l,resources:f,"request-status":h,rrule:p,sequence:g,status:d,summary:d,transp:d,trigger:{defaultType:"duration",allowedTypes:["duration","date-time"]},tzoffsetfrom:n,tzoffsetto:n,tzurl:k,tzid:d,tzname:d}),t=ICAL.helpers.extend(u,{text:b(c,e),uri:b(c,e),date:{decorate:function(a){return ICAL.VCardTime.fromDateAndOrTimeString(a,"date")},undecorate:function(a){return a.toString()},
fromICAL:function(a){return 8==a.length?s.date.fromICAL(a):"-"==a[0]&&6==a.length?a.substr(0,4)+"-"+a.substr(4):a},toICAL:function(a){return 10==a.length?s.date.toICAL(a):"-"==a[0]&&7==a.length?a.substr(0,4)+a.substr(5):a}},time:{decorate:function(a){return ICAL.VCardTime.fromDateAndOrTimeString("T"+a,"time")},undecorate:function(a){return a.toString()},fromICAL:function(a){var c=t.time._splitZone(a,!0);a=c[0];c=c[1];6==c.length?c=c.substr(0,2)+":"+c.substr(2,2)+":"+c.substr(4,2):4==c.length&&"-"!=
c[0]?c=c.substr(0,2)+":"+c.substr(2,2):5==c.length&&(c=c.substr(0,3)+":"+c.substr(3,2));5!=a.length||"-"!=a[0]&&"+"!=a[0]||(a=a.substr(0,3)+":"+a.substr(3));return c+a},toICAL:function(a){var c=t.time._splitZone(a);a=c[0];c=c[1];8==c.length?c=c.substr(0,2)+c.substr(3,2)+c.substr(6,2):5==c.length&&"-"!=c[0]?c=c.substr(0,2)+c.substr(3,2):6==c.length&&(c=c.substr(0,3)+c.substr(4,2));6!=a.length||"-"!=a[0]&&"+"!=a[0]||(a=a.substr(0,3)+a.substr(4));return c+a},_splitZone:function(a,c){var e=a.length-1,
b=a.length-(c?5:6),d=a[b];"Z"==a[e]?(d=a[e],e=a.substr(0,e)):6<a.length&&("-"==d||"+"==d)?(d=a.substr(b),e=a.substr(0,b)):(d="",e=a);return[d,e]}},"date-time":{decorate:function(a){return ICAL.VCardTime.fromDateAndOrTimeString(a,"date-time")},undecorate:function(a){return a.toString()},fromICAL:function(a){return t["date-and-or-time"].fromICAL(a)},toICAL:function(a){return t["date-and-or-time"].toICAL(a)}},"date-and-or-time":{decorate:function(a){return ICAL.VCardTime.fromDateAndOrTimeString(a,"date-and-or-time")},
undecorate:function(a){return a.toString()},fromICAL:function(a){a=a.split("T");return(a[0]?t.date.fromICAL(a[0]):"")+(a[1]?"T"+t.time.fromICAL(a[1]):"")},toICAL:function(a){a=a.split("T");return t.date.toICAL(a[0])+(a[1]?"T"+t.time.toICAL(a[1]):"")}},timestamp:s["date-time"],"language-tag":{matches:/^[a-zA-Z0-9\-]+$/}}),c=ICAL.helpers.extend(r,{adr:{defaultType:"text",structuredValue:";",multiValue:","},anniversary:q,bday:q,caladruri:k,caluri:k,clientpidmap:h,email:d,fburl:k,fn:d,gender:h,geo:k,
impp:k,key:k,kind:d,lang:{defaultType:"language-tag"},logo:k,member:k,n:{defaultType:"text",structuredValue:";",multiValue:","},nickname:f,note:d,org:{defaultType:"text",structuredValue:";"},photo:k,related:k,rev:{defaultType:"timestamp"},role:d,sound:k,source:k,tel:{defaultType:"uri",allowedTypes:["uri","text"]},title:d,tz:{defaultType:"text",allowedTypes:["text","utc-offset","uri"]},xml:d}),u=ICAL.helpers.extend(u,{binary:s.binary,date:t.date,"date-time":t["date-time"],"phone-number":{},uri:s.uri,
text:s.text,time:s.time,vcard:s.text,"utc-offset":{toICAL:function(a){return a.substr(0,7)},fromICAL:function(a){return a.substr(0,7)},decorate:function(a){return ICAL.UtcOffset.fromString(a)},undecorate:function(a){return a.toString()}}}),d=ICAL.helpers.extend(r,{fn:d,n:{defaultType:"text",structuredValue:";",multiValue:","},nickname:f,photo:{defaultType:"binary",allowedTypes:["binary","uri"]},bday:{defaultType:"date-time",allowedTypes:["date-time","date"],detectType:function(a){return-1===a.indexOf("T")?
"date":"date-time"}},adr:{defaultType:"text",structuredValue:";",multiValue:","},label:d,tel:{defaultType:"phone-number"},email:d,mailer:d,tz:{defaultType:"utc-offset",allowedTypes:["utc-offset","text"]},geo:{defaultType:"float",structuredValue:";"},title:d,role:d,logo:{defaultType:"binary",allowedTypes:["binary","uri"]},agent:{defaultType:"vcard",allowedTypes:["vcard","text","uri"]},org:h,note:f,prodid:d,rev:{defaultType:"date-time",allowedTypes:["date-time","date"],detectType:function(a){return-1===
a.indexOf("T")?"date":"date-time"}},"sort-string":d,sound:{defaultType:"binary",allowedTypes:["binary","uri"]},class:d,key:{defaultType:"binary",allowedTypes:["binary","text"]}}),f={value:s,param:{cutype:{values:["INDIVIDUAL","GROUP","RESOURCE","ROOM","UNKNOWN"],allowXName:!0,allowIanaToken:!0},"delegated-from":{valueType:"cal-address",multiValue:",",multiValueSeparateDQuote:!0},"delegated-to":{valueType:"cal-address",multiValue:",",multiValueSeparateDQuote:!0},encoding:{values:["8BIT","BASE64"]},
fbtype:{values:["FREE","BUSY","BUSY-UNAVAILABLE","BUSY-TENTATIVE"],allowXName:!0,allowIanaToken:!0},member:{valueType:"cal-address",multiValue:",",multiValueSeparateDQuote:!0},partstat:{values:"NEEDS-ACTION ACCEPTED DECLINED TENTATIVE DELEGATED COMPLETED IN-PROCESS".split(" "),allowXName:!0,allowIanaToken:!0},range:{values:["THISLANDFUTURE"]},related:{values:["START","END"]},reltype:{values:["PARENT","CHILD","SIBLING"],allowXName:!0,allowIanaToken:!0},role:{values:["REQ-PARTICIPANT","CHAIR","OPT-PARTICIPANT",
"NON-PARTICIPANT"],allowXName:!0,allowIanaToken:!0},rsvp:{values:["TRUE","FALSE"]},"sent-by":{valueType:"cal-address"},tzid:{matches:/^\//},value:{values:"binary boolean cal-address date date-time duration float integer period recur text time uri utc-offset".split(" "),allowXName:!0,allowIanaToken:!0}},property:g},h={value:t,param:{type:{valueType:"text",multiValue:","},value:{values:"text uri date time date-time date-and-or-time timestamp boolean integer float utc-offset language-tag".split(" "),
allowXName:!0,allowIanaToken:!0}},property:c},d={value:u,param:{type:{valueType:"text",multiValue:","},value:{values:"text uri date date-time phone-number time boolean integer float utc-offset vcard binary".split(" "),allowXName:!0,allowIanaToken:!0}},property:d},v={defaultSet:f,defaultType:"unknown",components:{vcard:h,vcard3:d,vevent:f,vtodo:f,vjournal:f,valarm:f,vtimezone:f,daylight:f,standard:f},icalendar:f,vcard:h,vcard3:d,getDesignSet:function(a){return a&&a in v.components?v.components[a]:
v.defaultSet}};return v}();
ICAL.stringify=function(){function b(a){"string"==typeof a[0]&&(a=[a]);for(var c=0,e=a.length,g="";c<e;c++)g+=b.component(a[c])+"\r\n";return g}var a=ICAL.design,c=ICAL.helpers;b.component=function(c,e){var h=c[0].toUpperCase(),g="BEGIN:"+h+"\r\n",l=c[1],m=0,k=l.length,n=c[0];"vcard"===n&&0<c[1].length&&("version"!==c[1][0][0]||"4.0"!==c[1][0][3])&&(n="vcard3");for(e=e||a.getDesignSet(n);m<k;m++)g+=b.property(l[m],e)+"\r\n";l=c[2];m=0;for(k=l.length;m<k;m++)g+=b.component(l[m],e)+"\r\n";return g+
("END:"+h)};b.property=function(c,e,h){var g=c[0].toUpperCase(),l=c[0],m=c[1],k;for(k in m){var n=m[k];if(m.hasOwnProperty(k)){var p=k in e.param&&e.param[k].multiValue;p&&Array.isArray(n)?(e.param[k].multiValueSeparateDQuote&&(p='"'+p+'"'),n=n.map(b._rfc6868Unescape),n=b.multiValue(n,p,"unknown",null,e)):n=b._rfc6868Unescape(n);g+=";"+k.toUpperCase();g+="\x3d"+b.propertyValue(n)}}if(3===c.length)return g+":";m=c[2];e||(e=a.defaultSet);n=k=p=!1;l in e.property?(l=e.property[l],"multiValue"in l&&(p=
l.multiValue),"structuredValue"in l&&Array.isArray(c[3])&&(k=l.structuredValue),"defaultType"in l?m===l.defaultType&&(n=!0):"unknown"===m&&(n=!0)):"unknown"===m&&(n=!0);n||(g+=";VALUE\x3d"+m.toUpperCase());g+=":";g=p&&k?g+b.multiValue(c[3],k,m,p,e,k):p?g+b.multiValue(c.slice(3),p,m,null,e,!1):k?g+b.multiValue(c[3],k,m,null,e,k):g+b.value(c[3],m,e,!1);return h?g:ICAL.helpers.foldline(g)};b.propertyValue=function(a){return-1===c.unescapedIndexOf(a,",")&&-1===c.unescapedIndexOf(a,":")&&-1===c.unescapedIndexOf(a,
";")?a:'"'+a+'"'};b.multiValue=function(a,c,e,g,l,m){for(var k="",n=a.length,p=0;p<n;p++)k=g&&Array.isArray(a[p])?k+b.multiValue(a[p],g,e,null,l,m):k+b.value(a[p],e,l,m),p!==n-1&&(k+=c);return k};b.value=function(a,c,e,b){return c in e.value&&"toICAL"in e.value[c]?e.value[c].toICAL(a,b):a};b._rfc6868Unescape=function(a){return a.replace(/[\n^"]/g,function(a){return e[a]})};var e={'"':"^'","\n":"^n","^":"^^"};return b}();
ICAL.parse=function(){function b(a){this.message=a;this.name="ParserError";try{throw Error();}catch(c){c.stack&&(a=c.stack.split("\n"),a.shift(),this.stack=a.join("\n"))}}function a(c){var e={},d=e.component=[];e.stack=[d];a._eachLine(c,function(c,b){a._handleContentLine(b,e)});if(1<e.stack.length)throw new b("invalid ical body. component began but did not end");e=null;return 1==d.length?d[0]:d}var c=/[^ \t]/,e=ICAL.design,d=ICAL.helpers;b.prototype=Error.prototype;a.property=function(c,b){var d=
{component:[[],[]],designSet:b||e.defaultSet};a._handleContentLine(c,d);return d.component[1][0]};a.component=function(c){return a(c)};a.ParserError=b;a._handleContentLine=function(c,d){var f=c.indexOf(":"),m=c.indexOf(";"),k,n={};-1!==m&&-1!==f&&m>f&&(m=-1);if(-1!==m){k=c.substring(0,m).toLowerCase();f=a._parseParameters(c.substring(m),0,d.designSet);if(-1==f[2])throw new b("Invalid parameters in '"+c+"'");n=f[0];m=f[1].length+f[2]+m;if(-1!==(f=c.substring(m).indexOf(":")))m=c.substring(m+f+1);else throw new b("Missing parameter value in '"+
c+"'");}else if(-1!==f){k=c.substring(0,f).toLowerCase();m=c.substring(f+1);if("begin"===k){k=[m.toLowerCase(),[],[]];1===d.stack.length?d.component.push(k):d.component[2].push(k);d.stack.push(d.component);d.component=k;d.designSet||(d.designSet=e.getDesignSet(d.component[0]));return}if("end"===k){d.component=d.stack.pop();return}}else throw new b('invalid line (no token ";" or ":") "'+c+'"');var p,q=f=!1,r;k in d.designSet.property&&(r=d.designSet.property[k],"multiValue"in r&&(f=r.multiValue),"structuredValue"in
r&&(q=r.structuredValue),m&&"detectType"in r&&(p=r.detectType(m)));p||(p="value"in n?n.value.toLowerCase():r?r.defaultType:"unknown");delete n.value;f&&q?(m=a._parseMultiValue(m,q,p,[],f,d.designSet,q),n=[k,n,p,m]):f?(n=[k,n,p],a._parseMultiValue(m,f,p,n,null,d.designSet,!1)):(m=q?a._parseMultiValue(m,q,p,[],null,d.designSet,q):a._parseValue(m,p,d.designSet,!1),n=[k,n,p,m]);"vcard"!==d.component[0]||0!==d.component[1].length||"version"===k&&"4.0"===m||(d.designSet=e.getDesignSet("vcard3"));d.component[1].push(n)};
a._parseValue=function(a,c,e,b){return c in e.value&&"fromICAL"in e.value[c]?e.value[c].fromICAL(a,b):a};a._parseParameters=function(c,e,f){var m=e,k=0;e={};for(var n,p,q=-1,r,u,s;!1!==k&&-1!==(k=d.unescapedIndexOf(c,"\x3d",k+1));){n=c.substr(m+1,k-m-1);if(0==n.length)throw new b("Empty parameter name in '"+c+"'");n=n.toLowerCase();r=n in f.param&&f.param[n].valueType?f.param[n].valueType:"text";n in f.param&&(u=f.param[n].multiValue,f.param[n].multiValueSeparateDQuote&&(s=a._rfc6868Escape('"'+u+
'"')));if('"'===c[k+1]){q=k+2;k=d.unescapedIndexOf(c,'"',q);if(u&&-1!=k)for(m=!0;m;)c[k+1]==u&&'"'==c[k+2]?k=d.unescapedIndexOf(c,'"',k+3):m=!1;if(-1===k)throw new b('invalid line (no matching double quote) "'+c+'"');p=c.substr(q,k-q);m=d.unescapedIndexOf(c,";",k);-1===m&&(k=!1)}else q=k+1,p=d.unescapedIndexOf(c,";",q),k=d.unescapedIndexOf(c,":",q),-1!==k&&p>k?(p=k,k=!1):-1===p?(p=-1===k?c.length:k,k=!1):k=m=p,p=c.substr(q,p-q);p=a._rfc6868Escape(p);e[n]=u?a._parseMultiValue(p,s||u,r,[],null,f):a._parseValue(p,
r,f)}return[e,p,q]};a._rfc6868Escape=function(a){return a.replace(/\^['n^]/g,function(a){return f[a]})};var f={"^'":'"',"^n":"\n","^^":"^"};a._parseMultiValue=function(c,e,b,f,k,n,p){var q=0,r=0;if(0===e.length)return c;for(;-1!==(q=d.unescapedIndexOf(c,e,r));)r=c.substr(r,q-r),r=k?a._parseMultiValue(r,k,b,[],null,n,p):a._parseValue(r,b,n,p),f.push(r),r=q+e.length;r=c.substr(r);r=k?a._parseMultiValue(r,k,b,[],null,n,p):a._parseValue(r,b,n,p);f.push(r);return 1==f.length?f[0]:f};a._eachLine=function(a,
e){var b=a.length,d=a.search(c),f=d,n,p,q;do f=a.indexOf("\n",d)+1,q=1<f&&"\r"===a[f-2]?2:1,0===f&&(f=b,q=0),p=a[d]," "===p||"\t"===p?n+=a.substr(d+1,f-d-(q+1)):(n&&e(null,n),n=a.substr(d,f-d-q)),d=f;while(f!==b);n=n.trim();n.length&&e(null,n)};return a}();
ICAL.Component=function(){function b(a,c){"string"===typeof a&&(a=[a,[],[]]);this.jCal=a;this.parent=c||null}b.prototype={_hydratedPropertyCount:0,_hydratedComponentCount:0,get name(){return this.jCal[0]},get _designSet(){return this.parent&&this.parent._designSet||ICAL.design.getDesignSet(this.name)},_hydrateComponent:function(a){this._components||(this._components=[],this._hydratedComponentCount=0);if(this._components[a])return this._components[a];var c=new b(this.jCal[2][a],this);this._hydratedComponentCount++;
return this._components[a]=c},_hydrateProperty:function(a){this._properties||(this._properties=[],this._hydratedPropertyCount=0);if(this._properties[a])return this._properties[a];var c=new ICAL.Property(this.jCal[1][a],this);this._hydratedPropertyCount++;return this._properties[a]=c},getFirstSubcomponent:function(a){if(a)for(var c=0,e=this.jCal[2],b=e.length;c<b;c++){if(e[c][0]===a)return this._hydrateComponent(c)}else if(this.jCal[2].length)return this._hydrateComponent(0);return null},getAllSubcomponents:function(a){var c=
this.jCal[2].length,e=0;if(a){for(var b=this.jCal[2],f=[];e<c;e++)a===b[e][0]&&f.push(this._hydrateComponent(e));return f}if(!this._components||this._hydratedComponentCount!==c)for(;e<c;e++)this._hydrateComponent(e);return this._components||[]},hasProperty:function(a){for(var c=this.jCal[1],e=c.length,b=0;b<e;b++)if(c[b][0]===a)return!0;return!1},getFirstProperty:function(a){if(a)for(var c=0,e=this.jCal[1],b=e.length;c<b;c++){if(e[c][0]===a)return this._hydrateProperty(c)}else if(this.jCal[1].length)return this._hydrateProperty(0);
return null},getFirstPropertyValue:function(a){return(a=this.getFirstProperty(a))?a.getFirstValue():null},getAllProperties:function(a){var c=this.jCal[1].length,e=0;if(a){for(var b=this.jCal[1],f=[];e<c;e++)a===b[e][0]&&f.push(this._hydrateProperty(e));return f}if(!this._properties||this._hydratedPropertyCount!==c)for(;e<c;e++)this._hydrateProperty(e);return this._properties||[]},_removeObjectByIndex:function(a,c,e){c=c||[];if(c[e]){var b=c[e];"parent"in b&&(b.parent=null)}c.splice(e,1);this.jCal[a].splice(e,
1)},_removeObject:function(a,c,e){var b=0,f=this.jCal[a],h=f.length;c=this[c];if("string"===typeof e)for(;b<h;b++){if(f[b][0]===e)return this._removeObjectByIndex(a,c,b),!0}else if(c)for(;b<h;b++)if(c[b]&&c[b]===e)return this._removeObjectByIndex(a,c,b),!0;return!1},_removeAllObjects:function(a,c,e){c=this[c];for(var b=this.jCal[a],f=b.length-1;0<=f;f--)e&&b[f][0]!==e||this._removeObjectByIndex(a,c,f)},addSubcomponent:function(a){this._components||(this._components=[],this._hydratedComponentCount=
0);a.parent&&a.parent.removeSubcomponent(a);var c=this.jCal[2].push(a.jCal);this._components[c-1]=a;this._hydratedComponentCount++;a.parent=this;return a},removeSubcomponent:function(a){(a=this._removeObject(2,"_components",a))&&this._hydratedComponentCount--;return a},removeAllSubcomponents:function(a){a=this._removeAllObjects(2,"_components",a);this._hydratedComponentCount=0;return a},addProperty:function(a){if(!(a instanceof ICAL.Property))throw new TypeError("must instance of ICAL.Property");
this._properties||(this._properties=[],this._hydratedPropertyCount=0);a.parent&&a.parent.removeProperty(a);var c=this.jCal[1].push(a.jCal);this._properties[c-1]=a;this._hydratedPropertyCount++;a.parent=this;return a},addPropertyWithValue:function(a,c){var e=new ICAL.Property(a);e.setValue(c);this.addProperty(e);return e},updatePropertyWithValue:function(a,c){var e=this.getFirstProperty(a);e?e.setValue(c):e=this.addPropertyWithValue(a,c);return e},removeProperty:function(a){(a=this._removeObject(1,
"_properties",a))&&this._hydratedPropertyCount--;return a},removeAllProperties:function(a){a=this._removeAllObjects(1,"_properties",a);this._hydratedPropertyCount=0;return a},toJSON:function(){return this.jCal},toString:function(){return ICAL.stringify.component(this.jCal,this._designSet)}};b.fromString=function(a){return new b(ICAL.parse.component(a))};return b}();
ICAL.Property=function(){function b(c,e){this._parent=e||null;"string"===typeof c?(this.jCal=[c,{},a.defaultType],this.jCal[2]=this.getDefaultType()):this.jCal=c;this._updateType()}var a=ICAL.design;b.prototype={get type(){return this.jCal[2]},get name(){return this.jCal[0]},get parent(){return this._parent},set parent(c){var e=!this._parent||c&&c._designSet!=this._parent._designSet;this._parent=c;this.type==a.defaultType&&e&&(this.jCal[2]=this.getDefaultType(),this._updateType());return c},get _designSet(){return this.parent?
this.parent._designSet:a.defaultSet},_updateType:function(){var a=this._designSet;this.type in a.value&&(this.isDecorated="decorate"in a.value[this.type]?!0:!1,this.name in a.property&&(this.isMultiValue="multiValue"in a.property[this.name],this.isStructuredValue="structuredValue"in a.property[this.name]))},_hydrateValue:function(a){return this._values&&this._values[a]?this._values[a]:this.jCal.length<=3+a?null:this.isDecorated?(this._values||(this._values=[]),this._values[a]=this._decorate(this.jCal[3+
a])):this.jCal[3+a]},_decorate:function(a){return this._designSet.value[this.type].decorate(a,this)},_undecorate:function(a){return this._designSet.value[this.type].undecorate(a,this)},_setDecoratedValue:function(a,e){this._values||(this._values=[]);"object"===typeof a&&"icaltype"in a?(this.jCal[3+e]=this._undecorate(a),this._values[e]=a):(this.jCal[3+e]=a,this._values[e]=this._decorate(a))},getParameter:function(a){if(a in this.jCal[1])return this.jCal[1][a]},setParameter:function(a,e){var b=a.toLowerCase();
"string"===typeof e&&b in this._designSet.param&&"multiValue"in this._designSet.param[b]&&(e=[e]);this.jCal[1][a]=e},removeParameter:function(a){delete this.jCal[1][a]},getDefaultType:function(){var c=this.jCal[0],e=this._designSet;return c in e.property&&(c=e.property[c],"defaultType"in c)?c.defaultType:a.defaultType},resetType:function(a){this.removeAllValues();this.jCal[2]=a;this._updateType()},getFirstValue:function(){return this._hydrateValue(0)},getValues:function(){var a=this.jCal.length-3;
if(1>a)return[];for(var e=0,b=[];e<a;e++)b[e]=this._hydrateValue(e);return b},removeAllValues:function(){this._values&&(this._values.length=0);this.jCal.length=3},setValues:function(a){if(!this.isMultiValue)throw Error(this.name+": does not not support mulitValue.\noverride isMultiValue");var e=a.length,b=0;this.removeAllValues();0<e&&"object"===typeof a[0]&&"icaltype"in a[0]&&this.resetType(a[0].icaltype);if(this.isDecorated)for(;b<e;b++)this._setDecoratedValue(a[b],b);else for(;b<e;b++)this.jCal[3+
b]=a[b]},setValue:function(a){this.removeAllValues();"object"===typeof a&&"icaltype"in a&&this.resetType(a.icaltype);this.isDecorated?this._setDecoratedValue(a,0):this.jCal[3]=a},toJSON:function(){return this.jCal},toICALString:function(){return ICAL.stringify.property(this.jCal,this._designSet,!0)}};b.fromString=function(a,e){return new b(ICAL.parse.property(a,e))};return b}();
ICAL.UtcOffset=function(){function b(a){this.fromData(a)}b.prototype={hours:0,minutes:0,factor:1,icaltype:"utc-offset",clone:function(){return ICAL.UtcOffset.fromSeconds(this.toSeconds())},fromData:function(a){if(a)for(var c in a)a.hasOwnProperty(c)&&(this[c]=a[c]);this._normalize()},fromSeconds:function(a){var c=Math.abs(a);this.factor=0>a?-1:1;this.hours=ICAL.helpers.trunc(c/3600);c-=3600*this.hours;this.minutes=ICAL.helpers.trunc(c/60);return this},toSeconds:function(){return this.factor*(60*this.minutes+
3600*this.hours)},compare:function(a){var c=this.toSeconds();a=a.toSeconds();return(c>a)-(a>c)},_normalize:function(){for(var a=this.toSeconds(),c=this.factor;-43200>a;)a+=97200;for(;50400<a;)a-=97200;this.fromSeconds(a);0==a&&(this.factor=c)},toICALString:function(){return ICAL.design.icalendar.value["utc-offset"].toICAL(this.toString())},toString:function(){return(1==this.factor?"+":"-")+ICAL.helpers.pad2(this.hours)+":"+ICAL.helpers.pad2(this.minutes)}};b.fromString=function(a){var c={};c.factor=
"+"===a[0]?1:-1;c.hours=ICAL.helpers.strictParseInt(a.substr(1,2));c.minutes=ICAL.helpers.strictParseInt(a.substr(4,2));return new ICAL.UtcOffset(c)};b.fromSeconds=function(a){var c=new b;c.fromSeconds(a);return c};return b}();
ICAL.Binary=function(){function b(a){this.value=a}b.prototype={icaltype:"binary",decodeValue:function(){return this._b64_decode(this.value)},setEncodedValue:function(a){this.value=this._b64_encode(a)},_b64_encode:function(a){var c,e,b,f,h=0,g=0,l="",l=[];if(!a)return a;do c=a.charCodeAt(h++),e=a.charCodeAt(h++),b=a.charCodeAt(h++),f=c<<16|e<<8|b,c=f>>18&63,e=f>>12&63,b=f>>6&63,f&=63,l[g++]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(c)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(e)+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(b)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(f);while(h<a.length);l=l.join("");a=a.length%3;return(a?l.slice(0,a-3):l)+"\x3d\x3d\x3d".slice(a||3)},_b64_decode:function(a){var c,b,d,f,h,g=0,l=0;f="";var m=[];if(!a)return a;a+="";do c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".indexOf(a.charAt(g++)),b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".indexOf(a.charAt(g++)),
f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".indexOf(a.charAt(g++)),h="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".indexOf(a.charAt(g++)),d=c<<18|b<<12|f<<6|h,c=d>>16&255,b=d>>8&255,d&=255,64==f?m[l++]=String.fromCharCode(c):64==h?m[l++]=String.fromCharCode(c,b):m[l++]=String.fromCharCode(c,b,d);while(g<a.length);return f=m.join("")},toString:function(){return this.value}};b.fromString=function(a){return new b(a)};return b}();
(function(){ICAL.Period=function(b){this.wrappedJSObject=this;if(b&&"start"in b){if(b.start&&!(b.start instanceof ICAL.Time))throw new TypeError(".start must be an instance of ICAL.Time");this.start=b.start}if(b&&b.end&&b.duration)throw Error("cannot accept both end and duration");if(b&&"end"in b){if(b.end&&!(b.end instanceof ICAL.Time))throw new TypeError(".end must be an instance of ICAL.Time");this.end=b.end}if(b&&"duration"in b){if(b.duration&&!(b.duration instanceof ICAL.Duration))throw new TypeError(".duration must be an instance of ICAL.Duration");
this.duration=b.duration}};ICAL.Period.prototype={start:null,end:null,duration:null,icalclass:"icalperiod",icaltype:"period",clone:function(){return ICAL.Period.fromData({start:this.start?this.start.clone():null,end:this.end?this.end.clone():null,duration:this.duration?this.duration.clone():null})},getDuration:function(){return this.duration?this.duration:this.end.subtractDate(this.start)},getEnd:function(){if(this.end)return this.end;var b=this.start.clone();b.addDuration(this.duration);return b},
toString:function(){return this.start+"/"+(this.end||this.duration)},toJSON:function(){return[this.start.toString(),(this.end||this.duration).toString()]},toICALString:function(){return this.start.toICALString()+"/"+(this.end||this.duration).toICALString()}};ICAL.Period.fromString=function(b,a){var c=b.split("/");if(2!==c.length)throw Error('Invalid string value: "'+b+'" must contain a "/" char.');var e={start:ICAL.Time.fromDateTimeString(c[0],a)},c=c[1];ICAL.Duration.isValueString(c)?e.duration=
ICAL.Duration.fromString(c):e.end=ICAL.Time.fromDateTimeString(c,a);return new ICAL.Period(e)};ICAL.Period.fromData=function(b){return new ICAL.Period(b)};ICAL.Period.fromJSON=function(b,a){return ICAL.Duration.isValueString(b[1])?ICAL.Period.fromData({start:ICAL.Time.fromDateTimeString(b[0],a),duration:ICAL.Duration.fromString(b[1])}):ICAL.Period.fromData({start:ICAL.Time.fromDateTimeString(b[0],a),end:ICAL.Time.fromDateTimeString(b[1],a)})}})();
(function(){var b=/([PDWHMTS]{1,1})/;ICAL.Duration=function(a){this.wrappedJSObject=this;this.fromData(a)};ICAL.Duration.prototype={weeks:0,days:0,hours:0,minutes:0,seconds:0,isNegative:!1,icalclass:"icalduration",icaltype:"duration",clone:function(){return ICAL.Duration.fromData(this)},toSeconds:function(){var a=this.seconds+60*this.minutes+3600*this.hours+86400*this.days+604800*this.weeks;return this.isNegative?-a:a},fromSeconds:function(a){var c=Math.abs(a);this.isNegative=0>a;this.days=ICAL.helpers.trunc(c/
86400);0==this.days%7?(this.weeks=this.days/7,this.days=0):this.weeks=0;c-=86400*(this.days+7*this.weeks);this.hours=ICAL.helpers.trunc(c/3600);c-=3600*this.hours;this.minutes=ICAL.helpers.trunc(c/60);this.seconds=c-=60*this.minutes;return this},fromData:function(a){var c="weeks days hours minutes seconds isNegative".split(" "),b;for(b in c)if(c.hasOwnProperty(b)){var d=c[b];this[d]=a&&d in a?a[d]:0}},reset:function(){this.isNegative=!1;this.seconds=this.minutes=this.hours=this.days=this.weeks=0},
compare:function(a){var c=this.toSeconds();a=a.toSeconds();return(c>a)-(c<a)},normalize:function(){this.fromSeconds(this.toSeconds())},toString:function(){if(0==this.toSeconds())return"PT0S";var a="";this.isNegative&&(a+="-");a+="P";this.weeks&&(a+=this.weeks+"W");this.days&&(a+=this.days+"D");if(this.hours||this.minutes||this.seconds)a+="T",this.hours&&(a+=this.hours+"H"),this.minutes&&(a+=this.minutes+"M"),this.seconds&&(a+=this.seconds+"S");return a},toICALString:function(){return this.toString()}};
ICAL.Duration.fromSeconds=function(a){return(new ICAL.Duration).fromSeconds(a)};ICAL.Duration.isValueString=function(a){return"P"===a[0]||"P"===a[1]};ICAL.Duration.fromString=function(a){for(var c=0,e=Object.create(null),d=0;-1!==(c=a.search(b));){var f=a[c],h=a.substr(0,c);a=a.substr(c+1);c=d;a:{var d=e,g=void 0;switch(f){case "P":d.isNegative=h&&"-"===h?!0:!1;break;case "D":g="days";break;case "W":g="weeks";break;case "H":g="hours";break;case "M":g="minutes";break;case "S":g="seconds";break;default:f=
0;break a}if(g){if(!h&&0!==h)throw Error('invalid duration value: Missing number before "'+f+'"');var l=parseInt(h,10);if(ICAL.helpers.isStrictlyNaN(l))throw Error('invalid duration value: Invalid number "'+h+'" before "'+f+'"');d[g]=l}f=1}d=c+f}if(2>d)throw Error('invalid duration value: Not enough duration components in "'+a+'"');return new ICAL.Duration(e)};ICAL.Duration.fromData=function(a){return new ICAL.Duration(a)}})();
(function(){var b=["tzid","location","tznames","latitude","longitude"];ICAL.Timezone=function(a){this.wrappedJSObject=this;this.fromData(a)};ICAL.Timezone.prototype={tzid:"",location:"",tznames:"",latitude:0,longitude:0,component:null,expandedUntilYear:0,icalclass:"icaltimezone",fromData:function(a){this.expandedUntilYear=0;this.changes=[];if(a instanceof ICAL.Component)this.component=a;else{if(a&&"component"in a)if("string"==typeof a.component){var c=ICAL.parse(a.component);this.component=new ICAL.Component(c)}else this.component=
a.component instanceof ICAL.Component?a.component:null;for(var e in b)b.hasOwnProperty(e)&&(c=b[e],a&&c in a&&(this[c]=a[c]))}this.component instanceof ICAL.Component&&!this.tzid&&(this.tzid=this.component.getFirstPropertyValue("tzid"));return this},utcOffset:function(a){if(this==ICAL.Timezone.utcTimezone||this==ICAL.Timezone.localTimezone)return 0;this._ensureCoverage(a.year);if(!this.changes.length)return 0;a={year:a.year,month:a.month,day:a.day,hour:a.hour,minute:a.minute,second:a.second};for(var c=
this._findNearbyChange(a),b=-1,d=1;;){var f=ICAL.helpers.clone(this.changes[c],!0);f.utcOffset<f.prevUtcOffset?ICAL.Timezone.adjust_change(f,0,0,0,f.utcOffset):ICAL.Timezone.adjust_change(f,0,0,0,f.prevUtcOffset);0<=ICAL.Timezone._compare_change_fn(a,f)?b=c:d=-1;if(-1==d&&-1!=b)break;c+=d;if(0>c)return 0;if(c>=this.changes.length)break}c=this.changes[b];0>c.utcOffset-c.prevUtcOffset&&0<b&&(d=ICAL.helpers.clone(c,!0),ICAL.Timezone.adjust_change(d,0,0,0,d.prevUtcOffset),0>ICAL.Timezone._compare_change_fn(a,
d)&&(a=this.changes[b-1],0!=c.is_daylight&&0==a.is_daylight&&(c=a)));return c.utcOffset},_findNearbyChange:function(a){a=ICAL.helpers.binsearchInsert(this.changes,a,ICAL.Timezone._compare_change_fn);return a>=this.changes.length?this.changes.length-1:a},_ensureCoverage:function(a){if(-1==ICAL.Timezone._minimumExpansionYear){var c=ICAL.Time.now();ICAL.Timezone._minimumExpansionYear=c.year}c=a;c<ICAL.Timezone._minimumExpansionYear&&(c=ICAL.Timezone._minimumExpansionYear);c+=ICAL.Timezone.EXTRA_COVERAGE;
c>ICAL.Timezone.MAX_YEAR&&(c=ICAL.Timezone.MAX_YEAR);if(!this.changes.length||this.expandedUntilYear<a){a=this.component.getAllSubcomponents();for(var b=a.length,d=0;d<b;d++)this._expandComponent(a[d],c,this.changes);this.changes.sort(ICAL.Timezone._compare_change_fn);this.expandedUntilYear=c}},_expandComponent:function(a,c,b){function d(a){return a.factor*(3600*a.hours+60*a.minutes)}function f(){var c={};c.is_daylight="daylight"==a.name;c.utcOffset=d(a.getFirstProperty("tzoffsetto").getFirstValue());
c.prevUtcOffset=d(a.getFirstProperty("tzoffsetfrom").getFirstValue());return c}if(!a.hasProperty("dtstart")||!a.hasProperty("tzoffsetto")||!a.hasProperty("tzoffsetfrom"))return null;var h=a.getFirstProperty("dtstart").getFirstValue(),g;if(a.hasProperty("rrule")||a.hasProperty("rdate")){var l=a.getAllProperties("rdate"),m;for(m in l)if(l.hasOwnProperty(m)){var k=l[m].getFirstValue();g=f();g.year=k.year;g.month=k.month;g.day=k.day;k.isDate?(g.hour=h.hour,g.minute=h.minute,g.second=h.second,h.zone!=
ICAL.Timezone.utcTimezone&&ICAL.Timezone.adjust_change(g,0,0,0,-g.prevUtcOffset)):(g.hour=k.hour,g.minute=k.minute,g.second=k.second,k.zone!=ICAL.Timezone.utcTimezone&&ICAL.Timezone.adjust_change(g,0,0,0,-g.prevUtcOffset));b.push(g)}if(l=a.getFirstProperty("rrule"))for(l=l.getFirstValue(),g=f(),l.until&&l.until.zone==ICAL.Timezone.utcTimezone&&(l.until.adjust(0,0,0,g.prevUtcOffset),l.until.zone=ICAL.Timezone.localTimezone),h=l.iterator(h);l=h.next();){g=f();if(l.year>c||!l)break;g.year=l.year;g.month=
l.month;g.day=l.day;g.hour=l.hour;g.minute=l.minute;g.second=l.second;g.isDate=l.isDate;ICAL.Timezone.adjust_change(g,0,0,0,-g.prevUtcOffset);b.push(g)}}else g=f(),g.year=h.year,g.month=h.month,g.day=h.day,g.hour=h.hour,g.minute=h.minute,g.second=h.second,ICAL.Timezone.adjust_change(g,0,0,0,-g.prevUtcOffset),b.push(g);return b},toString:function(){return this.tznames?this.tznames:this.tzid}};ICAL.Timezone._compare_change_fn=function(a,c){return a.year<c.year?-1:a.year>c.year?1:a.month<c.month?-1:
a.month>c.month?1:a.day<c.day?-1:a.day>c.day?1:a.hour<c.hour?-1:a.hour>c.hour?1:a.minute<c.minute?-1:a.minute>c.minute?1:a.second<c.second?-1:a.second>c.second?1:0};ICAL.Timezone.convert_time=function(a,c,b){if(a.isDate||c.tzid==b.tzid||c==ICAL.Timezone.localTimezone||b==ICAL.Timezone.localTimezone)return a.zone=b,a;c=c.utcOffset(a);a.adjust(0,0,0,-c);c=b.utcOffset(a);a.adjust(0,0,0,c);return null};ICAL.Timezone.fromData=function(a){return(new ICAL.Timezone).fromData(a)};ICAL.Timezone.utcTimezone=
ICAL.Timezone.fromData({tzid:"UTC"});ICAL.Timezone.localTimezone=ICAL.Timezone.fromData({tzid:"floating"});ICAL.Timezone.adjust_change=function(a,c,b,d,f){return ICAL.Time.prototype.adjust.call(a,c,b,d,f,a)};ICAL.Timezone._minimumExpansionYear=-1;ICAL.Timezone.MAX_YEAR=2035;ICAL.Timezone.EXTRA_COVERAGE=5})();
ICAL.TimezoneService=function(){var b,a={reset:function(){b=Object.create(null);var a=ICAL.Timezone.utcTimezone;b.Z=a;b.UTC=a;b.GMT=a},has:function(a){return!!b[a]},get:function(a){return b[a]},register:function(a,e){a instanceof ICAL.Component&&"vtimezone"===a.name&&(e=new ICAL.Timezone(a),a=e.tzid);if(e instanceof ICAL.Timezone)b[a]=e;else throw new TypeError("timezone must be ICAL.Timezone or ICAL.Component");},remove:function(a){return delete b[a]}};a.reset();return a}();
(function(){ICAL.Time=function(b,a){this.wrappedJSObject=this;var c=this._time=Object.create(null);c.year=0;c.month=1;c.day=1;c.hour=0;c.minute=0;c.second=0;c.isDate=!1;this.fromData(b,a)};ICAL.Time._dowCache={};ICAL.Time._wnCache={};ICAL.Time.prototype={icalclass:"icaltime",_cachedUnixTime:null,get icaltype(){return this.isDate?"date":"date-time"},zone:null,_pendingNormalization:!1,clone:function(){return new ICAL.Time(this._time,this.zone)},reset:function(){this.fromData(ICAL.Time.epochTime);this.zone=
ICAL.Timezone.utcTimezone},resetTo:function(b,a,c,e,d,f,h){this.fromData({year:b,month:a,day:c,hour:e,minute:d,second:f,zone:h})},fromJSDate:function(b,a){b?a?(this.zone=ICAL.Timezone.utcTimezone,this.year=b.getUTCFullYear(),this.month=b.getUTCMonth()+1,this.day=b.getUTCDate(),this.hour=b.getUTCHours(),this.minute=b.getUTCMinutes(),this.second=b.getUTCSeconds()):(this.zone=ICAL.Timezone.localTimezone,this.year=b.getFullYear(),this.month=b.getMonth()+1,this.day=b.getDate(),this.hour=b.getHours(),this.minute=
b.getMinutes(),this.second=b.getSeconds()):this.reset();this._cachedUnixTime=null;return this},fromData:function(b,a){if(b)for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&"icaltype"!==c&&(this[c]=b[c]);a&&(this.zone=a);!b||"isDate"in b?b&&"isDate"in b&&(this.isDate=b.isDate):this.isDate=!("hour"in b);b&&"timezone"in b&&(this.zone=ICAL.TimezoneService.get(b.timezone)||ICAL.Timezone.localTimezone);b&&"zone"in b&&(this.zone=b.zone);this.zone||(this.zone=ICAL.Timezone.localTimezone);this._cachedUnixTime=
null;return this},dayOfWeek:function(){var b=(this.year<<9)+(this.month<<5)+this.day;if(b in ICAL.Time._dowCache)return ICAL.Time._dowCache[b];var a=this.year-(3>this.month?1:0),c=this.day+a+ICAL.helpers.trunc(26*(this.month+(3>this.month?12:0)+1)/10)+ICAL.helpers.trunc(a/4),c=c+(6*ICAL.helpers.trunc(a/100)+ICAL.helpers.trunc(a/400)),c=(c+6)%7+1;return ICAL.Time._dowCache[b]=c},dayOfYear:function(){var b=ICAL.Time.isLeapYear(this.year)?1:0;return ICAL.Time.daysInYearPassedMonth[b][this.month-1]+this.day},
startOfWeek:function(b){b=b||ICAL.Time.SUNDAY;var a=this.clone();a.day-=(this.dayOfWeek()+7-b)%7;a.isDate=!0;a.hour=0;a.minute=0;a.second=0;return a},endOfWeek:function(b){b=b||ICAL.Time.SUNDAY;var a=this.clone();a.day+=(7-this.dayOfWeek()+b-ICAL.Time.SUNDAY)%7;a.isDate=!0;a.hour=0;a.minute=0;a.second=0;return a},startOfMonth:function(){var b=this.clone();b.day=1;b.isDate=!0;b.hour=0;b.minute=0;b.second=0;return b},endOfMonth:function(){var b=this.clone();b.day=ICAL.Time.daysInMonth(b.month,b.year);
b.isDate=!0;b.hour=0;b.minute=0;b.second=0;return b},startOfYear:function(){var b=this.clone();b.day=1;b.month=1;b.isDate=!0;b.hour=0;b.minute=0;b.second=0;return b},endOfYear:function(){var b=this.clone();b.day=31;b.month=12;b.isDate=!0;b.hour=0;b.minute=0;b.second=0;return b},startDoyWeek:function(b){b=b||ICAL.Time.SUNDAY;b=this.dayOfWeek()-b;0>b&&(b+=7);return this.dayOfYear()-b},getDominicalLetter:function(){return ICAL.Time.getDominicalLetter(this.year)},nthWeekDay:function(b,a){var c=ICAL.Time.daysInMonth(this.month,
this.year),e,d=a,f=0;e=this.clone();0<=d?(e.day=1,0!=d&&d--,f=e.day,c=e.dayOfWeek(),c=b-c,0>c&&(c+=7),f=f+c-b,e=b):(e.day=c,e=e.dayOfWeek(),d++,e-=b,0>e&&(e+=7),e=c-e);return f+(e+7*d)},isNthWeekDay:function(b,a){var c=this.dayOfWeek();return 0===a&&c===b||this.nthWeekDay(b,a)===this.day?!0:!1},weekNumber:function(b){var a=(this.year<<12)+(this.month<<8)+(this.day<<3)+b;if(a in ICAL.Time._wnCache)return ICAL.Time._wnCache[a];var c,e=this.clone();e.isDate=!0;var d=this.year;12==e.month&&25<e.day?(c=
ICAL.Time.weekOneStarts(d+1,b),0>e.compare(c)&&(c=ICAL.Time.weekOneStarts(d,b))):(c=ICAL.Time.weekOneStarts(d,b),0>e.compare(c)&&(c=ICAL.Time.weekOneStarts(--d,b)));b=e.subtractDate(c).toSeconds()/86400;b=ICAL.helpers.trunc(b/7)+1;return ICAL.Time._wnCache[a]=b},addDuration:function(b){var a=b.isNegative?-1:1,c=this.second,e=this.minute,d=this.hour,f=this.day,c=c+a*b.seconds,e=e+a*b.minutes,d=d+a*b.hours,f=f+a*b.days,f=f+7*a*b.weeks;this.second=c;this.minute=e;this.hour=d;this.day=f;this._cachedUnixTime=
null},subtractDate:function(b){var a=this.toUnixTime()+this.utcOffset();b=b.toUnixTime()+b.utcOffset();return ICAL.Duration.fromSeconds(a-b)},subtractDateTz:function(b){var a=this.toUnixTime();b=b.toUnixTime();return ICAL.Duration.fromSeconds(a-b)},compare:function(b){var a=this.toUnixTime();b=b.toUnixTime();return a>b?1:b>a?-1:0},compareDateOnlyTz:function(b,a){var c=this.convertToZone(a),e=b.convertToZone(a),d=0;return 0!=(d=ICAL.Time._cmp_attr(c,e,"year"))||0!=(d=ICAL.Time._cmp_attr(c,e,"month"))?
d:d=ICAL.Time._cmp_attr(c,e,"day")},convertToZone:function(b){var a=this.clone(),c=this.zone.tzid==b.tzid;this.isDate||c||ICAL.Timezone.convert_time(a,this.zone,b);a.zone=b;return a},utcOffset:function(){return this.zone==ICAL.Timezone.localTimezone||this.zone==ICAL.Timezone.utcTimezone?0:this.zone.utcOffset(this)},toICALString:function(){var b=this.toString();return 10<b.length?ICAL.design.icalendar.value["date-time"].toICAL(b):ICAL.design.icalendar.value.date.toICAL(b)},toString:function(){var b=
this.year+"-"+ICAL.helpers.pad2(this.month)+"-"+ICAL.helpers.pad2(this.day);this.isDate||(b+="T"+ICAL.helpers.pad2(this.hour)+":"+ICAL.helpers.pad2(this.minute)+":"+ICAL.helpers.pad2(this.second),this.zone===ICAL.Timezone.utcTimezone&&(b+="Z"));return b},toJSDate:function(){return this.zone==ICAL.Timezone.localTimezone?this.isDate?new Date(this.year,this.month-1,this.day):new Date(this.year,this.month-1,this.day,this.hour,this.minute,this.second,0):new Date(1E3*this.toUnixTime())},_normalize:function(){this._time.isDate&&
(this._time.hour=0,this._time.minute=0,this._time.second=0);this.adjust(0,0,0,0);return this},adjust:function(b,a,c,e,d){var f=0,h=0;d=d||this._time;d.isDate||(e=d.second+e,d.second=e%60,e=ICAL.helpers.trunc(e/60),0>d.second&&(d.second+=60,e--),c=d.minute+c+e,d.minute=c%60,c=ICAL.helpers.trunc(c/60),0>d.minute&&(d.minute+=60,c--),a=d.hour+a+c,d.hour=a%24,f=ICAL.helpers.trunc(a/24),0>d.hour&&(d.hour+=24,f--));12<d.month?h=ICAL.helpers.trunc((d.month-1)/12):1>d.month&&(h=ICAL.helpers.trunc(d.month/
12)-1);d.year+=h;d.month-=12*h;b=d.day+b+f;if(0<b)for(;;){h=ICAL.Time.daysInMonth(d.month,d.year);if(b<=h)break;d.month++;12<d.month&&(d.year++,d.month=1);b-=h}else for(;0>=b;)1==d.month?(d.year--,d.month=12):d.month--,b+=ICAL.Time.daysInMonth(d.month,d.year);d.day=b;this._cachedUnixTime=null;return this},fromUnixTime:function(b){this.zone=ICAL.Timezone.utcTimezone;var a=ICAL.Time.epochTime.clone();a.adjust(0,0,0,b);this.year=a.year;this.month=a.month;this.day=a.day;this.hour=a.hour;this.minute=a.minute;
this.second=Math.floor(a.second);this._cachedUnixTime=null},toUnixTime:function(){if(null!==this._cachedUnixTime)return this._cachedUnixTime;var b=this.utcOffset();return this._cachedUnixTime=Date.UTC(this.year,this.month-1,this.day,this.hour,this.minute,this.second-b)/1E3},toJSON:function(){for(var b="year month day hour minute second isDate".split(" "),a=Object.create(null),c=0,e=b.length,d;c<e;c++)d=b[c],a[d]=this[d];this.zone&&(a.timezone=this.zone.tzid);return a}};(function(){function b(a){Object.defineProperty(ICAL.Time.prototype,
a,{get:function(){this._pendingNormalization&&(this._normalize(),this._pendingNormalization=!1);return this._time[a]},set:function(c){this._cachedUnixTime=null;this._pendingNormalization=!0;return this._time[a]=c}})}"defineProperty"in Object&&(b("year"),b("month"),b("day"),b("hour"),b("minute"),b("second"),b("isDate"))})();ICAL.Time.daysInMonth=function(b,a){var c=30;if(1>b||12<b)return c;c=[0,31,28,31,30,31,30,31,31,30,31,30,31][b];2==b&&(c+=ICAL.Time.isLeapYear(a));return c};ICAL.Time.isLeapYear=
function(b){return 1752>=b?0==b%4:0==b%4&&0!=b%100||0==b%400};ICAL.Time.fromDayOfYear=function(b,a){var c=a,e=b,d=new ICAL.Time;d.auto_normalize=!1;var f=ICAL.Time.isLeapYear(c)?1:0;if(1>e)return c--,f=ICAL.Time.isLeapYear(c)?1:0,e+=ICAL.Time.daysInYearPassedMonth[f][12],ICAL.Time.fromDayOfYear(e,c);if(e>ICAL.Time.daysInYearPassedMonth[f][12])return f=ICAL.Time.isLeapYear(c)?1:0,e-=ICAL.Time.daysInYearPassedMonth[f][12],c++,ICAL.Time.fromDayOfYear(e,c);d.year=c;d.isDate=!0;for(c=11;0<=c;c--)if(e>
ICAL.Time.daysInYearPassedMonth[f][c]){d.month=c+1;d.day=e-ICAL.Time.daysInYearPassedMonth[f][c];break}d.auto_normalize=!0;return d};ICAL.Time.fromStringv2=function(b){return new ICAL.Time({year:parseInt(b.substr(0,4),10),month:parseInt(b.substr(5,2),10),day:parseInt(b.substr(8,2),10),isDate:!0})};ICAL.Time.fromDateString=function(b){return new ICAL.Time({year:ICAL.helpers.strictParseInt(b.substr(0,4)),month:ICAL.helpers.strictParseInt(b.substr(5,2)),day:ICAL.helpers.strictParseInt(b.substr(8,2)),
isDate:!0})};ICAL.Time.fromDateTimeString=function(b,a){if(19>b.length)throw Error('invalid date-time value: "'+b+'"');var c;b[19]&&"Z"===b[19]?c="Z":a&&(c=a.getParameter("tzid"));return new ICAL.Time({year:ICAL.helpers.strictParseInt(b.substr(0,4)),month:ICAL.helpers.strictParseInt(b.substr(5,2)),day:ICAL.helpers.strictParseInt(b.substr(8,2)),hour:ICAL.helpers.strictParseInt(b.substr(11,2)),minute:ICAL.helpers.strictParseInt(b.substr(14,2)),second:ICAL.helpers.strictParseInt(b.substr(17,2)),timezone:c})};
ICAL.Time.fromString=function(b){return 10<b.length?ICAL.Time.fromDateTimeString(b):ICAL.Time.fromDateString(b)};ICAL.Time.fromJSDate=function(b,a){return(new ICAL.Time).fromJSDate(b,a)};ICAL.Time.fromData=function(b,a){return(new ICAL.Time).fromData(b,a)};ICAL.Time.now=function(){return ICAL.Time.fromJSDate(new Date,!1)};ICAL.Time.weekOneStarts=function(b,a){var c=ICAL.Time.fromData({year:b,month:1,day:1,isDate:!0}),e=c.dayOfWeek(),d=a||ICAL.Time.DEFAULT_WEEK_START;e>ICAL.Time.THURSDAY&&(c.day+=
7);d>ICAL.Time.THURSDAY&&(c.day-=7);c.day-=e-d;return c};ICAL.Time.getDominicalLetter=function(b){var a=(b+(b/4|0)+(b/400|0)-(b/100|0)-1)%7;return ICAL.Time.isLeapYear(b)?"GFEDCBA"[(a+6)%7]+"GFEDCBA"[a]:"GFEDCBA"[a]};ICAL.Time.epochTime=ICAL.Time.fromData({year:1970,month:1,day:1,hour:0,minute:0,second:0,isDate:!1,timezone:"Z"});ICAL.Time._cmp_attr=function(b,a,c){return b[c]>a[c]?1:b[c]<a[c]?-1:0};ICAL.Time.daysInYearPassedMonth=[[0,31,59,90,120,151,181,212,243,273,304,334,365],[0,31,60,91,121,152,
182,213,244,274,305,335,366]];ICAL.Time.SUNDAY=1;ICAL.Time.MONDAY=2;ICAL.Time.TUESDAY=3;ICAL.Time.WEDNESDAY=4;ICAL.Time.THURSDAY=5;ICAL.Time.FRIDAY=6;ICAL.Time.SATURDAY=7;ICAL.Time.DEFAULT_WEEK_START=ICAL.Time.MONDAY})();
(function(){ICAL.VCardTime=function(b,a,c){this.wrappedJSObject=this;var e=this._time=Object.create(null);e.year=null;e.month=null;e.day=null;e.hour=null;e.minute=null;e.second=null;this.icaltype=c||"date-and-or-time";this.fromData(b,a)};ICAL.helpers.inherits(ICAL.Time,ICAL.VCardTime,{icalclass:"vcardtime",icaltype:"date-and-or-time",zone:null,clone:function(){return new ICAL.VCardTime(this._time,this.zone,this.icaltype)},_normalize:function(){return this},utcOffset:function(){return this.zone instanceof
ICAL.UtcOffset?this.zone.toSeconds():ICAL.Time.prototype.utcOffset.apply(this,arguments)},toICALString:function(){return ICAL.design.vcard.value[this.icaltype].toICAL(this.toString())},toString:function(){var b=ICAL.helpers.pad2,a=this.year,c=this.month,e=this.day,d=this.hour,f=this.minute,h=this.second,g=null!==c,l=null!==e,m=null!==d,k=null!==f,n=null!==h,a=(null!==a?b(a)+(g||l?"-":""):g||l?"--":"")+(g?b(c):"")+(l?"-"+b(e):""),b=(m?b(d):"-")+(m&&k?":":"")+(k?b(f):"")+(m||k?"":"-")+(k&&n?":":"")+
(n?b(h):""),d=this.zone===ICAL.Timezone.utcTimezone?"Z":this.zone instanceof ICAL.UtcOffset?this.zone.toString():this.zone===ICAL.Timezone.localTimezone?"":this.zone instanceof ICAL.Timezone?ICAL.UtcOffset.fromSeconds(this.zone.utcOffset(this)).toString():"";switch(this.icaltype){case "time":return b+d;case "date-and-or-time":case "date-time":return a+("--"==b?"":"T"+b+d);case "date":return a}return null}});ICAL.VCardTime.fromDateAndOrTimeString=function(b,a){function c(a,c,b){return a?ICAL.helpers.strictParseInt(a.substr(c,
b)):null}var e=b.split("T"),d=e[0],f=(e=e[1])?ICAL.design.vcard.value.time._splitZone(e):[],e=f[0],f=f[1],h=d?d.length:0,g=f?f.length:0,l=d&&"-"==d[0]&&"-"==d[1],m=f&&"-"==f[0],d={year:l?null:c(d,0,4),month:!l||4!=h&&7!=h?7==h?c(d,5,2):10==h?c(d,5,2):null:c(d,2,2),day:5==h?c(d,3,2):7==h&&l?c(d,5,2):10==h?c(d,8,2):null,hour:m?null:c(f,0,2),minute:m&&3==g?c(f,1,2):4<g?m?c(f,1,2):c(f,3,2):null,second:4==g?c(f,2,2):6==g?c(f,4,2):8==g?c(f,6,2):null},e="Z"==e?ICAL.Timezone.utcTimezone:e&&":"==e[3]?ICAL.UtcOffset.fromString(e):
null;return new ICAL.VCardTime(d,e,a)}})();
(function(){function b(a,c,b,e){var d=e;"+"===e[0]&&(d=e.substr(1));d=ICAL.helpers.strictParseInt(d);if(void 0!==c&&e<c)throw Error(a+': invalid value "'+e+'" must be \x3e '+c);if(void 0!==b&&e>b)throw Error(a+': invalid value "'+e+'" must be \x3c '+c);return d}var a={SU:ICAL.Time.SUNDAY,MO:ICAL.Time.MONDAY,TU:ICAL.Time.TUESDAY,WE:ICAL.Time.WEDNESDAY,TH:ICAL.Time.THURSDAY,FR:ICAL.Time.FRIDAY,SA:ICAL.Time.SATURDAY},c={},e;for(e in a)a.hasOwnProperty(e)&&(c[a[e]]=e);ICAL.Recur=function(a){this.wrappedJSObject=
this;this.parts={};a&&"object"===typeof a&&this.fromData(a)};ICAL.Recur.prototype={parts:null,interval:1,wkst:ICAL.Time.MONDAY,until:null,count:null,freq:null,icalclass:"icalrecur",icaltype:"recur",iterator:function(a){return new ICAL.RecurIterator({rule:this,dtstart:a})},clone:function(){return new ICAL.Recur(this.toJSON())},isFinite:function(){return!(!this.count&&!this.until)},isByCount:function(){return!(!this.count||this.until)},addComponent:function(a,c){var b=a.toUpperCase();b in this.parts?
this.parts[b].push(c):this.parts[b]=[c]},setComponent:function(a,c){this.parts[a.toUpperCase()]=c.slice()},getComponent:function(a){a=a.toUpperCase();return a in this.parts?this.parts[a].slice():[]},getNextOccurrence:function(a,c){var b=this.iterator(a),e;do e=b.next();while(e&&0>=e.compare(c));e&&c.zone&&(e.zone=c.zone);return e},fromData:function(a){for(var c in a){var b=c.toUpperCase();b in l?Array.isArray(a[c])?this.parts[b]=a[c]:this.parts[b]=[a[c]]:this[c]=a[c]}this.wkst&&"number"!=typeof this.wkst&&
(this.wkst=ICAL.Recur.icalDayToNumericDay(this.wkst));!this.until||this.until instanceof ICAL.Time||(this.until=ICAL.Time.fromString(this.until))},toJSON:function(){var a=Object.create(null);a.freq=this.freq;this.count&&(a.count=this.count);1<this.interval&&(a.interval=this.interval);for(var c in this.parts)if(this.parts.hasOwnProperty(c)){var b=this.parts[c];Array.isArray(b)&&1==b.length?a[c.toLowerCase()]=b[0]:a[c.toLowerCase()]=ICAL.helpers.clone(this.parts[c])}this.until&&(a.until=this.until.toString());
"wkst"in this&&this.wkst!==ICAL.Time.DEFAULT_WEEK_START&&(a.wkst=ICAL.Recur.numericDayToIcalDay(this.wkst));return a},toString:function(){var a="FREQ\x3d"+this.freq;this.count&&(a+=";COUNT\x3d"+this.count);1<this.interval&&(a+=";INTERVAL\x3d"+this.interval);for(var c in this.parts)this.parts.hasOwnProperty(c)&&(a+=";"+c+"\x3d"+this.parts[c]);this.until&&(a+=";UNTIL\x3d"+this.until.toString());"wkst"in this&&this.wkst!==ICAL.Time.DEFAULT_WEEK_START&&(a+=";WKST\x3d"+ICAL.Recur.numericDayToIcalDay(this.wkst));
return a}};ICAL.Recur.icalDayToNumericDay=function(c){return a[c]};ICAL.Recur.numericDayToIcalDay=function(a){return c[a]};var d=/^(SU|MO|TU|WE|TH|FR|SA)$/,f=/^([+-])?(5[0-3]|[1-4][0-9]|[1-9])?(SU|MO|TU|WE|TH|FR|SA)$/,h="SECONDLY MINUTELY HOURLY DAILY WEEKLY MONTHLY YEARLY".split(" "),g={FREQ:function(a,c,b){if(-1!==h.indexOf(a))c.freq=a;else throw Error('invalid frequency "'+a+'" expected: "'+h.join(", ")+'"');},COUNT:function(a,c,b){c.count=ICAL.helpers.strictParseInt(a)},INTERVAL:function(a,c,
b){c.interval=ICAL.helpers.strictParseInt(a);1>c.interval&&(c.interval=1)},UNTIL:function(a,c,b){c.until=b?10<a.length?ICAL.design.icalendar.value["date-time"].fromICAL(a):ICAL.design.icalendar.value.date.fromICAL(a):ICAL.Time.fromString(a)},WKST:function(a,c,b){if(d.test(a))c.wkst=ICAL.Recur.icalDayToNumericDay(a);else throw Error('invalid WKST value "'+a+'"');}},l={BYSECOND:b.bind(this,"BYSECOND",0,60),BYMINUTE:b.bind(this,"BYMINUTE",0,59),BYHOUR:b.bind(this,"BYHOUR",0,23),BYDAY:function(a){if(f.test(a))return a;
throw Error('invalid BYDAY value "'+a+'"');},BYMONTHDAY:b.bind(this,"BYMONTHDAY",-31,31),BYYEARDAY:b.bind(this,"BYYEARDAY",-366,366),BYWEEKNO:b.bind(this,"BYWEEKNO",-53,53),BYMONTH:b.bind(this,"BYMONTH",0,12),BYSETPOS:b.bind(this,"BYSETPOS",-366,366)};ICAL.Recur.fromString=function(a){a=ICAL.Recur._stringToData(a,!1);return new ICAL.Recur(a)};ICAL.Recur.fromData=function(a){return new ICAL.Recur(a)};ICAL.Recur._stringToData=function(a,c){for(var b=Object.create(null),e=a.split(";"),d=e.length,f=0;f<
d;f++){var h=e[f].split("\x3d"),s=h[0].toUpperCase(),t=h[0].toLowerCase(),v=c?t:s,h=h[1];if(s in l){for(var t=h.split(","),h=0,w=t.length;h<w;h++)t[h]=l[s](t[h]);b[v]=1==t.length?t[0]:t}else if(s in g)g[s](h,b,c);else b[t]=h}return b}})();
ICAL.RecurIterator=function(){function b(a){this.fromData(a)}b.prototype={completed:!1,rule:null,dtstart:null,last:null,occurrence_number:0,by_indices:null,initialized:!1,by_data:null,days:null,days_index:0,fromData:function(a){this.rule=ICAL.helpers.formatClassType(a.rule,ICAL.Recur);if(!this.rule)throw Error("iterator requires a (ICAL.Recur) rule");this.dtstart=ICAL.helpers.formatClassType(a.dtstart,ICAL.Time);if(!this.dtstart)throw Error("iterator requires a (ICAL.Time) dtstart");this.by_data=
a.by_data?a.by_data:ICAL.helpers.clone(this.rule.parts,!0);a.occurrence_number&&(this.occurrence_number=a.occurrence_number);this.days=a.days||[];a.last&&(this.last=ICAL.helpers.formatClassType(a.last,ICAL.Time));this.by_indices=a.by_indices;this.by_indices||(this.by_indices={BYSECOND:0,BYMINUTE:0,BYHOUR:0,BYDAY:0,BYMONTH:0,BYWEEKNO:0,BYMONTHDAY:0});(this.initialized=a.initialized||!1)||this.init()},init:function(){this.initialized=!0;this.last=this.dtstart.clone();var a=this.by_data;"BYDAY"in a&&
this.sort_byday_rules(a.BYDAY,this.rule.wkst);if("BYYEARDAY"in a&&("BYMONTH"in a||"BYWEEKNO"in a||"BYMONTHDAY"in a||"BYDAY"in a))throw Error("Invalid BYYEARDAY rule");if("BYWEEKNO"in a&&"BYMONTHDAY"in a)throw Error("BYWEEKNO does not fit to BYMONTHDAY");if("MONTHLY"==this.rule.freq&&("BYYEARDAY"in a||"BYWEEKNO"in a))throw Error("For MONTHLY recurrences neither BYYEARDAY nor BYWEEKNO may appear");if("WEEKLY"==this.rule.freq&&("BYYEARDAY"in a||"BYMONTHDAY"in a))throw Error("For WEEKLY recurrences neither BYMONTHDAY nor BYYEARDAY may appear");
if("YEARLY"!=this.rule.freq&&"BYYEARDAY"in a)throw Error("BYYEARDAY may only appear in YEARLY rules");this.last.second=this.setup_defaults("BYSECOND","SECONDLY",this.dtstart.second);this.last.minute=this.setup_defaults("BYMINUTE","MINUTELY",this.dtstart.minute);this.last.hour=this.setup_defaults("BYHOUR","HOURLY",this.dtstart.hour);this.last.day=this.setup_defaults("BYMONTHDAY","DAILY",this.dtstart.day);this.last.month=this.setup_defaults("BYMONTH","MONTHLY",this.dtstart.month);if("WEEKLY"==this.rule.freq)if("BYDAY"in
a){var c=this.ruleDayOfWeek(a.BYDAY[0]),a=c[0],c=c[1],a=c-this.last.dayOfWeek();if(this.last.dayOfWeek()<c&&0<=a||0>a)this.last.day+=a}else c=ICAL.Recur.numericDayToIcalDay(this.dtstart.dayOfWeek()),a.BYDAY=[c];if("YEARLY"==this.rule.freq){for(;;){this.expand_year_days(this.last.year);if(0<this.days.length)break;this.increment_year(this.rule.interval)}this._nextByYearDay()}if("MONTHLY"==this.rule.freq&&this.has_by_data("BYDAY")){var b=null,d=this.last.clone(),f=ICAL.Time.daysInMonth(this.last.month,
this.last.year),h;for(h in this.by_data.BYDAY)if(this.by_data.BYDAY.hasOwnProperty(h)){this.last=d.clone();var c=this.ruleDayOfWeek(this.by_data.BYDAY[h]),a=c[0],c=c[1],g=this.last.nthWeekDay(c,a);if(6<=a||-6>=a)throw Error("Malformed values in BYDAY part");if(g>f||0>=g){if(b&&b.month==d.month)continue;for(;g>f||0>=g;)this.increment_month(),f=ICAL.Time.daysInMonth(this.last.month,this.last.year),g=this.last.nthWeekDay(c,a)}this.last.day=g;if(!b||0>this.last.compare(b))b=this.last.clone()}this.last=
b.clone();this.has_by_data("BYMONTHDAY")&&this._byDayAndMonthDay(!0);if(this.last.day>f||0==this.last.day)throw Error("Malformed values in BYDAY part");}else this.has_by_data("BYMONTHDAY")&&0>this.last.day&&(f=ICAL.Time.daysInMonth(this.last.month,this.last.year),this.last.day=f+this.last.day+1)},next:function(){var a=this.last?this.last.clone():null;if(this.rule.count&&this.occurrence_number>=this.rule.count||this.rule.until&&0<this.last.compare(this.rule.until))return this.completed=!0,null;if(0==
this.occurrence_number&&0<=this.last.compare(this.dtstart))return this.occurrence_number++,this.last;var c;do switch(c=1,this.rule.freq){case "SECONDLY":this.next_second();break;case "MINUTELY":this.next_minute();break;case "HOURLY":this.next_hour();break;case "DAILY":this.next_day();break;case "WEEKLY":this.next_week();break;case "MONTHLY":c=this.next_month();break;case "YEARLY":this.next_year();break;default:return null}while(!this.check_contracting_rules()||0>this.last.compare(this.dtstart)||!c);
if(0==this.last.compare(a))throw Error("Same occurrence found twice, protecting you from death by recursion");if(this.rule.until&&0<this.last.compare(this.rule.until))return this.completed=!0,null;this.occurrence_number++;return this.last},next_second:function(){return this.next_generic("BYSECOND","SECONDLY","second","minute")},increment_second:function(a){return this.increment_generic(a,"second",60,"minute")},next_minute:function(){return this.next_generic("BYMINUTE","MINUTELY","minute","hour","next_second")},
increment_minute:function(a){return this.increment_generic(a,"minute",60,"hour")},next_hour:function(){return this.next_generic("BYHOUR","HOURLY","hour","monthday","next_minute")},increment_hour:function(a){this.increment_generic(a,"hour",24,"monthday")},next_day:function(){var a="DAILY"==this.rule.freq;if(0==this.next_hour())return 0;a?this.increment_monthday(this.rule.interval):this.increment_monthday(1);return 0},next_week:function(){var a=0;if(0==this.next_weekday_by_week())return a;this.has_by_data("BYWEEKNO")?
(++this.by_indices.BYWEEKNO,this.by_indices.BYWEEKNO==this.by_data.BYWEEKNO.length&&(this.by_indices.BYWEEKNO=0,a=1),this.last.month=1,this.last.day=1,this.last.day+=7*this.by_data.BYWEEKNO[this.by_indices.BYWEEKNO],a&&this.increment_year(1)):this.increment_monthday(7*this.rule.interval);return a},normalizeByMonthDayRules:function(a,c,b){a=ICAL.Time.daysInMonth(c,a);c=[];for(var d=0,f=b.length,h;d<f;d++)if(h=b[d],!(Math.abs(h)>a)){if(0>h)h=a+(h+1);else if(0===h)continue;-1===c.indexOf(h)&&c.push(h)}return c.sort(function(a,
c){return a-c})},_byDayAndMonthDay:function(a){function c(){n=ICAL.Time.daysInMonth(p.last.month,p.last.year);d=p.normalizeByMonthDayRules(p.last.year,p.last.month,p.by_data.BYMONTHDAY);for(l=d.length;d[g]<=q&&(!a||d[g]!=q)&&g<l-1;)g++}function b(){q=0;p.increment_month();g=0;c()}var d,f=this.by_data.BYDAY,h,g=0,l,m=f.length,k=0,n,p=this,q=this.last.day;c();a&&--q;for(var r=48;!k&&r;)if(r--,h=q+1,h>n)b();else{var u=d[g++];if(u>=h){q=u;for(h=0;h<m;h++){var s=this.ruleDayOfWeek(f[h]),u=s[0],s=s[1];
this.last.day=q;if(this.last.isNthWeekDay(s,u)){k=1;break}}k||g!==l||b()}else b()}if(0>=r)throw Error("Malformed values in BYDAY combined with BYMONTHDAY parts");return k},next_month:function(){var a=1;if(0==this.next_hour())return a;if(this.has_by_data("BYDAY")&&this.has_by_data("BYMONTHDAY"))a=this._byDayAndMonthDay();else if(this.has_by_data("BYDAY")){var c=ICAL.Time.daysInMonth(this.last.month,this.last.year),b=0,d=0;if(this.has_by_data("BYSETPOS")){for(var a=this.last.day,f=1;f<=c;f++)this.last.day=
f,this.is_day_in_byday(this.last)&&(d++,f<=a&&b++);this.last.day=a}a=0;for(f=this.last.day+1;f<=c;f++)if(this.last.day=f,this.is_day_in_byday(this.last)&&(!this.has_by_data("BYSETPOS")||this.check_set_position(++b)||this.check_set_position(b-d-1))){a=1;break}if(f>c)if(this.last.day=1,this.increment_month(),this.is_day_in_byday(this.last)){if(!this.has_by_data("BYSETPOS")||this.check_set_position(1))a=1}else a=0}else this.has_by_data("BYMONTHDAY")?(this.by_indices.BYMONTHDAY++,this.by_indices.BYMONTHDAY>=
this.by_data.BYMONTHDAY.length&&(this.by_indices.BYMONTHDAY=0,this.increment_month()),c=ICAL.Time.daysInMonth(this.last.month,this.last.year),f=this.by_data.BYMONTHDAY[this.by_indices.BYMONTHDAY],0>f&&(f=c+f+1),f>c?(this.last.day=1,a=this.is_day_in_byday(this.last)):this.last.day=f):(this.increment_month(),c=ICAL.Time.daysInMonth(this.last.month,this.last.year),this.by_data.BYMONTHDAY[0]>c?a=0:this.last.day=this.by_data.BYMONTHDAY[0]);return a},next_weekday_by_week:function(){var a=0;if(0==this.next_hour())return a;
if(!this.has_by_data("BYDAY"))return 1;for(;;){var c=new ICAL.Time;this.by_indices.BYDAY++;this.by_indices.BYDAY==Object.keys(this.by_data.BYDAY).length&&(this.by_indices.BYDAY=0,a=1);var b=this.ruleDayOfWeek(this.by_data.BYDAY[this.by_indices.BYDAY])[1],b=b-this.rule.wkst;0>b&&(b+=7);c.year=this.last.year;c.month=this.last.month;c.day=this.last.day;c=c.startDoyWeek(this.rule.wkst);if(!(1>b+c)||a)return b=ICAL.Time.fromDayOfYear(c+b,this.last.year),this.last.year=b.year,this.last.month=b.month,this.last.day=
b.day,a}},next_year:function(){if(0==this.next_hour())return 0;if(++this.days_index==this.days.length){this.days_index=0;do this.increment_year(this.rule.interval),this.expand_year_days(this.last.year);while(0==this.days.length)}this._nextByYearDay();return 1},_nextByYearDay:function(){var a=this.days[this.days_index],c=this.last.year;1>a&&(a+=1,c+=1);a=ICAL.Time.fromDayOfYear(a,c);this.last.day=a.day;this.last.month=a.month},ruleDayOfWeek:function(a){if(a=a.match(/([+-]?[0-9])?(MO|TU|WE|TH|FR|SA|SU)/)){var c=
parseInt(a[1]||0,10);a=ICAL.Recur.icalDayToNumericDay(a[2]);return[c,a]}return[0,0]},next_generic:function(a,c,b,d,f){var h=a in this.by_data;c=this.rule.freq==c;var g=0;if(f&&0==this[f]())return g;if(h)this.by_indices[a]++,f=this.by_data[a],this.by_indices[a]==f.length&&(this.by_indices[a]=0,g=1),this.last[b]=f[this.by_indices[a]];else if(c)this["increment_"+b](this.rule.interval);if(h&&g&&c)this["increment_"+d](1);return g},increment_monthday:function(a){for(var c=0;c<a;c++){var b=ICAL.Time.daysInMonth(this.last.month,
this.last.year);this.last.day++;this.last.day>b&&(this.last.day-=b,this.increment_month())}},increment_month:function(){this.last.day=1;if(this.has_by_data("BYMONTH"))this.by_indices.BYMONTH++,this.by_indices.BYMONTH==this.by_data.BYMONTH.length&&(this.by_indices.BYMONTH=0,this.increment_year(1)),this.last.month=this.by_data.BYMONTH[this.by_indices.BYMONTH];else{"MONTHLY"==this.rule.freq?this.last.month+=this.rule.interval:this.last.month++;this.last.month--;var a=ICAL.helpers.trunc(this.last.month/
12);this.last.month%=12;this.last.month++;0!=a&&this.increment_year(a)}},increment_year:function(a){this.last.year+=a},increment_generic:function(a,c,b,d){this.last[c]+=a;a=ICAL.helpers.trunc(this.last[c]/b);this.last[c]%=b;if(0!=a)this["increment_"+d](a)},has_by_data:function(a){return a in this.rule.parts},expand_year_days:function(a){var c=new ICAL.Time;this.days=[];var b={},d=["BYDAY","BYWEEKNO","BYMONTHDAY","BYMONTH","BYYEARDAY"],f;for(f in d)if(d.hasOwnProperty(f)){var h=d[f];h in this.rule.parts&&
(b[h]=this.rule.parts[h])}if("BYMONTH"in b&&"BYWEEKNO"in b){d=1;f={};c.year=a;c.isDate=!0;for(h=0;h<this.by_data.BYMONTH.length;h++){var g=this.by_data.BYMONTH[h];c.month=g;c.day=1;h=c.weekNumber(this.rule.wkst);c.day=ICAL.Time.daysInMonth(g,a);for(g=c.weekNumber(this.rule.wkst);h<g;h++)f[h]=1}for(g=0;g<this.by_data.BYWEEKNO.length&&d;g++)h=this.by_data.BYWEEKNO[g],d=52>h?d&f[g]:0;d?delete b.BYMONTH:delete b.BYWEEKNO}d=Object.keys(b).length;if(0==d)a=this.dtstart.clone(),a.year=this.last.year,this.days.push(a.dayOfYear());
else if(1==d&&"BYMONTH"in b)for(var l in this.by_data.BYMONTH)this.by_data.BYMONTH.hasOwnProperty(l)&&(c=this.dtstart.clone(),c.year=a,c.month=this.by_data.BYMONTH[l],c.isDate=!0,this.days.push(c.dayOfYear()));else if(1==d&&"BYMONTHDAY"in b)for(var m in this.by_data.BYMONTHDAY){if(this.by_data.BYMONTHDAY.hasOwnProperty(m)){l=this.dtstart.clone();var k=this.by_data.BYMONTHDAY[m];if(0>k)var n=ICAL.Time.daysInMonth(l.month,a),k=k+n+1;l.day=k;l.year=a;l.isDate=!0;this.days.push(l.dayOfYear())}}else if(2==
d&&"BYMONTHDAY"in b&&"BYMONTH"in b)for(l in this.by_data.BYMONTH){if(this.by_data.BYMONTH.hasOwnProperty(l))for(m in b=this.by_data.BYMONTH[l],n=ICAL.Time.daysInMonth(b,a),this.by_data.BYMONTHDAY)this.by_data.BYMONTHDAY.hasOwnProperty(m)&&(k=this.by_data.BYMONTHDAY[m],0>k&&(k=k+n+1),c.day=k,c.month=b,c.year=a,c.isDate=!0,this.days.push(c.dayOfYear()))}else if(!(1==d&&"BYWEEKNO"in b||2==d&&"BYWEEKNO"in b&&"BYMONTHDAY"in b))if(1==d&&"BYDAY"in b)this.days=this.days.concat(this.expand_by_day(a));else if(2==
d&&"BYDAY"in b&&"BYMONTH"in b){for(l in this.by_data.BYMONTH)if(this.by_data.BYMONTH.hasOwnProperty(l))if(g=this.by_data.BYMONTH[l],n=ICAL.Time.daysInMonth(g,a),c.year=a,c.month=this.by_data.BYMONTH[l],c.day=1,c.isDate=!0,b=c.dayOfWeek(),m=c.dayOfYear()-1,c.day=n,d=c.dayOfWeek(),this.has_by_data("BYSETPOS")){b=[];for(f=1;f<=n;f++)c.day=f,this.is_day_in_byday(c)&&b.push(f);for(n=0;n<b.length;n++)(this.check_set_position(n+1)||this.check_set_position(n-b.length))&&this.days.push(m+b[n])}else for(k in this.by_data.BYDAY)if(this.by_data.BYDAY.hasOwnProperty(k))if(h=
this.ruleDayOfWeek(this.by_data.BYDAY[k]),f=h[0],g=h[1],h=(g+7-b)%7+1,g=n-(d+7-g)%7,0==f)for(f=h;f<=n;f+=7)this.days.push(m+f);else 0<f?(f=h+7*(f-1),f<=n&&this.days.push(m+f)):(f=g+7*(f+1),0<f&&this.days.push(m+f));this.days.sort(function(a,c){return a-c})}else if(2==d&&"BYDAY"in b&&"BYMONTHDAY"in b)for(n in l=this.expand_by_day(a),l)l.hasOwnProperty(n)&&(f=l[n],c=ICAL.Time.fromDayOfYear(f,a),0<=this.by_data.BYMONTHDAY.indexOf(c.day)&&this.days.push(f));else if(3==d&&"BYDAY"in b&&"BYMONTHDAY"in b&&
"BYMONTH"in b)for(n in l=this.expand_by_day(a),l)l.hasOwnProperty(n)&&(f=l[n],c=ICAL.Time.fromDayOfYear(f,a),0<=this.by_data.BYMONTH.indexOf(c.month)&&0<=this.by_data.BYMONTHDAY.indexOf(c.day)&&this.days.push(f));else if(2==d&&"BYDAY"in b&&"BYWEEKNO"in b)for(n in l=this.expand_by_day(a),l)l.hasOwnProperty(n)&&(f=l[n],c=ICAL.Time.fromDayOfYear(f,a),h=c.weekNumber(this.rule.wkst),this.by_data.BYWEEKNO.indexOf(h)&&this.days.push(f));else 3==d&&"BYDAY"in b&&"BYWEEKNO"in b&&"BYMONTHDAY"in b||(this.days=
1==d&&"BYYEARDAY"in b?this.days.concat(this.by_data.BYYEARDAY):[]);return 0},expand_by_day:function(a){var c=[],b=this.last.clone();b.year=a;b.month=1;b.day=1;b.isDate=!0;a=b.dayOfWeek();b.month=12;b.day=31;b.isDate=!0;var d=b.dayOfWeek(),b=b.dayOfYear(),f;for(f in this.by_data.BYDAY)if(this.by_data.BYDAY.hasOwnProperty(f)){var h=this.ruleDayOfWeek(this.by_data.BYDAY[f]),g=h[0],h=h[1];if(0==g)for(g=(h+7-a)%7+1;g<=b;g+=7)c.push(g);else 0<g?c.push((h>=a?h-a+1:h-a+8)+7*(g-1)):(g=-g,c.push((h<=d?b-d+
h:b-d+h-7)-7*(g-1)))}return c},is_day_in_byday:function(a){for(var c in this.by_data.BYDAY)if(this.by_data.BYDAY.hasOwnProperty(c)){var b=this.ruleDayOfWeek(this.by_data.BYDAY[c]),d=b[0],b=b[1],f=a.dayOfWeek();if(0==d&&b==f||a.nthWeekDay(b,d)==a.day)return 1}return 0},check_set_position:function(a){return this.has_by_data("BYSETPOS")?-1!==this.by_data.BYSETPOS.indexOf(a):!1},sort_byday_rules:function(a,c){for(var b=0;b<a.length;b++)for(var d=0;d<b;d++){var f=this.ruleDayOfWeek(a[d])[1],h=this.ruleDayOfWeek(a[b])[1],
f=f-c,h=h-c;0>f&&(f+=7);0>h&&(h+=7);f>h&&(f=a[b],a[b]=a[d],a[d]=f)}},check_contract_restriction:function(a,c){var e=b._expandMap[this.rule.freq][b._indexMap[a]],d=!1;if(a in this.by_data&&e==b.CONTRACT){var e=this.by_data[a],f;for(f in e)if(e.hasOwnProperty(f)&&e[f]==c){d=!0;break}}else d=!0;return d},check_contracting_rules:function(){var a=this.last.dayOfWeek(),c=this.last.weekNumber(this.rule.wkst),b=this.last.dayOfYear();return this.check_contract_restriction("BYSECOND",this.last.second)&&this.check_contract_restriction("BYMINUTE",
this.last.minute)&&this.check_contract_restriction("BYHOUR",this.last.hour)&&this.check_contract_restriction("BYDAY",ICAL.Recur.numericDayToIcalDay(a))&&this.check_contract_restriction("BYWEEKNO",c)&&this.check_contract_restriction("BYMONTHDAY",this.last.day)&&this.check_contract_restriction("BYMONTH",this.last.month)&&this.check_contract_restriction("BYYEARDAY",b)},setup_defaults:function(a,c,e){return b._expandMap[this.rule.freq][b._indexMap[a]]!=b.CONTRACT&&(a in this.by_data||(this.by_data[a]=
[e]),this.rule.freq!=c)?this.by_data[a][0]:e},toJSON:function(){var a=Object.create(null);a.initialized=this.initialized;a.rule=this.rule.toJSON();a.dtstart=this.dtstart.toJSON();a.by_data=this.by_data;a.days=this.days;a.last=this.last.toJSON();a.by_indices=this.by_indices;a.occurrence_number=this.occurrence_number;return a}};b._indexMap={BYSECOND:0,BYMINUTE:1,BYHOUR:2,BYDAY:3,BYMONTHDAY:4,BYYEARDAY:5,BYWEEKNO:6,BYMONTH:7,BYSETPOS:8};b._expandMap={SECONDLY:[1,1,1,1,1,1,1,1],MINUTELY:[2,1,1,1,1,1,
1,1],HOURLY:[2,2,1,1,1,1,1,1],DAILY:[2,2,2,1,1,1,1,1],WEEKLY:[2,2,2,2,3,3,1,1],MONTHLY:[2,2,2,2,2,3,3,1],YEARLY:[2,2,2,2,2,2,2,2]};b.UNKNOWN=0;b.CONTRACT=1;b.EXPAND=2;b.ILLEGAL=3;return b}();
ICAL.RecurExpansion=function(){function b(a){return ICAL.helpers.formatClassType(a,ICAL.Time)}function a(a,c){return a.compare(c)}function c(a){this.ruleDates=[];this.exDates=[];this.fromData(a)}c.prototype={complete:!1,ruleIterators:null,ruleDates:null,exDates:null,ruleDateInc:0,exDateInc:0,exDate:null,ruleDate:null,dtstart:null,last:null,fromData:function(a){var c=ICAL.helpers.formatClassType(a.dtstart,ICAL.Time);if(c)this.dtstart=c;else throw Error(".dtstart (ICAL.Time) must be given");if(a.component)this._init(a.component);
else{this.last=b(a.last)||c.clone();if(!a.ruleIterators)throw Error(".ruleIterators or .component must be given");this.ruleIterators=a.ruleIterators.map(function(a){return ICAL.helpers.formatClassType(a,ICAL.RecurIterator)});this.ruleDateInc=a.ruleDateInc;this.exDateInc=a.exDateInc;a.ruleDates&&(this.ruleDates=a.ruleDates.map(b),this.ruleDate=this.ruleDates[this.ruleDateInc]);a.exDates&&(this.exDates=a.exDates.map(b),this.exDate=this.exDates[this.exDateInc]);"undefined"!==typeof a.complete&&(this.complete=
a.complete)}},next:function(){for(var a,c,b=0;;){if(500<b++)throw Error("max tries have occured, rule may be impossible to forfill.");c=this.ruleDate;a=this._nextRecurrenceIter(this.last);if(!c&&!a){this.complete=!0;break}if(!c||a&&0<c.compare(a.last))c=a.last.clone(),a.next();this.ruleDate===c&&this._nextRuleDay();this.last=c;if(this.exDate&&(a=this.exDate.compare(this.last),0>a&&this._nextExDay(),0===a)){this._nextExDay();continue}return this.last}},toJSON:function(){function a(c){return c.toJSON()}
var c=Object.create(null);c.ruleIterators=this.ruleIterators.map(a);this.ruleDates&&(c.ruleDates=this.ruleDates.map(a));this.exDates&&(c.exDates=this.exDates.map(a));c.ruleDateInc=this.ruleDateInc;c.exDateInc=this.exDateInc;c.last=this.last.toJSON();c.dtstart=this.dtstart.toJSON();c.complete=this.complete;return c},_extractDates:function(c,b){function f(c){k=ICAL.helpers.binsearchInsert(h,c,a);h.splice(k,0,c)}for(var h=[],g=c.getAllProperties(b),l=g.length,m=0,k;m<l;m++)g[m].getValues().forEach(f);
return h},_init:function(c){this.ruleIterators=[];this.last=this.dtstart.clone();if(c.hasProperty("rdate")||c.hasProperty("rrule")||c.hasProperty("recurrence-id")){c.hasProperty("rdate")&&(this.ruleDates=this._extractDates(c,"rdate"),this.ruleDates[0]&&0>this.ruleDates[0].compare(this.dtstart)?(this.ruleDateInc=0,this.last=this.ruleDates[0].clone()):this.ruleDateInc=ICAL.helpers.binsearchInsert(this.ruleDates,this.last,a),this.ruleDate=this.ruleDates[this.ruleDateInc]);if(c.hasProperty("rrule"))for(var b=
c.getAllProperties("rrule"),f=0,h=b.length,g;f<h;f++)g=b[f].getFirstValue(),g=g.iterator(this.dtstart),this.ruleIterators.push(g),g.next();c.hasProperty("exdate")&&(this.exDates=this._extractDates(c,"exdate"),this.exDateInc=ICAL.helpers.binsearchInsert(this.exDates,this.last,a),this.exDate=this.exDates[this.exDateInc])}else this.ruleDate=this.last.clone(),this.complete=!0},_nextExDay:function(){this.exDate=this.exDates[++this.exDateInc]},_nextRuleDay:function(){this.ruleDate=this.ruleDates[++this.ruleDateInc]},
_nextRecurrenceIter:function(){var a=this.ruleIterators;if(0===a.length)return null;for(var c=a.length,b,h,g=0,l;g<c;g++)if(b=a[g],h=b.last,b.completed)c--,0!==g&&g--,a.splice(g,1);else if(!l||0<l.last.compare(h))l=b;return l}};return c}();
ICAL.Event=function(){function b(a,b){a instanceof ICAL.Component||(b=a,a=null);this.component=a?a:new ICAL.Component("vevent");this._rangeExceptionCache=Object.create(null);this.exceptions=Object.create(null);this.rangeExceptions=[];b&&b.strictExceptions&&(this.strictExceptions=b.strictExceptions);b&&b.exceptions&&b.exceptions.forEach(this.relateException,this)}function a(a,b){return a[0]>b[0]?1:b[0]>a[0]?-1:0}b.prototype={THISANDFUTURE:"THISANDFUTURE",exceptions:null,strictExceptions:!1,relateException:function(c){if(this.isRecurrenceException())throw Error("cannot relate exception to exceptions");
c instanceof ICAL.Component&&(c=new ICAL.Event(c));if(this.strictExceptions&&c.uid!==this.uid)throw Error("attempted to relate unrelated exception");var b=c.recurrenceId.toString();this.exceptions[b]=c;c.modifiesFuture()&&(c=[c.recurrenceId.toUnixTime(),b],b=ICAL.helpers.binsearchInsert(this.rangeExceptions,c,a),this.rangeExceptions.splice(b,0,c))},modifiesFuture:function(){return this.component.getFirstPropertyValue("range")===this.THISANDFUTURE},findRangeException:function(c){if(!this.rangeExceptions.length)return null;
c=c.toUnixTime();var b=ICAL.helpers.binsearchInsert(this.rangeExceptions,[c],a);--b;if(0>b)return null;b=this.rangeExceptions[b];return c<b[0]?null:b[1]},getOccurrenceDetails:function(a){var b=a.toString(),d=a.convertToZone(ICAL.Timezone.utcTimezone).toString(),f={recurrenceId:a};if(b in this.exceptions)a=f.item=this.exceptions[b],f.startDate=a.startDate,f.endDate=a.endDate,f.item=a;else if(d in this.exceptions)a=this.exceptions[d],f.startDate=a.startDate,f.endDate=a.endDate,f.item=a;else if(d=this.findRangeException(a)){b=
this.exceptions[d];f.item=b;var h=this._rangeExceptionCache[d];if(!h){var h=b.recurrenceId.clone(),g=b.startDate.clone();h.zone=g.zone;h=g.subtractDate(h);this._rangeExceptionCache[d]=h}a=a.clone();a.zone=b.startDate.zone;a.addDuration(h);d=a.clone();d.addDuration(b.duration);f.startDate=a;f.endDate=d}else d=a.clone(),d.addDuration(this.duration),f.endDate=d,f.startDate=a,f.item=this;return f},iterator:function(a){return new ICAL.RecurExpansion({component:this.component,dtstart:a||this.startDate})},
isRecurring:function(){var a=this.component;return a.hasProperty("rrule")||a.hasProperty("rdate")},isRecurrenceException:function(){return this.component.hasProperty("recurrence-id")},getRecurrenceTypes:function(){for(var a=this.component.getAllProperties("rrule"),b=0,d=a.length,f=Object.create(null);b<d;b++){var h=a[b].getFirstValue();f[h.freq]=!0}return f},get uid(){return this._firstProp("uid")},set uid(a){this._setProp("uid",a)},get startDate(){return this._firstProp("dtstart")},set startDate(a){this._setTime("dtstart",
a)},get endDate(){var a=this._firstProp("dtend");if(!a){var b=this._firstProp("duration"),a=this.startDate.clone();b?a.addDuration(b):a.isDate&&(a.day+=1)}return a},set endDate(a){this._setTime("dtend",a)},get duration(){var a=this._firstProp("duration");return a?a:this.endDate.subtractDate(this.startDate)},get location(){return this._firstProp("location")},set location(a){return this._setProp("location",a)},get attendees(){return this.component.getAllProperties("attendee")},get summary(){return this._firstProp("summary")},
set summary(a){this._setProp("summary",a)},get description(){return this._firstProp("description")},set description(a){this._setProp("description",a)},get organizer(){return this._firstProp("organizer")},set organizer(a){this._setProp("organizer",a)},get sequence(){return this._firstProp("sequence")},set sequence(a){this._setProp("sequence",a)},get recurrenceId(){return this._firstProp("recurrence-id")},set recurrenceId(a){this._setProp("recurrence-id",a)},_setTime:function(a,b){var d=this.component.getFirstProperty(a);
d||(d=new ICAL.Property(a),this.component.addProperty(d));b.zone===ICAL.Timezone.localTimezone||b.zone===ICAL.Timezone.utcTimezone?d.removeParameter("tzid"):d.setParameter("tzid",b.zone.tzid);d.setValue(b)},_setProp:function(a,b){this.component.updatePropertyWithValue(a,b)},_firstProp:function(a){return this.component.getFirstPropertyValue(a)},toString:function(){return this.component.toString()}};return b}();
ICAL.ComponentParser=function(){function b(a){"undefined"===typeof a&&(a={});for(var b in a)a.hasOwnProperty(b)&&(this[b]=a[b])}b.prototype={parseEvent:!0,parseTimezone:!0,oncomplete:function(){},onerror:function(a){},ontimezone:function(a){},onevent:function(a){},process:function(a){"string"===typeof a&&(a=ICAL.parse(a));a instanceof ICAL.Component||(a=new ICAL.Component(a));a=a.getAllSubcomponents();for(var b=0,e=a.length,d;b<e;b++)switch(d=a[b],d.name){case "vtimezone":if(this.parseTimezone){var f=
d.getFirstPropertyValue("tzid");if(f)this.ontimezone(new ICAL.Timezone({tzid:f,component:d}))}break;case "vevent":if(this.parseEvent)this.onevent(new ICAL.Event(d))}this.oncomplete()}};return b}();