Object.assign(THREE.SEA3D.prototype,{_onHead:THREE.SEA3D.prototype.onHead,_updateTransform:THREE.SEA3D.prototype.updateTransform,_readMorph:THREE.SEA3D.prototype.readMorph,_readVertexAnimation:THREE.SEA3D.prototype.readVertexAnimation,_readGeometryBuffer:THREE.SEA3D.prototype.readGeometryBuffer,_readLine:THREE.SEA3D.prototype.readLine,_getModifier:THREE.SEA3D.prototype.getModifier,_readAnimation:THREE.SEA3D.prototype.readAnimation});
THREE.SEA3D.prototype.isLegacy=function(a){a=a.sea3d;return"S3D"===a.sign?a.config.legacy:!1};THREE.SEA3D.prototype.flipVec3=function(a){if(a){for(var b=2;b<a.length;)a[b]=-a[b],b+=3;return a}};THREE.SEA3D.prototype.addVector=function(a,b){if(a){for(var d=0;d<a.length;d++)a[d]+=b[d];return a}};
THREE.SEA3D.prototype.expandJoints=function(a){for(var b=4*a.numVertex,d=a.isBig?new Uint32Array(b):new Uint16Array(b),b=new Float32Array(b),c=0,k=a.jointPerVertex,h=0;h<a.numVertex;h++){var e=4*h,c=h*k;d[e]=a.joint[c];1<k&&(d[e+1]=a.joint[c+1]);2<k&&(d[e+2]=a.joint[c+2]);3<k&&(d[e+3]=a.joint[c+3]);b[e]=a.weight[c];1<k&&(b[e+1]=a.weight[c+1]);2<k&&(b[e+2]=a.weight[c+2]);3<k&&(b[e+3]=a.weight[c+3]);c=b[e]+b[e+1]+b[e+2]+b[e+3];b[e]+=1-c}a.joint=d;a.weight=b;a.jointPerVertex=4};
THREE.SEA3D.prototype.compressJoints=function(a){for(var b=4*a.numVertex,d=a.isBig?new Uint32Array(b):new Uint16Array(b),b=new Float32Array(b),c=0,k=a.jointPerVertex,h=0;h<a.numVertex;h++){var e=4*h,c=h*k;d[e]=a.joint[c];d[e+1]=a.joint[c+1];d[e+2]=a.joint[c+2];d[e+3]=a.joint[c+3];b[e]=a.weight[c];b[e+1]=a.weight[c+1];b[e+2]=a.weight[c+2];b[e+3]=a.weight[c+3];c=b[e]+b[e+1]+b[e+2]+b[e+3];b[e]+=1-c}a.joint=d;a.weight=b;a.jointPerVertex=4};
THREE.SEA3D.prototype.flipIndexes=function(a){for(var b=1;b<a.length;){var d=a[b+1];a[b+1]=a[b];a[b]=d;b+=3}return a};THREE.SEA3D.prototype.flipBoneMatrix=function(){var a=new THREE.Vector3;return function(b){var d=THREE.SEA3D.VECBUF.setFromMatrixPosition(b);d.z=-d.z;b.setPosition(a);b.multiplyMatrices(THREE.SEA3D.MTXBUF.makeRotationZ(THREE.Math.degToRad(180)),b);b.setPosition(d);return b}}();
THREE.SEA3D.prototype.flipScaleMatrix=function(){var a=new THREE.Vector3,b=new THREE.Quaternion,d=new THREE.Vector3;return function(c,k,h,e){h&&c.multiplyMatrices(h,c);c.decompose(a,b,d);d.z=-d.z;c.compose(a,b,d);k&&c.multiplyMatrices(c,THREE.SEA3D.MTXBUF.makeRotationZ(THREE.Math.degToRad(180)));h&&(h=h.clone(),this.flipScaleMatrix(h,e),c.multiplyMatrices(h.getInverse(h),c));return c}}();
THREE.SEA3D.prototype.flipDefaultAnimation=function(){var a=new THREE.Matrix4,b=new THREE.Matrix4,d=new THREE.Vector3,c=new THREE.Quaternion,k=new THREE.Vector3,h=new THREE.Vector3,e=new THREE.Quaternion,q=new THREE.Vector3;return function(r,l,m){if(!r.isFliped){for(var v=r.dataList,n=[],u=0;u<v.length;u++){var t=v[u],g=t.data,f=t.kind,t=g.length/t.blockSize;switch(f){case SEA3D.Animation.POSITION:case SEA3D.Animation.ROTATION:case SEA3D.Animation.SCALE:n.push({kind:f,numFrames:t,raw:g})}}if(0<n.length)for(t=
n[0].numFrames,g=void 0,m?(a.identity(),this.flipScaleMatrix(b.copy(l.matrixWorld))):(l.parent&&(g=this.flipScaleMatrix(b.copy(l.parent.matrixWorld))),this.flipScaleMatrix(a.copy(l.matrix),!1,g)),a.decompose(d,c,k),l=0;l<t;l++){for(m=0;m<n.length;m++)switch(g=n[m].raw,f=n[m].kind,f){case SEA3D.Animation.POSITION:f=3*l;d.set(g[f],g[f+1],g[f+2]);break;case SEA3D.Animation.ROTATION:f=4*l;c.set(g[f],g[f+1],g[f+2],g[f+3]);break;case SEA3D.Animation.SCALE:f=4*l,k.set(g[f],g[f+1],g[f+2])}a.compose(d,c,k);
this.flipScaleMatrix(a,!1,b);a.decompose(h,e,q);for(m=0;m<n.length;m++)switch(g=n[m].raw,f=n[m].kind,f){case SEA3D.Animation.POSITION:f=3*l;g[f]=h.x;g[f+1]=h.y;g[f+2]=h.z;break;case SEA3D.Animation.ROTATION:f=4*l;g[f]=e.x;g[f+1]=e.y;g[f+2]=e.z;g[f+3]=e.w;break;case SEA3D.Animation.SCALE:f=3*l,g[f]=q.x,g[f+1]=q.y,g[f+2]=q.z}}r.isFliped=!0}}}();THREE.SEA3D.prototype.readAnimation=function(a){this.isLegacy(a)||this._readAnimation(a)};
THREE.SEA3D.prototype.getModifier=function(a){var b=a.sea;if(this.isLegacy(b)&&!b.done)switch(b.done=!0,b.type){case SEA3D.SkeletonAnimation.prototype.type:return this.readSkeletonAnimationLegacy(b,a.skeleton),b.tag;case SEA3D.Animation.prototype.type:case SEA3D.MorphAnimation.prototype.type:case SEA3D.UVWAnimation.prototype.type:return a.scope instanceof THREE.Object3D&&this.flipDefaultAnimation(b,a.scope,a.relative),this._readAnimation(b),b.tag;case SEA3D.Morph.prototype.type:this.readMorphLegacy(b,
a.geometry)}return this._getModifier(a)};
THREE.SEA3D.prototype.updateTransform=function(){var a=new THREE.Matrix4,b=new THREE.Matrix4;return function(d,c){this.isLegacy(c)?(c.transform?a.fromArray(c.transform):a.makeTranslation(c.position.x,c.position.y,c.position.z),this.flipScaleMatrix(a,!1,d.parent?d.parent.matrixWorld:b,d.parent instanceof THREE.Bone),d.position.setFromMatrixPosition(a),d.scale.setFromMatrixScale(a),a.scale(THREE.SEA3D.VECBUF.set(1/d.scale.x,1/d.scale.y,1/d.scale.z)),d.rotation.setFromRotationMatrix(a),d.updateMatrixWorld()):
this._updateTransform(d,c)}}();
THREE.SEA3D.prototype.readSkeleton=function(){var a=new THREE.Matrix4,b=new THREE.Matrix4,d=new THREE.Matrix4,c=new THREE.Vector3,k=new THREE.Quaternion;return function(h){for(var e=[],q=h.sea3d.config.legacy,r=0;r<h.joint.length;r++){var l=h.joint[r];a.fromArray(l.inverseBindMatrix);b.getInverse(a);q&&this.flipBoneMatrix(b);-1<l.parentIndex&&(a.fromArray(h.joint[l.parentIndex].inverseBindMatrix),d.getInverse(a),q&&this.flipBoneMatrix(d),d.getInverse(d),b.multiplyMatrices(d,b));c.setFromMatrixPosition(b);
k.setFromRotationMatrix(b);e[r]={name:l.name,pos:[c.x,c.y,c.z],rotq:[k.x,k.y,k.z,k.w],parent:l.parentIndex}}this.domain.bones=this.bones=this.bones||[];this.bones.push(this.objects[h.name+".sklq"]=h.tag=e);return e}}();
THREE.SEA3D.prototype.readSkeletonAnimationLegacy=function(){var a=new THREE.Matrix4,b=new THREE.Matrix4,d=new THREE.Matrix4,c=new THREE.Matrix4;return function(k,h){if(k.tag)return k.tag;for(var e=[],q=1E3/k.frameRate/1E3,r=[1,1,1],l=0;l<k.sequence.length;l++){for(var m=k.sequence[l],v=m.start,n=v+m.count,u={name:m.name,repeat:m.repeat,fps:k.frameRate,JIT:0,length:q*m.count,hierarchy:[]},t=k.numJoints,g=k.raw,f=0;f<t;f++){for(var x=h.joint[f],A={parent:x.parentIndex,keys:[]},B=A.keys,y=0,z=v;z<n;z++){var p=
z*t*7+7*f;b.makeRotationFromQuaternion(THREE.SEA3D.QUABUF.set(g[p+3],g[p+4],g[p+5],g[p+6]));b.setPosition(THREE.SEA3D.VECBUF.set(g[p],g[p+1],g[p+2]));-1<x.parentIndex?(a.fromArray(h.joint[x.parentIndex].inverseBindMatrix),c.getInverse(a),d.multiplyMatrices(c,b),this.flipBoneMatrix(d),this.flipBoneMatrix(c),c.getInverse(c),b.multiplyMatrices(c,d)):this.flipBoneMatrix(b);var p=THREE.SEA3D.VECBUF.setFromMatrixPosition(b),w=THREE.SEA3D.QUABUF.setFromRotationMatrix(b);B.push({time:y,pos:[p.x,p.y,p.z],
rot:[w.x,w.y,w.z,w.w],scl:r});y+=q}u.hierarchy[f]=A}e.push(THREE.SEA3D.AnimationClip.fromClip(THREE.AnimationClip.parseAnimation(u,h.tag),m.repeat))}this.domain.clips=this.clips=this.clips||[];this.clips.push(this.objects[k.name+".anm"]=k.tag=e)}}();THREE.SEA3D.prototype.readMorphLegacy=function(a,b){for(var d=0;d<a.node.length;d++){var c=a.node[d];this.flipVec3(c.vertex);this.flipVec3(c.normal);this.addVector(c.vertex,b.vertex);this.addVector(c.normal,b.normal)}this._readMorph(a)};
THREE.SEA3D.prototype.readMorph=function(a){this.isLegacy(a)||this._readMorph(a)};THREE.SEA3D.prototype.readVertexAnimation=function(a){if(this.isLegacy(a))for(var b=0,d=a.frame.length;b<d;b++){var c=a.frame[b];this.flipVec3(c.vertex);this.flipVec3(c.normal)}this._readVertexAnimation(a)};
THREE.SEA3D.prototype.readGeometryBuffer=function(a){this.isLegacy(a)&&(this.flipVec3(a.vertex),this.flipVec3(a.normal),this.flipIndexes(a.indexes),4<a.jointPerVertex?this.compressJoints(a):4>a.jointPerVertex&&this.expandJoints(a));this._readGeometryBuffer(a)};THREE.SEA3D.prototype.readLines=function(a){this.isLegacy(a)&&this.flipVec3(a.vertex);this._readLines(a)};THREE.SEA3D.prototype.onHead=function(a){if("S3D"!=a.sign&&"TJS"!=a.sign)throw Error("Sign '"+a.sign+"' unknown.");};
THREE.SEA3D.EXTENSIONS_LOADER.push({setTypeRead:function(){this.config.legacy=void 0==this.config.legacy?!0:this.config.legacy;this.file.typeRead[SEA3D.Skeleton.prototype.type]=this.readSkeleton}});