THREE.SEA3D=function(a){this.config={id:"",scripts:!0,runScripts:!0,autoPlay:!1,dummys:!0,multiplier:1,bounding:!0,audioRolloffFactor:10,lights:!0,useEnvironment:!0,useVertexTexture:!0,forceStatic:!1,streaming:!0,async:!0,paths:{},timeLimit:10};a&&this.loadConfig(a)};void 0===THREE.Float32BufferAttribute&&(THREE.Float32BufferAttribute=THREE.Float32Attribute);THREE.SEA3D.useMultiMaterial=THREE.MultiMaterial.prototype.isMultiMaterial;THREE.SEA3D.MTXBUF=new THREE.Matrix4;THREE.SEA3D.VECBUF=new THREE.Vector3;
THREE.SEA3D.QUABUF=new THREE.Quaternion;THREE.SEA3D.BACKGROUND_COLOR=3355443;THREE.SEA3D.HELPER_COLOR=10140133;THREE.SEA3D.RTT_SIZE=512;THREE.SEA3D.identityMatrixScale=function(){var a=new THREE.Vector3;return function(b){a.setFromMatrixScale(b);return b.scale(a.set(1/a.x,1/a.y,1/a.z))}}();
THREE.SEA3D.prototype=Object.assign(Object.create(THREE.EventDispatcher.prototype),{constructor:THREE.SEA3D,setShadowMap:function(a){a.shadow.mapSize.width=2048;a.shadow.mapSize.height=1024;a.castShadow=!0;a.shadow.camera.left=-200;a.shadow.camera.right=200;a.shadow.camera.top=200;a.shadow.camera.bottom=-200;a.shadow.camera.near=1;a.shadow.camera.far=3E3;a.shadow.camera.fov=45;a.shadow.bias=-.001}});
Object.defineProperties(THREE.SEA3D.prototype,{container:{set:function(a){this.config.container=a},get:function(){return this.config.container}},elapsedTime:{get:function(){return this.file.timer.elapsedTime}}});THREE.SEA3D.Domain=function(a,b,c){this.id=a;this.objects=b;this.container=c;this.sources=[];this.local={};this.scriptTargets=[];this.events=new THREE.EventDispatcher};THREE.SEA3D.Domain.global={};
THREE.SEA3D.Domain.prototype=Object.assign(Object.create(THREE.EventDispatcher.prototype),{constructor:THREE.SEA3D.Domain,add:function(a){this.sources.push(a)},remove:function(a){this.sources.splice(this.sources.indexOf(a),1)},contains:function(a){return-1!=this.sources.indexOf(a)},addEventListener:function(a,b){this.events.addEventListener(a,b)},hasEventListener:function(a,b){return this.events.hasEventListener(a,b)},removeEventListener:function(a,b){this.events.removeEventListener(a,b)},print:function(){console.log.apply(console,
arguments)},watch:function(){console.log.apply(console,"watch:",arguments)},runScripts:function(){for(var a=0;a<this.scriptTargets.length;a++)this.runJSMList(this.scriptTargets[a])},runJSMList:function(a){for(var b=a.scripts,c=0;c<b.length;c++)this.runJSM(a,b[c]);return b},runJSM:function(a,b){var c={print:this.print,watch:this.watch,sea3d:this,scene:this.container,source:new THREE.SEA3D.ScriptDomain(this,a instanceof THREE.SEA3D.Domain)};Object.freeze(c.source);THREE.SEA3D.ScriptHandler.add(c.source);
try{this.methods[b.method](c,this.getReference,THREE.SEA3D.Domain.global,this.local,a,b.params)}catch(d){console.error('SEA3D JavaScript: Error running method "'+b.method+'".'),console.error(d)}},getReference:function(a){return eval(a)},disposeList:function(a){if(a&&a.length){a=a.concat();for(var b=a.length;b--;)a[b].dispose()}},dispatchEvent:function(a){a.domain=this;for(var b=this.sources.concat(),c=b.length;c--;)b[c].dispatchEvent(a);this.events.dispatchEvent(a)},dispose:function(){for(this.disposeList(this.sources);this.container.children.length;)this.container.remove(this.container.children[0]);
for(var a=THREE.SEA3D.EXTENSIONS_DOMAIN.length;a--;){var b=THREE.SEA3D.EXTENSIONS_DOMAIN[a];b.dispose&&b.dispose.call(this)}this.disposeList(this.materials);this.disposeList(this.dummys);this.dispatchEvent({type:"dispose"})}});THREE.SEA3D.DomainManager=function(a){this.domains=[];this.autoDisposeRootDomain=void 0!==a?a:!0};
Object.assign(THREE.SEA3D.DomainManager.prototype,{onDisposeDomain:function(a){this.remove(a.domain);this.autoDisposeRootDomain&&1==this.domains.length&&this.dispose()},add:function(a){this._onDisposeDomain=this._onDisposeDomain||this.onDisposeDomain.bind(this);a.on("dispose",this._onDisposeDomain);this.domains.push(a);this.textures=this.textures||a.textures;this.cubemaps=this.cubemaps||a.cubemaps;this.geometries=this.geometries||a.geometries},remove:function(a){a.removeEvent("dispose",this._onDisposeDomain);
this.domains.splice(this.domains.indexOf(a),1)},contains:function(a){return-1!=this.domains.indexOf(a)},disposeList:function(a){if(a&&a.length){a=a.concat();for(var b=a.length;b--;)a[b].dispose()}},dispose:function(){this.disposeList(this.domains);this.disposeList(this.textures);this.disposeList(this.cubemaps);this.disposeList(this.geometries)}});
THREE.SEA3D.ScriptDomain=function(a,b){a=a||new THREE.SEA3D.Domain;a.add(this);var c=new THREE.EventDispatcher;this.getId=function(){return a.id};this.isRoot=function(){return b};this.addEventListener=function(a,b){c.addEventListener(a,b)};this.hasEventListener=function(a,b){return c.hasEventListener(a,b)};this.removeEventListener=function(a,b){c.removeEventListener(a,b)};this.dispatchEvent=function(a){a.script=this;c.dispatchEvent(a)};this.dispose=function(){a.remove(this);b&&a.dispose();this.dispatchEvent({type:"dispose"})}};
THREE.SEA3D.ScriptManager=function(){this.scripts=[];var a=function(a){this.remove(a.script)}.bind(this);this.add=function(b){b.addEventListener("dispose",a);this.scripts.push(b)};this.remove=function(b){b.removeEventListener("dispose",a);this.scripts.splice(this.scripts.indexOf(b),1)};this.contains=function(a){return-1<this.scripts.indexOf(a)};this.dispatchEvent=function(a){for(var c=this.scripts.concat(),d=c.length;d--;)c[d].dispatchEvent(a)}};THREE.SEA3D.ScriptHandler=new THREE.SEA3D.ScriptManager;
THREE.SEA3D.ScriptHandler.dispatchUpdate=function(a){this.dispatchEvent({type:"update",delta:a})};THREE.SEA3D.AnimationClip=function(a,b,c,d){THREE.AnimationClip.call(this,a,b,c);this.repeat=void 0!==d?d:!0};THREE.SEA3D.AnimationClip.fromClip=function(a,b){return new THREE.SEA3D.AnimationClip(a.name,a.duration,a.tracks,b)};THREE.SEA3D.AnimationClip.prototype=Object.assign(Object.create(THREE.AnimationClip.prototype),{constructor:THREE.SEA3D.AnimationClip});
THREE.SEA3D.Animation=function(a,b){this.clip=a;this.timeScale=void 0!==b?b:1};THREE.SEA3D.Animation.COMPLETE="animationComplete";THREE.SEA3D.Animation.prototype=Object.assign(Object.create(THREE.EventDispatcher.prototype),{constructor:THREE.SEA3D.Animation,onComplete:function(a){this.dispatchEvent({type:THREE.SEA3D.Animation.COMPLETE,target:this})}});
Object.defineProperties(THREE.SEA3D.Animation.prototype,{name:{get:function(){return this.clip.name}},repeat:{get:function(){return this.clip.repeat}},duration:{get:function(){return this.clip.duration}},mixer:{set:function(a){this.mx&&(this.mx.uncacheClip(this.clip),delete this.mx);a&&(this.mx=a,this.mx.clipAction(this.clip))},get:function(){return this.mx}}});THREE.SEA3D.Animator=function(a,b){this.updateAnimations(a,b);this.clone=function(a){return(new this.constructor(this.clips,new THREE.AnimationMixer(a))).copyFrom(this)}.bind(this)};
Object.assign(THREE.SEA3D.Animator.prototype,{update:function(a){this.mixer.update(a||0);if(this.currentAnimationAction&&this.currentAnimationAction.paused&&(this.pause(),this.currentAnimation))this.currentAnimation.onComplete(this);return this},updateAnimations:function(a,b){this.playing&&this.stop();this.mixer&&THREE.SEA3D.AnimationHandler.remove(this);this.mixer=b;this.paused=this.playing=this.relative=!1;this.timeScale=1;this.animations=[];this.animation={};this.clips=[];if(a)for(var c=0;c<a.length;c++)this.addAnimation(a[c]);
return this},addAnimation:function(a){a instanceof THREE.AnimationClip&&(this.clips.push(a),a=new THREE.SEA3D.Animation(a));this.animations.push(a);this.animation[a.name]=a;a.mixer=this.mixer;return a},removeAnimation:function(a){a instanceof THREE.AnimationClip&&(a=this.getAnimationByClip(a));this.clips.splice(this.clips.indexOf(a.clip),1);delete this.animation[a.name];this.animations.splice(this.animations.indexOf(a),1);a.mixer=null;return a},getAnimationByClip:function(a){for(var b=0;b<this.animations.length;b++)if(this.animations[b].clip===
a)return a},getAnimationByName:function(a){return"number"===typeof a?this.animations[a]:this.animation[a]},setAnimationWeight:function(a,b){this.mixer.clipAction(this.getAnimationByName(a).clip).setEffectiveWeight(b)},getAnimationWeight:function(a){return this.mixer.clipAction(this.getAnimationByName(a).clip).getEffectiveWeight()},pause:function(){this.playing&&this.currentAnimation&&(THREE.SEA3D.AnimationHandler.remove(this),this.playing=!1);return this},resume:function(){!this.playing&&this.currentAnimation&&
(THREE.SEA3D.AnimationHandler.add(this),this.playing=!0);return this},setTimeScale:function(a){this.timeScale=a;this.currentAnimationAction&&this.updateTimeScale();return this},getTimeScale:function(){return this.timeScale},updateTimeScale:function(){this.currentAnimationAction.setEffectiveTimeScale(this.timeScale*(this.currentAnimation?this.currentAnimation.timeScale:1));return this},play:function(a,b,c,d){var e=this.getAnimationByName(a);if(!e)throw Error('Animation "'+a+'" not found.');if(e==this.currentAnimation)return void 0===
c&&e.repeat||(this.currentAnimationAction.time=void 0!==c?c:0<=this.currentAnimationAction.timeScale?0:this.currentAnimation.duration),this.currentAnimationAction.setEffectiveWeight(void 0!==d?d:1),this.currentAnimationAction.paused=!1,this.resume();this.previousAnimation=this.currentAnimation;this.currentAnimation=e;this.previousAnimationAction=this.currentAnimationAction;this.currentAnimationAction=this.mixer.clipAction(e.clip).setLoop(e.repeat?THREE.LoopRepeat:THREE.LoopOnce,Infinity).reset();
this.currentAnimationAction.clampWhenFinished=!e.repeat;this.currentAnimationAction.paused=!1;this.updateTimeScale();void 0===c&&e.repeat||(this.currentAnimationAction.time=void 0!==c?c:0<=this.currentAnimationAction.timeScale?0:this.currentAnimation.duration);this.currentAnimationAction.setEffectiveWeight(void 0!==d?d:1);this.currentAnimationAction.play();this.playing||this.mixer.update(0);this.playing=!0;this.previousAnimation&&this.previousAnimationAction.crossFadeTo(this.currentAnimationAction,
b||0,!1);THREE.SEA3D.AnimationHandler.add(this);return this},stop:function(){this.playing&&THREE.SEA3D.AnimationHandler.remove(this);this.currentAnimation&&(this.currentAnimationAction.stop(),this.previousAnimation=this.currentAnimation,this.previousAnimationAction=this.currentAnimationAction,delete this.currentAnimationAction,delete this.currentAnimation,this.playing=!1);return this},playw:function(a,b){this.playing||this.paused||THREE.SEA3D.AnimationHandler.add(this);var c=this.getAnimationByName(a);
this.playing=!0;var d=this.mixer.clipAction(c.clip);d.setLoop(c.repeat?THREE.LoopRepeat:THREE.LoopOnce,Infinity).reset();d.clampWhenFinished=!c.repeat;d.paused=!1;d.setEffectiveWeight(b).play();return d},crossFade:function(a,b,c,d){this.mixer.stopAllAction();a=this.playw(a,1);b=this.playw(b,1);a.crossFadeTo(b,c,void 0!==d?d:!1);return this},stopAll:function(){this.stop().mixer.stopAllAction();this.playing=!1;return this},unPauseAll:function(){this.mixer.timeScale=1;this.playing=!0;this.paused=!1;
return this},pauseAll:function(){this.mixer.timeScale=0;this.playing=!1;this.paused=!0;return this},setRelative:function(a){if(this.relative!=a)return this.stop(),this.relative=a,this},getRelative:function(){return this.relative},copyFrom:function(a){for(var b=0;b<this.animations.length;b++)this.animations[b].timeScale=a.animations[b].timeScale;return this}});
THREE.SEA3D.Object3DAnimator=function(a,b){this.object3d=b;THREE.SEA3D.Animator.call(this,a,new THREE.AnimationMixer(b));this.clone=function(a){return(new this.constructor(this.clips,a)).copyFrom(this)}.bind(this)};
THREE.SEA3D.Object3DAnimator.prototype=Object.assign(Object.create(THREE.SEA3D.Animator.prototype),{constructor:THREE.SEA3D.Object3DAnimator,stop:function(){if(this.currentAnimation){var a=this.object3d.animate;a&&this instanceof THREE.SEA3D.Object3DAnimator&&(a.position.set(0,0,0),a.quaternion.set(0,0,0,1),a.scale.set(1,1,1))}THREE.SEA3D.Animator.prototype.stop.call(this)},setRelative:function(a){THREE.SEA3D.Animator.prototype.setRelative.call(this,a);this.object3d.setAnimator(this.relative);this.updateAnimations(this.clips,
new THREE.AnimationMixer(this.relative?this.object3d.animate:this.object3d))}});THREE.SEA3D.CameraAnimator=function(a,b){THREE.SEA3D.Object3DAnimator.call(this,a,b)};THREE.SEA3D.CameraAnimator.prototype=Object.assign(Object.create(THREE.SEA3D.Object3DAnimator.prototype),{constructor:THREE.SEA3D.CameraAnimator});THREE.SEA3D.SoundAnimator=function(a,b){THREE.SEA3D.Object3DAnimator.call(this,a,b)};
THREE.SEA3D.SoundAnimator.prototype=Object.assign(Object.create(THREE.SEA3D.Object3DAnimator.prototype),{constructor:THREE.SEA3D.SoundAnimator});THREE.SEA3D.LightAnimator=function(a,b){THREE.SEA3D.Object3DAnimator.call(this,a,b)};THREE.SEA3D.LightAnimator.prototype=Object.assign(Object.create(THREE.SEA3D.Object3DAnimator.prototype),{constructor:THREE.SEA3D.LightAnimator});THREE.SEA3D.Object3D=function(){THREE.Object3D.call(this)};
THREE.SEA3D.Object3D.prototype=Object.assign(Object.create(THREE.Object3D.prototype),{constructor:THREE.SEA3D.Object3D,updateAnimateMatrix:function(a){!0===this.matrixAutoUpdate&&this.updateMatrix();if(!0===this.matrixWorldNeedsUpdate||!0===a)null===this.parent?this.matrixWorld.copy(this.matrix):this.matrixWorld.multiplyMatrices(this.parent.matrixWorld,this.matrix),this.animate.updateMatrix(),this.matrixWorld.multiplyMatrices(this.matrixWorld,this.animate.matrix),this.matrixWorldNeedsUpdate=!1,a=
!0;for(var b=0,c=this.children.length;b<c;b++)this.children[b].updateMatrixWorld(a)},setAnimator:function(a){this.getAnimator()!=a&&(a?(this.animate=new THREE.Object3D,this.updateMatrixWorld=THREE.SEA3D.Object3D.prototype.updateAnimateMatrix):(delete this.animate,this.updateMatrixWorld=THREE.Object3D.prototype.updateMatrixWorld),this.matrixWorldNeedsUpdate=!0)},getAnimator:function(){return void 0!=this.animate},copy:function(a){THREE.Object3D.prototype.copy.call(this,a);this.attribs=a.attribs;this.scripts=
a.scripts;a.animator&&(this.animator=a.animator.clone(this));return this}});THREE.SEA3D.Dummy=function(a,b,c){this.width=void 0!=a?a:100;this.height=void 0!=b?b:100;this.depth=void 0!=c?c:100;a=new THREE.BoxGeometry(this.width,this.height,this.depth,1,1,1);a.computeBoundingBox();a.computeBoundingSphere();THREE.Mesh.call(this,a,THREE.SEA3D.Dummy.MATERIAL)};THREE.SEA3D.Dummy.MATERIAL=new THREE.MeshBasicMaterial({wireframe:!0,color:THREE.SEA3D.HELPER_COLOR});
THREE.SEA3D.Dummy.prototype=Object.assign(Object.create(THREE.Mesh.prototype),THREE.SEA3D.Object3D.prototype,{constructor:THREE.SEA3D.Dummy,copy:function(a){THREE.Mesh.prototype.copy.call(this,a);this.attribs=a.attribs;this.scripts=a.scripts;a.animator&&(this.animator=a.animator.clone(this));return this},dispose:function(){this.geometry.dispose()}});THREE.SEA3D.Mesh=function(a,b){THREE.Mesh.call(this,a,b)};
THREE.SEA3D.Mesh.prototype=Object.assign(Object.create(THREE.Mesh.prototype),THREE.SEA3D.Object3D.prototype,{constructor:THREE.SEA3D.Mesh,setWeight:function(a,b){this.morphTargetInfluences["number"===typeof a?a:this.morphTargetDictionary[a]]=b},getWeight:function(a){return this.morphTargetInfluences["number"===typeof a?a:this.morphTargetDictionary[a]]},copy:function(a){THREE.Mesh.prototype.copy.call(this,a);this.attribs=a.attribs;this.scripts=a.scripts;a.animator&&(this.animator=a.animator.clone(this));
return this}});THREE.SEA3D.SkinnedMesh=function(a,b,c){THREE.SkinnedMesh.call(this,a,b,c);this.updateAnimations(a.animations,new THREE.AnimationMixer(this))};
THREE.SEA3D.SkinnedMesh.prototype=Object.assign(Object.create(THREE.SkinnedMesh.prototype),THREE.SEA3D.Mesh.prototype,THREE.SEA3D.Animator.prototype,{constructor:THREE.SEA3D.SkinnedMesh,boneByName:function(a){for(var b=this.skeleton.bones,c=0,d=b.length;c<d;c++)if(a==b[c].name)return b[c]},copy:function(a){THREE.SkinnedMesh.prototype.copy.call(this,a);this.attribs=a.attribs;this.scripts=a.scripts;a.animator&&(this.animator=a.animator.clone(this));return this}});
THREE.SEA3D.VertexAnimationMesh=function(a,b){THREE.Mesh.call(this,a,b);this.type="MorphAnimMesh";this.updateAnimations(a.animations,new THREE.AnimationMixer(this))};
THREE.SEA3D.VertexAnimationMesh.prototype=Object.assign(Object.create(THREE.Mesh.prototype),THREE.SEA3D.Mesh.prototype,THREE.SEA3D.Animator.prototype,{constructor:THREE.SEA3D.VertexAnimationMesh,copy:function(a){THREE.Mesh.prototype.copy.call(this,a);this.attribs=a.attribs;this.scripts=a.scripts;a.animator&&(this.animator=a.animator.clone(this));return this}});THREE.SEA3D.Camera=function(a,b,c,d){THREE.PerspectiveCamera.call(this,a,b,c,d)};
THREE.SEA3D.Camera.prototype=Object.assign(Object.create(THREE.PerspectiveCamera.prototype),THREE.SEA3D.Object3D.prototype,{constructor:THREE.SEA3D.Camera,copy:function(a){THREE.PerspectiveCamera.prototype.copy.call(this,a);this.attribs=a.attribs;this.scripts=a.scripts;a.animator&&(this.animator=a.animator.clone(this));return this}});THREE.SEA3D.OrthographicCamera=function(a,b,c,d,e,f){THREE.OrthographicCamera.call(this,a,b,c,d,e,f)};
THREE.SEA3D.OrthographicCamera.prototype=Object.assign(Object.create(THREE.OrthographicCamera.prototype),THREE.SEA3D.Object3D.prototype,{constructor:THREE.SEA3D.OrthographicCamera,copy:function(a){THREE.OrthographicCamera.prototype.copy.call(this,a);this.attribs=a.attribs;this.scripts=a.scripts;a.animator&&(this.animator=a.animator.clone(this));return this}});THREE.SEA3D.PointLight=function(a,b,c,d){THREE.PointLight.call(this,a,b,c,d)};
THREE.SEA3D.PointLight.prototype=Object.assign(Object.create(THREE.PointLight.prototype),THREE.SEA3D.Object3D.prototype,{constructor:THREE.SEA3D.PointLight,copy:function(a){THREE.PointLight.prototype.copy.call(this,a);this.attribs=a.attribs;this.scripts=a.scripts;a.animator&&(this.animator=a.animator.clone(this));return this}});THREE.SEA3D.PointSound=function(a,b){THREE.PositionalAudio.call(this,a);this.setSound(b)};
THREE.SEA3D.PointSound.prototype=Object.assign(Object.create(THREE.PositionalAudio.prototype),THREE.SEA3D.Object3D.prototype,{constructor:THREE.SEA3D.PointSound,setSound:function(a){(this.sound=a)&&(a.buffer?this.setBuffer(a.buffer):a.addEventListener("complete",function(b){this.setBuffer(a.buffer)}.bind(this)));return this},copy:function(a){THREE.PositionalAudio.prototype.copy.call(this,a);this.attribs=a.attribs;this.scripts=a.scripts;a.animator&&(this.animator=a.animator.clone(this));return this}});
THREE.SEA3D.AnimationHandler={animators:[],update:function(a){for(var b=0;b<this.animators.length;)this.animators[b++].update(a)},add:function(a){-1===this.animators.indexOf(a)&&this.animators.push(a)},remove:function(a){a=this.animators.indexOf(a);-1!==a&&this.animators.splice(a,1)}};THREE.SEA3D.Sound=function(a){this.uuid=THREE.Math.generateUUID();this.src=a;(new THREE.AudioLoader).load(a,function(a){this.buffer=a;this.dispatchEvent({type:"complete"})}.bind(this))};
THREE.SEA3D.Sound.prototype=Object.assign(Object.create(THREE.EventDispatcher.prototype),{constructor:THREE.SEA3D.Sound});THREE.SEA3D.Domain.prototype.getMesh=THREE.SEA3D.prototype.getMesh=function(a){return this.objects["m3d/"+a]};THREE.SEA3D.Domain.prototype.getDummy=THREE.SEA3D.prototype.getDummy=function(a){return this.objects["dmy/"+a]};THREE.SEA3D.Domain.prototype.getLine=THREE.SEA3D.prototype.getLine=function(a){return this.objects["line/"+a]};
THREE.SEA3D.Domain.prototype.getSound3D=THREE.SEA3D.prototype.getSound3D=function(a){return this.objects["sn3d/"+a]};THREE.SEA3D.Domain.prototype.getMaterial=THREE.SEA3D.prototype.getMaterial=function(a){return this.objects["mat/"+a]};THREE.SEA3D.Domain.prototype.getLight=THREE.SEA3D.prototype.getLight=function(a){return this.objects["lht/"+a]};THREE.SEA3D.Domain.prototype.getGLSL=THREE.SEA3D.prototype.getGLSL=function(a){return this.objects["glsl/"+a]};
THREE.SEA3D.Domain.prototype.getCamera=THREE.SEA3D.prototype.getCamera=function(a){return this.objects["cam/"+a]};THREE.SEA3D.Domain.prototype.getTexture=THREE.SEA3D.prototype.getTexture=function(a){return this.objects["tex/"+a]};THREE.SEA3D.Domain.prototype.getCubeMap=THREE.SEA3D.prototype.getCubeMap=function(a){return this.objects["cmap/"+a]};THREE.SEA3D.Domain.prototype.getJointObject=THREE.SEA3D.prototype.getJointObject=function(a){return this.objects["jnt/"+a]};
THREE.SEA3D.Domain.prototype.getContainer3D=THREE.SEA3D.prototype.getContainer3D=function(a){return this.objects["c3d/"+a]};THREE.SEA3D.Domain.prototype.getSprite=THREE.SEA3D.prototype.getSprite=function(a){return this.objects["m2d/"+a]};THREE.SEA3D.Domain.prototype.getProperties=THREE.SEA3D.prototype.getProperties=function(a){return this.objects["prop/"+a]};THREE.SEA3D.prototype.isPowerOfTwo=function(a){return a?(a&-a)==a:!1};
THREE.SEA3D.prototype.nearestPowerOfTwo=function(a){return Math.pow(2,Math.round(Math.log(a)/Math.LN2))};THREE.SEA3D.prototype.updateTransform=function(a,b){var c=THREE.SEA3D.MTXBUF;b.transform?c.fromArray(b.transform):c.makeTranslation(b.position.x,b.position.y,b.position.z);a.position.setFromMatrixPosition(c);a.scale.setFromMatrixScale(c);a.quaternion.setFromRotationMatrix(THREE.SEA3D.identityMatrixScale(c));if(this.config.forceStatic||b.isStatic)a.updateMatrix(),a.matrixAutoUpdate=!1};
THREE.SEA3D.prototype.toVector3=function(a){return new THREE.Vector3(a.x,a.y,a.z)};THREE.SEA3D.prototype.toFaces=function(a){var b=[];b[0]=a[1];b[1]=a[0];b[2]=a[3];b[3]=a[2];b[4]=a[5];b[5]=a[4];return b};THREE.SEA3D.prototype.updateScene=function(){if(void 0!=this.materials)for(var a=0,b=this.materials.length;a<b;++a)this.materials[a].needsUpdate=!0};
THREE.SEA3D.prototype.addSceneObject=function(a,b){b=b||a.tag;b.visible=a.visible;a.parent?a.parent.tag.add(b):this.config.container&&this.config.container.add(b);a.attributes&&(b.attribs=a.attributes.tag);a.scripts&&(b.scripts=this.getJSMList(b,a.scripts),this.config.scripts&&this.config.runScripts&&this.domain.runJSMList(b))};THREE.SEA3D.prototype.createObjectURL=function(a,b){return(window.URL||window.webkitURL).createObjectURL(new Blob([a],{type:b}))};
THREE.SEA3D.prototype.parsePath=function(a){var b=this.config.paths,c;for(c in b)a=a.replace(new RegExp("%"+c+"%","g"),b[c]);return a};
THREE.SEA3D.prototype.addDefaultAnimation=function(a,b){for(var c=a.tag,d=0,e=a.animations?a.animations.length:0;d<e;d++){var f=a.animations[d];switch(f.tag.type){case SEA3D.Animation.prototype.type:return d=f.tag.tag||this.getModifier({sea:f.tag,scope:c,relative:f.relative}),c.animator=new b(d,c),c.animator.setRelative(f.relative),this.config.autoPlay&&c.animator.play(0),c.animator}}};
THREE.SEA3D.prototype.readGeometryBuffer=function(a){for(var b=a.tag||new THREE.BufferGeometry,c=0;c<a.groups.length;c++){var d=a.groups[c];b.addGroup(d.start,d.count,c)}a.indexes&&b.setIndex(new THREE.BufferAttribute(a.indexes,1));b.addAttribute("position",new THREE.BufferAttribute(a.vertex,3));a.uv&&(b.addAttribute("uv",new THREE.BufferAttribute(a.uv[0],2)),1<a.uv.length&&b.addAttribute("uv2",new THREE.BufferAttribute(a.uv[1],2)));a.normal?b.addAttribute("normal",new THREE.BufferAttribute(a.normal,
3)):b.computeVertexNormals();a.tangent4&&b.addAttribute("tangent",new THREE.BufferAttribute(a.tangent4,4));a.color&&b.addAttribute("color",new THREE.BufferAttribute(a.color[0],a.numColor));a.joint&&(b.addAttribute("skinIndex",new THREE.Float32BufferAttribute(a.joint,a.jointPerVertex)),b.addAttribute("skinWeight",new THREE.Float32BufferAttribute(a.weight,a.jointPerVertex)));this.config.bounding&&(b.computeBoundingBox(),b.computeBoundingSphere());b.name=a.name;this.domain.geometries=this.geometries=
this.geometries||[];this.geometries.push(this.objects["geo/"+a.name]=a.tag=b)};THREE.SEA3D.prototype.readDummy=function(a){var b=new THREE.SEA3D.Dummy(a.width,a.height,a.depth);b.name=a.name;this.domain.dummys=this.dummys=this.dummys||[];this.dummys.push(this.objects["dmy/"+a.name]=a.tag=b);this.addSceneObject(a);this.updateTransform(b,a);this.addDefaultAnimation(a,THREE.SEA3D.Object3DAnimator)};
THREE.SEA3D.prototype.readLine=function(a){var b=new THREE.BufferGeometry;a.closed&&a.vertex.push(a.vertex[0],a.vertex[1],a.vertex[2]);b.addAttribute("position",new THREE.Float32BufferAttribute(a.vertex,3));b=new THREE.Line(b,new THREE.LineBasicMaterial({color:THREE.SEA3D.HELPER_COLOR,linewidth:3}));b.name=a.name;this.lines=this.lines||[];this.lines.push(this.objects["line/"+a.name]=a.tag=b);this.addSceneObject(a);this.updateTransform(b,a);this.addDefaultAnimation(a,THREE.SEA3D.Object3DAnimator)};
THREE.SEA3D.prototype.readContainer3D=function(a){var b=new THREE.SEA3D.Object3D;this.domain.containers=this.containers=this.containers||[];this.containers.push(this.objects["c3d/"+a.name]=a.tag=b);this.addSceneObject(a);this.updateTransform(b,a);this.addDefaultAnimation(a,THREE.SEA3D.Object3DAnimator)};
THREE.SEA3D.prototype.readSprite=function(a){var b;if(a.material)if(a.material.tag.sprite)b=a.material.tag.sprite;else{b=a.material.tag.sprite=new THREE.SpriteMaterial;this.setBlending(b,a.blendMode);var c=a.material.tag.map;c&&(c.flipY=!0,b.map=c);b.color.set(a.material.tag.color);b.opacity=a.material.tag.opacity;b.fog=a.material.receiveFog}b=new THREE.Sprite(b);b.name=a.name;this.domain.sprites=this.sprites=this.sprites||[];this.sprites.push(this.objects["m2d/"+a.name]=a.tag=b);this.addSceneObject(a);
this.updateTransform(b,a);b.scale.set(a.width,a.height,1)};
THREE.SEA3D.prototype.readMesh=function(a){var b,c,d=a.geometry.tag,e,f,l,h,g,n,k;b=0;for(c=a.modifiers?a.modifiers.length:0;b<c;b++){var m=a.modifiers[b];switch(m.type){case SEA3D.Skeleton.prototype.type:case SEA3D.SkeletonLocal.prototype.type:f=m;d.bones=f.tag;break;case SEA3D.Morph.prototype.type:l=m.tag||this.getModifier({sea:m,geometry:a.geometry}),d.morphAttributes=l.attribs,d.morphTargets=l.targets}}b=0;for(c=a.animations?a.animations.length:0;b<c;b++)switch(m=a.animations[b].tag,m.type){case SEA3D.SkeletonAnimation.prototype.type:h=
m;d.animations=h.tag||this.getModifier({sea:h,skeleton:f,relative:!0});break;case SEA3D.VertexAnimation.prototype.type:g=m;d.morphAttributes=g.tag.attribs;d.morphTargets=g.tag.targets;d.animations=g.tag.animations;break;case SEA3D.UVWAnimation.prototype.type:n=m.tag||this.getModifier({sea:m});break;case SEA3D.MorphAnimation.prototype.type:k=m.tag||this.getModifier({sea:m})}c=void 0!=l||void 0!=g;l=l&&void 0!=l.attribs.normal||g&&void 0!=g.tag.attribs.normal;if(a.material)if(1<a.material.length){e=
[];for(b=0;b<a.material.length;b++)e[b]=a.material[b].tag,e[b].skinning=void 0!=f,e[b].morphTargets=c,e[b].morphNormals=l,e[b].vertexColors=a.geometry.color?THREE.VertexColors:THREE.NoColors;e=THREE.SEA3D.useMultiMaterial?new THREE.MultiMaterial(e):e}else e=a.material[0].tag,e.skinning=void 0!=f,e.morphTargets=c,e.morphNormals=l,e.vertexColors=a.geometry.color?THREE.VertexColors:THREE.NoColors;f?(b=new THREE.SEA3D.SkinnedMesh(d,e,this.config.useVertexTexture),this.config.autoPlay&&h&&b.play(0)):g?
(b=new THREE.SEA3D.VertexAnimationMesh(d,e),this.config.autoPlay&&b.play(0)):b=new THREE.SEA3D.Mesh(d,e);n&&(b.uvwAnimator=new THREE.SEA3D.Animator(n,new THREE.AnimationMixer(e.map)),this.config.autoPlay&&b.uvwAnimator.play(0));k&&(b.morphAnimator=new THREE.SEA3D.Animator(k,new THREE.AnimationMixer(b)),this.config.autoPlay&&b.morphAnimator.play(0));b.name=a.name;b.castShadow=a.castShadows;b.receiveShadow=a.material?a.material[0].receiveShadows:!0;this.domain.meshes=this.meshes=this.meshes||[];this.meshes.push(this.objects["m3d/"+
a.name]=a.tag=b);this.addSceneObject(a);this.updateTransform(b,a);this.addDefaultAnimation(a,THREE.SEA3D.Object3DAnimator)};
THREE.SEA3D.prototype.readSoundPoint=function(a){this.audioListener||(this.audioListener=new THREE.AudioListener,this.config.container&&this.config.container.add(this.audioListener));var b=new THREE.SEA3D.PointSound(this.audioListener);b.autoplay=a.autoPlay;b.setLoop(a.autoPlay);b.setVolume(a.volume);b.setRefDistance(a.distance);b.setRolloffFactor(this.config.audioRolloffFactor);b.setSound(a.sound.tag);b.name=a.name;this.domain.sounds3d=this.sounds3d=this.sounds3d||[];this.sounds3d.push(this.objects["sn3d/"+
a.name]=a.tag=b);this.addSceneObject(a);this.updateTransform(b,a);this.addDefaultAnimation(a,THREE.SEA3D.SoundAnimator)};THREE.SEA3D.prototype.readCubeRender=function(a){var b=new THREE.CubeCamera(.1,5E3,THREE.SEA3D.RTT_SIZE);b.renderTarget.cubeCamera=b;a.tag=b.renderTarget;this.domain.cubeRenderers=this.cubeRenderers=this.cubeRenderers||[];this.cubeRenderers.push(this.objects["rttc/"+a.name]=b);this.addSceneObject(a,b);this.updateTransform(b,a)};
THREE.SEA3D.prototype.readTexture=function(a){var b=new Image,c=new THREE.Texture;c.name=a.name;c.wrapS=c.wrapT=THREE.RepeatWrapping;c.flipY=!1;c.image=b;void 0!==this.config.anisotropy&&(c.anisotropy=this.config.anisotropy);b.onload=function(){c.needsUpdate=!0};b.src=this.createObjectURL(a.data.buffer,"image/"+a.type);this.domain.textures=this.textures=this.textures||[];this.textures.push(this.objects["tex/"+a.name]=a.tag=c)};
THREE.SEA3D.prototype.readCubeMap=function(a){var b=this.toFaces(a.faces),c=new THREE.CubeTexture([]),d=0;c.name=a.name;c.flipY=!1;c.format=THREE.RGBFormat;for(var e=function(){6==++d&&(c.needsUpdate=!0,this.config.async||(this.file.resume=!0))}.bind(this),f=0;f<b.length;++f){var l=new Image;l.onload=e;l.src=this.createObjectURL(b[f].buffer,"image/"+a.extension);c.images[f]=l}this.config.async||(this.file.resume=!1);this.domain.cubemaps=this.cubemaps=this.cubemaps||[];this.cubemaps.push(this.objects["cmap/"+
a.name]=a.tag=c)};THREE.SEA3D.prototype.readTextureUpdate=function(a){var b=this.file.objects[a.index],c=b.tag,d=new Image;d.onload=function(){c.image=d;c.needsUpdate=!0};d.src=this.createObjectURL(a.bytes.buffer,"image/"+b.type)};THREE.SEA3D.prototype.readSound=function(a){var b=new THREE.SEA3D.Sound(this.createObjectURL(a.data.buffer,"audio/"+a.type));b.name=a.name;this.domain.sounds=this.sounds=this.sounds||[];this.sounds.push(this.objects["snd/"+a.name]=a.tag=b)};
THREE.SEA3D.prototype.readScriptURL=function(a){this.file.resume=!1;(new THREE.FileLoader).setResponseType("text").load(a.url,function(b){this.file.resume=!0;this.domain.scripts=this.scripts=this.scripts||[];this.scripts.push(this.objects["src/"+a.name]=a.tag=b)}.bind(this))};
THREE.SEA3D.prototype.readTextureURL=function(a){var b=(new THREE.TextureLoader).load(this.parsePath(a.url));b.name=a.name;b.wrapS=b.wrapT=THREE.RepeatWrapping;b.flipY=!1;void 0!==this.config.anisotropy&&(b.anisotropy=this.config.anisotropy);this.domain.textures=this.textures=this.textures||[];this.textures.push(this.objects["tex/"+a.name]=a.tag=b)};
THREE.SEA3D.prototype.readCubeMapURL=function(a){for(var b=this.toFaces(a.faces),c=0;c<b.length;c++)b[c]=this.parsePath(b[c]);if("hdr"==b[0].substr(-3)){var d=null!=THREE.PMREMGenerator;this.file.resume=!d;b=(new THREE.HDRCubeTextureLoader).load(THREE.UnsignedByteType,b,function(b){if(d){var c=new THREE.PMREMGenerator(b);c.update(this.config.renderer);c=new THREE.PMREMCubeUVPacker(c.cubeLods);c.update(this.config.renderer);b.dispose();this.objects["cmap/"+a.name]=a.tag=c.CubeUVRenderTarget.texture;
this.file.resume=!0}}.bind(this))}else b=(new THREE.CubeTextureLoader).load(b);b.name=a.name;b.wrapS=b.wrapT=THREE.RepeatWrapping;b.flipY=!1;void 0!==this.config.anisotropy&&(b.anisotropy=this.config.anisotropy);this.domain.cubemaps=this.cubemaps=this.cubemaps||[];this.cubemaps.push(this.objects["cmap/"+a.name]=a.tag=b)};
THREE.SEA3D.prototype.getJSMList=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=b[d];e.tag.type==SEA3D.JavaScriptMethod.prototype.type&&c.push(e)}this.domain.scriptTargets=this.scriptTargets=this.scriptTargets||[];this.scriptTargets.push(a);return c};
THREE.SEA3D.prototype.readJavaScriptMethod=function(a){try{var b="(function() {\nvar $METHOD \x3d {}\n",c='function($INC, $REF, global, local, self, $PARAM) {\nvar watch \x3d $INC["watch"],\nscene \x3d $INC["scene"],\nsea3d \x3d $INC["sea3d"],\nprint \x3d $INC["print"];\n',c=c+'var $SRC \x3d $INC["source"],\naddEventListener \x3d $SRC.addEventListener.bind( $SRC ),\nhasEventListener \x3d $SRC.hasEventListener.bind( $SRC ),\nremoveEventListener \x3d $SRC.removeEventListener.bind( $SRC ),\ndispatchEvent \x3d $SRC.dispatchEvent.bind( $SRC ),\ndispose \x3d $SRC.dispose.bind( $SRC );\n',
d;for(d in a.methods)b+='$METHOD["'+d+'"] \x3d '+c+a.methods[d].src+"}\n";this.domain.methods=eval(b+"return $METHOD; })")()}catch(e){console.error('SEA3D JavaScriptMethod: Error running "'+a.name+'".'),console.error(e)}};THREE.SEA3D.prototype.readGLSL=function(a){this.domain.glsl=this.glsl=this.glsl||[];this.glsl.push(this.objects["glsl/"+a.name]=a.tag=a.src)};
THREE.SEA3D.prototype.materialTechnique=function(){var a={onComplete:function(a,c){if(1>c.alpha||a.blending>THREE.NormalBlending)a.opacity=c.alpha,a.transparent=!0}};a[SEA3D.Material.PHYSICAL]=function(a,c){a.color.setHex(c.color);a.roughness=c.roughness;a.metalness=c.metalness};a[SEA3D.Material.REFLECTIVITY]=function(a,c){a.reflectivity=c.strength};a[SEA3D.Material.CLEAR_COAT]=function(a,c){a.clearCoat=c.strength;a.clearCoatRoughness=c.roughness};a[SEA3D.Material.PHONG]=function(a,c){a.color.setHex(c.diffuseColor);
a.specular.setHex(c.specularColor).multiplyScalar(c.specular);a.shininess=c.gloss};a[SEA3D.Material.DIFFUSE_MAP]=function(a,c,d){a.map=c.texture.tag;a.color.setHex(16777215);a.map.wrapS=a.map.wrapT=d.repeat?THREE.RepeatWrapping:THREE.ClampToEdgeWrapping;c.texture.transparent&&(a.transparent=!0)};a[SEA3D.Material.ROUGHNESS_MAP]=function(a,c){a.roughnessMap=c.texture.tag};a[SEA3D.Material.METALNESS_MAP]=function(a,c){a.metalnessMap=c.texture.tag};a[SEA3D.Material.SPECULAR_MAP]=function(a,c){a.specular&&
(a.specularMap=c.texture.tag,a.specular.setHex(16777215))};a[SEA3D.Material.NORMAL_MAP]=function(a,c){a.normalMap=c.texture.tag};a[SEA3D.Material.REFLECTION]=a[SEA3D.Material.FRESNEL_REFLECTION]=function(a,c){a.envMap=c.texture.tag;a.envMap.mapping=THREE.CubeReflectionMapping;a.combine=THREE.MixOperation;a.reflectivity=c.alpha};a[SEA3D.Material.REFLECTION_SPHERICAL]=function(a,c){a.envMap=c.texture.tag;a.envMap.mapping=THREE.SphericalReflectionMapping;a.combine=THREE.MixOperation;a.reflectivity=c.alpha};
a[SEA3D.Material.REFRACTION_MAP]=function(a,c){a.envMap=c.texture.tag;a.envMap.mapping=THREE.CubeRefractionMapping;a.refractionRatio=c.ior;a.reflectivity=c.alpha};a[SEA3D.Material.LIGHT_MAP]=function(a,c){"multiply"==c.blendMode?a.aoMap=c.texture.tag:a.lightMap=c.texture.tag};a[SEA3D.Material.EMISSIVE]=function(a,c){a.emissive.setHex(c.color)};a[SEA3D.Material.EMISSIVE_MAP]=function(a,c){a.emissiveMap=c.texture.tag};a[SEA3D.Material.ALPHA_MAP]=function(a,c,d){a.alphaMap=c.texture.tag;a.transparent=
!0;a.alphaMap.wrapS=a.alphaMap.wrapT=d.repeat?THREE.RepeatWrapping:THREE.ClampToEdgeWrapping};return a}();THREE.SEA3D.prototype.createMaterial=function(a){return a.tecniquesDict[SEA3D.Material.REFLECTIVITY]||a.tecniquesDict[SEA3D.Material.CLEAR_COAT]?new THREE.MeshPhysicalMaterial:a.tecniquesDict[SEA3D.Material.PHYSICAL]?new THREE.MeshStandardMaterial:new THREE.MeshPhongMaterial};
THREE.SEA3D.prototype.setBlending=function(a,b){if("normal"!==b){switch(b){case "add":a.blending=THREE.AdditiveBlending;break;case "subtract":a.blending=THREE.SubtractiveBlending;break;case "multiply":a.blending=THREE.MultiplyBlending;break;case "screen":a.blending=THREE.CustomBlending,a.blendSrc=THREE.OneFactor,a.blendDst=THREE.OneMinusSrcColorFactor,a.blendEquation=THREE.AddEquation}a.transparent=!0}};
THREE.SEA3D.prototype.readMaterial=function(a){var b=this.createMaterial(a);b.name=a.name;b.lights=a.receiveLights;b.fog=a.receiveFog;b.depthWrite=a.depthWrite;b.depthTest=a.depthTest;b.premultipliedAlpha=a.premultipliedAlpha;b.side=a.doubleSided?THREE.DoubleSide:THREE.FrontSide;this.setBlending(b,a.blendMode);for(var c=0;c<a.technique.length;c++){var d=a.technique[c];this.materialTechnique[d.kind]&&this.materialTechnique[d.kind].call(this,b,d,a)}this.materialTechnique.onComplete&&this.materialTechnique.onComplete.call(this,
b,a);this.domain.materials=this.materials=this.materials||[];this.materials.push(this.objects["mat/"+a.name]=a.tag=b)};
THREE.SEA3D.prototype.readPointLight=function(a){var b=new THREE.SEA3D.PointLight(a.color,a.multiplier*this.config.multiplier);b.name=a.name;a.attenuation&&(b.distance=a.attenuation.end);a.shadow&&this.setShadowMap(b);this.domain.lights=this.lights=this.lights||[];this.lights.push(this.objects["lht/"+a.name]=a.tag=b);this.addSceneObject(a);this.updateTransform(b,a);this.addDefaultAnimation(a,THREE.SEA3D.LightAnimator);this.updateScene()};
THREE.SEA3D.prototype.readHemisphereLight=function(a){var b=new THREE.HemisphereLight(a.color,a.secondColor,a.multiplier*this.config.multiplier);b.position.set(0,500,0);b.name=a.name;this.domain.lights=this.lights=this.lights||[];this.lights.push(this.objects["lht/"+a.name]=a.tag=b);this.addSceneObject(a);this.addDefaultAnimation(a,THREE.SEA3D.LightAnimator);this.updateScene()};
THREE.SEA3D.prototype.readAmbientLight=function(a){var b=new THREE.AmbientLight(a.color,a.multiplier*this.config.multiplier);b.name=a.name;this.domain.lights=this.lights=this.lights||[];this.lights.push(this.objects["lht/"+a.name]=a.tag=b);this.addSceneObject(a);this.addDefaultAnimation(a,THREE.SEA3D.LightAnimator);this.updateScene()};
THREE.SEA3D.prototype.readDirectionalLight=function(a){var b=new THREE.DirectionalLight(a.color,a.multiplier*this.config.multiplier);b.name=a.name;a.shadow&&this.setShadowMap(b);this.domain.lights=this.lights=this.lights||[];this.lights.push(this.objects["lht/"+a.name]=a.tag=b);this.addSceneObject(a);this.updateTransform(b,a);this.addDefaultAnimation(a,THREE.SEA3D.LightAnimator);this.updateScene()};
THREE.SEA3D.prototype.readCamera=function(a){var b=new THREE.SEA3D.Camera(a.fov);b.name=a.name;this.domain.cameras=this.cameras=this.cameras||[];this.cameras.push(this.objects["cam/"+a.name]=a.tag=b);this.addSceneObject(a);this.updateTransform(b,a);this.addDefaultAnimation(a,THREE.SEA3D.CameraAnimator)};
THREE.SEA3D.prototype.readOrthographicCamera=function(a){var b,c;c=void 0!==this.config.stageWidth?this.config.stageWidth:window?window.innerWidth:1024;var d=void 0!==this.config.stageHeight?this.config.stageHeight:window?window.innerHeight:1024;c>d?(b=c/d*a.height,c=a.height):(b=a.height,c=d/c*a.height);b=new THREE.SEA3D.OrthographicCamera(-b,b,c,-c);b.name=a.name;this.domain.cameras=this.cameras=this.cameras||[];this.cameras.push(this.objects["cam/"+a.name]=a.tag=b);this.addSceneObject(a);this.updateTransform(b,
a);this.addDefaultAnimation(a,THREE.SEA3D.CameraAnimator)};THREE.SEA3D.prototype.getSkeletonFromBones=function(a){var b=[],c,d,e,f;e=0;for(f=a.length;e<f;e++)d=a[e],c=new THREE.Bone,b.push(c),c.name=d.name,c.position.fromArray(d.pos),c.quaternion.fromArray(d.rotq),void 0!==d.scl&&c.scale.fromArray(d.scl);e=0;for(f=a.length;e<f;e++)d=a[e],-1!==d.parent&&null!==d.parent&&void 0!==b[d.parent]&&b[d.parent].add(b[e]);return new THREE.Skeleton(b)};
THREE.SEA3D.prototype.readSkeletonLocal=function(a){for(var b=[],c=0;c<a.joint.length;c++){var d=a.joint[c];b[c]={name:d.name,pos:[d.x,d.y,d.z],rotq:[d.qx,d.qy,d.qz,d.qw],parent:d.parentIndex}}this.domain.bones=this.bones=this.bones||[];this.bones.push(this.objects[a.name+".sklq"]=a.tag=b)};THREE.SEA3D.prototype.readJointObject=function(a){var b=a.target.tag.skeleton.bones[a.joint];this.domain.joints=this.joints=this.joints||[];this.joints.push(this.objects["jnt/"+a.name]=a.tag=b)};
THREE.SEA3D.prototype.readMorph=function(a){for(var b={position:[]},c=[],d=0;d<a.node.length;d++){var e=a.node[d];b.position[d]=new THREE.Float32BufferAttribute(e.vertex,3);b.position[d].name=e.name;e.normal&&(b.normal=b.normal||[],b.normal[d]=new THREE.Float32BufferAttribute(e.normal,3));c[d]={name:e.name}}a.tag={attribs:b,targets:c}};
THREE.SEA3D.prototype.readAnimation=function(a){for(var b=[],c=1E3/a.frameRate/1E3,d=0;d<a.sequence.length;d++){for(var e=a.sequence[d],f=[],l=0;l<a.dataList.length;l++){var h=a.dataList[l],g,n,k,m=h.data;k=e.start*h.blockSize;g=k+e.count*h.blockSize;var q=e.intrpl?THREE.InterpolateLinear:!1,p=null;switch(h.kind){case SEA3D.Animation.POSITION:p=".position";break;case SEA3D.Animation.ROTATION:p=".quaternion";break;case SEA3D.Animation.SCALE:p=".scale";break;case SEA3D.Animation.COLOR:p=".color";break;
case SEA3D.Animation.MULTIPLIER:p=".intensity";break;case SEA3D.Animation.FOV:p=".fov";break;case SEA3D.Animation.OFFSET_U:p=".offset[x]";break;case SEA3D.Animation.OFFSET_V:p=".offset[y]";break;case SEA3D.Animation.SCALE_U:p=".repeat[x]";break;case SEA3D.Animation.SCALE_V:p=".repeat[y]";break;case SEA3D.Animation.MORPH:p=".morphTargetInfluences["+h.name+"]"}if(p)switch(h.type){case SEA3D.Stream.BYTE:case SEA3D.Stream.UBYTE:case SEA3D.Stream.INT:case SEA3D.Stream.UINT:case SEA3D.Stream.FLOAT:case SEA3D.Stream.DOUBLE:case SEA3D.Stream.DECIMAL:k=
m.subarray(k,g);n=new Float32Array(k.length);for(g=h=0;g<n.length;g++)n[g]=h,h+=c;f.push(new THREE.NumberKeyframeTrack(p,n,k,q));break;case SEA3D.Stream.VECTOR3D:k=m.subarray(k,g);n=new Float32Array(k.length/h.blockSize);for(g=h=0;g<n.length;g++)n[g]=h,h+=c;f.push(new THREE.VectorKeyframeTrack(p,n,k,q));break;case SEA3D.Stream.VECTOR4D:k=m.subarray(k,g);n=new Float32Array(k.length/h.blockSize);for(g=h=0;g<n.length;g++)n[g]=h,h+=c;f.push(new THREE.QuaternionKeyframeTrack(p,n,k,q));break;case SEA3D.Stream.INT24:case SEA3D.Stream.UINT24:k=
new Float32Array(3*(g-k));n=new Float32Array(k.length/3);for(g=h=0;g<n.length;g++)k[3*g]=(m[g]>>16&255)/255,k[3*g+1]=(m[g]>>8&255)/255,k[3*g+2]=(m[g]&255)/255,n[g]=h,h+=c;f.push(new THREE.VectorKeyframeTrack(p,n,k,q))}}b.push(new THREE.SEA3D.AnimationClip(e.name,-1,f,e.repeat))}this.domain.clips=this.clips=this.clips||[];this.clips.push(this.objects[a.name+".anm"]=a.tag=b)};
THREE.SEA3D.prototype.readSkeletonAnimation=function(a,b){b=!b&&a.metadata&&a.metadata.skeleton?a.metadata.skeleton:b;if(!b||a.tag)return a.tag;for(var c=[],d=1E3/a.frameRate/1E3,e=0;e<a.sequence.length;e++){for(var f=a.sequence[e],l=f.start,h=l+f.count,g={name:f.name,fps:a.frameRate,length:d*f.count,hierarchy:[]},n=a.numJoints,k=a.raw,m=0;m<n;m++){for(var q={parent:b.joint[m].parentIndex,keys:[]},p=q.keys,t=0,u=l;u<h;u++){var r=u*n*7+7*m;p.push({time:t,pos:[k[r],k[r+1],k[r+2]],rot:[k[r+3],k[r+4],
k[r+5],k[r+6]],scl:[1,1,1]});t+=d}g.hierarchy[m]=q}c.push(THREE.SEA3D.AnimationClip.fromClip(THREE.AnimationClip.parseAnimation(g,b.tag),f.repeat))}this.domain.clips=this.clips=this.clips||[];this.clips.push(this.objects[a.name+".skla"]=a.tag=c)};
THREE.SEA3D.prototype.readVertexAnimation=function(a){var b={position:[]},c=[],d=[],e,f;e=0;for(f=a.frame.length;e<f;e++){var l=a.frame[e];b.position[e]=new THREE.Float32BufferAttribute(l.vertex,3);l.normal&&(b.normal=b.normal||[],b.normal[e]=new THREE.Float32BufferAttribute(l.normal,3));c[e]={name:e}}for(e=0;e<a.sequence.length;e++){var l=a.sequence[e],h=[];for(f=0;f<l.count;f++)h[f]=c[l.start+f];d.push(THREE.SEA3D.AnimationClip.fromClip(THREE.AnimationClip.CreateFromMorphTargetSequence(l.name,h,
a.frameRate),l.repeat))}a.tag={attribs:b,targets:c,animations:d};this.domain.clips=this.clips=this.clips||[];this.clips.push(this.objects[a.name+".vtxa"]=a.tag)};
THREE.SEA3D.prototype.getModifier=function(a){var b=a.sea;switch(b.type){case SEA3D.SkeletonAnimation.prototype.type:this.readSkeletonAnimation(b,a.skeleton);break;case SEA3D.Animation.prototype.type:case SEA3D.MorphAnimation.prototype.type:case SEA3D.UVWAnimation.prototype.type:this.readAnimation(b);break;case SEA3D.Morph.prototype.type:this.readMorph(b,a.geometry)}return b.tag};
THREE.SEA3D.prototype.applyEnvironment=function(a){for(var b=0,c=this.materials.length;b<c;++b){var d=this.materials[b];d instanceof THREE.MeshStandardMaterial&&!d.envMap&&(d.envMap=a,d.envMap.mapping=THREE.CubeReflectionMapping,d.needsUpdate=!0)}};
THREE.SEA3D.prototype.readActions=function(a){for(var b=0;b<a.actions.length;b++){var c=a.actions[b];switch(c.kind){case SEA3D.Actions.ATTRIBUTES:this.attribs=this.domain.attribs=c.attributes.tag;break;case SEA3D.Actions.SCRIPTS:this.domain.scripts=this.getJSMList(this.domain,c.scripts);this.config.scripts&&this.config.runScripts&&this.domain.runJSMList(this.domain);break;case SEA3D.Actions.CAMERA:this.domain.camera=this.camera=c.camera.tag;break;case SEA3D.Actions.ENVIRONMENT_COLOR:this.domain.background=
this.background=this.background||{};this.background.color=new THREE.Color(c.color);break;case SEA3D.Actions.ENVIRONMENT:this.domain.background=this.background=this.background||{},this.background.texture=c.texture.tag,this.config.useEnvironment&&void 0!=this.materials&&this.applyEnvironment(c.texture.tag)}}};
THREE.SEA3D.prototype.updatePropertiesAssets=function(a,b){for(var c in b)switch(b.__type[c]){case SEA3D.Stream.ASSET:b.__asset||(b.__asset={});b.__asset[c]||(b.__asset[c]=b[c]);b[c]=b.__asset[c].tag;break;case SEA3D.Stream.GROUP:b[c]=this.updatePropertiesAssets(a,b[c])}return b};THREE.SEA3D.prototype.readProperties=function(a){var b=this.updatePropertiesAssets(a,a.props);this.domain.properties=this.properties=this.properties||[];this.properties.push(this.objects["prop/"+a.name]=a.tag=b)};
THREE.SEA3D.prototype.readFileInfo=function(a){this.domain.info=this.updatePropertiesAssets(a,a.info)};THREE.SEA3D.Event={PROGRESS:"sea3d_progress",LOAD_PROGRESS:"sea3d_load",DOWNLOAD_PROGRESS:"sea3d_download",COMPLETE:"sea3d_complete",OBJECT_COMPLETE:"sea3d_object",PARSE_PROGRESS:"parse_progress",PARSE_COMPLETE:"parse_complete",ERROR:"sea3d_error"};THREE.SEA3D.prototype.onProgress=function(a){a.status=a.type;a.progress=a.loaded/a.total;a.type=THREE.SEA3D.Event.PROGRESS;this.dispatchEvent(a)};
THREE.SEA3D.prototype.onLoadProgress=function(a){a.type=THREE.SEA3D.Event.LOAD_PROGRESS;this.dispatchEvent(a);this.onProgress(a)};THREE.SEA3D.prototype.onDownloadProgress=function(a){a.type=THREE.SEA3D.Event.DOWNLOAD_PROGRESS;this.dispatchEvent(a);this.onProgress(a)};THREE.SEA3D.prototype.onComplete=function(a){a.type=THREE.SEA3D.Event.COMPLETE;this.dispatchEvent(a)};THREE.SEA3D.prototype.onCompleteObject=function(a){a.type=THREE.SEA3D.Event.OBJECT_COMPLETE;this.dispatchEvent(a)};
THREE.SEA3D.prototype.onParseProgress=function(a){a.type=THREE.SEA3D.Event.PARSE_PROGRESS;this.dispatchEvent(a)};THREE.SEA3D.prototype.onParseComplete=function(a){a.type=THREE.SEA3D.Event.PARSE_COMPLETE;this.dispatchEvent(a)};THREE.SEA3D.prototype.onError=function(a){a.type=THREE.SEA3D.Event.ERROR;this.dispatchEvent(a)};THREE.SEA3D.prototype.createDomain=function(){return this.domain=new THREE.SEA3D.Domain(this.config.id,this.objects={},this.config.container)};
THREE.SEA3D.prototype.clone=function(a,b,c){if(!this.file.isDone())throw Error("Previous parse is not completed.");this.config.container=a&&void 0!==a.container?a.container:new THREE.Object3D;a&&this.loadConfig(a);var d=this.config.timeLimit;this.config.timeLimit=a&&void 0!==a.timeLimit?a.timeLimit:Infinity;this.parse(b,c);this.config.timeLimit=d;return this.domain};THREE.SEA3D.prototype.loadConfig=function(a){for(var b in a)this.config[b]=a[b]};
THREE.SEA3D.prototype.parse=function(a,b){delete this.cameras;delete this.containers;delete this.lights;delete this.joints;delete this.meshes;delete this.materials;delete this.sprites;delete this.sounds3d;delete this.cubeRenderers;delete this.sounds;delete this.glsl;delete this.dummy;delete this.camera;delete this.background;delete this.properties;delete this.scriptTargets;delete this.domain;this.createDomain();this.setTypeRead();this.file.onParseComplete=function(b){this.config.manager&&this.config.manager.add(this.domain);
(a||this.onParseComplete).call(this,b)}.bind(this);this.file.onParseProgress=b||this.onParseProgress;for(var c=THREE.SEA3D.EXTENSIONS_LOADER.length;c--;){var d=THREE.SEA3D.EXTENSIONS_LOADER[c];d.parse&&d.parse.call(this)}this.file.parse();return this.domain};THREE.SEA3D.prototype.onHead=function(a){if("TJS"!=a.sign)throw Error("Sign '"+a.sign+"' not supported! Use SEA3D Studio to publish or SEA3DLegacy.js");};THREE.SEA3D.EXTENSIONS_LOADER=[];THREE.SEA3D.EXTENSIONS_DOMAIN=[];
THREE.SEA3D.prototype.setTypeRead=function(){this.file.typeRead={};this.file.typeRead[SEA3D.Geometry.prototype.type]=this.readGeometryBuffer;this.file.typeRead[SEA3D.Mesh.prototype.type]=this.readMesh;this.file.typeRead[SEA3D.Sprite.prototype.type]=this.readSprite;this.file.typeRead[SEA3D.Container3D.prototype.type]=this.readContainer3D;this.file.typeRead[SEA3D.Line.prototype.type]=this.readLine;this.file.typeRead[SEA3D.Material.prototype.type]=this.readMaterial;this.file.typeRead[SEA3D.Camera.prototype.type]=
this.readCamera;this.file.typeRead[SEA3D.OrthographicCamera.prototype.type]=this.readOrthographicCamera;this.file.typeRead[SEA3D.SkeletonLocal.prototype.type]=this.readSkeletonLocal;this.file.typeRead[SEA3D.SkeletonAnimation.prototype.type]=this.readSkeletonAnimation;this.file.typeRead[SEA3D.JointObject.prototype.type]=this.readJointObject;this.file.typeRead[SEA3D.CubeMap.prototype.type]=this.readCubeMap;this.file.typeRead[SEA3D.CubeRender.prototype.type]=this.readCubeRender;this.file.typeRead[SEA3D.Animation.prototype.type]=
this.file.typeRead[SEA3D.MorphAnimation.prototype.type]=this.file.typeRead[SEA3D.UVWAnimation.prototype.type]=this.readAnimation;this.file.typeRead[SEA3D.SoundPoint.prototype.type]=this.readSoundPoint;this.file.typeRead[SEA3D.TextureURL.prototype.type]=this.readTextureURL;this.file.typeRead[SEA3D.CubeMapURL.prototype.type]=this.readCubeMapURL;this.file.typeRead[SEA3D.TextureUpdate.prototype.type]=this.readTextureUpdate;this.file.typeRead[SEA3D.Morph.prototype.type]=this.readMorph;this.file.typeRead[SEA3D.VertexAnimation.prototype.type]=
this.readVertexAnimation;this.file.typeRead[SEA3D.Actions.prototype.type]=this.readActions;this.file.typeRead[SEA3D.FileInfo.prototype.type]=this.readFileInfo;this.file.typeRead[SEA3D.Properties.prototype.type]=this.readProperties;this.config.dummys&&(this.file.typeRead[SEA3D.Dummy.prototype.type]=this.readDummy);this.config.scripts&&(this.file.typeRead[SEA3D.ScriptURL.prototype.type]=this.readScriptURL,this.file.typeRead[SEA3D.JavaScriptMethod.prototype.type]=this.readJavaScriptMethod);this.config.lights&&
(this.file.typeRead[SEA3D.PointLight.prototype.type]=this.readPointLight,this.file.typeRead[SEA3D.DirectionalLight.prototype.type]=this.readDirectionalLight,this.file.typeRead[SEA3D.HemisphereLight.prototype.type]=this.readHemisphereLight,this.file.typeRead[SEA3D.AmbientLight.prototype.type]=this.readAmbientLight);this.file.typeRead[SEA3D.JPEG.prototype.type]=this.file.typeRead[SEA3D.JPEG_XR.prototype.type]=this.file.typeRead[SEA3D.PNG.prototype.type]=this.file.typeRead[SEA3D.GIF.prototype.type]=
this.readTexture;this.file.typeRead[SEA3D.MP3.prototype.type]=this.readSound;this.file.typeRead[SEA3D.GLSL.prototype.type]=this.readGLSL;for(var a=THREE.SEA3D.EXTENSIONS_LOADER.length;a--;){var b=THREE.SEA3D.EXTENSIONS_LOADER[a];b.setTypeRead&&b.setTypeRead.call(this)}};
THREE.SEA3D.prototype.load=function(a){this.file=new SEA3D.File;this.file.scope=this;this.file.config=this.config;this.file.onProgress=this.onLoadProgress.bind(this);this.file.onCompleteObject=this.onCompleteObject.bind(this);this.file.onDownloadProgress=this.onDownloadProgress.bind(this);this.file.onParseProgress=this.onParseProgress.bind(this);this.file.onParseComplete=this.onParseComplete.bind(this);this.file.onError=this.onError.bind(this);this.file.onHead=this.onHead.bind(this);this.file.onComplete=
function(a){this.config.manager&&this.config.manager.add(this.domain);this.onComplete.call(this,a)}.bind(this);this.createDomain();this.setTypeRead();void 0!==a&&("string"===typeof a?this.file.load(a):this.file.read(a))};