THREE.SEA3D.prototype.toAmmoVec3=function(a){return new Ammo.btVector3(a.x,a.y,a.z)};THREE.SEA3D.prototype.readSphere=function(a){var b=new Ammo.btSphereShape(a.radius);this.domain.shapes=this.shapes=this.shapes||[];this.shapes.push(this.objects["shpe/"+a.name]=a.tag=b)};THREE.SEA3D.prototype.readBox=function(a){var b=new Ammo.btBoxShape(new Ammo.btVector3(.5*a.width,.5*a.height,.5*a.depth));this.domain.shapes=this.shapes=this.shapes||[];this.shapes.push(this.objects["shpe/"+a.name]=a.tag=b)};
THREE.SEA3D.prototype.readCone=function(a){var b=new Ammo.btConeShape(a.radius,a.height);this.domain.shapes=this.shapes=this.shapes||[];this.shapes.push(this.objects["shpe/"+a.name]=a.tag=b)};THREE.SEA3D.prototype.readCylinder=function(a){var b=new Ammo.btCylinderShape(new Ammo.btVector3(a.height,a.radius,a.radius));this.domain.shapes=this.shapes=this.shapes||[];this.shapes.push(this.objects["shpe/"+a.name]=a.tag=b)};
THREE.SEA3D.prototype.readCapsule=function(a){var b=new Ammo.btCapsuleShape(a.radius,a.height);this.domain.shapes=this.shapes=this.shapes||[];this.shapes.push(this.objects["shpe/"+a.name]=a.tag=b)};
THREE.SEA3D.prototype.readConvexGeometry=function(a){if(this.config.convexHull)var b=SEA3D.AMMO.createConvexHull(a.geometry.tag,a.subGeometryIndex);else b=SEA3D.AMMO.createTriangleMesh(a.geometry.tag,a.subGeometryIndex),b=new Ammo.btConvexTriangleMeshShape(b,!0);this.domain.shapes=this.shapes=this.shapes||[];this.shapes.push(this.objects["shpe/"+a.name]=a.tag=b)};
THREE.SEA3D.prototype.readTriangleGeometry=function(a){var b=SEA3D.AMMO.createTriangleMesh(a.geometry.tag,a.subGeometryIndex),b=new Ammo.btBvhTriangleMeshShape(b,!0,!0);this.domain.shapes=this.shapes=this.shapes||[];this.shapes.push(this.objects["shpe/"+a.name]=a.tag=b)};
THREE.SEA3D.prototype.readCompound=function(a){for(var b=new Ammo.btCompoundShape,e=0;e<a.compounds.length;e++){var c=a.compounds[e];THREE.SEA3D.MTXBUF.elements=c.transform;var g=SEA3D.AMMO.getTransformFromMatrix(THREE.SEA3D.MTXBUF);b.addChildShape(g,c.shape.tag)}this.domain.shapes=this.shapes=this.shapes||[];this.shapes.push(this.objects["shpe/"+a.name]=a.tag=b)};
THREE.SEA3D.prototype.readRigidBodyBase=function(a){var b=a.shape.tag,e,c;a.target?(c=a.target.tag,c.physics={enabled:!0},c.updateMatrix(),e=SEA3D.AMMO.getTransformFromMatrix(a.target.tag.matrix)):(THREE.SEA3D.MTXBUF.fromArray(a.transform),e=SEA3D.AMMO.getTransformFromMatrix(THREE.SEA3D.MTXBUF));e=new Ammo.btDefaultMotionState(e);var g=new Ammo.btVector3(0,0,0);b.calculateLocalInertia(a.mass,g);b=new Ammo.btRigidBodyConstructionInfo(a.mass,e,b,g);b.set_m_friction(a.friction);b.set_m_restitution(a.restitution);
b.set_m_linearDamping(a.linearDamping);b.set_m_angularDamping(a.angularDamping);e=new Ammo.btRigidBody(b);c&&(c.physics.rigidBody=e,a.offset&&(g=new THREE.Matrix4,g.fromArray(a.offset),c.physics.offset=g));Ammo.destroy(b);this.domain.rigidBodies=this.rigidBodies=this.rigidBodies||[];this.rigidBodies.push(this.objects["rb/"+a.name]=a.tag=e);return e};THREE.SEA3D.prototype.readRigidBody=function(a){var b=this.readRigidBodyBase(a);SEA3D.AMMO.addRigidBody(b,a.target?a.target.tag:void 0,this.config.enabledPhysics)};
THREE.SEA3D.prototype.readCarController=function(a){var b=this.readRigidBodyBase(a);b.setActivationState(SEA3D.AMMO.DISABLE_DEACTIVATION);var e=new Ammo.btDefaultVehicleRaycaster(SEA3D.AMMO.world),c=new Ammo.btVehicleTuning;c.set_m_suspensionStiffness(a.suspensionStiffness);c.set_m_suspensionDamping(a.suspensionDamping);c.set_m_suspensionCompression(a.suspensionCompression);c.set_m_maxSuspensionTravelCm(a.maxSuspensionTravelCm);c.set_m_maxSuspensionForce(a.maxSuspensionForce);c.set_m_frictionSlip(a.frictionSlip);
var e=new Ammo.btRaycastVehicle(c,b,e),g=[];e.setCoordinateSystem(0,1,2);for(var k=0;k<a.wheel.length;k++){var d=a.wheel[k],h=e.addWheel(this.toAmmoVec3(d.pos),this.toAmmoVec3(d.dir),this.toAmmoVec3(d.axle),d.suspensionRestLength,d.radius,c,d.isFront),f=g[k]=d.target?d.target.tag:void 0;if(f){f.physics={enabled:!0,rigidBody:h};if(d.offset){var l=new THREE.Matrix4;l.fromArray(d.offset);f.physics.offset=l}f.parent&&f.parent.remove(f);this.container&&this.container.add(f)}h.set_m_suspensionStiffness(a.suspensionStiffness);
h.set_m_wheelsDampingRelaxation(a.dampingRelaxation);h.set_m_wheelsDampingCompression(a.dampingCompression);h.set_m_frictionSlip(a.frictionSlip)}SEA3D.AMMO.addVehicle(e,g);SEA3D.AMMO.addRigidBody(b,a.target?a.target.tag:void 0,this.config.enabledPhysics);this.domain.vehicles=this.vehicles=this.vehicles||[];this.vehicles.push(this.objects["vhc/"+a.name]=a.tag=e)};
THREE.SEA3D.prototype.readP2PConstraint=function(a){var b;b=a.targetB?new Ammo.btPoint2PointConstraint(a.targetA.tag,a.targetB.tag,this.toAmmoVec3(a.pointA),this.toAmmoVec3(a.pointB)):new Ammo.btPoint2PointConstraint(a.targetA.tag,this.toAmmoVec3(a.pointA));SEA3D.AMMO.addConstraint(b);this.domain.constraints=this.constraints=this.constraints||[];this.constraints.push(this.objects["ctnt/"+a.name]=a.tag=b)};
THREE.SEA3D.prototype.readHingeConstraint=function(a){var b;b=a.targetB?new Ammo.btHingeConstraint(a.targetA.tag,a.targetB.tag,this.toAmmoVec3(a.pointA),this.toAmmoVec3(a.pointB),this.toAmmoVec3(a.axisA),this.toAmmoVec3(a.axisB),!1):new Ammo.btHingeConstraint(a.targetA.tag,this.toAmmoVec3(a.pointA),this.toAmmoVec3(a.axisA),!1);a.limit&&b.setLimit(a.limit.low,a.limit.high,a.limit.softness,a.limit.biasFactor,a.limit.relaxationFactor);a.angularMotor&&b.enableAngularMotor(!0,a.angularMotor.velocity,a.angularMotor.impulse);
SEA3D.AMMO.addConstraint(b);this.domain.constraints=this.constraints=this.constraints||[];this.constraints.push(this.objects["ctnt/"+a.name]=a.tag=b)};
THREE.SEA3D.prototype.readConeTwistConstraint=function(a){var b;b=a.targetB?new Ammo.btConeTwistConstraint(a.targetA.tag,a.targetB.tag,this.toAmmoVec3(a.pointA),this.toAmmoVec3(a.pointB),!1):new Ammo.btConeTwistConstraint(a.targetA.tag,this.toAmmoVec3(a.pointA),!1);SEA3D.AMMO.addConstraint(b);this.domain.constraints=this.constraints=this.constraints||[];this.constraints.push(this.objects["ctnt/"+a.name]=a.tag=b)};
THREE.SEA3D.Domain.prototype.enabledPhysics=function(a){for(var b=this.rigidBodies?this.rigidBodies.length:0;b--;)SEA3D.AMMO.setEnabledRigidBody(this.rigidBodies[b],a)};THREE.SEA3D.Domain.prototype.applyContainerTransform=function(){this.container.updateMatrix();var a=this.container.matrix.clone();this.container.position.set(0,0,0);this.container.quaternion.set(0,0,0,1);this.container.scale.set(1,1,1);this.applyTransform(a)};
THREE.SEA3D.Domain.prototype.applyTransform=function(a){for(var b=THREE.SEA3D.MTXBUF,e=THREE.SEA3D.VECBUF,c=this.rigidBodies?this.rigidBodies.length:0,g=this.container?this.container.children:[],k=[];c--;){var d=this.rigidBodies[c],h=SEA3D.AMMO.getTargetByRigidBody(d),f=d.getWorldTransform(),f=SEA3D.AMMO.getMatrixFromTransform(f);f.multiplyMatrices(f,a);f=SEA3D.AMMO.getTransformFromMatrix(f);d.setWorldTransform(f);h&&k.push(h)}for(c=0;c<g.length;c++)d=g[c],-1<k.indexOf(d)||(d.updateMatrix(),b.copy(d.matrix),
b.multiplyMatrices(a,b),d.position.setFromMatrixPosition(b),d.scale.setFromMatrixScale(b),b.scale(e.set(1/d.scale.x,1/d.scale.y,1/d.scale.z)),d.quaternion.setFromRotationMatrix(b))};THREE.SEA3D.Domain.prototype.getShape=THREE.SEA3D.prototype.getShape=function(a){return this.objects["shpe/"+a]};THREE.SEA3D.Domain.prototype.getRigidBody=THREE.SEA3D.prototype.getRigidBody=function(a){return this.objects["rb/"+a]};
THREE.SEA3D.Domain.prototype.getConstraint=THREE.SEA3D.prototype.getConstraint=function(a){return this.objects["ctnt/"+a]};
THREE.SEA3D.EXTENSIONS_LOADER.push({parse:function(){delete this.shapes;delete this.rigidBodies;delete this.vehicles;delete this.constraints},setTypeRead:function(){this.config.physics=void 0!==this.config.physics?this.config.physics:!0;this.config.convexHull=void 0!==this.config.convexHull?this.config.convexHull:!0;this.config.enabledPhysics=void 0!==this.config.enabledPhysics?this.config.enabledPhysics:!0;this.config.physics&&(this.file.typeRead[SEA3D.Sphere.prototype.type]=this.readSphere,this.file.typeRead[SEA3D.Box.prototype.type]=
this.readBox,this.file.typeRead[SEA3D.Capsule.prototype.type]=this.readCapsule,this.file.typeRead[SEA3D.Cone.prototype.type]=this.readCone,this.file.typeRead[SEA3D.Cylinder.prototype.type]=this.readCylinder,this.file.typeRead[SEA3D.ConvexGeometry.prototype.type]=this.readConvexGeometry,this.file.typeRead[SEA3D.TriangleGeometry.prototype.type]=this.readTriangleGeometry,this.file.typeRead[SEA3D.Compound.prototype.type]=this.readCompound,this.file.typeRead[SEA3D.P2PConstraint.prototype.type]=this.readP2PConstraint,
this.file.typeRead[SEA3D.HingeConstraint.prototype.type]=this.readHingeConstraint,this.file.typeRead[SEA3D.ConeTwistConstraint.prototype.type]=this.readConeTwistConstraint,this.file.typeRead[SEA3D.RigidBody.prototype.type]=this.readRigidBody,this.file.typeRead[SEA3D.CarController.prototype.type]=this.readCarController)}});
THREE.SEA3D.EXTENSIONS_DOMAIN.push({dispose:function(){var a;for(a=this.rigidBodies?this.rigidBodies.length:0;a--;)SEA3D.AMMO.removeRigidBody(this.rigidBodies[a],!0);for(a=this.vehicles?this.vehicles.length:0;a--;)SEA3D.AMMO.removeVehicle(this.vehicles[a],!0);for(a=this.constraints?this.constraints.length:0;a--;)SEA3D.AMMO.removeConstraint(this.constraints[a],!0);for(a=this.shapes?this.shapes.length:0;a--;)Ammo.destroy(this.shapes[a])}});