(function(v){if("object"===typeof exports&&"undefined"!==typeof module)module.exports=v();else if("function"===typeof define&&define.amd)define([],v);else{var f;f="undefined"!==typeof window?window:"undefined"!==typeof global?global:"undefined"!==typeof self?self:this;(f.airbrakeJs||(f.airbrakeJs={})).Client=v()}})(function(){return function f(h,k,g){function e(c,d){if(!k[c]){if(!h[c]){var m="function"==typeof require&&require;if(!d&&m)return m(c,!0);if(a)return a(c,!0);m=Error("Cannot find module '"+
c+"'");throw m.code="MODULE_NOT_FOUND",m;}m=k[c]={exports:{}};h[c][0].call(m.exports,function(a){var m=h[c][1][a];return e(m?m:a)},m,m.exports,f,h,k,g)}return k[c].exports}for(var a="function"==typeof require&&require,b=0;b<g.length;b++)e(g[b]);return e}({1:[function(f,h,k){(function(g){var e,a,b,c;f("./internal/compat");c=f("./internal/merge");a=f("./internal/promise");b=function(a){return function(m,c,b,e,g){return g?a.notify(g):a.notify({error:{message:m,fileName:c,lineNumber:b,columnNumber:e||
0}})}};e=function(){function d(a){null==a&&(a={});this._projectId=a.projectId||0;this._projectKey=a.projectKey||"";this._host=a.host||"https://api.airbrake.io";this._processor=null;this._reporters=[];this._filters=[];this._processor=void 0!==a.processor?a.processor:f("./processors/stack");void 0!==a.reporter?this.addReporter(a.reporter):(a="withCredentials"in new g.XMLHttpRequest?"compat":"jsonp",this.addReporter(a));this.addFilter(f("./internal/default_filter"));this.onerror=b(this);null==g.onerror&&
(g.onerror=this.onerror)}d.prototype.setProject=function(a,c){this._projectId=a;return this._projectKey=c};d.prototype.setHost=function(a){return this._host=a};d.prototype.addContext=function(a){"undefined"!==typeof console&&null!==console&&"function"===typeof console.warn&&console.warn("airbrake: addContext is deprecated, please use addFilter");return this.addFilter(function(b){b.context=c({},a,b.context);return b})};d.prototype.setEnvironmentName=function(a){"undefined"!==typeof console&&null!==
console&&"function"===typeof console.warn&&console.warn("airbrake: setEnvironmentName is deprecated, please use addFilter");return this.addFilter(function(c){null==c.context.environment&&(c.context.environment=a);return c})};d.prototype.addParams=function(a){"undefined"!==typeof console&&null!==console&&"function"===typeof console.warn&&console.warn("airbrake: addParams is deprecated, please use addFilter");return this.addFilter(function(b){b.params=c({},a,b.params);return b})};d.prototype.addEnvironment=
function(a){"undefined"!==typeof console&&null!==console&&"function"===typeof console.warn&&console.warn("airbrake: addEnvironment is deprecated, please use addFilter");return this.addFilter(function(b){b.environment=c({},a,b.environment);return b})};d.prototype.addSession=function(a){"undefined"!==typeof console&&null!==console&&"function"===typeof console.warn&&console.warn("airbrake: addSession is deprecated, please use addFilter");return this.addFilter(function(b){b.session=c({},a,b.session);
return b})};d.prototype.addReporter=function(a){switch(a){case "compat":a=f("./reporters/compat");break;case "xhr":a=f("./reporters/xhr");break;case "jsonp":a=f("./reporters/jsonp")}return this._reporters.push(a)};d.prototype.addFilter=function(a){return this._filters.push(a)};d.prototype.notify=function(b){var d,e,n;d={language:"JavaScript",sourceMapEnabled:!0};null!=(n=g.navigator)&&n.userAgent&&(d.userAgent=g.navigator.userAgent);g.location&&(d.url=String(g.location),d.rootDirectory=g.location.protocol+
"//"+g.location.host);e=new a;this._processor(b.error||b,function(a){return function(g,n){var f,h,k,t,u,x;t={errors:[n],context:c(d,b.context),params:b.params||{},environment:b.environment||{},session:b.session||{}};t.context.notifier={name:"airbrake-js-"+g,version:"0.5.8",url:"https://github.com/airbrake/airbrake-js"};u=a._filters;h=0;for(k=u.length;h<k;h++){f=u[h];f=f(t);if(null===f||!1===f)return;null!=f.errors?t=f:"undefined"!==typeof console&&null!==console&&"function"===typeof console.warn&&
console.warn("airbrake: filter must return notice or null to ignore the notice")}u={projectId:a._projectId,projectKey:a._projectKey,host:a._host};f=a._reporters;h=0;for(k=f.length;h<k;h++)x=f[h],x(t,u,e)}}(this));return e};d.prototype.push=function(a){"undefined"!==typeof console&&null!==console&&"function"===typeof console.warn&&console.warn("airbrake: push is deprecated, please use notify");return this.notify(a)};d.prototype._wrapArguments=function(a){var b,c,d,e;c=d=0;for(e=a.length;d<e;c=++d)b=
a[c],"function"===typeof b&&(a[c]=this.wrap(b));return a};d.prototype.wrap=function(a){var b,c,d;if(a.__airbrake__)return a;d=this;b=function(){var b,c;b=d._wrapArguments(arguments);try{return a.apply(this,b)}catch(e){return c=e,b=Array.prototype.slice.call(arguments),d.notify({error:c,params:{arguments:b}}),null}};for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);b.__airbrake__=!0;b.__inner__=a;return b};return d}();h.exports=e}).call(this,"undefined"!==typeof global?global:"undefined"!==typeof self?self:
"undefined"!==typeof window?window:{})},{"./internal/compat":2,"./internal/default_filter":3,"./internal/merge":5,"./internal/promise":6,"./processors/stack":8,"./reporters/compat":9,"./reporters/jsonp":10,"./reporters/xhr":11}],2:[function(f,h,k){null==(f=Array.prototype).indexOf&&(f.indexOf=function(g,e){var a,b,c,d;a=b=c=e||0;for(d=this.length;c<=d?b<d:b>d;a=c<=d?++b:--b)if(this[a]===g)return a;return-1})},{}],3:[function(f,h,k){var g,e=[].indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(b in
this&&this[b]===a)return b;return-1};g=["Script error","Script error."];h.exports=function(a){return 0<=e.call(g,a.errors[0].message)?null:a}},{}],4:[function(f,h,k){var g,e;g=f("./truncate");e=function(a,b){var c,d;null==b&&(b=1E3);c={};for(d in a)c[d]=g(a[d],b);return c};h.exports=function(a,b,c){var d;null==b&&(b=1E3);for(null==c&&(c=64E3);;){a.params=e(a.params,b);a.environment=e(a.environment,b);a.session=e(a.session,b);d=JSON.stringify(a);if(d.length<c)return d;if(0===b)break;b=Math.floor(b/
2)}a=Error("airbrake-js: cannot jsonify notice (length\x3d"+d.length+" maxLength\x3d"+c+")");a.params={json:d.slice(0,+Math.floor(b/2)+1||9E9)+"..."};throw a;}},{"./truncate":7}],5:[function(f,h,k){h.exports=function(){var g,e,a,b,c,d;d=Array.prototype.slice.call(arguments);g=d.shift()||{};e=0;for(b=d.length;e<b;e++)for(a in c=d[e],c)Object.prototype.hasOwnProperty.call(c,a)&&(g[a]=c[a]);return g}},{}],6:[function(f,h,k){f=function(){function g(e){var a,b;this._onResolved=[];this._onRejected=[];b=
function(a){return function(){return a.resolve.apply(a,arguments)}}(this);a=function(a){return function(){return a.reject.apply(a,arguments)}}(this);null!=e&&e(b,a)}g.prototype.then=function(e,a){e&&(null!=this._resolvedWith&&e(this._resolvedWith),this._onResolved.push(e));a&&(null!=this._rejectedWith&&a(this._resolvedWith),this._onRejected.push(a));return this};g.prototype["catch"]=function(e){null!=this._rejectedWith&&e(this._rejectedWith);this._onRejected.push(e);return this};g.prototype.resolve=
function(){var e,a,b,c;this._resolvedWith=arguments;c=this._onResolved;a=0;for(b=c.length;a<b;a++)e=c[a],e.apply(this,this._resolvedWith);return this};g.prototype.reject=function(){var e,a,b,c;this._rejectedWith=arguments;c=this._onRejected;a=0;for(b=c.length;a<b;a++)e=c[a],e.apply(this,this._rejectedWith);return this};return g}();h.exports=f},{}],7:[function(f,h,k){var g;g=function(e,a){try{return e[a]}catch(b){}};h.exports=function(e,a,b){var c,d,f,h,k;null==a&&(a=1E3);null==b&&(b=5);h=0;f=[];k=
[];d=function(a){var b,c,d,e;c=k.indexOf(a);e=[f[c]];for(b=d=c;0>=c?0>=d:0<=d;b=0>=c?++d:--d)k[b]&&g(k[b],e[0])===a&&(a=k[b],e.unshift(f[b]));return"~"+e.join(".")};c=function(e,p,r){var l,q,s,w;null==p&&(p="");null==r&&(r=0);h++;if(h>a)return"[Truncated]";if(null===e||void 0===e)return e;switch(typeof e){case "boolean":case "number":case "string":case "function":return e;case "object":break;default:return String(e)}if(e instanceof Boolean||e instanceof Number||e instanceof String||e instanceof Date||
e instanceof RegExp)return e;if(0<=k.indexOf(e))return"[Circular "+d(e)+"]";r++;if(r>b)return"[Truncated]";f.push(p);k.push(e);h--;if("[object Array]"===Object.prototype.toString.apply(e)){l=[];q=s=0;for(w=e.length;s<w;q=++s){p=e[q];h++;if(h>=a)break;l.push(c(p,q,r))}return l}l={};for(p in e)if(Object.prototype.hasOwnProperty.call(e,p)){h++;if(h>=a)break;q=g(e,p);void 0!==q&&(l[p]=c(q,p,r))}return l};return c(e)}},{}],8:[function(f,h,k){var g,e;g=[{name:"v8",re:/^\s*at\s(.+?)\s\((?:(?:(.+):(\d+):(\d+))|(.+))\)$/,
fn:function(a){return{"function":a[1],file:a[2]||a[5],line:a[3]&&parseInt(a[3],10)||0,column:a[4]&&parseInt(a[4],10)||0}}},{name:"firefox30",re:/^(.*)@(.+):(\d+):(\d+)$/,fn:function(a){var b,c,d;c=a[1];b=a[2];if(d=b.match(/^(\S+)\s(line\s\d+\s>\seval.*)$/))c=0<c.length?c+" "+d[2]:d[2],b=d[1];return{"function":c,file:b,line:parseInt(a[3],10),column:parseInt(a[4],10)}}},{name:"firefox14",re:/^(.*)@(.+):(\d+)$/,fn:function(a,b,c){b=0===b?c.columnNumber||0:0;return{"function":a[1],file:a[2],line:parseInt(a[3],
10),column:b}}},{name:"v8-short",re:/^\s*at\s(.+):(\d+):(\d+)$/,fn:function(a){return{"function":"",file:a[1],line:parseInt(a[2],10),column:parseInt(a[3],10)}}},{name:"phantomjs",re:/^\s*at\s(.+):(\d+)$/,fn:function(a){return{"function":"",file:a[1],line:parseInt(a[2],10),column:0}}},{name:"default",re:/.+/,fn:function(a){return{"function":a[0],file:"",line:0,column:0}}}];e=/^\S+:\s.+$/;h.exports=function(a,b){var c,d,f,h,k,n,p,r,l,q,s;q="nostack";r=(a.stack||"").split("\n");c=[];d=f=0;for(k=r.length;f<
k;d=++f)if(p=r[d],""!==p)for(h=0,n=g.length;h<n;h++)if(s=g[h],l=p.match(s.re)){q=s.name;c.push(s.fn(l,d,a));break}("v8"===q||"v8-short"===q)&&0<c.length&&c[0]["function"].match(e)&&(c=c.slice(1));0!==c.length||null==a.fileName&&null==a.lineNumber&&null==a.columnNumber||c.push({"function":"",file:a.fileName||"",line:parseInt(a.lineNumber,10)||0,column:parseInt(a.columnNumber,10)||0});0!==c.length||null==a.filename&&null==a.lineno&&null==a.column&&null==a.colno||c.push({"function":"",file:a.filename||
"",line:parseInt(a.lineno,10)||0,column:parseInt(a.column||a.colno,10)||0});d=null!=a.message?a.message:String(a);null!=a.name&&""!==a.name?(l=a.name,d=l+": "+d):(l=/^Uncaught\s(.+?):\s.+$/,l=(l=d.match(l))?l[1]:"");return b(q,{type:l,message:d,backtrace:c})}},{}],9:[function(f,h,k){(function(g){var e;e=f("../internal/jsonify_notice");h.exports=function(a,b,c){var d,f;f=b.host+"/api/v3/projects/"+b.projectId+"/create-notice?key\x3d"+b.projectKey;b=e(a);d=new g.XMLHttpRequest;d.open("POST",f,!0);d.send(b);
return d.onreadystatechange=function(){var b;if(4===d.readyState&&200===d.status)return b=JSON.parse(d.responseText),a.id=b.id,c.resolve(a)}}}).call(this,"undefined"!==typeof global?global:"undefined"!==typeof self?self:"undefined"!==typeof window?window:{})},{"../internal/jsonify_notice":4}],10:[function(f,h,k){(function(g){var e,a;a=f("../internal/jsonify_notice");e=0;h.exports=function(b,c,d){var f,h,k,n;e++;f="airbrakeCb"+String(e);g[f]=function(a){b.id=a.id;d.resolve(b);try{return delete g[f]}catch(c){return g[f]=
void 0}};k=encodeURIComponent(a(b));k=c.host+"/api/v3/projects/"+c.projectId+"/create-notice?key\x3d"+c.projectKey+"\x26callback\x3d"+f+"\x26body\x3d"+k;c=g.document;h=c.getElementsByTagName("head")[0];n=c.createElement("script");n.src=k;c=function(){return h.removeChild(n)};n.onload=c;n.onerror=c;return h.appendChild(n)}}).call(this,"undefined"!==typeof global?global:"undefined"!==typeof self?self:"undefined"!==typeof window?window:{})},{"../internal/jsonify_notice":4}],11:[function(f,h,k){(function(g){var e;
e=f("../internal/jsonify_notice");h.exports=function(a,b,c){var d,f;f=b.host+"/api/v3/projects/"+b.projectId+"/notices?key\x3d"+b.projectKey;b=e(a);d=new g.XMLHttpRequest;d.open("POST",f,!0);d.setRequestHeader("Content-Type","application/json");d.send(b);return d.onreadystatechange=function(){var b;if(4===d.readyState&&201===d.status)return b=JSON.parse(d.responseText),a.id=b.id,c.resolve(a)}}}).call(this,"undefined"!==typeof global?global:"undefined"!==typeof self?self:"undefined"!==typeof window?
window:{})},{"../internal/jsonify_notice":4}]},{},[1])(1)});