THREE.Car=function(){function e(){if(a.bodyGeometry&&a.wheelGeometry){if(a.autoWheelGeometry){a.wheelGeometry.computeBoundingBox();var b=a.wheelGeometry.boundingBox;a.wheelOffset.addVectors(b.min,b.max);a.wheelOffset.multiplyScalar(.5);a.wheelDiameter=b.max.y-b.min.y;a.wheelGeometry.center()}var b=a.modelScale,c=new THREE.Vector3,d=a.wheelMaterials;a.bodyMesh=new THREE.Mesh(a.bodyGeometry,a.bodyMaterials);a.bodyMesh.scale.set(b,b,b);a.root.add(a.bodyMesh);c.multiplyVectors(a.wheelOffset,new THREE.Vector3(b,
b,b));a.frontLeftWheelRoot.position.add(c);a.frontLeftWheelMesh=new THREE.Mesh(a.wheelGeometry,d);a.frontLeftWheelMesh.scale.set(b,b,b);a.frontLeftWheelRoot.add(a.frontLeftWheelMesh);a.root.add(a.frontLeftWheelRoot);c.multiplyVectors(a.wheelOffset,new THREE.Vector3(-b,b,b));a.frontRightWheelRoot.position.add(c);a.frontRightWheelMesh=new THREE.Mesh(a.wheelGeometry,d);a.frontRightWheelMesh.scale.set(b,b,b);a.frontRightWheelMesh.rotation.z=Math.PI;a.frontRightWheelRoot.add(a.frontRightWheelMesh);a.root.add(a.frontRightWheelRoot);
c.multiplyVectors(a.wheelOffset,new THREE.Vector3(b,b,-b));c.z-=a.backWheelOffset;a.backLeftWheelMesh=new THREE.Mesh(a.wheelGeometry,d);a.backLeftWheelMesh.position.add(c);a.backLeftWheelMesh.scale.set(b,b,b);a.root.add(a.backLeftWheelMesh);c.multiplyVectors(a.wheelOffset,new THREE.Vector3(-b,b,-b));c.z-=a.backWheelOffset;a.backRightWheelMesh=new THREE.Mesh(a.wheelGeometry,d);a.backRightWheelMesh.position.add(c);a.backRightWheelMesh.scale.set(b,b,b);a.backRightWheelMesh.rotation.z=Math.PI;a.root.add(a.backRightWheelMesh);
a.meshes=[a.bodyMesh,a.frontLeftWheelMesh,a.frontRightWheelMesh,a.backLeftWheelMesh,a.backRightWheelMesh];a.loaded=!0;a.callback&&a.callback(a)}}function f(a){return 1===a?1:-Math.pow(2,-10*a)+1}var a=this;this.modelScale=1;this.backWheelOffset=2;this.autoWheelGeometry=!0;this.wheelOffset=new THREE.Vector3;this.wheelDiameter=1;this.MAX_SPEED=2200;this.MAX_REVERSE_SPEED=-1500;this.MAX_WHEEL_ROTATION=.6;this.FRONT_ACCELERATION=1250;this.BACK_ACCELERATION=1500;this.WHEEL_ANGULAR_ACCELERATION=1.5;this.FRONT_DECCELERATION=
750;this.WHEEL_ANGULAR_DECCELERATION=1;this.STEERING_RADIUS_RATIO=.0023;this.MAX_TILT_SIDES=.05;this.MAX_TILT_FRONTBACK=.015;this.carOrientation=this.wheelOrientation=this.acceleration=this.speed=0;this.root=new THREE.Object3D;this.frontLeftWheelRoot=new THREE.Object3D;this.frontRightWheelRoot=new THREE.Object3D;this.wheelMaterials=this.bodyMaterials=this.wheelGeometry=this.bodyGeometry=this.backRightWheelMesh=this.backLeftWheelMesh=this.frontRightWheelMesh=this.frontLeftWheelMesh=this.bodyMesh=null;
this.loaded=!1;this.meshes=[];this.enableShadows=function(a){for(var c=0;c<this.meshes.length;c++)this.meshes[c].castShadow=a,this.meshes[c].receiveShadow=a};this.setVisible=function(a){for(var c=0;c<this.meshes.length;c++)this.meshes[c].visible=a,this.meshes[c].visible=a};this.loadPartsJSON=function(b,c){var d=new THREE.JSONLoader;d.load(b,function(b,c){a.bodyGeometry=b;a.bodyMaterials=c;e()});d.load(c,function(b,c){a.wheelGeometry=b;a.wheelMaterials=c;e()})};this.loadPartsBinary=function(b,c){var d=
new THREE.BinaryLoader;d.load(b,function(b,c){a.bodyGeometry=b;a.bodyMaterials=c;e()});d.load(c,function(b,c){a.wheelGeometry=b;a.wheelMaterials=c;e()})};this.updateCarModel=function(a,c){c.moveForward&&(this.speed=THREE.Math.clamp(this.speed+a*this.FRONT_ACCELERATION,this.MAX_REVERSE_SPEED,this.MAX_SPEED),this.acceleration=THREE.Math.clamp(this.acceleration+a,-1,1));c.moveBackward&&(this.speed=THREE.Math.clamp(this.speed-a*this.BACK_ACCELERATION,this.MAX_REVERSE_SPEED,this.MAX_SPEED),this.acceleration=
THREE.Math.clamp(this.acceleration-a,-1,1));c.moveLeft&&(this.wheelOrientation=THREE.Math.clamp(this.wheelOrientation+a*this.WHEEL_ANGULAR_ACCELERATION,-this.MAX_WHEEL_ROTATION,this.MAX_WHEEL_ROTATION));c.moveRight&&(this.wheelOrientation=THREE.Math.clamp(this.wheelOrientation-a*this.WHEEL_ANGULAR_ACCELERATION,-this.MAX_WHEEL_ROTATION,this.MAX_WHEEL_ROTATION));if(!c.moveForward&&!c.moveBackward)if(0<this.speed){var d=f(this.speed/this.MAX_SPEED);this.speed=THREE.Math.clamp(this.speed-d*a*this.FRONT_DECCELERATION,
0,this.MAX_SPEED);this.acceleration=THREE.Math.clamp(this.acceleration-d*a,0,1)}else d=f(this.speed/this.MAX_REVERSE_SPEED),this.speed=THREE.Math.clamp(this.speed+d*a*this.BACK_ACCELERATION,this.MAX_REVERSE_SPEED,0),this.acceleration=THREE.Math.clamp(this.acceleration+d*a,-1,0);c.moveLeft||c.moveRight||(this.wheelOrientation=0<this.wheelOrientation?THREE.Math.clamp(this.wheelOrientation-a*this.WHEEL_ANGULAR_DECCELERATION,0,this.MAX_WHEEL_ROTATION):THREE.Math.clamp(this.wheelOrientation+a*this.WHEEL_ANGULAR_DECCELERATION,
-this.MAX_WHEEL_ROTATION,0));d=this.speed*a;this.carOrientation+=d*this.STEERING_RADIUS_RATIO*this.wheelOrientation;this.root.position.x+=Math.sin(this.carOrientation)*d;this.root.position.z+=Math.cos(this.carOrientation)*d;this.root.rotation.y=this.carOrientation;this.loaded&&(this.bodyMesh.rotation.z=this.speed/this.MAX_SPEED*this.wheelOrientation*this.MAX_TILT_SIDES,this.bodyMesh.rotation.x=-this.MAX_TILT_FRONTBACK*this.acceleration);d*=1/(this.wheelDiameter/2*this.modelScale);this.loaded&&(this.frontLeftWheelMesh.rotation.x+=
d,this.frontRightWheelMesh.rotation.x+=d,this.backLeftWheelMesh.rotation.x+=d,this.backRightWheelMesh.rotation.x+=d);this.frontLeftWheelRoot.rotation.y=this.wheelOrientation;this.frontRightWheelRoot.rotation.y=this.wheelOrientation}};