THREE.Volume=function(d,b,c,e,a){if(0<arguments.length){this.xLength=Number(d)||1;this.yLength=Number(b)||1;this.zLength=Number(c)||1;switch(e){case "Uint8":case "uint8":case "uchar":case "unsigned char":case "uint8_t":this.data=new Uint8Array(a);break;case "Int8":case "int8":case "signed char":case "int8_t":this.data=new Int8Array(a);break;case "Int16":case "int16":case "short":case "short int":case "signed short":case "signed short int":case "int16_t":this.data=new Int16Array(a);break;case "Uint16":case "uint16":case "ushort":case "unsigned short":case "unsigned short int":case "uint16_t":this.data=
new Uint16Array(a);break;case "Int32":case "int32":case "int":case "signed int":case "int32_t":this.data=new Int32Array(a);break;case "Uint32":case "uint32":case "uint":case "unsigned int":case "uint32_t":this.data=new Uint32Array(a);break;case "longlong":case "long long":case "long long int":case "signed long long":case "signed long long int":case "int64":case "int64_t":case "ulonglong":case "unsigned long long":case "unsigned long long int":case "uint64":case "uint64_t":throw"Error in THREE.Volume constructor : this type is not supported in JavaScript";
case "Float32":case "float32":case "float":this.data=new Float32Array(a);break;case "Float64":case "float64":case "double":this.data=new Float64Array(a);break;default:this.data=new Uint8Array(a)}if(this.data.length!==this.xLength*this.yLength*this.zLength)throw"Error in THREE.Volume constructor, lengths are not matching arrayBuffer size";}this.spacing=[1,1,1];this.offset=[0,0,0];this.matrix=new THREE.Matrix3;this.matrix.identity();var f=-Infinity;Object.defineProperty(this,"lowerThreshold",{get:function(){return f},
set:function(a){f=a;this.sliceList.forEach(function(a){a.geometryNeedsUpdate=!0})}});var g=Infinity;Object.defineProperty(this,"upperThreshold",{get:function(){return g},set:function(a){g=a;this.sliceList.forEach(function(a){a.geometryNeedsUpdate=!0})}});this.sliceList=[]};
THREE.Volume.prototype={constructor:THREE.Volume,getData:function(d,b,c){return this.data[c*this.xLength*this.yLength+b*this.xLength+d]},access:function(d,b,c){return c*this.xLength*this.yLength+b*this.xLength+d},reverseAccess:function(d){var b=Math.floor(d/(this.yLength*this.xLength)),c=Math.floor((d-b*this.yLength*this.xLength)/this.xLength);return[d-b*this.yLength*this.xLength-c*this.xLength,c,b]},map:function(d,b){var c=this.data.length;b=b||this;for(var e=0;e<c;e++)this.data[e]=d.call(b,this.data[e],
e,this.data);return this},extractPerpendicularPlane:function(d,b){var c,e,a,f=(new THREE.Matrix4).identity(),g,m,l,h=new THREE.Vector3;a=new THREE.Vector3;var k=new THREE.Vector3;e=new THREE.Vector3(this.xLength,this.yLength,this.zLength);switch(d){case "x":h.set(1,0,0);a.set(0,0,-1);k.set(0,-1,0);g=this.spacing[2];m=this.spacing[1];l=new THREE.Vector3(b,0,0);f.multiply((new THREE.Matrix4).makeRotationY(Math.PI/2));c=(this.RASDimensions[0]-1)/2;f.setPosition(new THREE.Vector3(b-c,0,0));break;case "y":h.set(0,
1,0);a.set(1,0,0);k.set(0,0,1);g=this.spacing[0];m=this.spacing[2];l=new THREE.Vector3(0,b,0);f.multiply((new THREE.Matrix4).makeRotationX(-Math.PI/2));c=(this.RASDimensions[1]-1)/2;f.setPosition(new THREE.Vector3(0,b-c,0));break;default:h.set(0,0,1),a.set(1,0,0),k.set(0,-1,0),g=this.spacing[0],m=this.spacing[1],l=new THREE.Vector3(0,0,b),c=(this.RASDimensions[2]-1)/2,f.setPosition(new THREE.Vector3(0,0,b-c))}a.applyMatrix4(this.inverseMatrix).normalize();a.argVar="i";k.applyMatrix4(this.inverseMatrix).normalize();
k.argVar="j";h.applyMatrix4(this.inverseMatrix).normalize();c=Math.floor(Math.abs(a.dot(e)));e=Math.floor(Math.abs(k.dot(e)));g=Math.abs(c*g);m=Math.abs(e*m);l=Math.abs(Math.round(l.applyMatrix4(this.inverseMatrix).dot(h)));var n=[new THREE.Vector3(1,0,0),new THREE.Vector3(0,1,0),new THREE.Vector3(0,0,1)];l=[a,k,h].find(function(a){return.9<Math.abs(a.dot(n[0]))});var p=[a,k,h].find(function(a){return.9<Math.abs(a.dot(n[1]))});a=[a,k,h].find(function(a){return.9<Math.abs(a.dot(n[2]))});var q=["volume.xLength-1-",
"volume.yLength-1-","volume.zLength-1-"],arguments=["i","j","k"];a=[l,p,a].map(function(a,b){return(0<a.dot(n[b])?"":q[b])+(a===h?"IJKIndex":a.argVar)}).join(",");a=eval("(function sliceAccess (i,j) {return volume.access( "+a+");})");return{iLength:c,jLength:e,sliceAccess:a,matrix:f,planeWidth:g,planeHeight:m}},extractSlice:function(d,b){var c=new THREE.VolumeSlice(this,b,d);this.sliceList.push(c);return c},repaintAllSlices:function(){this.sliceList.forEach(function(d){d.repaint()});return this},
computeMinMax:function(){for(var d=Infinity,b=-Infinity,c=this.data.length,e=0,e=0;e<c;e++)if(!isNaN(this.data[e]))var a=this.data[e],d=Math.min(d,a),b=Math.max(b,a);this.min=d;this.max=b;return[d,b]}};