(function(){function K(e,b){var m={},n;for(n in e)n!==b&&(m[n]=e[n]);if(b in e)for(n in e[b])m[n]=e[b][n];return m}function s(e,b,m,n){var a,s,C,D,f,v,k,w,x,E,F,G,r,t,H,z,A,I,J,p;b=b||{};b=K(b,"html");void 0!==b.wrap_line_length&&0!==parseInt(b.wrap_line_length,10)||void 0===b.max_char||0===parseInt(b.max_char,10)||(b.wrap_line_length=b.max_char);s=void 0===b.indent_inner_html?!1:b.indent_inner_html;C=void 0===b.indent_body_inner_html?!0:b.indent_body_inner_html;D=void 0===b.indent_head_inner_html?
!0:b.indent_head_inner_html;f=void 0===b.indent_size?4:parseInt(b.indent_size,10);v=void 0===b.indent_char?" ":b.indent_char;w=void 0===b.brace_style?"collapse":b.brace_style;k=0===parseInt(b.wrap_line_length,10)?32786:parseInt(b.wrap_line_length||250,10);x=b.unformatted||"a abbr area audio b bdi bdo br button canvas cite code data datalist del dfn em embed i iframe img input ins kbd keygen label map mark math meter noscript object output progress q ruby s samp select small span strong sub sup svg template textarea time u var video wbr text acronym address big dt ins strike tt".split(" ");
E=b.content_unformatted||["pre"];G=(F=void 0===b.preserve_newlines?!0:b.preserve_newlines)?isNaN(parseInt(b.max_preserve_newlines,10))?32786:parseInt(b.max_preserve_newlines,10):0;r=void 0===b.indent_handlebars?!1:b.indent_handlebars;t=void 0===b.wrap_attributes?"auto":b.wrap_attributes;H=isNaN(parseInt(b.wrap_attributes_indent_size,10))?f:parseInt(b.wrap_attributes_indent_size,10);z="force"===t.substr(0,5);A="force-expand-multiline"===t;I="force-aligned"===t;t=void 0===b.end_with_newline?!1:b.end_with_newline;
J="object"===typeof b.extra_liners&&b.extra_liners?b.extra_liners.concat():"string"===typeof b.extra_liners?b.extra_liners.split(","):["head","body","/html"];p=b.eol?b.eol:"auto";b.indent_with_tabs&&(v="\t",f=1);"auto"===p&&(p="\n",e&&B.test(e||"")&&(p=e.match(B)[0]));p=p.replace(/\\r/,"\r").replace(/\\n/,"\n");e=e.replace(L,"\n");a=new function(){function a(d){var c="";return{add:function(l){l=c+l.toLowerCase();c=l.length<=d.length?l:l.substr(l.length-d.length,d.length)},doesNotMatch:function(){return-1===
c.indexOf(d)}}}this.pos=0;this.token="";this.current_mode="CONTENT";this.tags={parent:"parent1",parentcount:1,parent1:""};this.token_text=this.last_token=this.last_text=this.token_type=this.tag_type="";this.newlines=0;this.indent_content=s;this.indent_body_inner_html=C;this.indent_head_inner_html=D;this.Utils={whitespace:["\n","\r","\t"," "],single_token:"area base br col embed hr img input keygen link menuitem meta param source track wbr !doctype ?xml ?php basefont isindex".split(" "),extra_liners:J,
in_array:function(d,c){for(var l=0;l<c.length;l++)if(d===c[l])return!0;return!1}};this.is_whitespace=function(d){for(var c=0;c<d.length;c++)if(!this.Utils.in_array(d.charAt(c),this.Utils.whitespace))return!1;return!0};this.traverse_whitespace=function(){var d="",d=this.input.charAt(this.pos);if(this.Utils.in_array(d,this.Utils.whitespace)){for(this.newlines=0;this.Utils.in_array(d,this.Utils.whitespace);)F&&"\n"===d&&this.newlines<=G&&(this.newlines+=1),this.pos++,d=this.input.charAt(this.pos);return!0}return!1};
this.space_or_wrap=function(d){if(this.line_char_count>=this.wrap_line_length)return this.print_newline(!1,d),this.print_indentation(d),!0;this.line_char_count++;d.push(" ");return!1};this.get_content=function(){for(var d="",c=[],l=0;"\x3c"!==this.input.charAt(this.pos)||2===l;){if(this.pos>=this.input.length)return c.length?c.join(""):["","TK_EOF"];if(this.traverse_whitespace())this.space_or_wrap(c);else{d=this.input.charAt(this.pos);if(r){"{"===d?l+=1:2>l&&(l=0);if("}"===d&&0<l&&0===l--)break;var a=
this.input.substr(this.pos,3);if("{{#"===a||"{{/"===a)break;else{if("{{!"===a)return[this.get_tag(),"TK_TAG_HANDLEBARS_COMMENT"];if("{{"===this.input.substr(this.pos,2)&&"{{else}}"===this.get_tag(!0))break}}this.pos++;this.line_char_count++;c.push(d)}}return c.length?c.join(""):""};this.get_contents_to=function(d){if(this.pos===this.input.length)return["","TK_EOF"];var c="";d=new RegExp("\x3c/"+d+"\\s*\x3e","igm");d.lastIndex=this.pos;d=(d=d.exec(this.input))?d.index:this.input.length;this.pos<d&&
(c=this.input.substring(this.pos,d),this.pos=d);return c};this.record_tag=function(d){this.tags[d+"count"]?this.tags[d+"count"]++:this.tags[d+"count"]=1;this.tags[d+this.tags[d+"count"]]=this.indent_level;this.tags[d+this.tags[d+"count"]+"parent"]=this.tags.parent;this.tags.parent=d+this.tags[d+"count"]};this.retrieve_tag=function(d){if(this.tags[d+"count"]){for(var c=this.tags.parent;c&&d+this.tags[d+"count"]!==c;)c=this.tags[c+"parent"];c&&(this.indent_level=this.tags[d+this.tags[d+"count"]],this.tags.parent=
this.tags[c+"parent"]);delete this.tags[d+this.tags[d+"count"]+"parent"];delete this.tags[d+this.tags[d+"count"]];1===this.tags[d+"count"]?delete this.tags[d+"count"]:this.tags[d+"count"]--}};this.indent_to_tag=function(d){if(this.tags[d+"count"]){for(var c=this.tags.parent;c&&d+this.tags[d+"count"]!==c;)c=this.tags[c+"parent"];c&&(this.indent_level=this.tags[d+this.tags[d+"count"]])}};this.get_tag=function(d){var c="",a=[],c="",b=!1,e=!0,u=!1,g,h,f=this.pos,k=this.line_char_count,n=!1,q;d=void 0!==
d?d:!1;do{if(this.pos>=this.input.length)return d&&(this.pos=f,this.line_char_count=k),a.length?a.join(""):["","TK_EOF"];c=this.input.charAt(this.pos);this.pos++;if(this.Utils.in_array(c,this.Utils.whitespace))b=!0;else{if("'"===c||'"'===c)c+=this.get_unformatted(c),b=!0;"\x3d"===c&&(b=!1);q=this.input.substr(this.pos-1);A&&u&&!n&&("\x3e"===c||"/"===c)&&q.match(/^\/?\s*>/)&&(b=!1,n=!0,this.print_newline(!1,a),this.print_indentation(a));if(a.length&&"\x3d"!==a[a.length-1]&&"\x3e"!==c&&b){var m=this.space_or_wrap(a)&&
"/"!==c&&!z,b=!1;if(z&&"/"!==c){var p=!1;A&&e&&(p=null===q.match(/^\S*(="([^"]|\\")*")?\s*\/?\s*>/));if(!e||p)this.print_newline(!1,a),this.print_indentation(a),m=!0}if(m)for(u=!0,q=H,I&&(q=a.indexOf(" ")+1),m=0;m<q;m++)a.push(v);if(e)for(q=0;q<a.length;q++)if(" "===a[q]){e=!1;break}}r&&"\x3c"===h&&"{{"===c+this.input.charAt(this.pos)&&(c+=this.get_unformatted("}}"),a.length&&" "!==a[a.length-1]&&"\x3c"!==a[a.length-1]&&(c=" "+c),b=!0);"\x3c"!==c||h||(g=this.pos-1,h="\x3c");r&&!h&&2<=a.length&&"{"===
a[a.length-1]&&"{"===a[a.length-2]&&(g="#"===c||"/"===c||"!"===c?this.pos-3:this.pos-2,h="{");this.line_char_count++;a.push(c);if(a[1]&&("!"===a[1]||"?"===a[1]||"%"===a[1])){a=[this.get_comment(g)];break}if(r&&a[1]&&"{"===a[1]&&a[2]&&"!"===a[2]){a=[this.get_comment(g)];break}if(r&&"{"===h&&2<a.length&&"}"===a[a.length-2]&&"}"===a[a.length-1])break}}while("\x3e"!==c);g=a.join("");h=-1!==g.indexOf("\n")?g.indexOf("\n"):-1!==g.indexOf(" ")?g.indexOf(" "):"{"===g.charAt(0)?g.indexOf("}"):g.indexOf("\x3e");
c="\x3c"!==g.charAt(0)&&r?"#"===g.charAt(2)?3:2:1;h=g.substring(c,h).toLowerCase();"/"===g.charAt(g.length-2)||this.Utils.in_array(h,this.Utils.single_token)?d||(this.tag_type="SINGLE"):r&&"{"===g.charAt(0)&&"else"===h?d||(this.indent_to_tag("if"),this.tag_type="HANDLEBARS_ELSE",this.indent_content=!0,this.traverse_whitespace()):this.is_unformatted(h,x)||this.is_unformatted(h,E)?(c=this.get_unformatted("\x3c/"+h+"\x3e",g),a.push(c),this.tag_type="SINGLE"):"script"===h&&(-1===g.search("type")||-1<
g.search("type")&&-1<g.search(/\b(text|application|dojo)\/(x-)?(javascript|ecmascript|jscript|livescript|(ld\+)?json|method|aspect)/))?d||(this.record_tag(h),this.tag_type="SCRIPT"):"style"===h&&(-1===g.search("type")||-1<g.search("type")&&-1<g.search("text/css"))?d||(this.record_tag(h),this.tag_type="STYLE"):"!"===h.charAt(0)?d||(this.tag_type="SINGLE",this.traverse_whitespace()):d||("/"===h.charAt(0)?(this.retrieve_tag(h.substring(1)),this.tag_type="END"):(this.record_tag(h),"html"!==h.toLowerCase()&&
(this.indent_content=!0),this.tag_type="START"),this.traverse_whitespace()&&this.space_or_wrap(a),this.Utils.in_array(h,this.Utils.extra_liners)&&(this.print_newline(!1,this.output),this.output.length&&"\n"!==this.output[this.output.length-2]&&this.print_newline(!0,this.output)));d&&(this.pos=f,this.line_char_count=k);return a.join("")};this.get_comment=function(a){var c="",b="\x3e",e=!1;this.pos=a;a=this.input.charAt(this.pos);for(this.pos++;this.pos<=this.input.length;){c+=a;if(c.charAt(c.length-
1)===b.charAt(b.length-1)&&-1!==c.indexOf(b))break;!e&&10>c.length&&(0===c.indexOf("\x3c![if")?(b="\x3c![endif]\x3e",e=!0):0===c.indexOf("\x3c![cdata[")?(b="]]\x3e",e=!0):0===c.indexOf("\x3c![")?(b="]\x3e",e=!0):0===c.indexOf("\x3c!--")?(b="--\x3e",e=!0):0===c.indexOf("{{!--")?(b="--}}",e=!0):0===c.indexOf("{{!")?5===c.length&&-1===c.indexOf("{{!--")&&(b="}}",e=!0):0===c.indexOf("\x3c?")?(b="?\x3e",e=!0):0===c.indexOf("\x3c%")&&(b="%\x3e",e=!0));a=this.input.charAt(this.pos);this.pos++}return c};
this.get_unformatted=function(d,c){if(c&&-1!==c.toLowerCase().indexOf(d))return"";var b="",e="",f=!0,u=a(d);do{if(this.pos>=this.input.length)break;b=this.input.charAt(this.pos);this.pos++;if(this.Utils.in_array(b,this.Utils.whitespace)){if(!f){this.line_char_count--;continue}if("\n"===b||"\r"===b){e+="\n";this.line_char_count=0;continue}}e+=b;u.add(b);this.line_char_count++;f=!0;r&&"{"===b&&e.length&&"{"===e.charAt(e.length-2)&&(e+=this.get_unformatted("}}"))}while(u.doesNotMatch());return e};this.get_token=
function(){var a;if("TK_TAG_SCRIPT"===this.last_token||"TK_TAG_STYLE"===this.last_token){var b=this.last_token.substr(7);a=this.get_contents_to(b);return"string"!==typeof a?a:[a,"TK_"+b]}if("CONTENT"===this.current_mode)return a=this.get_content(),"string"!==typeof a?a:[a,"TK_CONTENT"];if("TAG"===this.current_mode)return a=this.get_tag(),"string"!==typeof a?a:[a,"TK_TAG_"+this.tag_type]};this.get_full_indent=function(a){a=this.indent_level+a||0;return 1>a?"":Array(a+1).join(this.indent_string)};this.is_unformatted=
function(a,b){if(!this.Utils.in_array(a,b))return!1;if("a"!==a.toLowerCase()||!this.Utils.in_array("a",b))return!0;var e=(this.get_tag(!0)||"").match(/^\s*<\s*\/?([a-z]*)\s*[^>]*>\s*$/);return!e||this.Utils.in_array(e,b)?!0:!1};this.printer=function(a,b,e,f,k){this.input=a||"";this.input=this.input.replace(/\r\n|[\r\u2028\u2029]/g,"\n");this.output=[];this.indent_character=b;this.indent_string="";this.indent_size=e;this.brace_style=k;this.indent_level=0;this.wrap_line_length=f;for(a=this.line_char_count=
0;a<this.indent_size;a++)this.indent_string+=this.indent_character;this.print_newline=function(a,b){this.line_char_count=0;b&&b.length&&(a||"\n"!==b[b.length-1])&&("\n"!==b[b.length-1]&&(b[b.length-1]=b[b.length-1].replace(/\s+$/g,"")),b.push("\n"))};this.print_indentation=function(a){for(var b=0;b<this.indent_level;b++)a.push(this.indent_string),this.line_char_count+=this.indent_string.length};this.print_token=function(a){if(!this.is_whitespace(a)||this.output.length)(a||""!==a)&&this.output.length&&
"\n"===this.output[this.output.length-1]&&(this.print_indentation(this.output),a=a.replace(/^\s+/g,"")),this.print_token_raw(a)};this.print_token_raw=function(a){0<this.newlines&&(a=a.replace(/\s+$/g,""));a&&""!==a&&(1<a.length&&"\n"===a.charAt(a.length-1)?(this.output.push(a.slice(0,-1)),this.print_newline(!1,this.output)):this.output.push(a));for(a=0;a<this.newlines;a++)this.print_newline(0<a,this.output);this.newlines=0};this.indent=function(){this.indent_level++};this.unindent=function(){0<this.indent_level&&
this.indent_level--}};return this};for(a.printer(e,v,f,k,w);;){e=a.get_token();a.token_text=e[0];a.token_type=e[1];if("TK_EOF"===a.token_type)break;switch(a.token_type){case "TK_TAG_START":a.print_newline(!1,a.output);a.print_token(a.token_text);a.indent_content&&(!a.indent_body_inner_html&&a.token_text.match(/<body(?:.*)>/)||!a.indent_head_inner_html&&a.token_text.match(/<head(?:.*)>/)||a.indent(),a.indent_content=!1);a.current_mode="CONTENT";break;case "TK_TAG_STYLE":case "TK_TAG_SCRIPT":a.print_newline(!1,
a.output);a.print_token(a.token_text);a.current_mode="CONTENT";break;case "TK_TAG_END":"TK_CONTENT"===a.last_token&&""===a.last_text&&(e=(a.token_text.match(/\w+/)||[])[0],f=null,a.output.length&&(f=a.output[a.output.length-1].match(/(?:<|{{#)\s*(\w+)/)),(null===f||f[1]!==e&&!a.Utils.in_array(f[1],x))&&a.print_newline(!1,a.output));a.print_token(a.token_text);a.current_mode="CONTENT";break;case "TK_TAG_SINGLE":(e=a.token_text.match(/^\s*<([a-z-]+)/i))&&a.Utils.in_array(e[1],x)||a.print_newline(!1,
a.output);a.print_token(a.token_text);a.current_mode="CONTENT";break;case "TK_TAG_HANDLEBARS_ELSE":e=!1;for(f=a.output.length-1;0<=f&&"\n"!==a.output[f];f--)if(a.output[f].match(/{{#if/)){e=!0;break}e||a.print_newline(!1,a.output);a.print_token(a.token_text);a.indent_content&&(a.indent(),a.indent_content=!1);a.current_mode="CONTENT";break;case "TK_TAG_HANDLEBARS_COMMENT":a.print_token(a.token_text);a.current_mode="TAG";break;case "TK_CONTENT":a.print_token(a.token_text);a.current_mode="TAG";break;
case "TK_STYLE":case "TK_SCRIPT":if(""!==a.token_text){a.print_newline(!1,a.output);e=a.token_text;var y;k=1;"TK_SCRIPT"===a.token_type?y="function"===typeof m&&m:"TK_STYLE"===a.token_type&&(y="function"===typeof n&&n);"keep"===b.indent_scripts?k=0:"separate"===b.indent_scripts&&(k=-a.indent_level);f=a.get_full_indent(k);y?(k=function(){this.eol="\n"},k.prototype=b,k=new k,e=y(e.replace(/^\s*/,f),k)):(w=e.match(/^\s*/)[0].match(/[^\n\r]*$/)[0].split(a.indent_string).length-1,k=a.get_full_indent(k-
w),e=e.replace(/^\s*/,f).replace(/\r\n|\r|\n/g,"\n"+k).replace(/\s+$/,""));e&&(a.print_token_raw(e),a.print_newline(!0,a.output))}a.current_mode="TAG";break;default:""!==a.token_text&&a.print_token(a.token_text)}a.last_token=a.token_type;a.last_text=a.token_text}b=a.output.join("").replace(/[\r\n\t ]+$/,"");t&&(b+="\n");"\n"!==p&&(b=b.replace(/[\n]/g,p));return b}var B=/\r\n|[\n\r\u2028\u2029]/,L=new RegExp(B.source,"g");if("function"===typeof define&&define.amd)define(["require","./beautify","./beautify-css"],
function(e){var b=e("./beautify"),m=e("./beautify-css");return{html_beautify:function(e,a){return s(e,a,b.js_beautify,m.css_beautify)}}});else if("undefined"!==typeof exports){var M=require("./beautify.js"),N=require("./beautify-css.js");exports.html_beautify=function(e,b){return s(e,b,M.js_beautify,N.css_beautify)}}else"undefined"!==typeof window?window.html_beautify=function(e,b){return s(e,b,window.js_beautify,window.css_beautify)}:"undefined"!==typeof global&&(global.html_beautify=function(e,
b){return s(e,b,global.js_beautify,global.css_beautify)})})();