(function(l,m){"function"===typeof define&&define.amd?define([],m):"object"===typeof module&&module.exports?module.exports=m():l.parinferCodeMirror=m()})(this,function(){function l(a){return"parinferCodeMirror: "+a}function m(a){if(-1===v.indexOf(a))throw l('Mode "'+a+'" is invalid. Must be one of: '+v.join(","));}function p(a){a=a.__parinfer__;if(!a)throw l("You must call parinferCodeMirror.init(cm) on a CodeMirror instance before you can use the rest of the API.");return a}function G(a){return a.map(function(a){return{x:a.from.ch,
lineNo:a.from.line,oldText:a.removed.join("\n"),newText:a.text.join("\n")}})}function k(a,d){var b,c=a.getAllMarks();for(b=0;b<c.length;b++)c[b].className===d&&c[b].clear()}function r(a,d,b,c,e){a.markText({line:d,ch:b},{line:d,ch:c},{className:e})}function H(a,d){k(a,"parinfer-error");d&&(r(a,d.lineNo,d.x,d.x+1,"parinfer-error"),d.extra&&r(a,d.extra.lineNo,d.extra.x,d.extra.x+1,"parinfer-error"))}function I(a,d){k(a,"parinfer-paren-trail");if(d){var b,c;for(b=0;b<d.length;b++)c=d[b],r(a,c.lineNo,
c.startX,c.endX,"parinfer-paren-trail")}}function w(a){a=a.listSelections()[0];return Math.min(a.head.line,a.anchor.line)}function x(a,d,b){if(!a)return null;var c,e,g,f;for(c=0;c<a.length;c++){e=a[c];if(d<e){g=e;break}d>e&&(f=e)}if(-1===b)return f;if(1===b)return g}function y(a,d){var b=a.getLine(d),c;for(c=0;c<b.length;c++)if(" "!==b[c])return c;return null}function z(a,d){var b=a.somethingSelected(),c;if(c=p(a).tabStops){var e=[],g,f;for(g=0;g<c.length;g++)f=c[g],-1>=f.x&&e.pop(),e.push(f.x),e.push(f.x+
("("===f.ch?2:1)),null!=f.argX&&e.push(f.argX);c=e}else c=null;b?(b=c,c=w(a),c=y(a,c),b=x(b,c,d),null==b&&(b=Math.max(0,c+2*d)),a.indentSelection(b-c)):(g=c,e=a.getCursor(),b=e.line,c=e.ch,e=y(a,e.line),g=x(g,c,d),g=null==g||null!=e&&c!==e?Math.max(0,c+2*d):g,null!=e&&e<c&&c<g?(b=Array(g-c+1).join(" "),a.replaceSelection(b)):(c=g-c,""!==a.getDoc().getLine(b).trim()?a.indentLine(b,c):0<c?(b=Array(c+1).join(" "),a.replaceSelection(b)):(e=a.getCursor().ch,a.replaceRange("",{line:b,ch:e+c},{line:b,ch:e},
"+indent"))))}function A(a,d){return d.line===a.lineNo&&a.startX<=d.ch}function B(a,d){var b;for(b=0;b<d.length;b++){var c=a,e=d[b],g=c.getDoc().sel,f=g.ranges[0];(f=e.lineNo===e.closer.lineNo||!e.closer.trail||A(e.closer.trail,f.anchor)||A(e.closer.trail,f.head))||(f=e.closer,f=-1!==g.contains({line:f.lineNo,ch:f.x}));f||r(c,e.closer.lineNo,e.closer.x,e.closer.x+1,"parinfer-locus-paren");B(c,e.children)}}function t(a,d){var b=a.charCoords({line:d.lineNo,ch:d.x},"local");return{midx:b.left+(b.right-
b.left)/2,right:b.right,left:b.left,top:b.top,bottom:b.bottom}}function u(a,d){var b;for(b=0;b<d.length;b++){var c=a,e=d[b],g=c.__parinfer__.layer,f=g.paper,n=t(c,e),C=t(c,e.closer);if(e.closer.trail&&e.lineNo!==e.closer.lineNo)switch(g.type){case "guides":f.path(["M",n.midx,n.bottom,"V",C.bottom].join(" "));break;case "locus":for(var g=c,m=e.lineNo,h=e.closer.lineNo,q=g.getDoc(),l=0,p=0,k=void 0,k=m;k<=h;k++)m=q.getLine(k),m.length>l&&(l=m.length,p=k);g=t(g,{lineNo:p,x:l}).right;f.path(["M",n.midx,
n.top+4,"A",4,4,0,0,1,n.midx+4,n.top,"H",g-4,"A",4,4,0,0,1,g,n.top+4,"V",C.bottom,"H",n.midx,"V",n.bottom].join(" "))}u(c,e.children)}}function D(a,d){var b=a.__parinfer__.layer;b.type=d;var c=document.createElement("div");c.style.position="absolute";c.style.left="0";c.style.top="0";c.style["z-index"]=100;c.className="parinfer-locus";b.el=c;b.container.appendChild(c);b.paper=Raphael(c,b.container.clientWidth,b.container.clientHeight)}function E(a){(a=a.__parinfer__.layer)&&a.el&&a.container.removeChild(a.el)}
function J(a,d){k(a,"parinfer-locus-paren");d&&(B(a,d),E(a),D(a,"guides"),u(a,d))}function K(a,d){d&&(E(a),D(a,"guides"),u(a,d))}function q(a,d){var b=a.cm,c=b.getValue(),e=b.somethingSelected(),g=b.listSelections(),f=b.getCursor(),n=b.getScrollerElement(),f={cursorLine:f.line,cursorX:f.ch,prevCursorLine:a.prevCursorLine,prevCursorX:a.prevCursorX};e&&(f.selectionStartLine=w(b));if(a.options)for(var k in a.options)a.options.hasOwnProperty(k)&&(f[k]=a.options[k]);d&&(f.changes=G(d));k=a.options&&a.options.locus;
var l=a.options&&a.options.guides;if(k||l)delete f.locus,delete f.guides,f.returnParens=!0;var h,p=a.fixMode?"paren":a.mode;switch(p){case "indent":h=parinfer.indentMode(c,f);break;case "paren":h=parinfer.parenMode(c,f);break;case "smart":h=parinfer.smartMode(c,f);break;default:m(p)}a.parens=h.parens;a.tabStops=h.tabStops;c!==h.text&&(c=b.getHistory(),b.setValue(h.text),a.monitorCursor=!1,e?b.setSelections(g):b.setCursor(h.cursorLine,h.cursorX),b.setHistory(c),setTimeout(function(){a.monitorCursor=
!0},0),b.scrollTo(n.scrollLeft,n.scrollTop));H(b,h.error);I(b,h.parenTrails);a.prevCursorLine=h.cursorLine;a.prevCursorX=h.cursorX;k?J(b,h.parens):l&&K(b,h.parens);return a.fixMode&&h.success?(a.fixMode=!1,q(a,d)):h.success}function L(a){clearTimeout(a.cursorTimeout);a.monitorCursor&&(a.cursorTimeout=setTimeout(function(){q(a)},0))}function M(a){if(!a.enabled){a.callbackCursor=function(b){L(a)};a.callbackChanges=function(b,c){clearTimeout(a.cursorTimeout);"setValue"!==c[0].origin&&q(a,c)};var d=a.cm;
d.on("cursorActivity",a.callbackCursor);d.on("changes",a.callbackChanges);a.parinferKeys={Tab:function(a){z(a,1)},"Shift-Tab":function(a){z(a,-1)}};d.addKeyMap(a.parinferKeys);a.enabled=!0}}function F(a){a=p(a);"paren"!==a.mode&&(a.fixMode=!0);M(a);return q(a)}var v=["paren","indent","smart"];return{version:"1.4.1",init:function(a,d,b){var c=a.__parinfer__;if(c)throw l("init has already been called on this CodeMirror instance");d=d||"smart";m(d);c={cm:a,mode:d,options:b,enabled:!1,cursorTimeout:null,
monitorCursor:!0,prevCursorX:null,prevCursorLine:null,callbackCursor:null,callbackChanges:null};d=a.__parinfer__=c;b=a.getWrapperElement().querySelector(".CodeMirror-lines").parentNode;d.layer={container:b};return F(a)},enable:F,disable:function(a){a=p(a);if(a.enabled){var d=a.cm;k(d,"parinfer-error");k(d,"parinfer-paren-trail");d.off("cursorActivity",a.callbackCursor);d.off("changes",a.callbackChanges);d.removeKeyMap(a.parinferKeys);a.enabled=!1}},setMode:function(a,d){var b=p(a);m(d);b.mode=d;return q(b)},
setOptions:function(a,d){var b=p(a);b.options=d;return q(b)}}});