var _extends=Object.assign||function(a){for(var c=1;c<arguments.length;c++){var b=arguments[c],d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(a[d]=b[d])}return a};function _objectWithoutProperties(a,c){var b={},d;for(d in a)0<=c.indexOf(d)||Object.prototype.hasOwnProperty.call(a,d)&&(b[d]=a[d]);return b}
var InputElement=React.createClass({displayName:"InputElement",defaultCharsRules:{9:"[0-9]",a:"[A-Za-z]","*":"[A-Za-z0-9]"},defaultMaskChar:"_",lastCaretPos:null,isAndroidBrowser:function(){var a=/firefox/i,c=/android/i,b=navigator.userAgent;return!/windows/i.test(b)&&!a.test(b)&&c.test(b)},isWindowsPhoneBrowser:function(){var a=/phone/i,c=navigator.userAgent;return/windows/i.test(c)&&a.test(c)},isAndroidFirefox:function(){var a=/firefox/i,c=/android/i,b=navigator.userAgent;return!/windows/i.test(b)&&
a.test(b)&&c.test(b)},isDOMElement:function(a){return"object"===typeof HTMLElement?a instanceof HTMLElement:1===a.nodeType&&"string"===typeof a.nodeName},getInputDOMNode:function(){var a=this.refs.input;return a?this.isDOMElement(a)?a:a.getDOMNode():null},enableValueAccessors:function(){var a=this;if(this.canUseAccessors){var c=this.getInputDOMNode();this.valueDescriptor=Object.getOwnPropertyDescriptor(Object.getPrototypeOf(c),"value");Object.defineProperty(c,"value",{configurable:!0,enumerable:!0,
get:function(){return a.value},set:function(b){a.value=b;a.valueDescriptor.set.call(c,b)}})}},disableValueAccessors:function(){var a=this.valueDescriptor;if(a){this.valueDescriptor=null;var c=this.getInputDOMNode();Object.defineProperty(c,"value",a)}},getInputValue:function(){var a=this.getInputDOMNode(),c=this.valueDescriptor;return c?c.get.call(a):a.value},setInputValue:function(a){var c=this.getInputDOMNode();this.value=a;c.value=a},getPrefix:function(){for(var a="",c=this.mask,b=0;b<c.length&&
this.isPermanentChar(b);++b)a+=c[b];return a},getFilledLength:function(){var a=0>=arguments.length||void 0===arguments[0]?this.state.value:arguments[0],c;if(!this.maskChar)return a.length;for(c=a.length-1;0<=c;--c){var b=a[c];if(!this.isPermanentChar(c)&&this.isAllowedChar(b,c))break}return++c||this.getPrefix().length},getLeftEditablePos:function(a){for(;0<=a;--a)if(!this.isPermanentChar(a))return a;return null},getRightEditablePos:function(a){for(var c=this.mask;a<c.length;++a)if(!this.isPermanentChar(a))return a;
return null},isEmpty:function(){var a=this;return!(0>=arguments.length||void 0===arguments[0]?this.state.value:arguments[0]).split("").some(function(c,b){return!a.isPermanentChar(b)&&a.isAllowedChar(c,b)})},isFilled:function(){return this.getFilledLength(0>=arguments.length||void 0===arguments[0]?this.state.value:arguments[0])===this.mask.length},createFilledArray:function(a,c){for(var b=[],d=0;d<a;d++)b[d]=c;return b},formatValue:function(a){var c=this,b=this.maskChar,d=this.mask;if(!b){var e=this.getPrefix(),
f=e.length;for(a=this.insertRawSubstr("",a,0);a.length>f&&this.isPermanentChar(a.length-1);)a=a.slice(0,a.length-1);a.length<f&&(a=e);return a}return a?(e=this.formatValue(""),this.insertRawSubstr(e,a,0)):a.split("").concat(this.createFilledArray(d.length-a.length,null)).map(function(a,e){return c.isAllowedChar(a,e)?a:c.isPermanentChar(e)?d[e]:b}).join("")},clearRange:function(a,c,b){var d=this,e=c+b,f=this.maskChar,g=this.mask;if(!f){var h=this.getPrefix().length;a=a.split("").filter(function(a,
b){return b<h||b<c||b>=e}).join("");return this.formatValue(a)}return a.split("").map(function(a,b){return b<c||b>=e?a:d.isPermanentChar(b)?g[b]:f}).join("")},replaceSubstr:function(a,c,b){return a.slice(0,b)+c+a.slice(b+c.length)},insertRawSubstr:function(a,c,b){var d=this.mask,e=this.maskChar,f=this.isFilled(a),g=this.getPrefix().length;c=c.split("");for(!e&&b>a.length&&(a+=d.slice(a.length,b));b<d.length&&c.length;){var h=this.isPermanentChar(b);h&&d[b]!==c[0]?(!e&&b>=a.length?a+=d[b]:e&&h&&c[0]===
e&&c.shift(),++b):(h=c.shift(),this.isAllowedChar(h,b,!0)&&(b<a.length?a=e||f||b<g?this.replaceSubstr(a,h,b):this.formatValue(a.substr(0,b)+h+a.substr(b)):e||(a+=h),++b))}return a},getRawSubstrLength:function(a,c,b){a=this.mask;c=c.split("");for(var d=b;d<a.length&&c.length;)if(this.isPermanentChar(d)&&a[d]!==c[0])++d;else{var e=c.shift();this.isAllowedChar(e,d,!0)&&++d}return d-b},isAllowedChar:function(a,c){var b=2>=arguments.length||void 0===arguments[2]?!1:arguments[2],d=this.mask,e=this.maskChar;
return this.isPermanentChar(c)?d[c]===a:(new RegExp(this.charsRules[d[c]])).test(a||"")||b&&a===e},isPermanentChar:function(a){return-1!==this.permanents.indexOf(a)},setCaretToEnd:function(){var a=this.getFilledLength(),a=this.getRightEditablePos(a);null!==a&&this.setCaretPos(a)},setSelection:function(a){var c=1>=arguments.length||void 0===arguments[1]?0:arguments[1],b=this.getInputDOMNode();b&&(c=a+c,"selectionStart"in b&&"selectionEnd"in b?(b.selectionStart=a,b.selectionEnd=c):(b=b.createTextRange(),
b.collapse(!0),b.moveStart("character",a),b.moveEnd("character",c-a),b.select()))},getSelection:function(){var a=this.getInputDOMNode(),c=0,b=0;if("selectionStart"in a&&"selectionEnd"in a)c=a.selectionStart,b=a.selectionEnd;else{var d=document.selection.createRange();d.parentElement()===a&&(c=-d.moveStart("character",-a.value.length),b=-d.moveEnd("character",-a.value.length))}return{start:c,end:b,length:b-c}},getCaretPos:function(){return this.getSelection().start},setCaretPos:function(a){var c=window.requestAnimationFrame||
window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||function(a){return setTimeout(a,0)},b=this.setSelection.bind(this,a,0);b();c(b);this.lastCaretPos=a},isFocused:function(){return document.activeElement===this.getInputDOMNode()},parseMask:function(a){var c=this;if(!a||"string"!==typeof a)return{mask:null,lastEditablePos:null,permanents:[]};var b="",d=[],e=!1,f=null;a.split("").forEach(function(a){e||"\\"!==a?(e||!c.charsRules[a]?d.push(b.length):f=b.length+1,b+=a,e=!1):e=!0});return{mask:b,
lastEditablePos:f,permanents:d}},getStringValue:function(a){return a||0===a?a+"":""},getInitialState:function(){this.hasValue=null!=this.props.value;this.charsRules="formatChars"in this.props?this.props.formatChars:this.defaultCharsRules;var a=this.parseMask(this.props.mask),c=null!=this.props.defaultValue?this.props.defaultValue:"",c=null!=this.props.value?this.props.value:c,c=this.getStringValue(c);this.mask=a.mask;this.permanents=a.permanents;this.lastEditablePos=a.lastEditablePos;this.maskChar=
"maskChar"in this.props?this.props.maskChar:this.defaultMaskChar;this.mask&&(this.props.alwaysShowMask||c)&&(c=this.formatValue(c));return{value:c}},componentWillMount:function(){var a=this.state.value;this.mask&&a&&this.setState({value:a})},componentWillReceiveProps:function(a){this.hasValue=null!=this.props.value;this.charsRules="formatChars"in a?a.formatChars:this.defaultCharsRules;var c=this.mask,b=this.parseMask(a.mask),d=b.mask&&b.mask!==this.mask;this.mask=b.mask;this.permanents=b.permanents;
this.lastEditablePos=b.lastEditablePos;this.maskChar="maskChar"in a?a.maskChar:this.defaultMaskChar;if(this.mask){var e=null!=a.value?this.getStringValue(a.value):this.state.value;c||null!=a.value||(e=this.getInputDOMNode().value);a=a.alwaysShowMask||this.isFocused();if(d||b.mask&&(e||a&&!this.hasValue))e=this.formatValue(e),d&&(d=this.lastCaretPos,c=this.getFilledLength(e),c<d&&this.setCaretPos(this.getRightEditablePos(c)));b.mask&&this.isEmpty(e)&&!a&&!this.hasValue&&(e="");this.value=e;this.state.value!==
e&&this.setState({value:e})}},componentDidUpdate:function(a,c){(this.mask||a.mask)&&null==this.props.value&&this.updateUncontrolledInput();this.valueDescriptor&&this.getInputValue()!==this.state.value&&this.setInputValue(this.state.value)},updateUncontrolledInput:function(){this.getInputValue()!==this.state.value&&this.setInputValue(this.state.value)},onKeyDown:function(a){var c="function"===typeof this.props.onKeyDown;if(a.ctrlKey||a.metaKey){if(c)this.props.onKeyDown(a)}else{var b=this.getCaretPos(),
d=this.state.value,e=a.key,f=!1;switch(e){case "Backspace":case "Delete":var f=this.getPrefix().length,e="Delete"===e,g=this.getSelection();g.length?d=this.clearRange(d,g.start,g.length):b<f||!e&&b===f?b=f:(f=e?this.getRightEditablePos(b):this.getLeftEditablePos(b-1),null!==f&&(d=this.clearRange(d,f,1),b=f));f=!0}if(c)this.props.onKeyDown(a);if(d!==this.state.value&&(this.setInputValue(d),this.setState({value:this.hasValue?this.state.value:d}),f=!0,"function"===typeof this.props.onChange))this.props.onChange(a);
f&&(a.preventDefault(),this.setCaretPos(b))}},onKeyPress:function(a){var c=a.key,b="function"===typeof this.props.onKeyPress;if("Enter"===c||a.ctrlKey||a.metaKey){if(b)this.props.onKeyPress(a)}else if(!this.isWindowsPhoneBrowser){var b=this.getCaretPos(),d=this.getSelection(),e=this.state.value,f=this.mask,g=this.lastEditablePos,h=this.getPrefix().length;this.isPermanentChar(b)&&f[b]===c?(e=this.insertRawSubstr(e,c,b),++b):(f=this.getRightEditablePos(b),null!==f&&this.isAllowedChar(c,f)&&(e=this.clearRange(e,
d.start,d.length),e=this.insertRawSubstr(e,c,f),b=f+1));if(e!==this.state.value&&(this.setInputValue(e),this.setState({value:this.hasValue?this.state.value:e}),"function"===typeof this.props.onChange))this.props.onChange(a);a.preventDefault();b<g&&b>h&&(b=this.getRightEditablePos(b));this.setCaretPos(b)}},onChange:function(a){var c=this,b=this.pasteSelection,d=this.mask,e=this.maskChar,f=this.lastEditablePos,g=this.getInputValue();if(!g&&this.preventEmptyChange)this.disableValueAccessors(),this.preventEmptyChange=
!1,this.setInputValue(this.state.value);else{var h=this.state.value;if(b)this.pasteSelection=null,this.pasteText(h,g,b,a);else{var l=this.getSelection(),b=l.end,m=d.length,k=g.length,n=h.length,p=this.getPrefix().length;k>n?(e=k-n,k=l.end-e,l=g.substr(k,e),b=k<f&&(1!==e||l!==d[k])?this.getRightEditablePos(k):k,g=g.substr(0,k)+g.substr(k+e),d=this.clearRange(g,k,m-k),d=this.insertRawSubstr(d,l,b),g=this.insertRawSubstr(h,l,b),1!==e||b>=p&&b<f?b=this.getFilledLength(d):b<f&&b++):k<n&&(d=this.clearRange(h,
l.end,m-k),f=g.substr(0,l.end),h=f===h.substr(0,l.end),e&&(g=this.insertRawSubstr(d,f,0)),d=this.clearRange(d,l.end,m-l.end),d=this.insertRawSubstr(d,f,0),h?b<p&&(b=p):b=this.getFilledLength(d));g=this.formatValue(g);this.canUseAccessors&&(this.isAndroidBrowser||this.isWindowsPhoneBrowser)||this.setInputValue(g);this.canUseAccessors&&(this.isAndroidFirefox&&g&&!this.getInputValue()||this.isAndroidBrowser||this.isWindowsPhoneBrowser)&&(this.value=g,this.enableValueAccessors(),this.isAndroidFirefox&&
(this.preventEmptyChange=!0),setTimeout(function(){c.preventEmptyChange=!1;c.disableValueAccessors()},0));this.setState({value:this.hasValue?this.state.value:g});if("function"===typeof this.props.onChange)this.props.onChange(a);this.setCaretPos(b)}}},onFocus:function(a){if(this.state.value)this.getFilledLength()<this.mask.length&&this.setCaretToEnd();else{var c=this.getPrefix(),c=this.formatValue(c),c=this.formatValue(c),b=c!==a.target.value;b&&(a.target.value=c);this.setState({value:this.hasValue?
this.state.value:c},this.setCaretToEnd);if(b&&"function"===typeof this.props.onChange)this.props.onChange(a)}if("function"===typeof this.props.onFocus)this.props.onFocus(a)},onBlur:function(a){if(!this.props.alwaysShowMask&&this.isEmpty(this.state.value)){var c=""!==this.getInputValue();c&&this.setInputValue("");this.setState({value:this.hasValue?this.state.value:""});if(c&&"function"===typeof this.props.onChange)this.props.onChange(a)}if("function"===typeof this.props.onBlur)this.props.onBlur(a)},
onPaste:function(a){if(this.isAndroidBrowser)this.pasteSelection=this.getSelection(),this.setInputValue("");else{var c;window.clipboardData&&window.clipboardData.getData?c=window.clipboardData.getData("Text"):a.clipboardData&&a.clipboardData.getData&&(c=a.clipboardData.getData("text/plain"));if(c){var b=this.state.value,d=this.getSelection();this.pasteText(b,c,d,a)}a.preventDefault()}},pasteText:function(a,c,b,d){var e=b.start;b.length&&(a=this.clearRange(a,e,b.length));b=this.getRawSubstrLength(a,
c,e);a=this.insertRawSubstr(a,c,e);e+=b;e=this.getRightEditablePos(e)||e;if(a!==this.getInputValue()&&(d&&this.setInputValue(a),this.setState({value:this.hasValue?this.state.value:a}),d&&"function"===typeof this.props.onChange))this.props.onChange(d);this.setCaretPos(e)},componentDidMount:function(){this.isAndroidBrowser=this.isAndroidBrowser();this.isWindowsPhoneBrowser=this.isWindowsPhoneBrowser();this.isAndroidFirefox=this.isAndroidFirefox();if(Object.getOwnPropertyDescriptor&&Object.getPrototypeOf&&
Object.defineProperty){var a=this.getInputDOMNode(),a=Object.getOwnPropertyDescriptor(Object.getPrototypeOf(a),"value");this.canUseAccessors=!!(a&&a.get&&a.set)}this.mask&&null==this.props.value&&this.updateUncontrolledInput()},render:function(){var a=this,c=_objectWithoutProperties(this.props,["mask","alwaysShowMask","maskChar","formatChars"]);this.mask&&("onFocus onBlur onChange onKeyDown onKeyPress onPaste".split(" ").forEach(function(b){c[b]=a[b]}),null!=c.value&&(c.value=this.state.value));return React.createElement("input",
_extends({ref:"input"},c))}});