(function(n,l){"function"===typeof define&&define.amd?define([],l):"object"===typeof module&&module.exports?module.exports=l():n.parinfer=l()})(this,function(){function n(a){return"number"===typeof a&&isFinite(a)&&Math.floor(a)===a}function l(a){return"}"===a||")"===a||"]"===a}function p(a,c,b,g){-999===b&&(b=a.errorPosCache[c].lineNo);-999===g&&(g=a.errorPosCache[c].x);return{parinferError:!0,name:c,message:x[c],lineNo:b,x:g}}function q(a,c,b,g,k){var h;h=a.lines[c];h=h.substring(0,b)+k+h.substring(g);
a.lines[c]=h;k=k.length-(g-b);0!==k&&a.cursorLine===c&&-999!==a.cursorX&&(a.cursorX===b&&a.cursorX===g?0===a.cursorX:a.cursorX>=g)&&(a.cursorX+=k)}function r(a){return 0===a.length?-999:a[a.length-1]}function F(a,c){return 0===a.length?!1:r(a).ch===y[c]}function G(a,c){return a.lineNo===a.cursorLine&&-999!==a.cursorX&&-999!==c&&a.cursorX>c}function H(a,c,b){a.parenTrail.lineNo=c;a.parenTrail.startX=b;a.parenTrail.endX=b;a.parenTrail.openers=[];a.maxIndent=-999}function s(a,c){for(var b="";0<a.parenStack.length;){var g=
r(a.parenStack);if(g.x>=c)a.parenStack.pop(),b+=y[g.ch];else break}q(a,a.parenTrail.lineNo,a.parenTrail.startX,a.parenTrail.endX,b)}function z(a){a.trackingIndent=!1;if(a.quoteDanger)throw p(a,"quote-danger",-999,-999);if("INDENT_MODE"===a.mode)a.canPreviewCursorScope&&(a.cursorX>a.x&&(s(a,a.cursorX),H(a,a.cursorLine,a.cursorX)),a.canPreviewCursorScope=!1),s(a,a.x);else if("PAREN_MODE"===a.mode){var c=a.x,b=c,g=0,k=a.maxIndent,h=r(a.parenStack);-999!==h&&(g=h.x+1,b+=h.indentDelta);-999!==g&&(b=Math.max(g,
b));-999!==k&&(b=Math.min(k,b));if(b!==c){k="";for(g=0;g<b;g++)k+=" ";q(a,a.lineNo,0,c,k);a.x=b;a.indentDelta+=b-c}}}function t(a,c,b){a={mode:b,origText:a,origCursorX:-999,origLines:a.split(O),lines:[],lineNo:-1,ch:"",x:0,parenStack:[],tabStops:[],parenTrail:{lineNo:-999,startX:-999,endX:-999,openers:[]},cursorX:-999,cursorLine:-999,cursorDx:-999,previewCursorScope:!1,canPreviewCursorScope:!1,isInCode:!0,isEscaping:!1,isInStr:!1,isInComment:!1,commentX:-999,quoteDanger:!1,trackingIndent:!1,skipChar:!1,
success:!1,maxIndent:-999,indentDelta:0,error:{name:-999,message:-999,lineNo:-999,x:-999},errorPosCache:{}};c&&(n(c.cursorX)&&(a.cursorX=c.cursorX,a.origCursorX=c.cursorX),n(c.cursorLine)&&(a.cursorLine=c.cursorLine),n(c.cursorDx)&&(a.cursorDx=c.cursorDx),"boolean"===typeof c.previewCursorScope&&(a.previewCursorScope=c.previewCursorScope));try{var g;for(g=0;g<a.origLines.length;g++){c=a;var k=a.origLines[g];b=c;var h=k;b.x=0;b.lineNo++;b.lines.push(h);b.commentX=-999;b.indentDelta=0;b=c;if("INDENT_MODE"===
b.mode){if(b.trackingIndent=0!==b.parenStack.length&&!b.isInStr,b.previewCursorScope&&b.cursorLine===b.lineNo){var s=b.lines[b.lineNo].indexOf(";");b.canPreviewCursorScope=b.trackingIndent&&P.test(b.lines[b.lineNo])&&(-1===s||b.cursorX<=s)}}else"PAREN_MODE"===b.mode&&(b.trackingIndent=!b.isInStr);b=c;if(b.cursorLine===b.lineNo&&"INDENT_MODE"===b.mode)for(var f=h=void 0,h=0;h<b.parenStack.length;h++)f=b.parenStack[h],b.tabStops.push({ch:f.ch,x:f.x,lineNo:f.lineNo});b=void 0;h=k+"\n";for(b=0;b<h.length;b++){var f=
c,A=h[b];f.ch=A;f.skipChar=!1;"PAREN_MODE"===f.mode&&-999!==f.cursorDx&&f.cursorLine===f.lineNo&&f.cursorX===f.x&&(f.indentDelta+=f.cursorDx);if(f.trackingIndent){var d=f;if(l(d.ch)){if(d.skipChar=!0,"PAREN_MODE"===d.mode&&F(d.parenStack,d.ch))if(d.lineNo===d.cursorLine&&-999!==d.cursorX&&d.cursorX<=d.x)d.skipChar=!1,z(d);else{var t=d.parenStack.pop(),w=y[t.ch];d.maxIndent=t.x;var I=d.parenTrail.endX;q(d,d.parenTrail.lineNo,I,I,w);d.parenTrail.endX++}}else";"===d.ch?d.trackingIndent=!1:"\n"!==d.ch&&
" "!==d.ch&&"\t"!==d.ch&&z(d)}if(f.skipChar)f.ch="";else{var d=f,m=d.ch;if(d.isEscaping){var e=d;e.isEscaping=!1;if("\n"===e.ch){if(e.isInCode)throw p(e,"eol-backslash",e.lineNo,e.x-1);e.isInComment=!1;e.ch=""}}else if("{"===m||"("===m||"["===m)d.isInCode&&d.parenStack.push({lineNo:d.lineNo,x:d.x,ch:d.ch,indentDelta:d.indentDelta});else if(l(m)){if(e=d,e.isInCode)if(F(e.parenStack,e.ch)){var J=r(e.parenStack);e.parenTrail.endX=e.x+1;e.parenTrail.openers.push(J);e.maxIndent=J.x;e.parenStack.pop()}else e.ch=
""}else'"'===m?(e=d,e.isInStr?e.isInStr=!1:e.isInComment?(e.quoteDanger=!e.quoteDanger,e.quoteDanger&&(e.errorPosCache["quote-danger"]={lineNo:e.lineNo,x:e.x})):(e.isInStr=!0,e.errorPosCache["unclosed-quote"]={lineNo:e.lineNo,x:e.x})):";"===m?(e=d,e.isInCode&&(e.isInComment=!0,e.commentX=e.x)):"\\"===m?d.isEscaping=!0:"\t"===m?d.isInCode&&(d.ch="  "):"\n"===m&&(e=d,e.isInComment=!1,e.ch="");d.isInCode=!d.isInComment&&!d.isInStr;var d=f,x=d.lines[d.lineNo],e=-999;0<d.x&&(e=x[d.x-1]);var u=d.ch;!d.isInCode||
l(u)&&"\\"!==e||""===u||" "===u&&"\\"!==e||"  "==u||H(d,d.lineNo,d.x+1)}var B=f.ch;A!==B&&q(f,f.lineNo,f.x,f.x+A.length,B);f.x+=B.length}if(c.lineNo===c.parenTrail.lineNo)if(c.isInStr)c.parenTrail={lineNo:-999,startX:-999,endX:-999,openers:[]};else if("INDENT_MODE"===c.mode){b=c;var C=b.parenTrail.startX,Q=b.parenTrail.endX;if(G(b,C)&&!G(b,b.commentX)){for(var K=Math.max(C,b.cursorX),R=Math.max(Q,b.cursorX),S=b.lines[b.lineNo],h=0,f=void 0,f=C;f<K;f++)l(S[f])&&h++;b.parenTrail.openers.splice(0,h);
b.parenTrail.startX=K;b.parenTrail.endX=R}if(c.parenTrail.startX!==c.parenTrail.endX)for(var L=c.parenTrail.openers;0!==L.length;)c.parenStack.push(L.pop())}else if("PAREN_MODE"===c.mode&&c.lineNo!==c.cursorLine){var D=c.parenTrail.startX,E=c.parenTrail.endX;if(D!==E&&c.lineNo===c.parenTrail.lineNo){var M=c.lines[c.lineNo];b="";h=0;f=void 0;for(f=D;f<E;f++)l(M[f])?b+=M[f]:h++;0<h&&(q(c,c.lineNo,D,E,b),c.parenTrail.endX-=h)}}}if(a.quoteDanger)throw p(a,"quote-danger",-999,-999);if(a.isInStr)throw p(a,
"unclosed-quote",-999,-999);if(0!==a.parenStack.length){if("PAREN_MODE"===a.mode){var N=r(a.parenStack);throw p(a,"unclosed-paren",N.lineNo,N.x);}"INDENT_MODE"===a.mode&&(a.x=0,z(a))}a.success=!0}catch(v){a.success=!1,v.parinferError?(delete v.parinferError,a.error=v):(a.error.name="unhandled",a.error.message=v.stack)}return a}function w(a){if(!a.success)return{text:a.origText,cursorX:a.origCursorX,success:!1,error:a.error};var c;c=-1!==a.origText.search("\r")?"\r\n":"\n";c=a.lines.join(c);var b=
a.cursorX,g=[],k;for(k=0;k<a.lines.length;k++)a.lines[k]!==a.origLines[k]&&g.push({lineNo:k,line:a.lines[k]});return{text:c,cursorX:b,success:!0,changedLines:g,tabStops:a.tabStops}}var O=/\r?\n/,P=/^[\s\]\)\}]*(;.*)?$/,y={"{":"}","}":"{","[":"]","]":"[","(":")",")":"("},x={"quote-danger":"Quotes must balanced inside comment blocks.","eol-backslash":"Line cannot end in a hanging backslash.","unclosed-quote":"String is missing a closing quote.","unclosed-paren":"Unmatched open-paren."};return{version:"1.8.1",
indentMode:function(a,c){var b=t(a,c,"INDENT_MODE");return w(b)},parenMode:function(a,c){var b=t(a,c,"PAREN_MODE");return w(b)}}});